### ISSUE TITLE
Some examples fail to load cursor

### ISSUE THREAD

**Issue by dcz-purism** [swaywm/wlroots#1038]
When running some examples including `layer-shell.c`, they consistently crash at startup:

```
$ ./examples/layer-shell -l bottom -x 100
layer-shell: ../wlroots/examples/layer-shell.c:603: main: Assertion `cursor' failed.
Aborted (core dumped)
```

Revision 78966417, Built on Fedora 27, KDE, wayland 1.15 (local), Intel HD4000 graphics.

**Comment by emersion** [comment]
It seems you're missing `tcross` in your cursor theme. Maybe we should replace it with `crosshair`?

**Comment by dcz-purism** [comment]
I tried `crosshair` and was greeted with a calming pulsing square. That being said, I have no idea what cursors are assumed to always exist.

**Comment by emersion** [comment]
>a calming pulsing square

What. This wasn't expected.

>That being said, I have no idea what cursors are assumed to always exist.

Yeah, no idea neither. I think the intent was to display a cross. The list of supported cursors is in the rootston logs.

**Comment by dcz-purism** [comment]
The square was shining with all colors of the rainbow. I think it was the purpose of the app. I don't think it loses much when the cursor would fall back to some safe default, or even if that code would be gone entirely.

**Comment by emersion** [comment]
>The square was shining with all colors of the rainbow.

Oh, I though you were talking about the cursor, not the app. Yeah, that's expected! :rainbow: 

In fact, the `crosshair` is already used for the surface, and `tcross` is being used for popups. The cursor code is useful to know that the surface receives pointer input. Maybe we should fallback to `crosshair` if `tcross` is not found?
