### ISSUE TITLE
PR #1040 breaks new windows on firefox

### ISSUE THREAD

**Issue by aenda** [swaywm/wlroots#1042]
On current master, opening a new window on firefox will work, but all that will be displayed in it is the background. It can still be interacted with, and drop-downs like search suggestions will show up. Opening multiple firefox instances with `--no-remote` works, it's specifically new windows opened with Ctrl+N.
I cannot reproduce this on commits https://github.com/swaywm/wlroots/commit/a57d1baf57e86201c89c2e43c7cc0b0269f1b5d3 and earlier, so I believe https://github.com/swaywm/wlroots/pull/1040 is the cause.

**Comment by ascent12** [comment]
Yes, I'm seeing this on master also.

**Comment by Dudemanguy911** [comment]
I've also had this happen to me on a few tkinter windows. The cause are the ``- 1``'s in ``wlr_box_intersection`` The bool likely isn't calculated correctly and this messes up rendering for any windows that need need it. I don't if just removing is the correct approach though.
