### ISSUE TITLE
Provide a way for compositors to keep the texture of a surface for an indefinite amount of time

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1046]
Currently we can keep the texture only until it is re-uploaded. Having the ability to keep them for more time is useful when creating a closing animation and other things (like atomic layout in sway)

**Comment by SirCmpwn** [comment]
Maybe it'd be nice to have a function which creates a new wlr_texture from an existing one and copies its GPU resources (or refcounts them if that'd be too expensive?).

**Comment by emersion** [comment]
As I've said on IRC, copying a texture is expensive because it involves rendering to a pbuffer/FBO (there's no direct way to just copy it). Refcounting is not really possible because textures are mutable (for wl_shm, they're updated by wlr_surface, and for dma-buf or wl_drm, they're updated by the client).

We don't send `wl_buffer.release` at the right time in the first place. We currently sned it as soon as we create the texture. This is fine for wl_shm since we've copied the data to the GPU, but it's incorrect for wl_drm and dma-buf since the data is not copied (it's shared). We need to make sure the client doesn't re-use the wl_buffer before a new wl_buffer is attached (this _may_ explain some of our rendering/damage tracking issues).

**Comment by SirCmpwn** [comment]
Do Bad Things happen if we just... don't release the texture?

**Comment by emersion** [comment]
Yes, the memory is not released in the client, and the client has no choice but to allocate a new buffer at each new frame. We must manage this properly.

For this issue, what we want to basically to allow the compositor to prevent `wl_buffer.release` from being sent - and send it later. We could e.g. refcount `wl_buffer`, this would require to have something like `wlr_buffer`:

```c
struct wlr_buffer {
   struct wl_buffer wl_buffer;
   size_t refs;
   struct wlr_texture *texture; // destroyed when wl_buffer.release is sent
};
```

**Comment by emersion** [comment]
Oh, and `wlr_buffer` might allow use to get rid of the `wl_buffer` type switch in `wlr_surface` - by making protocol interfaces that create `wl_buffer` responsible for providing a way to get a texture from the resource. That would be pretty cool.

**Comment by emersion** [comment]
More detailed constraints:

* For wl_shm, we need to release the wl_buffer when the pixels have been uploaded to the GPU.
* For dma-buf, we need to release the wl_buffer when a new buffer is committed - unless the compositor still holds a reference to the texture.
* For wl_shm, buffers are mutable: when a new buffer is committed, we don't need to reupload the whole buffer, we can only reupload the damaged regions. Unless the compositor still holds a reference to the texture.

More detailed proposal:

```c
struct wlr_buffer {
	struct wl_resource *resource;
	struct wlr_texture *texture;
	size_t n_refs;
	bool released;
};

// Checks if a resource is a wl_buffer.
bool wlr_resource_is_buffer(struct wl_resource *resource);
// Returns the buffer size.
bool wlr_buffer_get_resource_size(struct wl_resource *resource,
	int *width, int *height);

// Uploads the texture to the GPU and references it.
struct wlr_buffer *wlr_buffer_create(struct wlr_renderer *renderer,
	struct wl_resource *resource);
// References and unreferences the buffer.
void wlr_buffer_ref(struct wlr_buffer *buffer);
void wlr_buffer_unref(struct wlr_buffer *buffer);
// Tries to update the texture in the provided buffer. This destroys `buffer`
// and returns a new buffer.
// Fails if `buffer->n_refs` > 1 or if the texture isn't mutable.
struct wlr_buffer *wlr_buffer_apply_damage(struct wlr_buffer *buffer,
	struct wl_resource *resource, pixman_region32_t *damage);
// Returns the underlying texture
struct wlr_texture *wlr_buffer_get_texture(struct wlr_buffer *buffer);
```

I'm not a fan of the refcounting functions. Maybe we can instead make `wlr_buffer_get_texture` increment `n_refs` and decrease it when the texture is destroyed?

**Comment by SirCmpwn** [comment]
refcounting seems fine here

**Comment by atomnuker** [comment]
Yep, looks fine to me as well.
