### ISSUE TITLE
Support custom modelines on outputs

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#1080]
I'd be nice to support this to allow for specific modes. This is especilly nice in QEMU where you can then set e.g. phone like screen dimensions. Weston supports this like:

https://github.com/krh/weston/blob/master/weston.ini#L49

**Comment by emersion** [comment]
Hmm, this is pretty DRM-specific. I wonder what should be done for other backends.

Maybe only implementing DRM custom modes would be enough for your use-case?

**Comment by ascent12** [comment]
>173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
I honestly have no idea what the 2nd-4th of each set of numbers even mean.
Also, I don't really want to add a modeline parser, but would prefer to just make a function accept a drmModeModeInfo (see xf86drmMode.h) and we could directly use that.

**Comment by agx** [comment]
@emersion for other backends like X11 we could derive the desired output resolution. 

The format is what's used by x.org (see e.g. cvt(1) or xorg.conf(5):
```
 ModeLine  "name" mode-description
              This  entry  is  a  more  compact version of the Mode entry, and it also can be used to specify video modes for the monitor.  This is a single line format for specifying video modes.  In most
              cases this isn't necessary because the built-in set of VESA standard modes will be sufficient.

              The mode-description is in four sections, the first three of which are mandatory.  The first is the dot (pixel) clock.  This is a single number specifying the pixel clock rate for the mode in
              MHz.   The  second  section is a list of four numbers specifying the horizontal timings.  These numbers are the hdisp, hsyncstart, hsyncend, and htotal values.  The third section is a list of
              four numbers specifying the vertical timings.  These numbers are the vdisp, vsyncstart, vsyncend, and vtotal values.  The final section is a list of flags specifying other characteristics  of
              the  mode.   Interlace  indicates  that the mode is interlaced.  DoubleScan indicates a mode where each scanline is doubled.  +HSync and -HSync can be used to select the polarity of the HSync
              signal.  +VSync and -VSync can be used to select the polarity of the VSync signal.  Composite can be used to specify composite sync on hardware where this is supported.  Additionally, on some
              hardware, +CSync and -CSync may be used to select the composite sync polarity.  The HSkew and VScan options mentioned above in the Mode entry description can also be used here.
```

they're mapping to drmModeModeInfo nicely.

**Comment by emersion** [comment]
The backend interface already has a `set_custom_mode` function. I think implementing it for the DRM backend would be enough for your use-case.
