### ISSUE TITLE
DRM backend leaking FDs

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#1090]
I've just had a fun crash on sway with `"dup failed: Too many open files"` and... fair enough, we're leaking FDs like crazy.

The most obvious I noticed just now is DRM backend, swapping VT and back adds ~20 new fd everytime, we must be missing some cleanup or reopening too much.
(mostly /dev/input/event* and some deleted /run/user/x/wlroots-shared-xxx)

There's also something going on with anon_inode:[timerfd] but I think these are on the sway side, mostly noticeable on config reload, but I don't see them on X11 backend so it must also be related to DRM somehow... Delaying opening an issue in sway for that until we've figured what they're about.

**Comment by emersion** [comment]
Checked and the DRM backend doesn't seem to leak FDs. Feel free to re-open if you can reproduce again.
