### ISSUE TITLE
wl_surface.enter/leave events are wonky on rootston

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlroots#1098]
>Starting a client, I first get one leave event for an output for which there was no enter events. Then I get two enter events for the screen the surface is actually on.

**Comment by emersion** [comment]
I'm trying to figure out a good way to fix this one. Ideally I'd like the renderer to be able to send enter right before sending frame done. That'd make sure each surface knows exactly how to draw itself when receiving a frame event, even subsurfaces and popups. It'll be fairly easy and cheap to maintain a list of outputs each surface is on (that's what Weston does).

However I'm not sure how to send the leave event.
