### ISSUE TITLE
Only send current mode via wl_output

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1099]
Modes were a protocol design mistake. If a client uses this information, it's probably broken.

GNOME does this.

**Comment by SirCmpwn** [comment]
I don't see any reason *not* to send modes. It's easy and in the protocol, and it's not dangerous if the client knows what other modes are available. I find it useful to enumerate modes with weston-info at times, too.

**Comment by emersion** [comment]
Will discuss this with the rest of the Wayland community. If possible, I'd like those to get deprecated.

**Comment by emersion** [comment]
I'd like to bump this again for two reasons:

- Modes as exposed in the core protocol have many issues: https://gitlab.freedesktop.org/wayland/wayland/issues/92
- We now support a specialized protocol for output management, which exposes modes in a better way.
