### ISSUE TITLE
Fallback to pointer events if client doesn't support tablet protocol

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1142]
See https://github.com/swaywm/wlroots/pull/960

**Comment by Ongy** [comment]
I think it would actually be nicer to fallback to touch (which then falls back to pointer) here.

Provided we do want that feature. I'm not quite sure we ended up saying we do. It would be mostly weird hacks either way.

**Comment by SirCmpwn** [comment]
Why would falling back to touch be better?

**Comment by Ongy** [comment]
Because I feel like the expected result of dragging (wrt scrolling/selection) would be closer to touch.

Then again, we'd have troubles mapping buttons in. So it's probably better do fallback to pointer to get slightly more sane fallback behaviour

**Comment by emersion** [comment]
Yeah, I'd prefer to fallback to pointer for both tablet and touch. I feel like the tablet → touch → pointer fallback is going to be pretty wonky.
