### ISSUE TITLE
Fallback to pointer events if client doesn't support touch

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1143]
Related to #1142

**Comment by Ongy** [comment]
I've actually implemented this in waymonad, in a very basic form.

The hardest part here is to scope it IMO.
The waymonad code only supports 1 left drag in practice, the first touch-point will be a fake pointer.

To actually get usable fallback, a small state machine is necessary, to support right click as well, either by multi-tap, or tap+hold. Maybe even some method to move the cursor without a button being clicked.

**Comment by emersion** [comment]
>To actually get usable fallback, a small state machine is necessary, to support right click as well, either by multi-tap, or tap+hold.

The fallback is not intended to be a full replacement. It's meant for extremely simple clients which don't implement the touch interface. So I think even a first super-simple version that blindly forwards events to the pointer has value.

**Comment by SirCmpwn** [comment]
Customizing the precise behavior of that state machine would be hard to justify in wlroots.

**Comment by emersion** [comment]
I don't think this should live in wlroots at all.

**Comment by SirCmpwn** [comment]
I agree, I've always expected this to be implemented by sway.
