### ISSUE TITLE
60Hz-capable setup uses 30Hz

### ISSUE THREAD

**Issue by rvolosatovs** [swaywm/wlroots#1154]
I have a multihead setup, where I have a 1080p laptop screen on eDP and a 4k screen connected via DP1.2(60Hz-capable setup).
While there's no tool like `xrandr` to confirm this, it seems that the 4k screen uses 30Hz - it is made obvious by moving the cursor across the screen - movement on the laptop screen is way smoother than on the external 4k monitor.
Note, that both screens work on 60 Hz in X11.
In X11 I'd be able to simply fix it using `xrandr`.

1. `wlroots` shall select the highest available refresh rate for each screen at all times.
2. (optional) It would be nice to have a command-line tool similar to `xrandr`, which would allow the user to alter/query the setup manually at runtime.

**Comment by SirCmpwn** [comment]
What compositor are you using? By default wlroots chooses the default mode. You have to modeset to get something else. It's possible that your display advertises a default mode which is not 60 Hz.

**Comment by SirCmpwn** [comment]
Actually by default I don't think wlroots chooses anything at all. But some compositors choose the default mode.

**Comment by rvolosatovs** [comment]
I'm using sway

**Comment by SirCmpwn** [comment]
You can set the mode by putting this in your config:

    output HDMI-A-1 mode 1920x1080@60Hz

Or whatever is appropriate, use `swaymsg -t get_outputs` to list output modes. And **do not report any more bugs**!
