### ISSUE TITLE
Should not lose focus when click dragging out of a window

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#1161]
If e.g. click dragging a slider in GTK+ and moving the cursor out of the window makes the slider remain in that position it was in when leaving the window even when moving the pointer (while still holding the button) back into the window. 

To reproduce: start e.g. gnome-control-center, select the power panel. Click-drag the "Screen brightness" slider to the right to change the brightness. Now drag further right until the cursor leaves the window. When moving back in the slider should still function but it remains in the maximum position. Only releasing the button and starting a new click-drag makes it work again.

Expected result:
The grab should not be broken until the user releases the button (inside or outside the window).

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/wlroots/issues/613
