### ISSUE TITLE
Dropdowns (xdg-popups) sometimes close when the pointer button is released

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1162]
Steps to reproduce:
Open gnome-calculator, switch to advanced mode. Try to click on the second dropdown (the one on the right). Popup opens, but as soon as the user releases the pointer button (the one used to click on the dropdown) the popup closes.

The same thing happens with some other popups, for example in simple-scanner's preferences.

 This bug is specific to rootston, and doesn't happen in sway. I haven't been able to pin down the exact cause yet.

**Comment by ammen99** [comment]
Update: found the reason why this doesn't work. Rootston updates cursor focus surface on button release (https://github.com/swaywm/wlroots/blob/master/rootston/cursor.c#L272), where sway doesn't. Without this focus update, the dropdowns start working. However, removing this creates another problem - for example, in `weston-terminal`. Open it, right click, release, don't move the mouse. The popup isn't focused until the mouse is moved. This is the current behavior in sway. This is unfortunate because we can't right click + left click on the first menu item without moving the mouse. Any ideas how to proceed?

**Comment by Ongy** [comment]
That's only half a cause so far IMO.
What causes the actual unmap?
Does rootston unmap something? Or does the client react to something? Which event does it react to?
If it closes the popup because of the `pointer_enter` I'd say it's a client bug. If rootston does something weird (maybe with which surface gets the button release event) we might have to change order of things.

**Comment by ammen99** [comment]
@Ongy didn't notice your comment until now, sorry. I thought and still think the reason is wlroots/rootston because it works fine under GNOME. They might have some non-standard workarounds though. I'll investigate more soon.

**Comment by emersion** [comment]
Do you have a GNOME `WAYLAND_DEBUG` log so that we can compare it with rootston's behaviour?

**Comment by ammen99** [comment]
@emersion, yes, here are some extracts (which I think are relevant, from the button press event to the popup destruction):

working:
Weston: https://pastebin.com/3GHGQWNt
GNOME: https://pastebin.com/sx4j2mYp

not working:
rootston: https://pastebin.com/wMRPBem7

**Comment by Ongy** [comment]
Well, first thing I see in rootston log, is that my asumption was correct. The `.button` release event is sent after `.leave` and `.enter`events.

But I think GNOME/weston do the same. Could be interesting to know what the intended flow of events is (and how the implicit grab shenanigans behave =.=).
I think we'd need to send a button event for the held button in the enter frame at the very least.


The actual difference I can see, is that both weston and GNOME send the button as the very next frame, while rootston has a motion in between. Maybe that's mapped to differen behaviour in GTK? (whether that's correct or not)

**Comment by ammen99** [comment]
I think that the difference in timing (when the button gets sent) comes from the fact that rootston doesn't update cursor focus until the button is released. On the other hand, AFAIK weston updates cursor focus when the view/popup gets mapped

**Comment by Ongy** [comment]
Added a bunch of comment to the header, renamed to something that hopefully makes it more obvious and inverted the logic to fit the name better.

**Comment by ammen99** [comment]
Okay, I solved the problem in my own compositor, I'm not sure how to add this to rootston. Here's what's needed: Update focus each time a new surface (subsurface/popup/toplevel) is mapped. Plus, I had to be careful not to send a `wl_pointer.motion` when I change the focus on this occasion, because we don't have a correct timestamp of the event.
