### ISSUE TITLE
Implement presentation-time

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1172]
```
23:27 <ascent12> presentation-time is one of those things I was going to get
around to doing in my "DRM 2.0" thing, but it would be easy enough for someone
to just do now if they wanted to. the "page_flip_callback" function in drm.c
basically contains all of the values you'd need.
```

**Comment by ascent12** [comment]
>page_flip_callback

Correcting myself: `page_flip_handler`.

Also, when doing this (at least initially), it's probably only worth implementing/exposing this for the DRM backend. We could do it with the Wayland backend by doing this as a client and passing the values through, and I even think X11 had an extension related to this, but it's probably not worth the effort.

**Comment by emersion** [comment]
Talked to some guys at XDC today, it seems that this extension suffers from a chicken-and-egg problem: no client implements it because no compositor implements it. Use cases include VR, games, medical apps, video players.
