### ISSUE TITLE
"wlr-layer-shell-unstable-v1-protocol.h"  not found

### ISSUE THREAD

**Issue by kenogo** [swaywm/wlroots#1180]
I wanted to start working on a compositor by forking rootston and using my own Makefile. However, rootston includes `<wlr/types/wlr_layer_shell.h>` which in turn includes `"wlr-layer-shell-unstable-v1-protocol.h"`. It also gives an error message saying I should add `-DWLR_USE_UNSTABLE`, but it is unclear to me where I should add that.

**Comment by SirCmpwn** [comment]
You need to integrate wayland-scanner with your build system to compile xml files to protocol headers and put them in your include path. How you specify `-DWLR_USE_UNSTABLE` also depends on your build system, this is a flag you must pass to your C compiler.

**Comment by SirCmpwn** [comment]
Side note: if [this](https://github.com/kenogo/bspwwm) is your project you might consider joining forces with [bspwc](https://github.com/Bl4ckb0ne/bspwc).
