### ISSUE TITLE
failed to load driver: amdgpu

### ISSUE THREAD

**Issue by hanko34** [swaywm/wlroots#1185]
When running sway (or rootston), the performance for native wayland application is rather bad and after logout I get this message:

    libGL error: MESA-LOADER: failed to retrieve device information
    libGL error: unable to load driver: amdgpu_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: amdgpu

When I run weston, everything works fine and there are not issues with the driver or the performance of graphical applications. The amdgpu driver itself seems to have loaded normally too.

This bug was first reported here where you can also find the detailed sway logfile for more information: https://github.com/swaywm/sway/issues/2442

wlroots version: git (Aug 9 2018, branch 'master')
sway version 1.0-alpha.5-43-g425ee270 (Aug 9 2018, branch 'master')
GPU: AMD Radeon RX 480

**Comment by SirCmpwn** [comment]
I guess I should ask the obvious question: do you have an `amdgpu_dri.so` file on your system?

**Comment by hanko34** [comment]
> I guess I should ask the obvious question: do you have an amdgpu_dri.so file on your system?

I do not.
However I have usr/lib/xorg/modules/drivers/amdgpu_drv.so

Installed by this package: https://www.archlinux.org/packages/extra/x86_64/xf86-video-amdgpu/

**Comment by ascent12** [comment]
After some investigation, it seems that `amdgpu_dri.so` is actually from AMDGPU-PRO, and is not part of mesa, so it __should__ fail to load it. Using an amdgpu card myself, it's actually using `radeonsi_dri.so` as the mesa driver.

I believe the problem may be something else.

**Comment by SirCmpwn** [comment]
Ah fair point.

**Comment by hanko34** [comment]
Any idea how to further debug this?

**Comment by SirCmpwn** [comment]
trace the ioctls and compare with weston? I dunno.

**Comment by hanko34** [comment]
Tested with 'strace firefox' and triggering the crash behavior by double clicking the address bar:

The only obvious difference I found was the following output when running on sway:


> getpeername(2, 0x7ceb6241cf10, [128])   = -1 ENOTSOCK (Socket operation on non-socket)
> futex(0x6e14c71bef38, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
> write(2, "Gdk-\33[1;32mMessage\33[0m: \33[34m16:"..., 99) = 99
> exit_group(1)                           = ?
> +++ exited with 1 +++

When running on Weston there is no getpeername syscall

**Comment by SirCmpwn** [comment]
You should probably be tracing sway and weston, not firefox.

**Comment by progandy** [comment]
Are you sure that the error message comes from sway or did you run firefox in your sway session?
Firefox has a sandbox bug with webgl that produces this error message.
https://bugzilla.mozilla.org/show_bug.cgi?id=148755
Firefox is also no native wayland application.

**Comment by hanko34** [comment]
The error message above also appears with other native wayland application (using gtk)

Here are the strace logs for sway and weston
[logSwayStrace.txt](https://github.com/swaywm/wlroots/files/2290469/logSwayStrace.txt)
[logWestonStrace.txt](https://github.com/swaywm/wlroots/files/2290471/logWestonStrace.txt)

@progandy Are you sure the referenced link is correct? It does not mention webgl or any related issue.

And yes I know that firefox still has only experimental wayland support but since it works on weston, we will probably have to fix it here it firefox is ever going to work properly on sway/rootston

**Comment by progandy** [comment]
Sorry, somehow I must have deleted a "0" from the ticket id. Here is the correct [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1480755)

**Comment by emersion** [comment]
Can you still reproduce this issue?
