### ISSUE TITLE
[GDM] [DRM] Atomic commit failed

### ISSUE THREAD

**Issue by XakepSDK** [swaywm/wlroots#1206]
I'm getting these errors after log in. Screen shows gray gdm background until i switch to another tty and back.
I have 2 monitors. Arch Linux, latest updates. Sway installed using this AUR: https://aur.archlinux.org/packages/sway-wlroots-git/
> wlroots-git-r2996.633663cd-1-x86_64.pkg.tar.xz
> sway-wlroots-git-1.0.alpha.5.r196.gde9e8045-1-x86_64.pkg.tar.xz
> 
```
aug 30 21:57:04 arch /usr/lib/gdm-wayland-session[25340]: 2018-08-30 21:57:04 - [backend/drm/atomic.c:55] DP-1: Atomic commit failed (modeset): Permission denied
aug 30 21:57:04 arch /usr/lib/gdm-wayland-session[25340]: 2018-08-30 21:57:04 - [backend/drm/atomic.c:55] VGA-1: Atomic commit failed (modeset): Permission denied
```

**Comment by emersion** [comment]
`Permission denied` generally means someone else is the DRM master. Not sure what to do here. Does it work with one screen? Does it work without GDM?

**Comment by XakepSDK** [comment]
I'll try with LightDM

**Comment by XakepSDK** [comment]
Works fine with LightDM

**Comment by SirCmpwn** [comment]
Report to GDM, it should release DRM before executing sway.
