### ISSUE TITLE
meson_options.txt:1:0: ERROR:  Unknown type feature.

### ISSUE THREAD

**Issue by fusion809** [swaywm/wlroots#1258]
Hi,

I've wanted to build this program, so that I can build swaywm. Unfortunately, I get the error:

```bash
Build dir: /data/GitHub/others/wlroots/build
Build type: native build

meson_options.txt:1:0: ERROR:  Unknown type feature.

A full log can be found at /data/GitHub/others/wlroots/build/meson-logs/meson-log.txt
```

This error occurs at the `meson build` phase of building this program. I'm trying to make a Sway 1.0 alpha 6 package for personal use (I know your warning to packagers, that's why this is for personal use only). I have all the dependencies for building without X support that is mentioned in the README. Here's a spec file I've tried using, although I've also tried the old fashion way of building it manually:

```bash
#
# spec file for package wlroots
#
# Copyright (c) 2018 SUSE LINUX GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#

Name:           wlroots
Version:	3100
%define commit f5658c2ca2b46b876ffeeaaff3c43d7073536244
Release:	1
License:	MIT
Summary:	A modular Wayland compositor library
Url:		https://github.com/swaywm/wlroots
Group:		System/GUI/Other
Source:		https://github.com/swaywm/wlroots/archive/%{commit}.tar.gz
BuildRequires:  meson
BuildRequires:  ninja
BuildRequires:  wayland-devel
BuildRequires:	pkgconfig(egl)
BuildRequires:	pkgconfig(glesv2)
BuildRequires:	pkgconfig(libdrm)
Buildrequires:  pkgconfig(gbm)
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:	pkgconfig(udev)
BuildRequires:	pixmap
BuildRequires:	pkgconfig(systemd)
BuildRequires:	pkgconfig(libcap)
BuildRoot:      %{_tmppath}/%{name}-%{version}-build

%description
A modular Wayland compositor library for Sway.

%prep
%setup -q -n %{name}-%{commit}

%build
%meson
ninja -C build

%install
%meson_install

%post

%postun

%files
%defattr(-,root,root)
%doc ChangeLog README COPYING
```

at the %meson stage it fails. But running `meson build` manually (in the repo on my PC) fails too with this error. Here's meson-log.txt:

```bash
Build started at 2018-09-23T19:13:32.421112
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.46.1
Source dir: /data/GitHub/others/wlroots
Build dir: /data/GitHub/others/wlroots/build
Build type: native build

meson_options.txt:1:0: ERROR:  Unknown type feature.
```

Oh and I'm building the latest commit f5658c2ca2b46b876ffeeaaff3c43d7073536244.

My OS is openSUSE Tumbleweed (20180920). 

Thanks for your time,
Brenton

**Comment by zzhuang-cancon** [comment]
Hello, I also encountered the same problem when compiling the code, did you find a solution? I read that my meson version is 0.45
![image](https://user-images.githubusercontent.com/56622764/79632068-88951700-818f-11ea-98de-25efe482e8aa.png)

**Comment by ascent12** [comment]
@zzhuang-cancon You're using a severely out of date version of Meson. We require at least version 0.51.2, and have a PR that's going to bump it up to 0.54.0.

I'm surprised Meson itself didn't tell you that, as we have the requirement listed in out project definition.

**Comment by zzhuang-cancon** [comment]
OK，thank you first , but I have tried to update with the update command, I want to upgrade the version to the latest, but the system gave me feedback that it is already the latest.
So I hope to find the latest version of the installation package of independent meson

**Comment by ascent12** [comment]
@zzhuang-cancon You can install meson with pip (as much as I don't really recommend language-specific package managers) or otherwise can run it directly from a git clone.
```sh
cd /path/to/wlroots
/path/to/meson/meson.py build
```

But considering your distribution doesn't have the required meson version, it's probable you don't have some of the required versions of some of our other dependencies.

**Comment by Emantor** [comment]
@zzhuang-cancon Looking at the screenshot, this does not seem to be related to wlroots.

**Comment by zzhuang-cancon** [comment]
@ascent12  hello， i install the meson with the command: pip3 install meson and then i input 'meson build', it still failed.
look below :
![image](https://user-images.githubusercontent.com/56622764/79815723-f02bac00-83b3-11ea-94f9-4be232264ede.png)

![image](https://user-images.githubusercontent.com/56622764/79815783-2406d180-83b4-11ea-82dd-e442592d6192.png)

**Comment by zzhuang-cancon** [comment]
@ascent12  hello, i install the meson with the command: pip3 install meson and then i input 'meson build', it still failed.
look below :
![image](https://user-images.githubusercontent.com/56622764/79815890-70521180-83b4-11ea-88e5-bda1089d6ba4.png)
and then i use meson build.look:
![image](https://user-images.githubusercontent.com/56622764/79815921-88c22c00-83b4-11ea-9ea8-cde9184174ea.png)
 i think if  i need to setup the environment  path?

**Comment by solonfan** [comment]
Hi,zzhuang-cancon!

Try execute the below cmd on your shell terminal after meson0.54 be installed sucessed.
**export PATH=~/.local/bin**

![Screenshot from 2020-06-10 16-28-00](https://user-images.githubusercontent.com/15608567/84245284-65f00080-ab37-11ea-8ae1-246a8b0ece1c.png)

Thanks,
SolonFan
