### ISSUE TITLE
Add support for the DRM IN_FORMATS property

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1263]
See https://gitlab.freedesktop.org/wayland/weston/commit/f4456221db312f326dc0f16a306686d8c2f3c999

**Comment by agx** [comment]
libdrm's `modetest` lists these nicely.

**Comment by emersion** [comment]
Note that some drivers don't support it, e.g. vc4, so we'll need to fallback to the non-atomic property if it isn't available.

**Comment by emersion** [comment]
We now support this.
