### ISSUE TITLE
Touch gesture support status

### ISSUE THREAD

**Issue by xiamaz** [swaywm/wlroots#1293]
I am currently working on a small program for acting on touchscreen gestures (similar to touchegg, but working directly with libinput events).

One of the issues I have been faced with is abortion of touch events if they have been recognized as a gesture by the engine. There does not seem to be a straightforward way to do this in X11, but wayland enables the compositor to filter input events to subsequent applications. Thus it is possible to send TOUCH_CANCEL events on gesture recognition. Only this will need to be implemented on the compositor level. (https://blog.martin-graesslin.com/blog/2017/02/how-input-works-touch-input/)

wlroots currently does not seem to interpret libinput touchscreen events in any special way. Are there already plans on ways to support touchscreen gestures or should anything like this be handled by the window manager?

**Comment by SirCmpwn** [comment]
We were talking about this at XDC. I would like to build a backend-agnostic and generic gesture recognition library based on the designs given at https://github.com/swaywm/sway/issues/1904, which the compositor would then be responsible for using (not wlroots).

**Comment by xiamaz** [comment]
I have uploaded a WIP of the gesture recognition tool I am building. It currently only has depedencies to libinput, so it should work on wayland too.

Do you mean backend-agnostic, as in independent from libinput etc?

Your design looks pretty similar to some of the things I have included, although I currently did not work explicitly on rotations.

Also the current process only inspects gestures after they have been completed. I am in the process of rewriting this part to allow sending CANCEL signals to subsequent devices.

One of the issues I have, is that wanting visual feedback would make the whole process a lot more complicated, since we would somehow need to transmit cues before gestures are actually completed. Does your design already incorporate some mechanism for forwarding cues for animation etc?

Feedback always welcome:
https://github.com/xiamaz/libinput-touchscreen

**Comment by SirCmpwn** [comment]
>Do you mean backend-agnostic, as in independent from libinput etc?

Yep

>One of the issues I have, is that wanting visual feedback would make the whole process a lot more complicated, since we would somehow need to transmit cues before gestures are actually completed. Does your design already incorporate some mechanism for forwarding cues for animation etc?

I think this would take the form of an event indicating a gesture has started, guesses as to which gesture it might be, and the progress of each gesture to completion (which could be 0..1, or more than 1 if the user drags far enough).

**Comment by SirCmpwn** [comment]
Folding this into the main issue
