### ISSUE TITLE
Layer shell overlay vs. fullscreen surfaces

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#1300]
A layer shell surface of type ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY should be above any full screen surfaces. This does not seem to be currently the case. I can reproduce this with evince in full screen mode and then e.g. waiting for phosh's lock screen to kick in. Evince is the topmost surface then making it impossible to unlock the screen.

Ran into this while doing a presentation with evince's surface on HDMI-A-1 (using two outputs in total HDMI-A-1 and eDP-1)

I experienced this on 2f484537181c515082b632f9d575613abda72a48 not latest master.

**Comment by emersion** [comment]
This is a rootston bug. Cannot reproduce in sway.
