### ISSUE TITLE
kitty / glfw input issues

### ISSUE THREAD

**Issue by SWW13** [swaywm/wlroots#1306]
When I ran `kitty` a second time in a wlroots / sway session any instance of `kitty` does no longer receive input.

I tested with commit c5452feb773496a6631f35a4b49355ddd052d555, but it was also broken same weeks ago and is with the current master (haven't tested them in detail).
`sway` (alpha) and `rootston` are affected, `weston` works fine.
The `glfw` examples are also affected (haven't tested them in detail).

I minified my test case:
- run `rootston -E kitty -l9`
- type and execute `ls` in kitty(1) -> works
- type and execute `kitty` -> works
- kitty(2) opens -> no input
- close kitty(2) with Ctrl+E
- kitty is now active -> no input

Here is the corresponding log: [rootston.log](https://github.com/swaywm/wlroots/files/2474945/rootston.log)

**Comment by Ongy** [comment]
Hm, XWayland. Doesn't glfw have a wayland backend?

Anyways, the most interesting thing I see is
`2018-10-13 02:34:39 - [xwayland/xwm.c:1224] unhandled X11 event: FocusOut (10)` when you switch focus from first to second kitty I guess.
Oh and `2018-10-13 02:34:42 - [xwayland/xwm.c:1200] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 314, value 6291470` sounds interesting.

**Comment by virome** [comment]
Are you running it with KITTY_ENABLE_WAYLAND=1?

**Comment by SWW13** [comment]
Oh, didn't knew `kitty` doesn't use wayland as default. With `KITTY_ENABLE_WAYLAND=1` does work as expected.

**Comment by emersion** [comment]
Cannot reproduce in sway or rootston with Xwayland.
