### ISSUE TITLE
warning: type of 'get_x11_backend_from_backend' does not match original declaration

### ISSUE THREAD

**Issue by skrps** [swaywm/wlroots#1311]
I submitted a recipe for compiling wlroots and Sway alpha for Void Linux, for early feedback on the scripts, but I found the following warnings when compiling wlroots:

```
../include/backend/x11.h:75:25: warning: type of 'get_x11_backend_from_backend' does not match original declaration [-Wlto-type-mismatch]
 struct wlr_x11_backend *get_x11_backend_from_backend(
                         ^
../backend/x11/backend.c:92:25: note: 'get_x11_backend_from_backend' was previously declared here
 struct wlr_x11_backend *get_x11_backend_from_backend(
                         ^
../backend/x11/backend.c:92:25: note: code may be misoptimized unless -fno-strict-aliasing is used
```

I skimmed through the code, and the declaration and the definition seems to be the same...  But I'm perhaps short sighted here, so I brought this little problem for you to see.

Here's the [Travis CI job log][travis-log].  Also here are the [recipes for wlroots and Sway alpha][wlr-pr], in case one wishes to see which flags are set etc., if they somehow influence how wlroots is built.  The rev used for wlroots is the one recommended to be used with Sway 1.0-alpha.6, 842368e.

[travis-log]: https://travis-ci.org/void-linux/void-packages/jobs/441279630
[wlr-pr]: https://github.com/void-linux/void-packages/pull/3769

**Comment by emersion** [comment]
Probably a GCC bug.

**Comment by martinetd** [comment]
travis ci / recipe isn't enough to get full flags because your toolchain defaults (and for void linux probably some gcc wrapper) might change them.

I'd be curious to see the preprocessed file you have if you can reproduce manually - rebuild with ninja -v to get the full gcc line then replace `-o backend/x11/backend@x11@@wlr_backend_x11@sta/backend.c.o` by `-E -o whatever` and upload that file somewhere?
But tempted to agree with emersion that this smells fishy...

**Comment by ascent12** [comment]
Check you are on the latest wlroots commit. I fixed something related to this recently.

**Comment by skrps** [comment]
> Check you are on the latest wlroots commit. I fixed something related to this recently.

I'm using 842368e, as recommended [here](https://github.com/swaywm/sway/releases/tag/1.0-alpha.6).  Anyway, I'll test with the last commit to see if it goes away.

**Comment by skrps** [comment]
> rebuild with ninja -v to get the full gcc line then replace `-o backend/x11/backend@x11@@wlr_backend_x11@sta/backend.c.o` by `-E -o whatever` and upload that file somewhere?

[There you go.](https://ptpb.pw/kRWU)

**Comment by martinetd** [comment]
@skrps Thanks (although page doesn't load, timeout, but now I have seen the fix and understand the problem better it wouldn't have been enough anyway, the thing is another file includes this `backend/x11.h` without `wlr/config.h` included first (for example `backend/x11/output.c` and if you compare the output with -E there the struct will be different); so doesn't latest commit resolve this?
The commit ascent12 referred to ( 93a496f3a8df5601fe1daab3ec0377fffd5155cc ) should probably fix it and was a real bug, if that `output.c` used any field of the struct past the ifdefs it would just process bad values.

I'm actually kind of annoyed I can't reproduce the warning on my setup as I'd love to see this kind of warnings.

**Comment by martinetd** [comment]
Ah... I suppose it's rebuilding from a clean state just in case?

Well, then, hands-on debugging, take all files including `backend/x11.h` (where the struct is defined - I see `backend/x11/output.c`, `backend/x11/backend.c` and `backend/x11/input_device.c`) and do that -E command I asked you, looking at the `struct wlr_x11_backend` declaration in all three should be identical, is it?

It's either that struct or `wlr_backend` (the argument of the function), and that one has no reason to be different... Even if `wlr_x11_backend` looks identical it could be one of the embedded struct e.g. `wlr_keyboard` or another so have fun :/

I'd offer to look at all three files if you upload the other two but I still can't open your previous link :P

**Comment by skrps** [comment]
> Ah... I suppose it's rebuilding from a clean state just in case?

I thought I was rebuilding from a clean state, but I wasn't.  I built 814fc13 again, and the error doesn't show anymore.

Thanks for the help, guys.
