### ISSUE TITLE
Non primary GPUs not updating rendering.

### ISSUE THREAD

**Issue by JonathanILevi** [swaywm/wlroots#1328]
I have a multi-GPU setup with 3 GPUs.

Only the monitors on the main (first) GPU update what is rendering (the mouse pointer excepted).  They will update the rendering if I switch ttys and back.

Regardless of the version of Sway:
swaywm/wlroots@4e89a2139749c996d0c3ef6da5042d0a3cd9c9e6 is the last commit that works.
swaywm/wlroots@1280b4920d311e311e339a6f13b004bac6bc668f does not work but swaywm/wlroots@4e89a2139749c996d0c3ef6da5042d0a3cd9c9e6 reverts it.

When I capture the terminal with `script` I get this.

```
Script started on 2018-10-23 20:03:49+00:00
[jonathan@j-dtop-arch ~]$ sway
i3status: trying to auto-detect output_format setting
i3status: auto-detected "i3bar"
2018-10-23 20:03:52 - ^[[1;31m[backend/drm/legacy.c:21] DVI-D-3: Failed to page flip: No such file or directory^[[0m
2018-10-23 20:03:52 - ^[[1;31m[backend/drm/legacy.c:21] DVI-I-1: Failed to page flip: No such file or directory^[[0m
Exiting due to signal.
[jonathan@j-dtop-arch ~]$ exit
exit

Script done on 2018-10-23 20:04:03+00:00
```

**Comment by JonnyMako** [comment]
Looks like this is the same issue as https://github.com/swaywm/sway/issues/2800
