### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by rabits** [swaywm/wlroots#1343]
Hello Guys,

Found that it's pretty hard to build the wlroots and swaywm due to the requirements - I was lucky to install wayland-server 1.15.0 to my Ubuntu 18.04 LTS (from 18.10 packages) but looks like it will be harder if you will continue to have such unstable deps base.

Could you please consider to stick to some LTS package versions? Just to make sure that you will have enough alpha-beta testers.

Thank you

**Comment by rabits** [comment]
Unfortunately LTS versions can't provide most recent versions (due to reasonable LTS `stable` requirements), but providing stable base for the developers. Yeah, wayland is pretty much new thing, but maybe you guys can make this features, that requires new version, optional - enable them only if there is the required version, otherwise skip this feature / prepare workaround?

I know, it will take some time - but it's the necessary thing for any stable project that going to be used somewhere.

**Comment by ascent12** [comment]
It's been our "policy" (we never formally decided it) to keep up with the latest versions of our dependencies.
The entire ecosystem around wayland compositors evolves at a blistering pace, and we need to keep up with it (and even advance it ourselves).

It's also too much of a maintenance burden to try and support older versions of dependencies and see what works on whatever version that some distro uses.

**Comment by emersion** [comment]
Note that manually building the necessary dependencies isn't that much of a burden. It would be nice if someone was able to maintain a PPA.

**Comment by rabits** [comment]
PPA is not a good solution for the guys who actually working on the current installation - because many of the dependencies is pretty basic-system... And when the recent dependencies will ruin somone's setup... So it's kinda tricky.

But I got the point, thank you.

**Comment by CameronNemo** [comment]
@rabits sorry to not be of help one more year until 20.04 !
