### ISSUE TITLE
Support for rotating input devices

### ISSUE THREAD

**Issue by tokyovigilante** [swaywm/wlroots#1345]
On tablet and hybrid devices, rotating the output does not also rotate the associated touch or pen input device, so the touchscreen inputs no longer match the display when rotated. It would be useful to have an option to rotate input devices.

Also, for devices that have only a single rotation button, a function for `transform` to take an offset eg `swaymsg output LVDS-1 transform +90` to increase rotation by 90 degrees would be useful.

**Comment by emersion** [comment]
Actually, we already transform input events when you map an input device to an output. See `apply_output_transform` in `wlr_cursor`.

**Comment by tokyovigilante** [comment]
Oh right, have just set up the mappings for touch and pen input and the transforms work great, thanks! Closing this one.

**Comment by tokyovigilante** [comment]
Re-opening for `transform` offset

**Comment by SirCmpwn** [comment]
Reopening for what?

**Comment by emersion** [comment]
"Transform offset" would be a sway feature, not a wlroots feature.

**Comment by tokyovigilante** [comment]
Makes sense, thanks.
