### ISSUE TITLE
Grim cannot take a screenshot in sway-1.0 master, GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by mithodin** [swaywm/wlroots#1348]
With the latest master of sway and wlroots, grim fails to take a screenshot, saying "failed to copy output X11-1". I have filed a bug report there (https://github.com/emersion/grim/issues/22), but they claim it is a wlroots issue.

Therefore, I'm posting this bug here. I have attached a logfile. The last entry pops up every time I try to take a screenshot.

Now to avoid the (justified) anger, I am aware that using nvidia drivers is unsupported and if this bug is caused by that, I will be happy to just shut up about it, because I agree that nvidia needs to fix their shit. In my defense, I do not control the hardware on this machine and I need cuda support, so I'm kinda stuck with those shitty drivers. Sorry.

[sway.log](https://github.com/swaywm/wlroots/files/2533333/sway.log)

**Comment by emersion** [comment]
Can you try to reproduce with rootston? Please enable debug logs and upload the whole file.

>I am aware that using nvidia drivers is unsupported and if this bug is caused by that

Since you use the X11 backend, it _should_ work. We don't support nvidia on DRM.

**Comment by mithodin** [comment]
Here's a log. I'm starting rootston just like I normally would sway, open a terminal, try grim test.png, and close the session.

[rootston.log](https://github.com/swaywm/wlroots/files/2533748/rootston.log)
