### ISSUE TITLE
Use #if instead of #ifdef for config.h

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1365]
`#ifdef`s silently fail when `config.h` is not included. This has been a source of silent mistakes in the past. Instead we could `#define` constants in `config.h` with 0 or 1 and use `#if`.

Meson has:

```
conf.set10(name, bool)
```

**Comment by ascent12** [comment]
Something people don't generally know that the C preprocessor is that if you `#if` an identifier that doesn't exist as a macro, it'll just get replaced with 0. That alone won't fix it, but I guess the `conf.set10` will.

I'm for this change, but I also think we may want to unconditionally add `#include <wlr/config..h>` basically everywhere, at the beginning of every file, including all of our public headers, even if it's not technically required for that file.

**Comment by emersion** [comment]
>Something people don't generally know that the C preprocessor is that if you #if an identifier that doesn't exist as a macro, it'll just get replaced with 0. That alone won't fix it, but I guess the conf.set10 will.

We can set `-Wundef` to make sure this doesn't happen.
