### ISSUE TITLE
Protocol error with clients binding a `wl_data_device` multiple times

### ISSUE THREAD

**Issue by vberger** [swaywm/wlroots#1379]
If a client binds a `wl_data_device` associated with a given seat more than one time, when a data source enters it, the client dies with the following protocol error from libwayland-client:

```
not a valid new object id (4278190080), message data_offer(n)
```

The clients do not crash when doing the same manipulation on weston.

I suspect wlroots is sending `wl_data_device.data_offer` to all the `wl_data_devices` using the same `wl_data_offer` object, while the `data_offer` message has a `new_id` argument, so the same data offer cannot be reused this way.

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/wlroots/issues/1041

**Comment by vberger** [comment]
Ah well, I guess I didn't search well enough.
