### ISSUE TITLE
GL_INVALID_OPERATION in glGetIntegerv(GL_IMPLEMENTATION_COLOR_READ_FORMAT: no GL_READ_BUFFER)

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1389]
This happens when using `wlr-screencopy-v1`. How to reproduce (at least on my setup):

1. Open sway/rootston/wayfire (probably all wlroots compositors)
2. Start wf-recorder (https://github.com/ammen99/wf-recorder)
3. Open a dmabuf/EGL client - it happens immediately after I open a Xwayland client, `weston-simple-dmabuf-drm` or `weston-simple-egl`, but `weston-simple-shm` doesn't break it.

The above GL error is printed to the log, which causes a change in the buffer format advertised to the client. This isn't handled by `wf-recorder`, causing it to misbehave (and being force disconnected by the compositor) but that is a bug in wf-recorder. This bug is about the GL errors in `wlroots`

My guess is that we need to properly bind the framebuffer when importing a dmabuf, or maybe we need to reset some other state.

**Comment by emersion** [comment]
Weird, there shouldn't be any buffer import between `wlr_renderer_begin` and `wlr_output_swap_buffers`.

**Comment by ammen99** [comment]
> Weird, there shouldn't be any buffer import between `wlr_renderer_begin` and `wlr_output_swap_buffers`.

But this isn't happening between `wlr_renderer_begin` and `wlr_output_swap_buffers` AFAIK, it happens during screencopy operation (which generally happens between frames, no?). The thing is, this error comes when querying the renderer for which GL format the buffer for screencopy should have.

**Comment by emersion** [comment]
The screencopy operation happens in `wlr_output_swap_buffers`.

**Comment by ammen99** [comment]
Not only. See https://github.com/swaywm/wlroots/blob/master/types/wlr_screencopy_v1.c#L222, this is where the error happens.

**Comment by ammen99** [comment]
Some other things I notice: this isn't directly related to creating a surface. Sometimes it works (dmenu opens, recording works) then I start typing in dmenu and at some point this bug happens. Maybe it happens if we have the following sequence:

1) swap buffers
2) import dmabuf
3) screencopy capture request
4) next frame

So 2) sets up some state which messes with 3), and if the order changes (like 3) before 2)) then it works - which could explain why it happens immediately sometimes, and sometimes after a few commits.

**Comment by emersion** [comment]
Oh, right. We probably need to move `preferred_read_format` in the output interface.
