### ISSUE TITLE
Implement screenshot protocol

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#139]
So the original idea for the screenshooter is to implement weston's protocol: https://github.com/wayland-project/weston/blob/master/protocol/weston-screenshooter.xml

Though, this protocol has some issues, discussed here: https://lists.freedesktop.org/archives/wayland-devel/2013-December/thread.html#12571. Also, this protocol is just a demo, not a standard.

Orbital has fixed one of them, by adding a `screenshot` interface: https://github.com/giucam/orbital/blob/gamma/protocol/screenshooter.xml

So we have 3 solutions:

1. Implement weston's protocol
2. Implement orbital's protocol
3. Design another protocol, and propose it as a standard

**Comment by ascent12** [comment]
I don't really want to invent our own protocols, unless we have a really good reason to: it just compounds the issue that there is no "standard".

Also, maybe this is something we should leave to the library users? The screenshot issues (i.e. security issues) are complicated, and nether of these protocols do anything to address it. The library user can decide if they want to implement a potentially insecure protocol, or can try with their own solutions. It's not a terribly large amount of code for them to write, and I don't think require any internal wlroots state.

**Comment by SirCmpwn** [comment]
We can implement it, but we might want to have a hook where the user can authorize a client to bind to it. We should implement a similar hook for the gamma control protocol.

**Comment by SirCmpwn** [comment]
Oh, and let's do the orbital protocol.

**Comment by ascent12** [comment]
How much effort would it be to do both? Most of it would be shared, anyway.

**Comment by SirCmpwn** [comment]
Eh...

**Comment by acrisci** [comment]
Maybe we should turn things on or off with compile flags?

**Comment by emersion** [comment]
@acrisci: compositors need to enable explicitly the screenshot interface so that shouldn't be an issue.

**Comment by Ongy** [comment]
It's not just about a global enable/disable.
At least I think this should be hookable for things like the [sway security configuration](https://github.com/SirCmpwn/sway/blob/master/sway/sway-security.7.txt).
To do this, the compositor has to have some control.

At least which clients are allowed to use this interface at all, maybe finer.

**Comment by emersion** [comment]
Should I add a binary in `examples` that takes a screenshot?

**Comment by SirCmpwn** [comment]
Sure, I guess.
