### ISSUE TITLE
cannot modeset 'DP-4': no CRTC for this connector

### ISSUE THREAD

**Issue by AndreasBackx** [swaywm/wlroots#1394]
I have 3 monitors connected, 2 of which are daisy chained and are not successfully being "modeset" and therefore not turning on.

This is in my sway config, DP-4 and DP-5 are the monitors that are not turning on:

```
set $monitor-center "DP-1"
set $monitor-right "DP-4"
set $monitor-left "DP-5"

output $monitor-center res 2560x1440@119.880997Hz
output $monitor-left res 2560x1440@59.951000Hz
output $monitor-right res 2560x1440@59.951000Hz
```

More output from commands, the error "cannot modeset 'DP-4': no CRTC for this connector" can be found on line 1563 of the sway log: https://gist.github.com/AndreasBackx/e28fd95a215dc2dad15d83fe0aae1801

If you'd like me to include some more information, feel free to ask.

**Comment by AndreasBackx** [comment]
I honestly don't know what I've updated in a month's time, but right now it seems to be working.

**Comment by AndreasBackx** [comment]
Now I'm getting the same problem again on a different machine. The machine is a Thinkpad X1C7 connected to [this](https://www.lenovo.com/us/en/accessories-and-monitors/home-office/Thunderbolt-Dock-Gen-2-US/p/40AN0135US) Thunderbolt 3 dock. All of the firmware is up-to-date on the machine itself, it might not be on Thunderbolt dock though because I cannot get it to update from a Windows VM whatever I try and I do not have access to another Windows laptop. My Windows desktop machine cannot detect it either, and it doesn't have Thunderbolt(though doesn't work over USB-C).

Here's a gist according to the DRM debugging info in the wiki: https://gist.github.com/AndreasBackx/0e860e51df024ad39a10c71dabb3d6cb

I probably won't be able to help much further as I will probably return the Thunderbolt 3 dock. Though let me know if I can help.

Also I don't know what I used for `drm_info` last time, the only thing I could find now was `drminfo` on AUR.

**Comment by Emantor** [comment]
Please post debug logs. @emersion meant this [drm_info](https://github.com/ascent12/drm_info).

**Comment by AndreasBackx** [comment]
> Please post debug logs. @emersion meant this [drm_info](https://github.com/ascent12/drm_info).

This gist has been updated with that info now.

> Edit: Intel supports only up to 3 displays at once, so you'll need to disable one.

When I close my lid, it will turn the eDP-1 display off. It will then enable the Acer display but the other Dell display still fails to turn on.

**Comment by Emantor** [comment]
Please try with `WLR_DRM_NO_MODIFIERS=1` in the environment variables.

**Comment by AndreasBackx** [comment]
> Please try with `WLR_DRM_NO_MODIFIERS=1` in the environment variables.

That doesn't seem to help unfortunately. The furthest I can get is 2 out of 3 even if the laptop's internal display is disabled: https://gist.github.com/AndreasBackx/ea09a23c584e22a8d0a9d9c92fd1238c

Sometimes if I fiddle a bit I can get the middle one to work, the Acer one, but then the right Dell one is disabled. I also for some reason cannot exit sway without disconnecting the Thunderbolt dock. It freezes Sway and sway reports a broken pipe:

```
Gdk-Message: 11:12:31.440: Error reading events from display: Broken pipe
Gdk-Message: 11:12:31.457: Error 104 (Connection reset by peer) dispatching to Wayland display.
```

**Comment by emersion** [comment]
```
[ 2165.384602] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000d4331a4a] requires 44 vcpi slots
[ 2165.384620] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000fd2c07dc] requires 44 vcpi slots
[ 2165.384635] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000fd2c07dc] not enough VCPI slots in mst state 0000000045ea632e (avail=19)
[ 2165.384720] [drm:intel_dump_pipe_config [i915]] [CRTC:51:pipe A] enable: yes [failed]
```

**Comment by AndreasBackx** [comment]
> ```
> [ 2165.384602] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000d4331a4a] requires 44 vcpi slots
> [ 2165.384620] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000fd2c07dc] requires 44 vcpi slots
> [ 2165.384635] [drm:drm_dp_mst_atomic_check [drm_kms_helper]] [MST PORT:00000000fd2c07dc] not enough VCPI slots in mst state 0000000045ea632e (avail=19)
> [ 2165.384720] [drm:intel_dump_pipe_config [i915]] [CRTC:51:pipe A] enable: yes [failed]
> ```

Okay, I thought that the 2 Dell ones were using MST together and that the other one was separate on its own stream (not sure about the correct term). I'll have a look at moving the cables around and check whether I can resolve it. Thank you so much for the quick help with the troubleshooting, I really appreciate it! :heart:

Is it possible for wlroots to give a better error message in the future?

**Comment by ascent12** [comment]
>Is it possible for wlroots to give an error message with more information in the future?

Unfortunately the kernel does not give us any information beyond "it didn't work", so there is no way for us to know.
