### ISSUE TITLE
Add support for unconstraining of layer-shell popups

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1425]
Currently the logic for unconstraining xdg-shell popups depends on the fact that the popup's topmost parent is an `xdg_shell_surface` which of course is wrong when the popup has been created on a layer-shell surface, resulting in a crash.

**Comment by emersion** [comment]
The main culprit seems `wlr_xdg_popup_get_toplevel_coords`, which walks up the xdg-surface tree until it finds a toplevel.

**Comment by ammen99** [comment]
There are three approaches that come to my mind to solve this:

1) Add some sort of a `wlr_surface_get_offset` which will return `surface->geometry.x/y` for xdg-toplevels, `surface->popup->geometry.x/y` for xdg-popups, and `0` for layer-shell/whatever surfaces.

2) Just special-case in `wlr_xdg_popup_get_toplevel_coords()` - we know that we will either encounter an xdg-shell surface, layer-shell surface or an xdg-popup, so it is just several cases to handle

3) Add a dedicated `layer_shell_popup_unconstrain`, which will basically be a copy-paste of `xdg_popup_unconstrain` 

I feel like the first one is the best, because in `3.` we will end up having duplicate code and in `2.` we get increasing complexity if in the future xdg-popups can be used with yet another shell protocol.

Of course, all of the solutions need some kind of special-casing, but I still think `1.` is the easiest to adapt to potential future changes. I even already have this function in wayfire :)

**Comment by emersion** [comment]
I'm not a fan of (1) because it leaks xdg-shell details (geometry) in `wlr_surface`.

I'd prefer something like (2), but we don't need to add special cases. We just need to check if the root is an xdg-surface, if not, assume a zero geometry offset.

Another solution would be to expect the caller to add the toplevel offset to the rectangle before calling `wlr_xdg_popup_unconstrain`.

**Comment by ammen99** [comment]
> I'd prefer something like (2), but we don't need to add special cases. We just need to check if the root is an xdg-surface, if not, assume a zero geometry offset.

Yes, but we generally assume when iterating that it is an xdg_surface which means we also need to change the loop.

**Comment by emersion** [comment]
Yes. The patch is basically `if (wlr_surface_is_xdg_surface(surface)) return;`.
