### ISSUE TITLE
Mouse capture support?

### ISSUE THREAD

**Issue by daenney** [swaywm/wlroots#1430]
In a few different issues on Sway it's been noted that certain games don't work that do their own mouse capturing. Those tickets have always been closed with "will be fixed with wlroots" but I've been unable to find any indication of whether that happened.

So I'm curious, is this supposed to already work? I tried playing Minecraft under Sway and unfortunately it seems this isn't implemented yet, but I'm unsure whether that's something in wlroots missing or something peculiar Minecraft might be doing?

**Comment by ddevault** [comment]
We have done the wlroots work for this feature and still need to do the sway work. This would be a great place for you to contribute to sway!

**Comment by daenney** [comment]
Would you be able to tell me what to look and where to start? I'd love to contribute, but I'm honestly a little lost.

**Comment by ddevault** [comment]
Actually, some of the wlroots work is still WIP: https://github.com/swaywm/wlroots/pull/1274

This was the first part of the work: https://github.com/swaywm/wlroots/pull/852
