### ISSUE TITLE
Support for multiple xwayland instances

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1442]
Would be better to let compositors start as many xwayland instances as they want.

I don't think a lot of things are blocking this. We probably just need to make the compositor set `DISPLAY` instead of setting it automatically. Since the compositor already sets `WAYLAND_DISPLAY` it pobably makes more sense anyway.

**Comment by Timidger** [comment]
Out of curiosity what is the use case for this? Sandboxing?

**Comment by emersion** [comment]
Yeah

**Comment by Freyr666** [comment]
Could this also be used to fix the annoying blurry upscale for X11 windows?

**Comment by emersion** [comment]
No.
