### ISSUE TITLE
Don't expose non-desktop DRM outputs

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1445]
The "non-desktop" property allows us to know when an output is not supposed to be used for regular desktops. This happens e.g. for VR headsets. We should probably ignore those outputs for now, at least until the DRM lease protocol is standardized.

**Comment by ddevault** [comment]
Related: #171

**Comment by guygastineau** [comment]
Is this still valid?  I am pretty new to the code base here, but I am interested in getting involved.

I was hoping to cut my teeth on some easier issues around here.

**Comment by ddevault** [comment]
I actually implemented this as part of https://github.com/swaywm/wlroots/pull/1730

If you want to pull it out into a separate change, I'm all for it.

**Comment by guygastineau** [comment]
Cool.  I will look into that.  It seems like it could take a while for that protocol proposal makes it through review.

I was also considering #2000  I don't have much experience with graphics, but I do have experience working matrices and n-dimensional arrays in multiple languages (hopefully that will help).  Even more experience with lazy IO actually...

Anyway, I can tell you all are busy here, so I wont expect a lot of hand holding for getting acquainted with the code base.  I will read your other PR to get more of a feel for `wlroots`; then I will start poking around the blending issue I referenced above.

Thank you for anwering my question :wink:

**Comment by ascent12** [comment]
@guygastineau Feel free to ask questions about anything on #sway-devel on freenode. There are some parts of the codebase that would be pretty difficult to understand without context (especially the backends) and people are more than willing to help, but do make sure you stick around; people won't always be able to get to your questions immediately.

**Comment by guygastineau** [comment]
@ascent12 Thank you for the info ;)

**Comment by RPigott** [comment]
I suppose this can be closed now?

**Comment by bl4ckb0ne** [comment]
Yup! Fixed in #2929
