### ISSUE TITLE
Mention that xkeyboard-config is required

### ISSUE THREAD

**Issue by Hjdskes** [swaywm/wlroots#1446]
The README mentions that xkbcommon is required. On some distributions (e.g. Arch), when installing libxkbcommon you also get xkeyboard-config. On buildroot, however, both are separate and you need to enable both in `make menuconfig` for wlroots-based compositors to work. I suggest you mention this in the README for future reference, to avoid confusion like I had just now. Without xkeyboard-config installed, compositors do not start properly, do not respond to keyboard presses and e.g. rootston's `-E` option does not launch any application.

**Comment by emersion** [comment]
Maybe we could improve error logging when this happens. Can you track down what fails when `xkeyboard-config` isn't available? I suspect `-E` works but apps crash.

**Comment by Hjdskes** [comment]
Tracking down what happens when xkeyboard-config isn't installed is a little complicated, since I am running this on an embedded device (a Raspberry Pi), that has no logging whatsoever. I cannot change to a different TTY, because the keyboard is nonfunctional once a compositor has launched.

**Comment by Hjdskes** [comment]
I could do a build with SSH installed, but at the moment my builds do not have SSH. Redirecting rootston's output to a file doesn't work, as there is no way to get out of rootston but unplugging the power.

I'll get back to you later when I have a build with SSH going, but it could be a while.

**Comment by emersion** [comment]
This seems to be printed in case the layout cannot be loaded:

```
xkbcommon: ERROR: Couldn't find file "symbols/nonexistinglayout" in include paths
xkbcommon: ERROR: 1 include paths searched:
xkbcommon: ERROR: 	/usr/share/X11/xkb
xkbcommon: ERROR: 1 include paths could not be added:
xkbcommon: ERROR: 	/home/simon/.xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
2019-03-02 14:09:20 - [rootston/keyboard.c:330] Cannot create XKB keymap
2019-03-02 14:09:20 - [rootston/seat.c:826] could not allocate keyboard for seat
```

I believe this is explicit enough. You should ask your distribution to add warnings when installing xkbcommon.
