### ISSUE TITLE
xwayland clients vsync to 60 Hz instead of 144 Hz

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/wlroots#1456]
I've two 144 Hz monitors, but some xwayland clients seem to incorrectly sync to 60 Hz instead. Examples include glxgears, mpv ([issue](https://github.com/mpv-player/mpv/issues/6431)), firefox, Half-Life 1 (game, uses SDL).

I'm not sure whose fault this is since weston seems to exhibit the same behavior and mpv devs seem to be confused too (see the issue). However this is definitely not the expected behavior of clients correctly vsyncing to my monitor's refresh rate.

I tested this on sway, rootston and weston, the behavior seems to be consistent between them.

**Comment by emersion** [comment]
Does `weston-info` show the current mode with 144 Hz? Can you try `weston-presentation-shm`?

**Comment by YaLTeR** [comment]
`weston-info` current modes:
```
        mode:
                width: 2560 px, height: 1440 px, refresh: 143.998 Hz,
                flags: current
```
and
```
        mode:
                width: 1920 px, height: 1080 px, refresh: 144.001 Hz,
                flags: current
```

`weston-presentation-shm` seems to render at 144 Hz correctly, here are some lines from its log:
```
   190: f2c  1 ms, c2p  7 ms, f2p  8 ms, p2p  6944 us, t2p   6795, [sce_], seq 1108479
   191: f2c  1 ms, c2p  7 ms, f2p  8 ms, p2p  6945 us, t2p   6874, [sce_], seq 1108480
   192: f2c  1 ms, c2p  7 ms, f2p  8 ms, p2p  6945 us, t2p   6809, [sce_], seq 1108481
   193: f2c  1 ms, c2p  7 ms, f2p  8 ms, p2p  6944 us, t2p   6855, [sce_], seq 1108482
   194: f2c  1 ms, c2p  6 ms, f2p  7 ms, p2p  6945 us, t2p   6861, [sce_], seq 1108483
   195: f2c  1 ms, c2p  6 ms, f2p  7 ms, p2p  6944 us, t2p   6851, [sce_], seq 1108484
   196: f2c  1 ms, c2p  6 ms, f2p  7 ms, p2p  6945 us, t2p   6852, [sce_], seq 1108485
   197: f2c  0 ms, c2p  7 ms, f2p  7 ms, p2p  6945 us, t2p   6845, [sce_], seq 1108486
   198: f2c  0 ms, c2p  7 ms, f2p  7 ms, p2p  6944 us, t2p   6837, [sce_], seq 1108487
   199: f2c  0 ms, c2p  7 ms, f2p  7 ms, p2p  6945 us, t2p   6857, [sce_], seq 1108488
```

**Comment by ascent12** [comment]
Possibly a mesa issue or even something else.
There is no special handling for 60 FPS anywhere inside sway/wlroots. Everything is driven completely by the monitor's refresh rate.

**Comment by haasn** [comment]
I agree that the mesa wayland WSI code is a good place to start digging for clues.

**Comment by haasn** [comment]
Actually, given that this is xwayland, the wayland WSI code is irrelevant. How is xwayland even handled architecturally? Does mesa have specific code for glx under wayland, or is this an emulation provided by some other component?

**Comment by emersion** [comment]
>Edit: Seems that XWayland is a patchset on top of X.org. If all the compositors use the same xwayland binary/library/whatever, that would also be a great candidate to look for clues.

Xwayland is an executable implementing an X11 server which forwards requests to a Wayland compositor. It's shared between all compositors, code is in `hw/xwayland/` in xorg-server.

Does `xrandr` output the correct refresh rate?

The presentation code would be a place to check for bugs, assuming mpv uses the X11 present extension.

**Comment by YaLTeR** [comment]
`xrandr` does seem to output the correct refresh rates:
```
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 8192 x 8192
XWAYLAND0 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   2560x1440    143.91*+
XWAYLAND1 connected 1920x1080+2560+360 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080    143.88*+
```

(actually, it doesn't seem to update properly when switching output refresh rates in sway, but that's besides this issue as it reports 144 Hz and I'm testing at 144 Hz)

**Comment by haasn** [comment]
As a hack-around until this bug is resolved, you could try forcing `vblank_mode=0` (either as an env var, or in `.drirc`)

**Comment by emersion** [comment]
Thanks! This indeed seems to be an Xwayland issue per comments in the xserver tracker, so I'll close this for now.
