### ISSUE TITLE
rootston: resizing rotated clients is broken

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/wlroots#1458]
wlroots 1840c8c130c91b24bc980dbdaa2d701144ef5cb0

Resizing rotated clients behaves very strangely and leaves garbage pixels around.

1. Open a client.
2. Rotate it.
3. Try resizing it.

[Example video.](https://my.mixtape.moe/znbxtp.mp4)

**Comment by panaman67** [comment]
@YaLTeR Can close? (rootston archived)

**Comment by YaLTeR** [comment]
@emersion seems to be closing these so yeah.
