### ISSUE TITLE
Build fails from AUR

### ISSUE THREAD

**Issue by elsandosgrande** [swaywm/wlroots#1460]
[glxinfo.txt](https://github.com/swaywm/wlroots/files/2752021/glxinfo.txt)
[glxinfo egl.txt](https://github.com/swaywm/wlroots/files/2752022/glxinfo.egl.txt)
[meson-log.txt](https://github.com/swaywm/wlroots/files/2752023/meson-log.txt)
[pakku AUR helper terminal output.txt](https://github.com/swaywm/wlroots/files/2752028/pakku.AUR.helper.terminal.output.txt)
[all egl packages found with pakku.txt](https://github.com/swaywm/wlroots/files/2752037/all.egl.packages.found.with.pakku.txt)
[all installed packages.txt](https://github.com/swaywm/wlroots/files/2752039/all.installed.packages.txt)

*After going over some of the tickets in /sway and /wlroots, I have found that it would be most beneficial to provide as many details about my Antergos installation and about the build process and failure that could possibly be beneficial in any way concievable to me. **Do correct me if I am mistaken on this note.***

I have tried to install sway and wlroots from the AUR -git packages due to the binaries available being out-of-date. As seen in the attachments, pkg-config located all build dependencies up to egl, but neither pkg-config nor cmake found the relevant binary. I have tried installing all packages found when searching egl in pacman other than those with nvidia in their name, since I don't think the AUR packages are relevant, but I included them as well in one of the files just in case, which is also why I included a list of all of my installed packages as well.

***To note, the Wayland sessions of KDE Plasma and GNOME 3 work just fine** (KDE's implementation is subpar relative to GNOME's, but that's neither here nor there in the end).*

*If this issue has already been referenced with the solution somewhere else where it is easily found, please forgive me (this is my first time opening a ticket and I have been looking around a bit for the issue).*

I thank you in advance and have a nice day and good luck with the project, whatever the outcome of this issue is!

**Comment by emersion** [comment]
libegl is provided by mesa. Do you have it installed?

**Comment by emersion** [comment]
Seems like it. Though `pkg-config --cflags egl` fails. Probably an issue with your distribution's mesa packaging.

On my system:

```
> pkg-config --cflags egl
-I/usr/include/libdrm
> cat /usr/lib/pkgconfig/egl.pc 
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: egl
Description: Mesa EGL Library
Version: 18.3.1
Requires.private: x11, xext, xdamage >=  1.1, xfixes, x11-xcb, xcb, xcb-glx >=  1.8.1, xcb-dri2 >=  1.8, xxf86vm, libdrm >=  2.4.75
Libs: -L${libdir} -lEGL
Libs.private: -lpthread -pthread -lm -ldl
Cflags: -I${includedir}
```

**Comment by elsandosgrande** [comment]
> Seems like it. Though `pkg-config --cflags egl` fails. Probably an issue with your distribution's mesa packaging.
> 
> On my system:
> 
> ```
> > pkg-config --cflags egl
> -I/usr/include/libdrm
> > cat /usr/lib/pkgconfig/egl.pc 
> prefix=/usr
> libdir=${prefix}/lib
> includedir=${prefix}/include
> 
> Name: egl
> Description: Mesa EGL Library
> Version: 18.3.1
> Requires.private: x11, xext, xdamage >=  1.1, xfixes, x11-xcb, xcb, xcb-glx >=  1.8.1, xcb-dri2 >=  1.8, xxf86vm, libdrm >=  2.4.75
> Libs: -L${libdir} -lEGL
> Libs.private: -lpthread -pthread -lm -ldl
> Cflags: -I${includedir}
> ```

The command results in:

`pkg-config --cflags egl
Package xfixes was not found in the pkg-config search path.
Perhaps you should add the directory containing 'xfixes.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xfixes', required by 'xdamage', not found
Package 'xfixes', required by 'egl', not found`

**Comment by emersion** [comment]
Please report this to your distribution.

**Comment by elsandosgrande** [comment]
Don't know how, so basically gotta go git all of the way, huh?

**Comment by elsandosgrande** [comment]
> SDDM does not support Wayland.

Then how am I logging into Plasma Wayland through it?

**Comment by ddevault** [comment]
>Err, I'm thinking of a different display manager.

**Comment by elsandosgrande** [comment]
> > Err, I'm thinking of a different display manager.

Oh, sorry, didn't see it!

**Comment by elsandosgrande** [comment]
So, the issue seems to be `Package xfixes was not found in the pkg-config search path.`. pkg-config requires xfixes for egl, so the terminal output given is that egl was not found, when, in fact, it's xfixes that is missing (even though the package is installed).

**Comment by elsandosgrande** [comment]
> You could also try to install the missing xfixes dependency, but I'm not sure it'll fix your issue. It should definitely be a dependency of mesa in the Antergos package.

Well, libxfixes is installed, so that did not help.
