### ISSUE TITLE
wlroots 0.3

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1465]
This changelog is provisional. It includes breaking changes up to 018727b1fc41dcd739ab464c84581c44dd1497ca.

* * *

wlroots 0.3 contains the following breaking changes:

* gtk-primary-selection: refactor everything, untie from seat (#1397). Various properties related to this unstable protocol have been removed from `wlr_seat` and `wlr_seat_client`. Use `wlr_gtk_primary_selection_*` instead.
* output: switch `wlr_output_swap_buffers` damage to output-buffer-local coords (#1403)
* Standardize the `wlr_box` input paramaters (#1441). The destination parameter is now always the first one.
* Remove `wlr_xdg_surface_send_close` (#1461). Use `wlr_xdg_toplevel_send_close` and `wlr_xdg_popup_destroy` instead.
* data-device, primary-selection: add request_set_selection (#1402). Compositors now need to listen on `wlr_seat.events.request_set_selection` and `wlr_seat.events.request_set_primary_selection`, then decide whether or not to accept the request with `wlr_seat_set_selection` and `wlr_seat_set_primary_selection`.
* `wlr_seat_client_send_selection` has been removed, this is an internal function (#1427)
* `wlr_data_source_finish` has been removed, this is now handled by `wlr_data_source_destroy` (#1427)
* `wlr_data_source_cancel` has been renamed to `wlr_data_source_destroy` (#1427)
* Compositors now need to listen on the `wlr_pointer.frame` or `wlr_cursor.frame` events, and call `wlr_seat_notify_frame` (#1503). If you're simulating pointer events, you'll need to call `wlr_seat_notify_frame` manually.

**Comment by jubalh** [comment]
Are you planning to have a regular ChangeLog file?

**Comment by emersion** [comment]
wlroots 0.3 has been released: https://github.com/swaywm/wlroots/releases/tag/0.3

>Are you planning to have a regular ChangeLog file?

New features and improvements will not be included, sorry.

**Comment by martinetd** [comment]
I think he meant having what you wrote in the github releases notes in a file.

I'd second having this info somewhere within the git repository, would have been fine to have the info as the tag annotation but now it's been created that is too late to change, so a file makes sense -- if github disappears tomorrow I wouldn't know where to find the current changelog entry (well, it's in my mailbox, but everyone isn't subscribed)

**Comment by ddevault** [comment]
I don't want a changelog file but we could start annotating the tags

**Comment by ddevault** [comment]
I don't want to maintain one. I think tags are better.

**Comment by jubalh** [comment]
Well I'm okay with annotated tags, so thanks for that.

Though I think the amount of work is the same. Writing the changes into the tags or writing them in a file. I don't see a difference in maintenance effort. But downstream can copy/install the whole ChangeLog file. In case some changes are missed and to the log later, then it's possible with a file but not with the tags (though that probably seldom happens).

**Comment by ddevault** [comment]
If that's desirable, downstream should be able to extract a changelog file from the tags with some light scripting.
