### ISSUE TITLE
xwayland: _NET_CLIENT_LIST support

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/wlroots#1469]
`_NET_CLIENT_LIST` (https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472723904) contains, as far as I understand, all top-level X windows. It's used by e.g. the [obs X capture plugin](https://github.com/obsproject/obs-studio/blob/22.0.3/plugins/linux-capture/xcompcap-helper.cpp#L127-L160) to enumerate windows to capture.

**Comment by emersion** [comment]
This won't work for Wayland clients. I'm not sure we want to implement this.

**Comment by emersion** [comment]
I'd rather patch OBS to support either the screencopy protocol or xdg-desktop-portal.
