### ISSUE TITLE
Popup menus are blurry in rootston with HiDPI

### ISSUE THREAD

**Issue by myfreeweb** [swaywm/wlroots#1472]
In GTK apps:

![menu-fs8](https://user-images.githubusercontent.com/208340/51282658-bd4b7900-19f6-11e9-9eb4-0ce7f22c851c.png)

In some Qt apps:

![menu-picard-fs8](https://user-images.githubusercontent.com/208340/51282965-b2ddaf00-19f7-11e9-8dbf-2bcad56a5228.png)

But not others:

![menu-krita-fs8](https://user-images.githubusercontent.com/208340/51282952-a5282980-19f7-11e9-965a-c23fc8aaa555.png)

**Comment by emersion** [comment]
Maybe missing some `round` call somewhere...
