### ISSUE TITLE
Huion tablet pressure do not work

### ISSUE THREAD

**Issue by ernierasta** [swaywm/wlroots#1535]
Hi,
first - **thank you** all for such amazing work on wlroots/sway.

I am using current master of wlroots (with -DWLR_USE_UNSTABLE=true) and sway.
My tablet is HUION which works:

```
Input device: HID 256c:006e Pen
  Type: Tablet tool
  Identifier: 9580:110:HID_256c:006e_Pen
  Product ID: 110
  Vendor ID: 9580
  Libinput Send Events: enabled
```
But in Krita and Gimp pressure is not working. Is that expected at current stage or is that a problem with my environment. It is working fine under i3/Xorg.

And is there a way to setup tablet buttons? In xorg tablet occurred as separate device (Pad) so buttons can be setup by `xsetwacom`, which obviously can not work under Wayland.

**Comment by ddevault** [comment]
Sway has only basic drawing tablet support.

**Comment by emersion** [comment]
Related sway issue: https://github.com/swaywm/sway/issues/2288
