### ISSUE TITLE
Reader view shortcut in Firefox-wayland doesn't work

### ISSUE THREAD

**Issue by Vorsplummi** [swaywm/wlroots#1542]
Using the reader view shortcut (Control+Alt+r) doesn't work in Firefox-wayland. Instead of going to reader mode the webpage will refresh. Firefox via XWayland works fine and so does Firefox-wayland on Weston.

I'm using the master version of Wlroots and Mozilla Firefox 65.0 from Fedora repositories. 

I tested this on Sway on Rootston.

[Firefox debug log](https://pastebin.com/uMWGMevy)

**Comment by myfreeweb** [comment]
> Control+**Alt**+r

Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1519940

**Comment by Vorsplummi** [comment]
> > Control+**Alt**+r
> 
> Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1519940

It seems to be the same issue.
