### ISSUE TITLE
wlroots 0.4

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1569]
This is a provisional changelog of breaking changes. It contains changes up to e77e53dae51a3a46e1327c0c53e69d6da695cc9a.

---

## Drag-and-drop has been refactored (https://github.com/swaywm/wlroots/pull/1517)

Compositors need to listen to the `wlr_seat.request_start_drag` event (just like selection). They need to accept the drag with `wlr_seat_start_{pointer,touch}_drag` or to reject it. See [the related rootston changes](https://github.com/swaywm/wlroots/pull/1517/files#diff-19f03743c0929495d76a97cfd459b7ceR606).

Additionally, the `new_drag_icon` event has been removed, use `start_drag` instead to collect the drag icon.

**Comment by ddevault** [comment]
wlroots 0.4 has been released: https://github.com/swaywm/wlroots/releases/tag/0.4
