### ISSUE TITLE
dnd sometimes unresponsive

### ISSUE THREAD

**Issue by p-hamann** [swaywm/wlroots#1576]
After a certain uptime dnd becomes unresponsive. Then dnd is functional again after restarting the compositor (sway in my case).

Btw, thank you for the great work :-)

**Comment by emersion** [comment]
Apparently serial validation stops working at some point.

See:
* https://github.com/swaywm/sway/issues/3538#issuecomment-466766603
* https://github.com/swaywm/sway/issues/3538#issuecomment-466681822

**Comment by ddevault** [comment]
Is this not a dupe?

**Comment by emersion** [comment]
Nope, the sway one is "doesn't work when there's a floating window", this one is "works but doesn't after some time". The other issue has been used as a general "it doesn't work" issue, so it's pretty confusing.

**Comment by p-hamann** [comment]
I still could not identify the triggering event. Anyway, after a while - sometimes after a short and sometimes longer time - dnd is unresponsive in all native wayland windows. In xwayland windows, on the other hand, it works consistently
