### ISSUE TITLE
Error at 268:3: Tables cannot be indented

### ISSUE THREAD

**Issue by aspieln3r** [swaywm/wlroots#1597]
I cannot install sway on my arch system.

[fsinft@s15s510un][~/git-clones/sway]$ sudo ninja -C build install                                                                                                                                                      
[sudo] password for fsinft: 
ninja: Entering directory `build'
[6/274] Generating sway-ipc.7 with a custom command.
FAILED: sway-ipc.7 
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway-ipc.7.scd > sway-ipc.7'
Error at 268:3: Tables cannot be indented
[15/274] Generating 'protocols/8998617@@client_protos@sta/xdg-shell-client-protocol.h'.
ninja: build stopped: subcommand failed.

**Comment by emersion** [comment]
This is not a wlroots bug, and there is already a sway issue about it.
