### ISSUE TITLE
Don't expose output position via wl_output

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1610]
The reason for this is: any regular client using the position from `wl_output` is broken and needs to be fixed.

Another reason is that it'll simplify our `wlr_output` code.

I've taken two steps to improve the current situation:

* Warning client writers that they shouldn't use the position information from `wl_output` in the protocol: https://gitlab.freedesktop.org/wayland/wayland/commit/8c121e10178070f23a06c438a292703fe76d5c06
* Adding xdg-output support to `weston-info` so that it's still easy to find out the position of outputs from the CLI: https://gitlab.freedesktop.org/wayland/weston/commit/b49af1ed199a2b69350447f5d8aa4f66c6fa7796

**Comment by ascent12** [comment]
Sounds good to me.
