### ISSUE TITLE
Consider offering deb builds in your releases please

### ISSUE THREAD

**Issue by wade-welles** [swaywm/wlroots#1619]
The debian repos are lagging and getting files directly off their servers is a giant pain. It would be nice to be able to get the debs from you directly. 

There are plently of programs which automate taking a binary and creating a *.deb file.

**Comment by RedSoxFan** [comment]
We do not supply packages for any distribution, only source code, and this is not something that is going to change. All packages are created and maintained by volunteers who want wlroots to be in the repos for the distro(s) of their choosing.

If you feel that the debian repos are lagging, I would suggest reaching out to the maintainer of the debian package and asking how you can help.
