### ISSUE TITLE
When you launch Wine window, half of the screen is not responding for mouse click

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1632]
**Game**: NosTale
**Wine**: 4.1-gallium-nine, 4.3-staging, 4.3 unmodified
**Description**: If you launch NosTale it does not respond for clicks at right part of screen, BUT mouse is captured on different monitor for different applications.
Also if you switch window size to windowed and back to fullscreen everything works just fine.
**Sway**: 1.0-6
**wl-roots**: 0.5.0-1
**xorg-server-xwayland**: 1.20.4-1

**Comment by emersion** [comment]
We need a debug log.
