### ISSUE TITLE
When moving window from non-scaled monitor to scaled and otherwise, window content does not fit window container

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1639]
![test](https://user-images.githubusercontent.com/21007545/55024392-09222c00-4fff-11e9-997f-ef2d614f4e41.png)

**Comment by RedSoxFan** [comment]
Are you only experiencing this with the wayland version of firefox? If so, this is a firefox bug and can be tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1528581

**Comment by ddevault** [comment]
Aye, this seems like a Firefox bug to me. We definitely send Firefox the info it needs to handle this correctly.
