### ISSUE TITLE
Use libinput's seat key state handling

### ISSUE THREAD

**Issue by whot** [swaywm/wlroots#1644]
Apologies if this is misfiled, I just stumbled across this while looking for something else in the sources.

`keyboard_key_update()` updates the keyboard state for the first press and the last release of a specific key. At least some part of the logic here can be punted to libinput with `libinput_event_keyboard_get_seat_key_count()`. That function returns the number of times that particular key is held down on all keyboards attached to this current physical seat. So instead of manually counting it, you can just handle the event as press when it switches from 0 to 1, and as release when it switches from 1 to 0.

**Comment by ddevault** [comment]
Thanks for the tip! The catch is that the `wlr_keyboard` type is an abstraction over multiple keyboard backends - and libinput isn't the only one. This code works for libinput, x11, wayland, headless, and rdp keyboards alike.

**Comment by whot** [comment]
ah, right, fair call. thanks and sorry for the noise.
