### ISSUE TITLE
Steam under XWayland is not interpreting mouse clicks correctly

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1645]
Two monitors, one FullHD, second with scale 1.75, Steam from Arch repo, newest packages.

**Comment by HoshiYamazaki** [comment]
So the problem is, when I get dropdown menu for example in library and try to click something, it doesn't work (for example Utilities - I wanted to install SteamVR to test WMR under OpenHMD).

**Comment by RedSoxFan** [comment]
Related swaywm/sway#1865

**Comment by emersion** [comment]
I actually think it's a duplicate.
