### ISSUE TITLE
Randomized display names (not sure if this is wlroots bug or something about drivers)

### ISSUE THREAD

**Issue by HoshiYamazaki** [swaywm/wlroots#1646]
So, I have problem because my display names get randomized, probably because of i915 and AMDGPU racing condition (yes, I have enabled iGPU in bios for Hackintosh). 
I'm not sure if this is wlroots bug and here is my workaround for that:
https://github.com/HoshiYamazaki/hidpi-dots/blob/master/disp.py

(I grep JSON from sway, and do conditional iteration, after that I apply to display correct settings)

Sorry if this is not thread for here 😞

**Comment by HoshiYamazaki** [comment]
This problem of course is causing `output` command in sway behaving incorrectly, so maybe there will be an partial solution (maybe aliases for certain displays?).

**Comment by emersion** [comment]
I don't think it's a wlroots bug. This also sometimes happen because of DisplayPort MST.

You can use output identifiers instead. For instance for this `swaymsg -t get_outputs`:

```
Output LVDS-1 'Chimei Innolux Corporation 0x1484 0x00000000' (focused)
  Current mode: 1600x900 @ 60.035000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Transform: normal
  Workspace: 4
  Available modes:
    1600x900 @ 40.020000 Hz
    1600x900 @ 60.035000 Hz
```

The identifier is "Chimei Innolux Corporation 0x1484 0x00000000".

**Comment by ascent12** [comment]
Right, the names the kernel gives the connectors are not guaranteed to be stable.
In a multi-gpu situation, they could get brought up at boot in a different order, meaning they'll get different connector numbers.
