### ISSUE TITLE
Unable to add DRM framebuffer with QEMU

### ISSUE THREAD

**Issue by Ypnose** [swaywm/wlroots#1656]
Hi there,
sway is unable to start in a guest, due to <code>Unable to add DRM framebuffer: No such file or directory</code> with QEMU 3.1.0. I remember it was working fine, few months ago.
I went to #sway IRC channel and ascent12 told me to post an issue about that.  
Weston is working fine, when it's launched with <code>weston-launch</code>.

Here the required logs:
[sway](https://gist.githubusercontent.com/Ypnose/ebbb2eb188141c7d4963c107cb84c686/raw/d8537ff8ba29883eca6463f6cc9dd28f34f9634e/sway.log)
[weston](https://gist.githubusercontent.com/Ypnose/0914374aabeecfbee9ac404949a3f59d/raw/b17fede92c719df78c4d110a223cbb5993851a02/weston.log)
[drm_info](https://gist.githubusercontent.com/Ypnose/81544cf728a1d1d9a63f81bd2d420063/raw/cc95bbde358522d196a642b2b7f331cc3fc77472/drm_info)

**Comment by CaptainBloodz** [comment]
Latest sway.log v1.0 , system-qemu-4-aarch64, no kvm
[sway.log](https://github.com/swaywm/wlroots/files/3169271/sway.log)
I don't think there's a DRM issue there, but please feel free to check by yourself.

**Comment by emersion** [comment]
>I don't think there's a DRM issue there, but please feel free to check by yourself.

Yeah. @Ypnose seems to be using a too old QEMU (and the legacy DRM interface). I'll close this, please try with the latest QEMU and re-open if it doesn't work.

**Comment by Ypnose** [comment]
I switched from <code>-vga std</code> to <code>-vga qxl</code> or <code>-vga virtio</code> and sway works fine. Sorry for the noise.

**Comment by ascent12** [comment]
Yeah, that makes sense.
I'll have to make sure to remember that detail whenever VMs are brought up; I normally just "default" to virtio when doing anything VM related myself.

Perhaps that is worth sticking on the sway wiki.
