### ISSUE TITLE
Platform does not have some core libraries

### ISSUE THREAD

**Issue by twaik** [swaywm/wlroots#1679]
Can you please fix build for platform which does not have libudev, libdrm, libinput, libgbm and librt? And make using of symbols eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL, eglQueryWaylandBufferWL, eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL, EGL_TEXTURE_EXTERNAL_WL not essential for platform which does not have those? Or just make them optional? I am trying to port Wlroots to Android, but I am afraid that I can make something wrong and my builds will fall with segfaults for some reasons.

**Comment by ddevault** [comment]
Would accept a patch making these optional, but you're going to have to write it yourself.

**Comment by emersion** [comment]
No librt? This is going to be annoying.

**Comment by twaik** [comment]
> No librt? This is going to be annoying.

librt is a part of libc in Android so it is unneded there.

**Comment by emersion** [comment]
Oh okay, that's not a big issue then. For libudev, libdrm, libinput, libgbm you'll just want to add a way to make the DRM/libinput backends optional. I'd definitely be happy to make `eglBindWaylandDisplayWL` et al optional, it's semi-legacy interfaces (we're still stuck with them but want to replace them).

**Comment by twaik** [comment]
So you can make it optional? I am afraid that I will break the build if try to make all of these symbols libs optional.

**Comment by emersion** [comment]
libinput symbols should only be used in the libinput backend. Some other backends are optional, see e.g. the X11 backend or the RDP one. The idea is to only compile the backend if the dependency is found.

It should be possible to make the DRM backend optional, though maybe it'll be a little more difficult because DMA-BUF code might use DRM headers in the renderer and other places.

**Comment by twaik** [comment]
DRM is problem because in Android only root users can connect to /dev/* but userspace applications have personal UIDs. Wlroots based compositor will be ran as normal application. Termux has libdrm as package but it is used only as dependency for other packages.

**Comment by ascent12** [comment]
We'd only need libdrm outside of the DRM backend for the <drm_fourcc.h> header, because that contains the canonical list of formats and modifiers. That makes it purely a build-time dependency, so on android, you shouldn't need to link to it or use it.

**Comment by twaik** [comment]
> you shouldn't need to link to it or use it.

It is perfect.

**Comment by twaik** [comment]
What is the current issue status?

**Comment by emersion** [comment]
We're waiting for you to send patches ;)

**Comment by twaik** [comment]
Ok.

**Comment by twaik** [comment]
Looks like all my devices do not support `EGL_KHR_surfaceless_context` extension. 
patch: https://gist.github.com/twaik/50b82028a0bd3192bec4d98b9ae522a6
```
2019-05-07 21:16:27 - [src/rootston/config.c:541] No config file found. Using sensible defaults.
2019-05-07 21:16:27 - [src/backend/headless/backend.c:90] Creating headless backend
2019-05-07 21:16:28 - [src/render/egl.c:176] Using EGL 1.4
2019-05-07 21:16:28 - [src/render/egl.c:177] Supported EGL extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_create_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_KHR_image EGL_KHR_image_base EGL_KHR_lock_surface EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update 
2019-05-07 21:16:28 - [src/render/egl.c:178] EGL vendor: Android
2019-05-07 21:16:28 - [src/render/egl.c:117] Supported dmabuf buffer formats: AR24 XR24 
2019-05-07 21:16:28 - [src/render/egl.c:262] Failed to make EGL context current
2019-05-07 21:16:28 - [src/render/wlr_renderer.c:208] Could not initialize EGL
2019-05-07 21:16:28 - [src/backend/headless/backend.c:119] Failed to create renderer
2019-05-07 21:16:28 - [src/backend/backend.c:280] failed to start backend 'headless'
2019-05-07 21:16:28 - [src/rootston/main.c:26] could not start backend
```

**Comment by emersion** [comment]
I guess what you really want is an Android backend?

**Comment by twaik** [comment]
Exactly. But it is impossible with the current renderer structure. And looks like wlroots has only EGL/GLESv2 renderer so I just can not use it on Android.

**Comment by emersion** [comment]
>But it is impossible with the current renderer structure.

Why?

>And looks like wlroots has only EGL/GLESv2 renderer so I just can not use it on Android.

Is EGL/GLES2 not supported on Android?

**Comment by twaik** [comment]
All of my Android devices do not support `EGL_KHR_surfaceless_context` extension. Without this extension [this line](https://github.com/swaywm/wlroots/blob/master/render/egl.c#L246) fails.

**Comment by twaik** [comment]
> Why?

Wlroots do not support any _not_GL_ renderer (i.e. pixman). Weston supports pixman, but I did not find how to change screen resolution in runtime. Wlroots/Rootston/tinywl support it, but I did not manage it to build it for Android correctly.

**Comment by emersion** [comment]
>All of my Android devices do not support EGL_KHR_surfaceless_context extension. Without this extension this line fails.

Without this extension it's possible to use a dummy pbuffer surface. See e.g. `gl_renderer_create_pbuffer_surface` in Weston's source code.

>Wlroots do not support any not_GL renderer (i.e. pixman). Weston supports pixman, but I did not find how to change screen resolution in runtime. Wlroots/Rootston/tinywl support it, but I did not manage it to build it for Android correctly.

Well it seems that EGL/GLES2 is supported on Android. If that's the case I don't know why you would want to use a pixman renderer.

**Comment by twaik** [comment]
> Without this extension it's possible to use a dummy pbuffer surface. See e.g. gl_renderer_create_pbuffer_surface in Weston's source code.

Did not work. Still fails.

**Comment by twaik** [comment]
Is it possible to use Android's EGLNativeWindowType window inside wlroots'es renderer?

**Comment by twaik** [comment]
Or is it possible to use software only rendering?

**Comment by ascent12** [comment]
The current renderer code works with EGLSurfaces, so if you create a `struct ANativeWindow` inside of a backend, that in theory should work. I've been very slowly working on a renderer redesign, and intend to stop using EGLSurfaces for using lower level allocations with GBM and EGLImageKHR instead. I don't know how this would affect Android.

Software rendering (outside of Mesa's llvmpipe etc.) is something that is not supported yet, but is something I intend to eventually add after the new renderer.

**Comment by twaik** [comment]
Yes, Android supports creating EGLSurface with EGLNativeWindowType (aka struct ANativeWindow*). But there is a problem. Some devices do not support surfaceless contexts (EGL_KHR_surfaceless_context) so renderer context should be initialized only when EGLSurface is created. Another problem that Android supports EGLImage only as an EGLImageKHR. 
Is it possible to adapt Weston's renderer?

**Comment by emersion** [comment]
Software rendering is now supported.
