### ISSUE TITLE
Handle hotplugging of DRM devices

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#1697]
Recently #1696 was merged as a workaround, but we eventually want to add proper support to hotplugging DRM devices. It's particularly interesting for things like docking stations or other things which are putting monitors over USB 3 or thunderbolt, but also applies to external GPUs.

### Just as a little bit of background

There are really 2 types of DRM devices: **display controllers** and **rendering devices**.

- A display controller is something that can have computer monitors attached, and would go through the DRM KMS API.
- A rendering device is obviously something we can do rendering with, e.g. via GBM + GLES/Vulkan.

When you're dealing with most desktop hardware, you're dealing with a device that does both, so naively, wlroots was designed treating the two types of devices as the same thing. On some ARM hardware, you'll find you have two different pieces of hardware doing these separately, and docking stations etc. are usually just a display controller without rendering capabilities.

### The point

Hotplugging display controllers is easy, hotplugging rendering devices (that we're using) is hard.
A display controller going away is basically the same situation as a few outputs being disconnected, but a rendering device going away means that we have to tear down all of our rendering state and try and bring it up elsewhere, which is not something I want to try.

Renderer v6 actually helps a lot towards this, as it moves a lot of the rendering code outside of the backend, but there would still be a bit of extra work to get this working properly.

- 1 DRM backend per display controller (possibly zero)
- Make sure there is absolutely no rendering code inside of the DRM backend
- Make wlr_session aware of the difference between display controllers and rendering devices
- Make wlr_session listen for hotplug events and bring up and tear down DRM backends as necessary
- Kill the compositor if our chosen rendering device goes away (unless someone is masochistic enough to get this working properly)

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/wlroots/issues/1278

**Comment by ascent12** [comment]
Damn, I guess I missed that when I was going through the old issues, but I wanted to expand on what I think needs to be done.

**Comment by emersion** [comment]
Maybe you can add a comment there and close this one?

**Comment by ascent12** [comment]
Yup
