### ISSUE TITLE
rootston: dnd cursor unset when leaving surface

### ISSUE THREAD

**Issue by nyorain** [swaywm/wlroots#1698]
Tested with rootston: When you start a dnd session (e.g. weston-dnd) and then leave the surface it was started on, the cursor will be reset to the default cursor. Expected behavior would be to allow the source client of the dnd session to set the cursor until the session ends (even if the cursor leaves the source surface). Weston implements it like that. Also tested it with other dnd clients, shouldn't be an issue related to weston-dnd.
This way dnd sessions can't offer any feedback whether dropping is valid or not; this is usually done via the cursor image. From a first glance the issue doesn't seem to be in the wlroots library, but neither rootston nor sway show expected behavior.

**Comment by emersion** [comment]
I agree. I have a WIP patch to fix this, but IIRC allowing the dnd source client to change the cursor wasn't enough. It may just have been a bug in my patch though.

**Comment by ammen99** [comment]
This is a rootston bug, changing cursor when dragging outside of the surface works in Wayfire.

**Comment by panaman67** [comment]
@nyorain Can close as rootston no longer maintained?
