### ISSUE TITLE
Xwayland do not work while executed manually

### ISSUE THREAD

**Issue by twaik** [swaywm/wlroots#1712]
Hi. Tried to execute Xwayland without arguments (only display number) to be shown on rootston.
Log: https://gist.github.com/twaik/4978c995731d287f989cf83a7fc171f7.

**Comment by emersion** [comment]
You're not supposed to execute Xwyaland manually. rootston will do it for you.

**Comment by twaik** [comment]
I know about built in launcher, but it opens X applications inside of its WM. Manual launching allows to use Xwayland in fullscreen mode.

**Comment by ascent12** [comment]
@twaik If you're trying to run X nested, it sounds like you should be using [xephyr](https://en.wikipedia.org/wiki/Xephyr) instead. I'm not too sure how well hardware acceleration works, though.

**Comment by emersion** [comment]
I don't know how it can work or if it can work, but this is unsupported.

**Comment by twaik** [comment]
> it sounds like you should be using xephyr instead.

Implementing Wayland server for Android is much easier than porting Xorg to Android. Also it let us keep Xserver in separate process. For now I am trying to port Weston with pixman renderer.
