### ISSUE TITLE
Crash when `xwayland_surface_create` returns `NULL`

### ISSUE THREAD

**Issue by FreeFull** [swaywm/wlroots#1721]
https://github.com/swaywm/sway/issues/4203#issuecomment-500917642

This can be reproduced in both sway and rootston, by launching three instances of pysolfc.

**Comment by FreeFull** [comment]
I'm not sure if this bug is still reproducible. At least, I can't reproduce it using pysolfc any more (although that might be due to a change in pysolfc itself).

**Comment by emersion** [comment]
Here's a fix: https://github.com/swaywm/wlroots/pull/2343

>I'm not sure if this bug is still reproducible. At least, I can't reproduce it using pysolfc any more (although that might be due to a change in pysolfc itself).

Probably because libwayland doesn't create one timerfd per event loop timer anymore.
