### ISSUE TITLE
Decorations for nested wlroots sessions

### ISSUE THREAD

**Issue by sheenobu** [swaywm/wlroots#1725]
Is it possible to provide CSD decorations (maybe as part of rootston/tinywl examples) for using wlroots nested in another Wayland session?

wlroots version: 0.6.0 and master

Current behaviour: sway and rootston both create decoration-less windows when run inside of an existing Wayland compositor (Gnome, for me)

Expected Behaviour: sway and rootston have window decorations when running nested inside of an existing Wayland compositor.

If this just requires some guidance, that's fine too. Then it becomes searchable in the issues list.

(I'm all for SSD over CSD but my own system works best with Gnome right now, so I think I end up needing CSD )

**Comment by emersion** [comment]
>Current behaviour: sway and rootston both create decoration-less windows when run inside of an existing Wayland compositor (Gnome, for me)

This is a GNOME bug, they lack support for the xdg-decoration protocol.

**Comment by sheenobu** [comment]
It doesn't sound like GNOME will _ever_ support xdg-decoration?

**Comment by emersion** [comment]
Yes.

**Comment by sheenobu** [comment]
So some minimal CSD example for nested wlroots sounds... worth it?

**Comment by ddevault** [comment]
No, I have no intention of merging patches which add CSDs to wlroots.

**Comment by DemiMarie** [comment]
As a workaround, you can use the X11 backend instead of the Wayland backend.
