### ISSUE TITLE
rootston: Xwayland windows freeze on fullscreen

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/wlroots#1745]
`rootston.ini`:
```ini
[core]
xwayland=true

[keyboard]
meta-key = Logo

[bindings]
Logo+Shift+e = exit
Logo+q = close
Logo+m = maximize
Logo+Escape = break_pointer_constraint
Logo+Tab = next_window
Logo+Return = exec glxgears -fullscreen
```
Launching `rootston`, pressing `Logo+Return` to launch `glxgears` and then pressing `Logo+m` results in the following:
1. everything freezes for about 2 seconds;
2. one more frame of `glxgears` is drawn and the mouse cursor unfreezes;
3. a second later, everything freezes again for about a second;
4. the mouse cursor unfreezes, `glxgears` stays frozen.

Closing `glxgears` via `Logo+q` results in it hanging if launched from a terminal, and `Ctrl+c` is needed to quit it.

Rootston log: https://gist.github.com/YaLTeR/28ae376b565fff2e107c12fe01a48eb3#file-rootston-log

I observed similar behavior with another Xwayland client (a game), except it also crashed after hanging. Backtrace for that: https://gist.github.com/YaLTeR/28ae376b565fff2e107c12fe01a48eb3#file-backtrace

**Comment by emersion** [comment]
This isn't related to direct scan-out.

**Comment by emersion** [comment]
Can you reproduce in Weston?

**Comment by YaLTeR** [comment]
Weston acts... very strangely for me with `glxgears`. Attempting to maximize it or bring fullscreen seem to set the window to the correct size, but its position is way off, so it's not actually fullscreen. `weston-terminal` seems to be maximizing and fullscreening correctly though. So to sum up I wasn't able to test this.

**Comment by YaLTeR** [comment]
When running rootston as a Wayland client, upon maximizing `glxgears` just freezes and doesn't unfreeze.

[rootston.log](https://gist.github.com/YaLTeR/9eed08b3c64344088b274a234f8ec6d6#file-rootston-log)

There's an xcb error printed to the log when I hit maximize:
```
[xwayland/xwm.c:1264] xcb error: op ConfigureWindow (no minor), code Alloc (no extension), sequence 152, value 0
```

**Comment by panaman67** [comment]
@YaLTeR Can this be closed as Rootston isnt here anymore?

**Comment by YaLTeR** [comment]
Maybe move this into the rootston repo? I believe you can move issues on GitHub now.
