### ISSUE TITLE
`wlr/types/wlr_xdg_decoration_v1.h` does not work with `wlr/types/wlr_xdg_shell_v6.h`

### ISSUE THREAD

**Issue by Gaspard--** [swaywm/wlroots#1767]
This is because `wlr/types/wlr_xdg_decoration_v1.h` includes `wlr/types/wlr_xdg_shell.h` directly.

I don't know if the protocols xdg_decoration_v1 and xdg_shell_v6 are incompatible, I couldn't find any indication that was the case at least.

**Comment by emersion** [comment]
xdg-decoration only works with xdg-shell stable. See the protocol file.
