### ISSUE TITLE
backend/wayland: spurious eglSwapBuffers failures

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1768]
Sometimes `eglSwapBuffers` fails on the Wayland backend. Maybe we're running out of buffers.

```
2019-07-23 19:12:39 - [EGL] eglSwapInterval: eglSwapInterval
2019-07-23 19:12:39 - [EGL] eglSwapBuffers: eglSwapBuffers
2019-07-23 19:12:39 - [render/egl.c:400] eglSwapBuffers failed
```

**Comment by RedSoxFan** [comment]
It looks like this effects the DRM backend as well: swaywm/sway#4419 and #1780

**Comment by Emantor** [comment]
Probably "fixed" by #1781

**Comment by emersion** [comment]
Can still reproduce.

**Comment by aemino** [comment]
I also encounter this with my toy compositor using the Wayland backend. It tends to happen occasionally when I move my mouse in and out of the compositor window.

**Comment by ascent12** [comment]
I recently updated the EGL log message to give the error code, now making it:
```
2019-09-20 15:30:31 - [EGL] command: eglSwapInterval, error: 0x300d, message: "eglSwapInterval"
2019-09-20 15:30:31 - [EGL] command: eglSwapBuffers, error: 0x300d, message: "eglSwapBuffers"
2019-09-20 15:30:31 - [render/egl.c:402] eglSwapBuffers failed
```

The reliable way to trigger it on sway is to simply have a client open, unfocus then focus the window (happens on both), which I assume is triggering an `xdg_surface.configure` and `wl_surface.frame`. The X11 backend is not affected.

0x300d is `EGL_BAD_SURFACE`.

**Comment by emersion** [comment]
Seems like the error code has changed. It's now:

```
00:01:01.199 [EGL] command: eglSwapInterval, error: 0x3006, message: "eglSwapInterval"
00:01:01.199 [EGL] command: eglSwapBuffers, error: 0x300d, message: "eglSwapBuffers"
00:01:01.199 [render/egl.c:449] eglSwapBuffers failed
```

Seems related to the cursor. Maybe we swap too fast.
