### ISSUE TITLE
Proposal: remove rootston

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlroots#1778]
- It's basically unmaintained
- It's bad
- It has served its purpose

It would be nice to have other compositors exist which exercise some wlroots features which are currently only implemented in rootston:

- [ ] Drawing tablet protocol
- [ ] Text input protocol
- [ ] Input method protocol

**Comment by ascent12** [comment]
Just to put what I said on IRC in a more permanent place:

I'm not opposed to this.

If someone is interested in doing it, it could be rewritten to truly be simple, yet be a complete compositor. It would live in a separate repository and wouldn't be "blessed" like rootston currently is; it would just be like any other wlroots compositor.

**Comment by ammen99** [comment]
I would say just move rootston to its own repository, I never understood why it is together with wlroots.

However, if we remove rootston completely, then I would say we should have another simple compositor as a test bed. Rootston has been very helpful to me when implementing pointer-constraints and tablet tool support for Wayfire, as I could go straight to the code and figure out what is necessary for those protocols.

**Comment by ammen99** [comment]
Oh and drawing tablet is almost supported in Wayfire, except for tablet pad support (but I gather tablet pads are pretty rare?)

**Comment by Ongy** [comment]
Tablet Pads are on pretty much every tablet out there :)

**Comment by ammen99** [comment]
@Ongy but do they support the stuff like rings, pad buttons and what not?

Plus you are forgetting all the touchscreen laptops with stylus support :)

**Comment by Ongy** [comment]
Ha, found my [shitty old drawing](https://i.imgur.com/iITP6b9.jpg) :)
^ That's my intuous3 (old somewhat entry level wacom) It has strip support.
The current Intuous Pro have a ring.

Outside entry level tablets, you'll have them :) And even entry level tablets (and signing pads) have buttons.

If you only support the tool, you should probably "market" it as stylus support, not full tablet.
And yes, I did forget about them^^

**Comment by ddevault** [comment]
I've filter-branched it into its own project here:

https://github.com/swaywm/rootston

I'll push a commit removing it from the wlroots tree shortly.

**Comment by emersion** [comment]
While I agree rootston's code wasn't great (especially the input code), I think it was still useful. I'll maintain a fork of rootston here: https://github.com/emersion/rootston

Making it nicer is on my TODO-list.
