### ISSUE TITLE
Destroying surface with active touchpoints leads to crashes

### ISSUE THREAD

**Issue by dos1** [swaywm/wlroots#1788]
Reproduced with sway, phoc and rootston.

Steps to reproduce:
1. Launch any app, say, weston-terminal
2. Touch it and don't release.
3. Kill weston-terminal (for instance via ssh)
4. Move or release the finger.

Result: events are being sent on a surface that has been already destroyed, leading to a crash.

**Comment by FreeFull** [comment]
Really easy to reproduce. You can just use your normal "close window" shortcut (or in the case of a terminal, Ctrl+D) too rather than ssh. It seems like the crash is delayed a little, until you try to do something like switching workspaces or launching another terminal.
