### ISSUE TITLE
New libinput adds support for Dell Totem device

### ISSUE THREAD

**Issue by chasinglogic** [swaywm/wlroots#1796]
This causes failure with building with `-Werror` on GCC 9.1.1:

```
../backend/libinput/tablet_tool.c: In function ‘wlr_type_from_libinput_type’:
../backend/libinput/tablet_tool.c:101:2: error: enumeration value ‘LIBINPUT_TABLET_TOOL_TYPE_TOTEM’ not handled in switch [-Werror=switch]
  101 |  switch (value) {
      |  ^~~~~~
cc1: all warnings being treated as errors
```

I don't have one of these devices or any experience with libinput so I wasn't able to make a meaningful patch.

**Comment by emersion** [comment]
Already fixed in https://github.com/swaywm/wlroots/commit/94f65e354d09ded037e6ba724dc3eeed6d63778f

**Comment by emersion** [comment]
As a side note, if that still happens to you, please run:

```
meson build/ --wipe
```

Apparently Meson keeps a cache of dependency versions (no, `--reconfigure` doesn't clear the cache).
