### ISSUE TITLE
Glut/Freeglut fails o initialize display

### ISSUE THREAD

**Issue by nostdm** [swaywm/wlroots#1799]
**Wlroots version:** 0.6.0.r90.g4f4d3cf2

I'm trying to find a GLUT implementation that works with Wayland/Sway. I tried installing `freeglut-wayland-svn` from AUR and compiling manually from [source](https://github.com/dcnieho/FreeGLUT) with `-DFREEGLUT_WAYLAND=ON` to enable Wayland support and the library always fails with `Error: failed to discover all needed compositor interfaces`. I'm assuming this is a problem with Freeglut since they implemented Wayland support in 2015 and most likely some things have changed since then and the integration is broken. I opened an issue https://github.com/dcnieho/FreeGLUT/issues/72 but so far no one has responded. Here's the code for the wayland initalization: https://github.com/dcnieho/FreeGLUT/blob/git_master/freeglut/freeglut/src/wayland/fg_init_wl.c

So I guess the question is, does anyone more adept at Wayland protocol implementation know how one would go about fixing this issue? Or maybe you know a better GLUT implementation that works with Wayland/Sway.

**Comment by emersion** [comment]
It uses wl_shell, which is obsolete. They should migrate to xdg-shell stable.

**Comment by nostdm** [comment]
Great, thanks!
