### ISSUE TITLE
Find and test arbitrarily nested subsurfaces

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#180]
#160 is an implementation that should handle nested subsurfaces. It works ok with the depth = 1 case anyway.

The most likely candidates are menu trees. But I believe those interact with xdg-toplevel in most toolkits so I can't test that yet.

This might require that we write our own client to test all the edge cases of the subsurface implementation based on some assumptions about hypothetical clients that use subsurface nesting might behave.

If nobody actually uses this feature and so there are no test clients in the wild, then maybe we should just wait until we have a test suite to do this testing.

**Comment by SirCmpwn** [comment]
I think we're good?
