### ISSUE TITLE
Horizontal Scrolling in GTK Application Menu not working

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/wlroots#1801]
Horizontal Scrolling (i.e. click in menubar on e.g. "file", file submenu opens, hover to "edit", file submenu stays open and edit submenu doesn't fold open. Click again on edit, the edit submenu folds open, etc.) in the Menubar of some GTK Applications (e.g. Transmission-GTK, Gnome Evolution, Handbrake, et al.).

Firefox does not appear to be affected by this issue.

sway version 1.2-rc1-16-g06c36f84 (Aug 19 2019, branch 'master')

**Comment by dos1** [comment]
Hah, yeah, that commit is wrong. xdg-shell spec says:

	During a popup grab, the client owning the grab will receive pointer
	and touch events for all their surfaces as normal (similar to an
	"owner-events" grab in X11 parlance), while the top most grabbing popup
	will always have keyboard focus.

and

	Explicitly destroying the xdg_popup object will also dismiss the popup and
	unmap the surface. Clients that want to dismiss the popup when another
	surface of their own is clicked should dismiss the popup using the destroy
	request.

So looks like #897 wasn't a bug after all.

**Comment by emersion** [comment]
Hmm, I'm not sure. This second quote only mentions the client's other surfaces, not other clients'.

**Comment by dos1** [comment]
We were hittting that "bug" in phosh, and there both the popup and the background surfaces were coming from the same client. It sure worked with xdg-shell surfaces from other clients - I'll have to check if the same holds for layer-surfaces from other clients, but judging from the code, I'd expect it to work fine. Basically, I've trusted the bug report and haven't actually checked the spec for this one, oops ;)

**Comment by emersion** [comment]
Oh I see. We should have caught that in review. :)

Can you send a revert?
