### ISSUE TITLE
sway starts with black screen with only cursor working

### ISSUE THREAD

**Issue by ThePiGrepper** [swaywm/wlroots#1806]
After bisecting it, the first commit where the issue appears is 96d6fde5dc7ed2e9897297ed459246cb4133a30f.
*This commit, along with the next 4 commits, doesnt compile, because of an struct member, which no longer exists by that name, being called by this patch. The variable's name gets fixed 5 commit later.(1d222309)
A quick grep for 'needs_swap' will find the variable, it should be 'needs_frame'.

This is a segment of the debug log, which is repeated several times:(the complete log is here: https://termbin.com/w9db)
2019-08-27 04:01:54 - [backend/drm/drm.c:950] LVDS-1: Retrying pageflip
2019-08-27 04:01:54 - [backend/drm/drm.c:503] Starting renderer on output 'LVDS-1'
2019-08-27 04:01:54 - [backend/drm/util.c:214] Unable to add DRM framebuffer: No such file or directory
2019-08-27 04:01:54 - [backend/drm/legacy.c:15] LVDS-1: Failed to set CRTC: No such file or directory

**Comment by emersion** [comment]
Can you paste the output of https://github.com/ascent12/drm_info?

**Comment by emersion** [comment]
Seems like it's taking the `drmModeAddFB2` path. Maybe it isn't supported and we should add a `drmModeAddFB` path just like Weston (see `drm_fb_addfb` in `libweston/backend-drm/fb.c`)?

**Comment by emersion** [comment]
Hmm, maybe not. We've always been using `drmModeAddFB2`.

**Comment by ThePiGrepper** [comment]
is this going anywhere? if anyone can help me understand the issue or at least give me hints on what could be the problem I'd appreciate it.

**Comment by Simonas0** [comment]
I have the same problem. Have to mention, our hardware is very similar.
I can confirm that Sway worked fine a month ago, but didn't check if the commit @ThePiGrepper mentioned in first post is the exact one which broke things.
[DRM info](http://termbin.com/p7m1), [Sway log](http://termbin.com/nv93).

**Comment by ThePiGrepper** [comment]
what happened to this? does anyone have a clue of how to fix it? My build of wlroots is frozen is quite old now and new builds of sway et al started depending on the newest versions of wlroots so I cant build them either now.

**Comment by ddevault** [comment]
Bumping this issue over and over again isn't going to solve it. Debug the problem, send a patch.

**Comment by ThePiGrepper** [comment]
As a matter of fact, I know that, I asked for at least a guideline. a 3min look into the issue and a hint so that I can move/work from there. nothing more than that. I bisected the issue, found the commit, actually found the line and more or less the way it stopped working, however I dont have the knowledge to go further, so I asked (look up in the thread) for at least a hint regarding where to focus my attention. Im not asking you to slave yourself for me or anything, so don't assume so.

**Comment by Simonas0** [comment]
A month ago I tried to debug the issue and got to the point where I wasn't sure anymore if it was sway or i915 doing something wrong. Anyway, I just updated all packages (`pacman -Syu`) and the issue doesn't persist anymore, so @ThePiGrepper, try to update your packages. Unfortunately, now I got [another issue](https://github.com/swaywm/sway/issues/4672). This issue can be closed.
