### ISSUE TITLE
bad signature from public key 52CB6609B22DA89A

### ISSUE THREAD

**Issue by ainola** [swaywm/wlroots#1808]
When verifying the latest 0.7.0 release with the accompanying .sig file, I'm presented with the above.

**Comment by ddevault** [comment]
Seems Github generated a slightly different tarball than my local git. I've verified it's authentic and re-signed the release.

**Comment by progandy** [comment]
It looks like github includes the creation timestamp in the gzip headers, which make it impossible to sign the compressed tarball.

$  gzip -lv <wlroots-0.7.0.tar.gz
method  crc     date  time           compressed        uncompressed  ratio uncompressed_name
defla d7950909 Aug 28 16:39              446392             2508800  82.2% stdout
```

**Comment by ddevault** [comment]
```
~/downloads $ gpg --verify wlroots-0.7.0.tar.gz.sig
gpg: assuming signed data in 'wlroots-0.7.0.tar.gz'
gpg: Signature made Wed Aug 28 11:20:17 2019 JST
gpg:                using RSA key 9DDA3B9FA5D58DD5392C78E652CB6609B22DA89A
gpg:                issuer "sway@cmpwn.com"
gpg: Good signature from "Drew DeVault (sway signing key) <sway@cmpwn.com>" [full]
```

**Comment by progandy** [comment]
I just downloaded a new copy. Are the generated files different depending on the region of the user / the serverfarm processing the download request?

```
$ gpg --verify wlroots-0.7.0.tar.gz.sig        :(
gpg: assuming signed data in 'wlroots-0.7.0.tar.gz'
gpg: Signature made 2019-08-28 W35-3 04:19:21 +0200 CEST
gpg:                using RSA key 9DDA3B9FA5D58DD5392C78E652CB6609B22DA89A
gpg:                issuer "sway@cmpwn.com"
gpg: BAD signature from "Drew DeVault (sway signing key) <sway@cmpwn.com>" [unknown]

$ sha256sum wlroots-0.7.0.tar.gz*              :(
e93091d49fc4a3dc1743eca7cdfa75584f2922f59036ba0a99194a9fc8b5e818  wlroots-0.7.0.tar.gz
437ee49ca334f21ce4fbf3f87771b97237b8cd04710edc38a7b9c8d27e074556  wlroots-0.7.0.tar.gz.sig
```

**Comment by ddevault** [comment]
That signature file is wrong. Let me try reuploading it, maybe github caches files by name...

**Comment by ddevault** [comment]
Try that. The sha256sum of the sig file should be `8ed37727ecbd0ab91385c0ee6b29b50f4797d3753df8c4a786075999ed4b1690`.

**Comment by progandy** [comment]
The sha256sum matches and it seems to work now.

```gpg --verify wlroots-0.7.0.tar.gz.sig
gpg: assuming signed data in 'wlroots-0.7.0.tar.gz'
gpg: Signature made 2019-08-28 W35-3 04:20:17 +0200 CEST
gpg:                using RSA key 9DDA3B9FA5D58DD5392C78E652CB6609B22DA89A
gpg:                issuer "sway@cmpwn.com"
gpg: Good signature from "Drew DeVault (sway signing key) <sway@cmpwn.com>" [unknown]
```
