### ISSUE TITLE
xwayland's SIGUSR1 kills sway on platforms where the OpenGL DSO uses threads

### ISSUE THREAD

**Issue by a-m-joseph** [swaywm/wlroots#1816]
Sway needs to mask out SIGUSR1 before loading any DSOs such as OpenGL drivers -- like Weston does. Otherwise if the GPU driver DSO spawns its own threads (ARM Mali does) those threads won't have SIGUSR1 blocked and xwayland will kill sway.

Pull request to fix: https://github.com/swaywm/wlroots/pull/1815

This issue replaces https://github.com/swaywm/sway/issues/4538

**Comment by emersion** [comment]
No need to open multiple issues -- we are aware of the issue, a pull request is enough.
