### ISSUE TITLE
Whole sway crashes when using squeekboard (unprotected handler)

### ISSUE THREAD

**Issue by amingin** [swaywm/wlroots#1821]
Sway crashes completely (with all childs...) with segfault when key "q" is pressed on squeekboard (https://source.puri.sm/Librem5/squeekboard). Otherwise it's working very nice, btw.

Actual reason is that keycode 0 is arriving here: https://github.com/swaywm/wlroots/blob/master/types/wlr_virtual_keyboard_v1.c#L75

It eventually crashes in set_add due assert.

Root cause for this keycode 0 is irrelevant in this case, in my humble opinion, because the thing shouldn't crash because of it in any case - this function is given to Wayland server as handler, so it can give it anything.

Simple if(keycode == 0) ... would be nice there.

**Comment by emersion** [comment]
Can you send a pull request?

**Comment by amingin** [comment]
Added PR
