### ISSUE TITLE
`undefined symbol: wlr_gamma_control_manager_create` for debian package >=libwlroots3:amd64 0.7.0-1

### ISSUE THREAD

**Issue by alex-krk** [swaywm/wlroots#1837]
Recent libwlroots3 updates in debian experimental are breaking sway with an error:
`sway: symbol lookup error: sway: undefined symbol: wlr_gamma_control_manager_create`

No problems with libwlroots3:amd64 0.6.0-1.

Hardware: [Intel NUC Kit NUC5i5RYH](https://ark.intel.com/content/www/us/en/ark/products/83255/intel-nuc-kit-nuc5i5ryh.html)

I can only speculate that issue may be caused by integrated GPU:
```
# lspci -nnk | grep -i vga -A3
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Graphics 6100 [8086:162b] (rev 09)
        Subsystem: Intel Corporation Iris Graphics 6100 [8086:2057]
        Kernel driver in use: i915
        Kernel modules: i915
```

**Comment by RedSoxFan** [comment]
Debian Experimental needs to package Sway 1.2. Older versions of Sway will not work with wlroots 0.7 as there have been breaking changes
