### ISSUE TITLE
There is no /dev/ttyv10 on FreeBSD

### ISSUE THREAD

**Issue by lantw44** [swaywm/wlroots#1854]
In file `backend/session/direct-freebsd.c`, function `setup_tty`, it constructs the path to vty with:
```c
snprintf(tty_path, sizeof(tty_path), "/dev/ttyv%d", tty - 1);
```
It fails when `tty - 1` is 10 or greater because there is no /dev/ttyv10 on the system. FreeBSD uses /dev/ttyva and /dev/ttyvb instead.
```
$ ls -1 /dev/ttyv*
/dev/ttyv0
/dev/ttyv1
/dev/ttyv2
/dev/ttyv3
/dev/ttyv4
/dev/ttyv5
/dev/ttyv6
/dev/ttyv7
/dev/ttyv8
/dev/ttyv9
/dev/ttyva
/dev/ttyvb
```
This causes sway to fail with 'Cannot open tty: No such file or directory.'

**Comment by ascent12** [comment]
Patches are welcome. We don't really have a prominent FreeBSD user/maintainer to test things like this.

**Comment by myfreeweb** [comment]
Did you launch a bunch of direct sessions simultaneously? :) I've never really used more than one display server, and I use consolekit anyway so my wayfire is on `/dev/ttyv0` all the time.

This seems trivial, try changing that line to use `%x` instead of `%d`.

**Comment by lantw44** [comment]
> Did you launch a bunch of direct sessions simultaneously? :)

Yes!

/dev/ttyv8 ran GDM (installed from FreeBSD ports) on Xorg.
/dev/ttyv9 ran GNOME (installed from upstream git) on Xorg.

The next vty available for use was /dev/ttyva, but wlroots chose /dev/ttyv10 and failed.

> I've never really used more than one display server, and I use consolekit anyway so my wayfire is on `/dev/ttyv0` all the time.

I know there is an option called `CONSOLEKIT` in x11-toolkits/wlroots port, but I don't know how to use it. I was just finding an easy way to run Wayland natively on FreeBSD. I used to run mutter in nested mode (`mutter --wayland --nested --no-x11`), but I guess applications and toolkits may behave differently if I run them natively.

This bug was found during testing a GTK4 bug: https://gitlab.gnome.org/GNOME/gtk/issues/2201.

> This seems trivial, try changing that line to use `%x` instead of `%d`.

I already did it on my local installation, but I haven't checked how the kernel will pick the name if the number of consoles is greater tha 16.

**Comment by lantw44** [comment]
> > This seems trivial, try changing that line to use `%x` instead of `%d`.
> 
> I already did it on my local installation, but I haven't checked how the kernel will pick the name if the number of consoles is greater than 16.

I increased the number of consoles to 1600 in a VM in order to understand how the kernel chooses names. It seems that it is a number of base 32 with digits 0 ~ 9 and a ~ v. When the number goes up to `/dev/ttyvv`, the next device is `/dev/ttyv10`. The same thing happens when the number goes up to `/dev/ttyvvv`. The next device is `/dev/ttyv100`.

**Comment by lantw44** [comment]
I opened https://github.com/swaywm/wlroots/pull/1945 to fix this issue.

**Comment by shamazmazum** [comment]
Please forgive me for a little offtopic.

@lantw44 With consolekit2 you do not have to mess with permissions of `/dev/input/event*` devices (like granting RW access for all users) or even set `setuid` flag on wayland compositor to get input devices working. 

More info here, if you may find this interesting: https://lists.freebsd.org/pipermail/freebsd-x11/2019-September/024038.html

**Comment by lantw44** [comment]
@shamazmazum Thanks for the link. It seems that I can't use `CONSOLEKIT` option without applying patches to ports.
