### ISSUE TITLE
After updating Arch to latest wlroots-git - external display errors

### ISSUE THREAD

**Issue by godeater** [swaywm/wlroots#1861]
I ran an upgrade yesterday on my laptop to the latest wlroots-git and sway-git packages, and subsequently sway doesn't seem able to utilise all three displays I usually have connected to my laptop via a thunderbolt adapter.

Previous wlroots-git version : 0.7.0.r13.gb1b93c2c-1
New wlroots-git version : 0.8.1.r12.g02d664b3-1

Debug log is available here : https://gist.github.com/godeater/cc6a6514fca5428a5c03161d0f19c7cb
But some of the salient issues which leaped out at me when I read it were :

> 2019-10-17 15:37:05 - [EGL] command: eglGetPlatformDisplay, error: 0x300c, message: "EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
> "
> 2019-10-17 15:37:05 - [EGL] command: eglGetPlatformDisplay, error: 0x300c, message: "EGL_BAD_PARAMETER error: In function eglGetPlatformDisplay(), unsupported EGL Platform
> "

> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] eDP-1: Atomic commit failed (modeset): Invalid argument

> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] DP-1: Atomic commit failed (modeset): Invalid argument

and then later on again :

> 2019-10-17 15:37:05 - [backend/drm/drm.c:952] eDP-1: Retrying pageflip
> 2019-10-17 15:37:05 - [backend/drm/drm.c:503] Starting renderer on output 'eDP-1'
> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] eDP-1: Atomic commit failed (modeset): Invalid argument
> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] eDP-1: Atomic commit failed (pageflip): Invalid argument
> 2019-10-17 15:37:05 - [backend/drm/drm.c:952] DP-1: Retrying pageflip
> 2019-10-17 15:37:05 - [backend/drm/drm.c:503] Starting renderer on output 'DP-1'
> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] DP-1: Atomic commit failed (modeset): Invalid argument
> 2019-10-17 15:37:05 - [backend/drm/drm.c:952] eDP-1: Retrying pageflip
> 2019-10-17 15:37:05 - [backend/drm/drm.c:503] Starting renderer on output 'eDP-1'
> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] eDP-1: Atomic commit failed (modeset): Invalid argument
> 2019-10-17 15:37:05 - [backend/drm/atomic.c:56] DP-1: Atomic commit failed (pageflip): Invalid argument

Once sway has actually started, I'm left with a single working display (one of the external ones).

I've tried starting sway without the external monitors connected, and in that case, the built in display of the laptop works fine - so not really sure at all what's going on here!

**Comment by ecocode** [comment]
same here...

**Comment by emersion** [comment]
Can you try this wlroots PR? https://github.com/swaywm/wlroots/pull/1870

**Comment by ecocode** [comment]
tried, but gives a compile error
see attached log

[log.txt](https://github.com/swaywm/wlroots/files/3761088/log.txt)

**Comment by Emantor** [comment]
@ecocode what command are you using to rebuilt wlroots-git?

**Comment by ecocode** [comment]
I used the PKGBUILD from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wlroots-git and modified the source git repo (on line 7) to yours.  Then ran makepkg -si.
I checked and the original repo does compile nicely.

**Comment by ecocode** [comment]
yes of course I did !
I can confirm it compiles and works !

Thanks for your bugfix.  Awesome job!
