### ISSUE TITLE
[ArchLinux Testing]  repackaged mesa and libglvnd break glapi.c / glapi.h

### ISSUE THREAD

**Issue by Ferdi265** [swaywm/wlroots#1862]
The update of `mesa` and `libglvnd` from versions `mesa-19.2.1-1` and `libglvnd-1.2.0-2` to `mesa-19.2.1-2` and `libglvnd-1.2.0-3` break the build in the `glapi.c` and `glapi.h` files:

I don't quite know wether ArchLinux or wlroots is at fault here, which is why I first reported it here. If this is not a wlroots problem I will instead report it in the ArchLinux bug tracker.

ArchLinux changed the providing package of `/usr/include/EGL/eglext.h` from `mesa` to `libglvnd`. Since `/usr/include/EGL/eglmesaext.h` is provided by `mesa`, which is not a dependency of `libglvnd`, `<EGL/eglext.h>` no longer automatically includes `<EGL/eglmesaext.h>`. This naturally breaks the build since `PFNEGLQUERYWAYLANDBUFFERWL` and a few other types are defined in that header.

Build Log: https://gist.github.com/Ferdi265/5f5a46f00d43af11eb2f4bc5524f5756

Here is a quick patch that workarounds the issue by manually including the header:

```diff
diff --git a/glgen.sh b/glgen.sh
index 7324fdf6..31af2812 100755
--- a/glgen.sh
+++ b/glgen.sh
@@ -75,6 +75,7 @@ cat > "$OUTDIR/$BASE.h" << EOF
 
 #include <EGL/egl.h>
 #include <EGL/eglext.h>
+#include <EGL/eglmesaext.h>
 #include <GLES2/gl2.h>
 #include <GLES2/gl2ext.h>
```

**Comment by emersion** [comment]
Can you report this as an Arch bug too?

**Comment by RedSoxFan** [comment]
This is an upstream mesa change that is staged for the next release. https://gitlab.freedesktop.org/mesa/mesa/commit/8355658fa857536d948773b361c5ede770e637a3

**Comment by emersion** [comment]
Oh, my bad. No need for an Arch bug then. We should fix it in wlroots.

**Comment by Ferdi265** [comment]
I can send a PR in the evening, won't get to my development setup before then
