### ISSUE TITLE
WLR_RDP_PORT defaults to 3389, but user values are clamped to 0<n<1024...?

### ISSUE THREAD

**Issue by colemickens** [swaywm/wlroots#1883]
https://github.com/swaywm/wlroots/blob/ca45f4490ccce64bf7aa0985951319646b55d258/backend/backend.c#L161

I don't understand why `WLR_RDP_PORT` is restricted to <1024 when it defaults to 3389, and this restriction makes it harder to run Sway RDP as a regular user.

**Comment by oHaiyang** [comment]
Same question here 😰

**Comment by emersion** [comment]
Send patch?
