### ISSUE TITLE
Incorrect modes detected (on boot) with UsbC->DP adapter; correct modes after hotplug

### ISSUE THREAD

**Issue by colemickens** [swaywm/wlroots#1885]
I am attempting to switch from using my external monitor via HDMI (via usb type c hub) to using a direct usb type c -> displayport cable. (Also note, the cable is weird. I got it from Google. I've updated the firmware with a chromebook, and yet, DP mode seems to only work in ONE orientation... so it could be that the wire is just wonky in this case. Or there's a wlroots bug. Or both).

When I start `sway` with the external monitor attached, this is `swaymsg -t get_outputs`: 
[sway-outputs-onboot.txt](https://github.com/swaywm/wlroots/files/3781789/sway-outputs-onboot.txt)

And after hot plugging: 
[sway-outputs-after-hotplug.txt](https://github.com/swaywm/wlroots/files/3781790/sway-outputs-after-hotplug.txt)

The display doesn't activate after hotplug, but I think that's the same issue as #1877.

**Comment by ascent12** [comment]
Post the output of https://github.com/ascent12/drm_info in both situations.
We're simply using the modes that the kernel tells us. This tool gets the modes the kernel reports too.

**Comment by colemickens** [comment]
[1-nothing-plugged-in.txt](https://github.com/swaywm/wlroots/files/3781889/1-nothing-plugged-in.txt)
[2-tty-plugged-in-cable.txt](https://github.com/swaywm/wlroots/files/3781890/2-tty-plugged-in-cable.txt)
[3-sway-started-with-plugged-in.txt](https://github.com/swaywm/wlroots/files/3781891/3-sway-started-with-plugged-in.txt)
[4-sway-after-hotplug.txt](https://github.com/swaywm/wlroots/files/3781892/4-sway-after-hotplug.txt)

**Comment by ascent12** [comment]
Yes, the kernel is not reporting the resolution. There is nothing **we** can do about it.
Maybe it's worth seeming if anything is interesting in dmesg.
`parse-edid < /sys/class/drm/card0-DP-1/edid` might be interesting too, assuming the kernel isn't actually modifying that at all.

**Comment by colemickens** [comment]
This log might be weird because I left the other hub plugged in, but this time, I was able to start sway, hotplug the monitor, it temporarily comes up *at the right resolution*, and then flickers and is back at the wrong resolution. Maybe drm reports it correctly briefly?
[sway.log](https://github.com/swaywm/wlroots/files/3781913/sway.log)

**Comment by colemickens** [comment]
Very, very bizarre. I put DRM in debug mode and saw this:

```
[  121.317701] [drm:drm_detect_monitor_audio [drm]] Monitor has basic audio support    
[  121.319780] [drm:drm_add_display_info [drm]] non_desktop set to 0    
[  121.319788] [drm:drm_add_edid_modes [drm]] ELD monitor Dell AW3418DW    
[  121.319794] [drm:drm_add_edid_modes [drm]] ELD size 36, SAD count 1    
[  121.319814] [drm:drm_add_display_info [drm]] non_desktop set to 0    
[  121.319860] [drm:drm_mode_debug_printmodeline [drm]] Modeline "3440x1440": 60 319750 3440 3488 3520 3600 1440 1443 1453 1481 0x48 0x9    
[  121.319865] [drm:drm_mode_prune_invalid [drm]] Not using 3440x1440 mode: CLOCK_HIGH    
[  121.319870] [drm:drm_mode_debug_printmodeline [drm]] Modeline "3440x1440": 120 633600 3440 3448 3480 3520 1440 1443 1453 1500 0x40 0x5    
[  121.319875] [drm:drm_mode_prune_invalid [drm]] Not using 3440x1440 mode: CLOCK_HIGH    
[  121.319881] [drm:drm_mode_debug_printmodeline [drm]] Modeline "3440x1440": 100 531520 3440 3448 3480 3520 1440 1496 1504 1510 0x40 0x9    
[  121.319885] [drm:drm_mode_prune_invalid [drm]] Not using 3440x1440 mode: CLOCK_HIGH    
[  121.319891] [drm:drm_mode_debug_printmodeline [drm]] Modeline "3440x1440": 85 458500 3440 3488 3520 3600 1440 1443 1453 1499 0x40 0x9    
[  121.319895] [drm:drm_mode_prune_invalid [drm]] Not using 3440x1440 mode: CLOCK_HIGH    
[  121.319901] [drm:drm_mode_debug_printmodeline [drm]] Modeline "3440x1440": 50 265250 3440 3488 3520 3600 1440 1443 1453 1474 0x40 0x9    
[  121.319906] [drm:drm_mode_prune_invalid [drm]] Not using 3440x1440 mode: CLOCK_HIGH    
[  121.319909] [drm:drm_helper_probe_single_connector_modes [drm_kms_helper]] [CONNECTOR:92:DP-1] probed modes :    
[  121.319914] [drm:drm_mode_debug_printmodeline [drm]] Modeline "1024x768": 60 65000 1024 1048 1184 1344 768 771 777 806 0x40 0xa    
[  121.319920] [drm:drm_mode_debug_printmodeline [drm]] Modeline "800x600": 60 40000 800 840 968 1056 600 601 605 628 0x40 0x5    
[  121.319925] [drm:drm_mode_debug_printmodeline [drm]] Modeline "640x480": 60 25200 640 656 752 800 480 490 492 525 0x40 0xa    
[  121.319930] [drm:drm_mode_debug_printmodeline [drm]] Modeline "640x480": 60 25175 640 656 752 800 480 490 492 525 0x40 0xa 
```

So, uh, I used the USB ports on the left side of my XPS 13 and now my ultrawide is being driven at 120Hz by Sway just fine:

```
Output DP-1 'Dell Inc. Dell AW3418DW #ASPD8psOnhPd' (focused)
  Current mode: 3440x1440 @ 120.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    3440x1440 @ 49.987000 Hz
    3440x1440 @ 84.963997 Hz
    3440x1440 @ 100.000000 Hz
    3440x1440 @ 120.000000 Hz
    3440x1440 @ 59.973000 Hz
```

I have no idea if this is something to do with my laptop or a kernel/drm bug, or both.

Anyway... thanks!
