### ISSUE TITLE
Stop including EGL/eglmesaext.h

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1899]
This was a mistake on Mesa's side. We'll need to revert https://github.com/swaywm/wlroots/commit/d113e48a2a32542fe6e12f1759f07888364609bf.

See https://gitlab.freedesktop.org/wayland/weston/merge_requests/289#note_283447

**Comment by ascent12** [comment]
https://github.com/KhronosGroup/EGL-Registry/pull/95 was merged. We should be able to drop it the next mesa release if they pull in the new EGL headers.

**Comment by emersion** [comment]
* https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4953
* https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/225

**Comment by emersion** [comment]
Also need to revert https://github.com/swaywm/wlroots/pull/2171

**Comment by emersion** [comment]
Done in https://github.com/swaywm/wlroots/pull/2222.
