### ISSUE TITLE
Performance and profiling

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#190]
We need to profile wlroots - we know at least some performance issues exist, and we could always be faster. Someone should run it through gprof and post a flame graph in this ticket. We'll make a better todo list out of that. Also might be worthwhile to do a pass on memory usage and check for leaks.

**Comment by ascent12** [comment]
Built with
`meson configure -Dbuildtype=debugoptimized -Dc_args=-fno-omit-frame-pointer`
on commit
b0527e7d4880ba234d77384c7fc3006afc609183

Captured with
`perf record -F 99 --call-graph dwarf -- rootston/rootston`
Recording was 1 minute, there was no user input at all, and no clients were opened.

X11:
![rootston-x11](https://user-images.githubusercontent.com/5235114/31113280-01fb290a-a875-11e7-862b-87faa283b320.png)

DRM:
![rootston-drm](https://user-images.githubusercontent.com/5235114/31113291-0acdf1f2-a875-11e7-95ff-0969f0dd5c3a.png)


Obviously, we can see that most of the CPU time is being dominated by the renderer.

**Comment by SirCmpwn** [comment]
This also confirms my suspicion that we can save a lot of time + power by skipping all of this on frames where nothing has changed. I also imagine these might get thinner if we set our viewport smaller to do partial redraws. Is it possible to swap only part of the buffer, I wonder?

**Comment by Hello71** [comment]
compton says yes but it often doesn't work well: https://github.com/chjj/compton/blob/master/man/compton.1.asciidoc

**Comment by SirCmpwn** [comment]
>GLX backend: Use MESA_copy_sub_buffer to do partial screen update. My tests on nouveau shows a 200% performance boost when only 1/4 of the screen is updated. May break VSync and is not available on some drivers. Overrides --glx-copy-from-front.

Looks like it gives a nice boost. We shouldn't have to work about vsync.

**Comment by acrisci** [comment]
I think the damage stuff solved our worst performance problems. Closing this because it is old.
