### ISSUE TITLE
weston-simple-egl aborts

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#191]
```
~/s/wlroots > env WAYLAND_DISPLAY=wayland-1 weston-simple-egl
has EGL_EXT_buffer_age and EGL_EXT_swap_buffers_with_damage
listener function for opcode 1 of wl_seat is NULL
fish: “env WAYLAND_DISPLAY=wayland-1 w…” terminated by signal SIGABRT (Abort)
```

Someone said this might be because of the order of globals, but it's not - I made the ordering match sway to no avail, and the abort comes during the dispatch anyway.

**Comment by acrisci** [comment]
When we send the name of the seat with `wl_seat_send_name()`, simple-egl does not implement a listener for it in their interface. The name listener has opcode 1, which is not there hence the error message.
