### ISSUE TITLE
Implement direct scan-out for fullscreen views

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlroots#193]

**Comment by ascent12** [comment]
DRM overlay planes can be used for this, where available. We already have all of the shit there to detect them, but we currently do not expose them in the API.

**Comment by emersion** [comment]
@ascent12 Can you elaborate how the API could look like? We need to extend both `wlr_output` and `wlr_drm_connector`. Concerning the `wlr_output` side, is adding a `wlr_output_set_fullscreen(struct wlr_output *, struct wlr_surface *)` enough? Same for `wlr_output_interface`? Or do we want a more complicated interface?

**Comment by linkmauve** [comment]
You shouldn’t need any API change, you can promote any surface matching the criteria to a plane, as long as you still have some available.

**Comment by emersion** [comment]
We need a wlr_output API change.
