### ISSUE TITLE
The performance/responsiveness of EGL apps is broken on the sway with the lastest wlroots

### ISSUE THREAD

**Issue by kchibisov** [swaywm/wlroots#1955]
After 515679e4fed1c7c762a8c269fca09cbb195a4323 some OpenGL/EGL apps are barely usable(e.g. alacritty). Alacritty performance degraded by ~25%(on our benchmarks) by the commit I've mentioned, input became jerky and so on. Firefox on Wayland also seems to be affected. Now it start's like 5-10+ seconds to just open a window and also feels very slow.

cc @emersion ?

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by kchibisov** [comment]
From broken commit: [broken_sway.log](https://github.com/swaywm/wlroots/files/3988988/broken_sway.log)

From the one before it: [good_sway.log](https://github.com/swaywm/wlroots/files/3988990/good_sway.log)

**Comment by GreyXor** [comment]
Same here, 
Seen before with @emersion : 

> DMA-BUF import extension not present
> early eglGetString(EGL_EXTENSIONS) doesnt advertise everything

**Comment by emersion** [comment]
Thanks for reporting this issue. Can you try https://github.com/swaywm/wlroots/pull/1956?
