### ISSUE TITLE
Popup placement is wrong

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1974]
In constrast to #1733, this issue is about xdg-popups of xdg-toplevels. The issue is reproducible in both Sway and Wayfire, so I assume the problem is in wlroots. Just look at the following screenshot:

Note that this happens only in some cases. From my tests so far the problem happens if the toplevel is in the lower half of the screen (it works for the left terminator window for example):

![popup](https://user-images.githubusercontent.com/6287487/71573766-29cb6500-2aee-11ea-8b46-40b4c20aa0d8.png)

**Comment by emersion** [comment]
Can you describe how to reproduce? Which client is this?

**Comment by ammen99** [comment]
Sorry, I was just debugging this. The client is terminator. It seems that it does not call `set_constraint_adjustment` at all, and according to the protocol, this means we should not constrain the popup at all (so everything is good on our side). I'll report the issue to terminator/GTK.
