### ISSUE TITLE
Support for wp_primary_selection_device_manager

### ISSUE THREAD

**Issue by Fale** [swaywm/wlroots#1981]
Recently I've had a problem with Kitty (https://github.com/kovidgoyal/kitty/issues/2254) and the maintainer suggested that the problem was that my compositor would not support wp_primary_selection_device_manager.
Checking, I see that I have `wlroots-0.5.0-1.fc30.x86_64` installed (from Fedora 30 repositories).
I do understand that this is a fairly old version, and I'll see how to upgrade it, but from the wlroots changelog I've not seen any changes to primary selection from version 0.4. Is `wp_primary_selection_device_manager` implemented in wlroots? If so, when was it added?

**Comment by emersion** [comment]
See the Git history: https://github.com/swaywm/wlroots/commits/master/types/wlr_primary_selection_v1.c

**Comment by Fale** [comment]
If I understand correctly, then, it should be present and working in wlroots 0.5.0. If so there is probably another problem in my situation, since Kitty is not able to pick it up

**Comment by emersion** [comment]
The compositor also needs to enable it, see the header file.
