### ISSUE TITLE
Fails to configure with no ffmpeg dependencies

### ISSUE THREAD

**Issue by dos1** [swaywm/wlroots#1994]
When there are no ffmpeg dependencies installed, meson fails to configure wlroots on `dmabuf-capture` example regardless of whether examples are enabled or not.

```
examples/meson.build:170:1: ERROR: Argument is of an unacceptable type 'Disabler'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency()).
```

Meson 0.51.1

**Comment by ascent12** [comment]
Apparently meson fixed some of their disabler handling between 0.51 and 0.52.
A list of disablers + dependencies wasn't acting like a disabler should.
