### ISSUE TITLE
use RPC to make wlroots language agonistic

### ISSUE THREAD

**Issue by unmellow** [swaywm/wlroots#2004]
so I read [this](https://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html) and, thought RPC in the style of what Raph Levien did with [xi-editor](https://github.com/xi-editor) 
would be a good way to allow people to write compositors in whatever language they want. 
I wrote a little more about it in an [issue](https://github.com/Smithay/smithay/issues/150) I posted for smithay
It might be possible or even a better idea to just have a wrapper on your currant API so as to not break
compatibility with current  compositors but if you want this to be even more ubiquitous there needs to be a solution to cross language compositors

**Comment by emersion** [comment]
We're not interested in having this upstream. The [Way Cooler post-mortem post](https://way-cooler.org/blog/2020/01/09/way-cooler-post-mortem.html) explains a few reasons why this isn't desirable.

Compositors can implement RPC if they want to, and there are various wlroots bindings available for other languages.
