### ISSUE TITLE
error building master

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/wlroots#2028]
Full build log
[gui-libs:wlroots-9999:20200217-212855.log.zip](https://github.com/swaywm/wlroots/files/4216290/gui-libs.wlroots-9999.20200217-212855.log.zip)

**Comment by ddevault** [comment]
Your version of Wayland is outdated.

**Comment by CaptainBloodz** [comment]
Thks

**Comment by CaptainBloodz** [comment]
Gentoo bugzillla [https://bugs.gentoo.org/710008](url)
