### ISSUE TITLE
Input grab interface

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#203]
Some Wayland interfaces require grab interfaces that species certain behavior for input handling. The first interface with grabs we have encountered is xdg-popup but other interfaces have grabs as well.

Interfaces that might require grabs:

* xdg-popup
* wl_shell
* ivi-shell
* data-device
* exposay
* pointer constraints

I think it also makes sense to expose the same grab interface as part of the user api for wm user interface actions and elements. A grab might be useful for implementations of keyboard and mouse bindings.

By a "grab" we mean that some interface will take control of the seat. A grab is initiated on the seat to override seat actions. For every capability of the seat that is grabbed (pointer, touch, keyboard), the grabber must provide an interface that implements the seat actions.

For instance, a grabber might call a function like `wlr_seat_keyboard_grab()` passing an implementation of the `wlr_seat_keyboard_grab_interface` implementing the functions `send_key()`, `send_modifiers()`, `enter()`, and `cancel_grab()`.

The grabber can for instance override the `enter` function to only send keyboard keys to its own clients or maintain keyboard focus on a particular user interface element.

**Comment by acrisci** [comment]
Work on grabs will happen in #183.

**Comment by SirCmpwn** [comment]
Sounds good to me.

**Comment by acrisci** [comment]
Implemented now in #183.
