### ISSUE TITLE
virtual-keyboard: release unreleased keys

### ISSUE THREAD

**Issue by xhebox** [swaywm/wlroots#2034]
Follow https://github.com/swaywm/sway/pull/4932#issuecomment-586108940.

It's not restricted to IME. Any application aborted may leave some unreleased virtual_keyboard key events.  I think there should be similar thing to https://github.com/swaywm/wlroots/blob/master/types/wlr_keyboard_group.c#L203-L219.

As it is using wlr_keyboard, so pressed keys are recorded. So keyboard_group can handle unreleased keys, then why can not virtual_keyboard?

**Comment by emersion** [comment]
Indeed, destroying the virtual keyboard should release the keys.

We likely have the same issue with virtual pointer.
