### ISSUE TITLE
wlroots doesn't keep mode set via video= kernel cmdline

### ISSUE THREAD

**Issue by flokli** [swaywm/wlroots#2040]
I want to run a wayland compositor on a device with a fixed screen resolution, and to ease debugging, want to provide a similar environment in a qemu VM.

I used the kernels cmdline option to configure a resolution:

```
video=Virtual-1:2280x800@60me
```

During boot, I see this custom resolution being configured. However, as soon as my compositor (cage in that case) starts, it seems to fall back to 1024x768.

I'm running qemu with `-vga std`, `-m 2048` and `-smp 2`, if that helps.

I experienced this bug in sway as well, so assume it's a wlroots problem, and not cage-specific.

**Comment by emersion** [comment]
`video` is a kernel option for framebuffer devices. fbdev isn't used on wlroots, DRM/KMS is used instead, so this option won't work. You should configure your compositor to set a custom mode instead (e.g. `output XXX mode --custom YYY` in Sway).

**Comment by agx** [comment]
we're using a modeline in the config file for that https://source.puri.sm/Librem5/phosh/blob/master/data/rootston.ini#L12

**Comment by flokli** [comment]
I went generating a custom edid with my custom mode, added it to the initrd, and passed it as kernel cmdline:

> drm_kms_helper.edid_firmware=Virtual-1:edid/1280x800.bin

That way, I don't need to rely on the compositor providing a way to add/set custom modes.
