### ISSUE TITLE
Busy loop with clients requesting frame callbacks without rendering

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2051]
Because of https://github.com/swaywm/wlroots/pull/2046 clients requesting frame callbacks without rendering at all cause a busy-loop in the compositor:

1. Client requests frame callback without rendering anything
2. Compositor resumes the rendering loop immediately
3. Compositor notices nothing changed on screen, skips the page-flip
4. Compositor sends frame callback event to client
5.  Goto (1)

This can be reproduced with the so-called "last good mpv commit" 8a83430a:

```
mpv --force-window --vid=1 --external-file=<path to image> <path to audio file>
```

Firefox also uses this behavior.

I'm putting together a test client right now.

**Comment by ascent12** [comment]
I think we should just make compositors always perform `wlr_output_commit` every frame, even if it contains no state changes or new rendering. i.e. `wlr_output_commit` is the thing that will trigger the frame callback to happen.

**Comment by emersion** [comment]
No, this will keep the rendering loop active even if nothing is happening (no clients requesting the frame callback).

**Comment by emersion** [comment]
Test client: https://github.com/emersion/wleird/blob/master/frame-callback.c
