### ISSUE TITLE
WLR_DRM_NO_ATOMIC=1 solves flickering. Bug or feature?

### ISSUE THREAD

**Issue by brandsimon** [swaywm/wlroots#2087]
Hello,

I use sway and sometimes I have for a part of a second a white bar flickering over the screen.
This happens sometimes very rarely, sometimes there are like 5 white bars per second and this continues for a few minutes.
The height differs, but the width covers always the complete screen.
If I set `WLR_DRM_NO_ATOMIC=1` the flickering is gone.

Is this a bug in wlroots or is this a feature, to mitigate bugs in the kernel driver?
Is there a downside of setting this? (havent noticed anything)
Will the legacy drm interface be removed from the kernel in the future?

Is there a way to debug this easily?
Would a video help to debug this?
I use an Intel Corporation HD Graphics 630 with Arch Linux.

**Comment by emersion** [comment]
This is a Sway bug, tracked in https://github.com/swaywm/wlroots/issues/1873.
