### ISSUE TITLE
Sway crashes when hotplugging with Assertion `layout_output` failed

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/wlroots#2088]
* Sway Version: `sway version 1.4-82d02ce7 (Mar 28 2020, branch 'master')`

* Debug Log: https://0x0.st/iB08.txt
Created with `WAYLAND_DEBUG=1 sway -d -c /etc/sway/config 2> ~/log.file`

* Configuration File: default (`/etc/sway/config`)

Reproducing this requires two monitors. It's worth noting that the second monitor is HDMI and the first monitor is DP

1. Start sway with only one monitor on (second monitor is plugged in but turned off)
2. Turn on the second monitor
3. Sway crashes almost instantly, after first trying to set the second monitor output

* Stack Trace, if sway crashes: https://0x0.st/iB0K.txt

**Comment by emersion** [comment]
Note, we should add checks to all `wlr_output_from_resource` call sites.
