### ISSUE TITLE
GTK+ apps are blurry

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#210]
I suspect this is due to some way we're handling their stupid client-side shadows compared to their main UI's width/height.

**Comment by emersion** [comment]
Note that window sizes are correct (_pixel-perfect_). Also, plain color areas look strange.

![screenshot from 2017-10-05 20-41-16](https://user-images.githubusercontent.com/506932/31246405-95f12904-aa0d-11e7-87b1-ed124082b691.png)

**Comment by SirCmpwn** [comment]
Here's my comparison:

![](https://sr.ht/uBNO.png)

**Comment by SirCmpwn** [comment]
Window size is definitely NOT accurate here. Hmm, actually - this only seems to manifest itself after I move the calculator around (in rootston)
