### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by koraa** [swaywm/wlroots#2105]
Hey, I just wanted to say thanks! I currently need to build a quick demo project for something and that involved some wayland hacking. I decided to build one version using sway & wlroots and the other using qt. Getting the qt version right took me a week; working with sway and wlroots on the other hand has been an absolute blast. Despite the lack of documentation and the added complexity of function pointer interfaces, I have had very little trouble finding my way around; compiling both project has been quite easy.

This is awesome! Thank you!

**Comment by emersion** [comment]
Glad you like it! :)

Indeed, we really need better docs. Patches welcome!
