### ISSUE TITLE
Spawn rootston windows centered on-screen

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#212]

**Comment by versusvoid** [comment]
Maybe a better approach is to spawn them randomly distributed on screen, so two sequentially spawned windows won't occupy same space?

**Comment by SirCmpwn** [comment]
We don't need to get too complicated for rootston. I just don't want windows spawning off-screen.

**Comment by SirCmpwn** [comment]
Should also be centered on the output that the cursor is currently on.

**Comment by acrisci** [comment]
Maybe if there is some window exactly at the place that it spawns (or some threshhold), it gets a 100px boost in the x and y direction. Repeat until you find a place on the output where it contains the whole window. If there is no such place, just open it in the center.

**Comment by SirCmpwn** [comment]
Perhaps - we should also consider cases like save file dialogs and such that are best shown centered on the window that created them.
