### ISSUE TITLE
[intel/ivybridge] no signal on DP with native resolution - atomic driver check for 00000000be360ce3 failed: -22

### ISSUE THREAD

**Issue by efouladi** [swaywm/wlroots#2124]
No signal on my external display with max supported resolution of 2560x1440.
It works with lower resolutions. 

sway version 1.4-2b15cf45 (Apr 17 2020, branch 'master')

sway.log: https://gist.github.com/efouladi/6c0cb94ee545481699581160a4cd5a00

The dmesg log is too big to put in a git gist so I truncated it to the first and last 10000 lines of the original log 
https://gist.github.com/efouladi/a6d2be693928e866e928e72d876d91ed

**Comment by emersion** [comment]
```
[ 4340.843694] [drm:intel_atomic_check [i915]] only 2 lanes on pipe C: required 3 lanes
```

Have you tried `WLR_DRM_NO_MODIFIERS=1`?

**Comment by efouladi** [comment]
Yes I've tried it. It doesn't make any difference

**Comment by emersion** [comment]
Well, then your GPU doesn't support this resolution, we can't do anything about it. If you think it should support it, open a kernel bug.

**Comment by efouladi** [comment]
Ok but I tested it with X and gnome on wayland and it works with that resolution

**Comment by efouladi** [comment]
I was fiddling around a bit more and I figured it works if I connect the external display prior to starting sway. It looks like it's similar to this: https://github.com/swaywm/sway/issues/3511 
specially given that I'm using the same hardware (lenovo x230)
