### ISSUE TITLE
Banding in uniform areas under wayland backend

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#213]
Wayland backend. There's some noise where there shouldn't be.

![screenshot from 2017-10-05 21-00-24](https://user-images.githubusercontent.com/506932/31247242-3aa26d3a-aa10-11e7-8705-e3c4948162f1.png)

**Comment by SirCmpwn** [comment]
Cannot reproduce. What theme is that?

**Comment by emersion** [comment]
This is just Adwaita, dark variant. This also happens with Adwaita light, but it's very hard to notice, because the window is white.

**Comment by SirCmpwn** [comment]
I cannot reproduce this on the DRM backend.

**Comment by emersion** [comment]
I can confirm. This seems to be specific to the Wayland backend.
