### ISSUE TITLE
Add "special" rootston command to close the focused window

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#216]
Special meaning similar to the quit command.

**Comment by SirCmpwn** [comment]
We might consider making these "special" commands not so special. Maybe:

```
[meta-bindings]
exit=Logo+Shift+q
close=Logo+q

[command-bindings]
Logo+Enter=weston-terminal
```

Or something like that?

**Comment by emersion** [comment]
I don't like how keys/values are inverted between the two blocks, but yeah, that's a better idea. Another idea is to force "real" commands to be prefixed with `exec`.

**Comment by SirCmpwn** [comment]
That's also an option. I want to avoid having a command parser in rootston if we can.
