### ISSUE TITLE
Outputs do not re-enable after `swaymsg reload`

### ISSUE THREAD

**Issue by Xyene** [swaywm/wlroots#2170]
I have https://github.com/swaywm/wlroots/pull/2168 and https://github.com/swaywm/wlroots/pull/2167 applied on sway/wlroots master, filing as requested in https://github.com/swaywm/wlroots/pull/2167#issuecomment-625429907.

I have two monitors connected:
* DP-2, 2560x1440@144Hz, VRR disabled
* DP-1, 2560x1440@60Hz

When I run `swaymsg reload`, occasionally DP-1 does not re-enable. A second `swaymsg reload` tends to bring it back up. This started happening recently. The logs contain messages about this:

```
... DP-2 turns on ...
00:00:05.781 [sway/config/output.c:348] Turning on output DP-1                                                              
00:00:05.781 [sway/config/output.c:353] Set DP-1 mode to 2560x1440 (59.951000 Hz)                                                                        
00:00:05.781 [sway/config/output.c:266] Assigning configured mode to DP-1                                               
00:00:05.781 [sway/config/output.c:363] Set DP-1 subpixel to unknown                                                    
00:00:05.781 [sway/config/output.c:368] Set DP-1 transform to 0                                                         
00:00:05.781 [sway/config/output.c:326] Output DPI: 108.373333x107.576471                                               
00:00:05.781 [sway/config/output.c:379] Auto-detected output scale: 1.000000                                            
00:00:05.781 [sway/config/output.c:418] Committing output DP-1                                                          
00:00:05.781 [INFO] [backend/drm/drm.c:829] Modesetting 'DP-1' with '2560x1440@59951 mHz'                               
00:00:05.781 [DEBUG] [backend/drm/drm.c:708] Initializing renderer on connector 'DP-1'                                  
00:00:05.836 [ERROR] [backend/drm/drm.c:345] Failed to page-flip output 'DP-1': a page-flip is already pending          
00:00:05.836 [INFO] [backend/drm/drm.c:742] Page-flip failed with primary FB modifiers enabled, retrying without modifiers
00:00:05.836 [ERROR] [backend/drm/drm.c:345] Failed to page-flip output 'DP-1': a page-flip is already pending          
00:00:05.836 [ERROR] [backend/drm/drm.c:752] Failed to initialize renderer on connector 'DP-1': initial page-flip failed
00:00:05.836 [ERROR] [backend/drm/drm.c:833] Failed to initialize renderer for plane 
```

([Full log](https://gist.github.com/Xyene/19bb5d2d2c6768c953591713c8bb6c60), failure [here](https://gist.github.com/Xyene/19bb5d2d2c6768c953591713c8bb6c60#file-gistfile1-txt-L2724), entire log contains 4 reloads of which the first was unsuccessful in turning the monitor back on.)

**Comment by emersion** [comment]
Hmm. I guess the modeset is performed while a page-flip is pending, which fails. I wonder what we should do in this case… Ignore that a page-flip is pending on modeset? But then KMS will fail with EBUSY?

cc @ascent12

**Comment by Xyene** [comment]
FWIW, I haven't had this happen to me again since updating wlroots a while ago, after some of the DRM fixes from after 19 days ago went in.
