### ISSUE TITLE
Xwayland hangs after restart

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2174]
1. Run `xeyes`
2. Kill Xwayland
3. Run `xeyes` again

Xwayland is correctly restarted, but `xeyes` hangs.

Tested with the lazy mode.

**Comment by emersion** [comment]
@ammen99 bisected it to 27609ba0

**Comment by ammen99** [comment]
I just realized that in Wayfire, a hang can happen even without restarting Xwayland - just opening a google chrome window on two outputs is enough (but doesn't seem to happen in Sway). I will try to investigate when I have time.
