### ISSUE TITLE
Meson build command not recognizing command line option

### ISSUE THREAD

**Issue by B0G0311** [swaywm/wlroots#2184]
Disclaimer: This is my first post and so i am sorry if it is a little unclear or not well put together.

when using the meson build command i keep getting 
`meson.build:97:0: ERROR: Pkg-config binary for machine MachineChoice.HOST not found. Giving up.`

so I pulled up the meson-log.txt to which I got a whole list of errors:

> None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
> None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
> Project name: wlroots
> Project version: 0.10.0
> None of 'CC' are defined in the environment, not changing global flags.
> None of 'CFLAGS' are defined in the environment, not changing global flags.
> None of 'LDFLAGS' are defined in the environment, not changing global flags.
> None of 'CPPFLAGS' are defined in the environment, not changing global flags.
> None of 'CC_LD' are defined in the environment, not changing global flags.
> Sanity testing C compiler: cc
> Is cross compiler: False.
> 
I originally thought that it was a cmake problem but i am running the most current version.

I am running:
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-51-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 15.3 GiB of RAM

**Comment by emersion** [comment]
This error doesn't seem related to wlroots. Please ask the Meson devs for help.
