### ISSUE TITLE
No output with Amlogic SoC (meson)

### ISSUE THREAD

**Issue by L-as** [swaywm/wlroots#2187]
No output as in, when running it from a tty, what was rendered before launching will be what is shown after too. I tested this with the simple example.

I bisected this and commit [70883fd10beba4f78e3325eb6e38750360502f58](https://github.com/swaywm/wlroots/commit/70883fd10beba4f78e3325eb6e38750360502f58) introduced this behavior for me.

[dmesg](https://github.com/swaywm/wlroots/files/4613204/dmesg.txt)
[drminfo.json](https://github.com/swaywm/sway/files/4594620/drminfo.json.txt)

@emersion

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by emersion** [comment]
DRM debug log doesn't contain any failed atomic commit.

**Comment by progandy** [comment]
https://github.com/swaywm/wlroots/blob/70883fd10beba4f78e3325eb6e38750360502f58/backend/drm/atomic.c#L197-L199

What happens if ```crtc->props.gamma_lut == 0``` or ```crtc->gamma_lut == 0```?

**Comment by emersion** [comment]
Ah, this causes issues if `crtc->props.gamma_lut == 0`. We should guard this behind an if. The `crtc->gamma_lut == 0` case would just reset the LUT.

**Comment by L-as** [comment]
@emersion I was stupid and thought nothing was written to stderr, when it just wasn't rendered in my tty somehow.

[stderr.txt](https://github.com/swaywm/wlroots/files/4616050/stderr.txt)

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2194?
