### ISSUE TITLE
Use the XRes protocol instead of _NET_WM_PID

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2189]
_NET_WM_PID is set by the client. This has issues:

- Clients can lie
- Doesn't work when the client is sandboxed in a PID namespace
- Doesn't work with remote clients

Using XRes would allow us to get the info directly form the X11 server: https://gitlab.freedesktop.org/xorg/proto/xorgproto/blob/master/resproto.txt

**Comment by damianatorrpm** [comment]
https://gitlab.freedesktop.org/xorg/xserver/issues/1022

**Comment by damianatorrpm** [comment]
It seems that the xorg would't work for all cases, some clients do not wish to set their _NET_WM_PID

**Comment by damianatorrpm** [comment]
@emersion How do you think a fix should look like?
You mentioned on irc the atoms are not a good place.

**Comment by emersion** [comment]
The XRes protocol doesn't involve atoms. This code is probably a good starting point: https://stackoverflow.com/a/37309217

We'll want to get the PID from the X11 server when a window is created.

**Comment by damianatorrpm** [comment]
@emersion My question was more to where in wlroots xwayland.h you would like to see it.
Like a function get_xres_pid() or?

**Comment by emersion** [comment]
No, get the PID when the window is created, populate the PID field we already have.

**Comment by emersion** [comment]
Example code doing this with Xlib: https://github.com/Plagman/gamescope/pull/146
