### ISSUE TITLE
No output with vmwgfx (regression)

### ISSUE THREAD

**Issue by escalade** [swaywm/wlroots#2193]
PR #2169 broke output for vmwgfx (Mesa's VMware SVGA3D driver).

Sway log: http://ix.io/2lRS

**Comment by emersion** [comment]
Can you run [`drm_info`](https://github.com/ascent12/drm_info)?

**Comment by escalade** [comment]
http://ix.io/2lSy

**Comment by emersion** [comment]
>Segmentation fault

Eh, this isn't supposed to happen. Can you run it in GDB and then type `bt full`?

**Comment by progandy** [comment]
The wlroots issue might be a duplicate of #2187 

(The drm_info crash is something else)

**Comment by escalade** [comment]
GDB backtrace: http://ix.io/2lSS

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2194?

**Comment by escalade** [comment]
That fixed it :)
