### ISSUE TITLE
Segfault in handle_pointer_motion

### ISSUE THREAD

**Issue by gabm** [swaywm/wlroots#2211]
Running 2988ebb6f37e201ba5884aa434aa7120fa951852 on arch linux I get the following segfault in or below `handle_pointer_motion`:

[gdb.txt](https://github.com/swaywm/wlroots/files/4654994/gdb.txt)

**Comment by Xyene** [comment]
You're missing debug symbols for wlroots, but from the rest of the trace, this looks like a duplicate of  https://github.com/swaywm/sway/issues/5294, introduced in https://github.com/swaywm/sway/commit/091f580b7cb0df92f0f6e0be34b52f8abfdbe97a (you can follow the linked issues for some more context and discussion, if you're interested).

**Comment by gabm** [comment]
oh thanks.. I only checked wlroots and didnt find any reference... looks like a duplicate indeed.
