### ISSUE TITLE
"eglSwapBuffers failed" for all outputs at sway start with latest wlroots

### ISSUE THREAD

**Issue by Ferdi265** [swaywm/wlroots#2214]
Since wlroots commit "backend/drm: add missing wlr_egl_unset_current" (d28a7da95d1adeabb9f628d91c872fb2cb7fcee3), starting sway on my Laptop never manages to enable/modeset any output (not even the internal display / display the tty was rendered on), but doesn't crash.

First broken commit: d28a7da95d1adeabb9f628d91c872fb2cb7fcee3

System:
- CPU: Intel i3-8130U CPU (Kaby Lake)
- iGPU: Intel UHD Graphics 620
- Connected displays: internal eDP-1 display, also happens with external display on HDMI-A-1 connected

Versions:
- wlroots version: d28a7da95d1adeabb9f628d91c872fb2cb7fcee3 (first broken commit) -  72f28ed0b36e4f8a6a8732788bc557533ac36ab1 (latest master)
- sway version: 2bf14cb747154251b754fecc004bd568e3f80470 (latest master)

Configuration and Logs:
- sway config file: (empty file)
- sway log file: [sway.bug.log](https://github.com/swaywm/wlroots/files/4657938/sway.bug.log)

**Comment by emersion** [comment]
Update wlroots.

**Comment by Ferdi265** [comment]
Thanks for notifying me that this was fixed while I was bisecting and writing up this bug report, but a slightly nicer tone than just "Update wlroots." would have been appreciated (e.g. "this has been fixed just now, in $COMMITHASH").

**Comment by emersion** [comment]
Sorry, I didn't mean to be rude. I replied with a brief sentence to avoid wasting time looking all that up.

**Comment by Ferdi265** [comment]
I'm also sorry if my answer seemed rude; I think I was just slightly worked up about the fact that I had spent some time writing up this bug report while the fix was already being pushed, and my bug report was therefore unneeded.

**Comment by emersion** [comment]
Well, I'll keep this in mind for the future. In any case, thanks for testing the bleeding edge Sway commits!
