### ISSUE TITLE
Color corruption on the second display

### ISSUE THREAD

**Issue by sylvaindurand** [swaywm/wlroots#2231]
Hello! First of all, I would like to take this opportunity to say a huge thank you to the developers and contributors of these pieces of software. I've been using Sway for several weeks now and I'm really happy with it, my experience with Linux is more enjoyable than it has ever been.

To the issue now: when I connect a second monitor with USB C/HDMI, it is correctly detected, but the colors are very degraded on it. The screen of the laptop remains correct. This also happens if the screen is plugged in at startup. Here is a picture (both pictures should be identical on both screens) :

![IMG_6442](https://user-images.githubusercontent.com/65806132/83163672-95e8de00-a10b-11ea-906d-61f968e411af.JPG)

`sway version 1.4-704d675a (May 27 2020, branch 'master')`
`XPS 13 9300`
`5.6.14-arch1-1`
`Intel Iris Plus Graphics G7`
[sway debug log](https://gist.github.com/sylvaindurand/289826718518136d40cea362a5e32671)

While using the sway 1:1.4-9 version, I had the same problem on my laptop screen whenever I quit/launched sway, or changed tty. 

It is now solved with the master version, I believe it's thanks to this [pull](https://github.com/swaywm/wlroots/pull/2071) from this [issue](https://github.com/swaywm/sway/issues/4826) (whose user has the same graphics card as me). If it can help!

Last but not least, I used the minimal sway configuration below (for the issue), but it does the same with sway default configuration:

```
set $mod Mod1
input * xkb_layout "fr"
output * bg ~/.config/wallpapers/sunrise.webp fill
```

Again, thanks a lot!

**Comment by emersion** [comment]
Does it work with another compositor, e.g. Weston?

**Comment by sylvaindurand** [comment]
I just tried and I actuallly have the same bug with Weston.

**Comment by emersion** [comment]
All right, please report this to the Intel developers: https://mesa3d.org/bugs.html
