### ISSUE TITLE
session/direct: consider removing privileged child process

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2232]
After https://cgit.freedesktop.org/drm/drm-misc/commit/?id=45bc3d26c95a8fc63a7d8668ca9e57ef0883351c once we've gained DRM master we don't need to keep root permissions to drop/regain it.

Investigate whether we could remove our privileged child process in the direct session. Maybe we still need it for input devices?

**Comment by emersion** [comment]
Actually, maybe we don't need suid at all after this kernel patch -- would need to check.

**Comment by progandy** [comment]
SUID is still needed for the initial setup. The permission check is basically ```process_was_master || CAP_SYS_ADMIN``` (function ```drm_master_check_perm```)

Is CAP_SYS_ADMIN not also needed for evedv/libinput devices?

**Comment by emersion** [comment]
>the first client (for a given VT) is _always_ master

This part would maybe make it work without suid altogether.

>CAP_SYS_ADMIN is also needed for evedv/libinput devices (or some handling in e.g. udev to change the file permissions to allow access for the user)

Yeah, I think so.

**Comment by emersion** [comment]
The direct session has been dropped in favor of libseat.
