### ISSUE TITLE
Permission issue with systemd 245

### ISSUE THREAD

**Issue by DurandA** [swaywm/wlroots#2236]
Using _wlroots_ with _systemd_ 245 yields a permission issue.

This can be illustrated with `./tinywl`:
```
2020-05-29 12:52:08 - [backend/session/logind.c:217] Failed to activate session: Permission denied
2020-05-29 12:52:08 - [backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master
2020-05-29 12:52:08 - [backend/session/session.c:96] Failed to load session backend
2020-05-29 12:52:08 - [backend/backend.c:286] Failed to start a DRM session
```

Apparently, this is due to a change in _systemd_ (https://github.com/systemd/systemd/commit/4acf0cfd2f92edb94ad48d04f1ce6c9ab4e19d55) that was later reverted (https://github.com/systemd/systemd/pull/15111).

How can users stuck with _systemd_ 245 solve this issue? Unfortunately, this is the version shipped in Ubuntu 20.04.

**Comment by emersion** [comment]
We can't do anything in wlroots.

Maybe a workaround would be to use the direct session (see WLR_SESSION). Comes will all of its drawbacks.

**Comment by progandy** [comment]
Polkit can be configured. An untested example:

```/etc/polkit-1/rules.d/10-allow-inactive-chvt.rules```
```js
/* Allow users with inactive sessions to switch the console */
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.login1.chvt" &&
        subject.local && subject.session) {
        return polkit.Result.YES;
    }
});

```

**Comment by progandy** [comment]
> Ah, didn't know polkit used javascript like this, That's disgusting.

It's even worse. Currently the JS interpreter is Mozilla SpiderMonkey which weighs in at 24MiB. For configuration files.
Oh, and here is the [argument for javascript](https://davidz25.blogspot.com/2012/06/authorization-rules-in-polkit.html) by the developer.

**Comment by agx** [comment]
that's why debian based distros are using older polkit (pre JS)

**Comment by progandy** [comment]
> that's why debian based distros are using older polkit (pre JS)

Ah, right. Then it can be fixed with a pkla file that sets ResultInactive=yes for that action:

https://manpages.ubuntu.com/manpages/focal/en/man8/pklocalauthority.8.html

**Comment by DurandA** [comment]
Thank you all for the clarification.

> Polkit can be configured. An untested example:
> 
> `/etc/polkit-1/rules.d/10-allow-inactive-chvt.rules`
> 
> ```js
> /* Allow users with inactive sessions to switch the console */
> polkit.addRule(function(action, subject) {
>     if (action.id == "org.freedesktop.login1.chvt" &&
>         subject.local && subject.session) {
>         return polkit.Result.YES;
>     }
> });
> ```
> 
> https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

This solved the issue, thanks again.
