### ISSUE TITLE
EGL windows are rendered mirrored and upside down.

### ISSUE THREAD

**Issue by jgmdev** [swaywm/wlroots#2247]
Reported this [issue to wayfire](https://github.com/WayfireWM/wayfire/issues/545) thinking it was the compositor but it turns out the issue is on wlroots since it also happens on sway. Sample applications I tested are mpv and glmark2-es2-wayland. The issue is not present on weston or gnome shell using same hardware and video driver.

Here are some screenshots:
![mpv](https://user-images.githubusercontent.com/1702572/83558152-96ed8700-a4e0-11ea-8100-51078a7ebbb1.jpg)

![glmark2](https://user-images.githubusercontent.com/1702572/83558246-ba183680-a4e0-11ea-8797-5bbe087e3503.jpg)

This happens on the Odroid N2 (ARM device) which has Mali G52 GPU with Mali binary drivers. While this is using closed source drivers I took the chance to report it since it properly works on weston and gnome shell. 

Here are some log files using WAYLAND_DEBUG=1 as suggested by wayfire developer:

[mpv_wayland_debug.log](https://github.com/WayfireWM/wayfire/files/4719791/mpv_wayland_debug.log)

[glmark2_wayland_debug.log](https://github.com/WayfireWM/wayfire/files/4719801/glmark2_wayland_debug.log)

**Comment by emersion** [comment]
Sorry, we can't debug closed source drivers, so we can't help here. Feel free to send a patch if you find the cause.
