### ISSUE TITLE
Xwayland clients resize in a janky, laggy fashion

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#226]

**Comment by versusvoid** [comment]
This is due the buffer destruction immediately following size configuration. Sequence of operations goes like this:

1. Surface configuration
2. Buffer destroyed from wayland
3. Frame draw - buffer is NULL
4. New buffer assigned
5. Surface configuration
6. Buffer destroyed from wayland
7. Frame draw - buffer is NULL

Flushing xcb connection though `wl_event_loop_add_idle` (like it is done in xdg shell) does not help. I'm looking for solution.

**Comment by versusvoid** [comment]
I moved `wlr_surface_flush_damage()` call into `wlr_surface_commit_pending()` (analogous to weston) and windows began to resize smoothly.

**Comment by acrisci** [comment]
> I moved wlr_surface_flush_damage() call into wlr_surface_commit_pending() (analogous to weston) and windows began to resize smoothly.

I think that should be ok.
