### ISSUE TITLE
Corruption when fullscreening application while using hardware cursors

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/wlroots#2263]
### wlroots/sway versions
wlroots version: `0.10.0.r178.ga3ba8288-1`
sway version: `sway version 1.4-d7900c6e (Jun  6 2020, branch 'master')`
Kernel: `5.6.15-arch1-1`
mesa: `20.0.7-3`
GPU/Drivers: Navi, amdgpu

### Description
When using hardware cursors and fullscreening `kitty`, I get graphical corruption rendering the terminal unsuable. That does not mean the terminal does not work, I just cannot see what I am typing on it. When exiting fullscreen everything works as expected. I have only been able to reproduce this with `kitty`, so it is entirely possible this is a `kitty` or `glfw` bug, however this bug manifests itself by changing the `WLR_NO_HARDWARE_CURSORS` environment variable.

### Reproduction

Start sway with `WLR_NO_HARDWARE_CURSORS=0 sway -c test_config`, and then launch kitty. 

`test_config` is two lines:
```
include /etc/sway/config
bindsym $mod+m exec kitty
```
When setting `WLR_NO_HARDWARE_CURSORS=1` this issue does not occur.

### Logs
Log files created with 
```
WLR_NO_HARDWARE_CURORS=(1|0) WAYLAND_DEBUG=1 sway -c test_config -d 2>sway.log
```
With `WLR_NO_HARDWARE_CURSORS=1`: https://0x0.st/iVPG.log
With `WLR_NO_HARDWARE_CURSORS=0`: https://0x0.st/iVPD.log

Please let me know whatever information is relevant. I did not attempt to bisect this because I have never known a version where this works. I rarely put terminals in fullscreen.

**Comment by emersion** [comment]
Sounds related to direct scan-out. Maybe related to https://github.com/swaywm/sway/issues/5428

**Comment by LaserEyess** [comment]
Cannot reproduce this anymore.
