### ISSUE TITLE
Use wlr_keyboard_notify_modifiers under X11 backend

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#227]
This can be done by listening to `XCB_INPUT_KEY_PRESS` and `XCB_INPUT_KEY_RELEASE`. The `xcb_input_key_press_event_t` contains a `xcb_input_modifier_info_t` struct with the required data.

See https://github.com/swaywm/wlroots/pull/221 for more info.

**Comment by acrisci** [comment]
Is this still relevant with the keyboard redesign?

**Comment by emersion** [comment]
Yes.
