### ISSUE TITLE
wlr_renderer_rect() misrenders negative width and height

### ISSUE THREAD

**Issue by goleo108** [swaywm/wlroots#2281]
I was trying to find a bug in Wio's render_view_border() which causes it to render borders in wrong positions when you reflect view, it's more noticeable when you reflect view by both x and y coordinates:
![bug](https://user-images.githubusercontent.com/56087471/84708324-d3dd6300-af4f-11ea-8e5d-b3028189c056.png).

**Comment by emersion** [comment]
We should probably `assert(width > 0 && height > 0)`

**Comment by goleo108** [comment]
But then it's pointless to have them as signed integers? If you are ok breaking backwards compatibility, it's better to either make them unsigned integers or replace them with x2 and y2 almost like in Go: https://golang.org/pkg/image/#Rectangle

**Comment by emersion** [comment]
1. Not worth it to break the API for this
2. Unsigned integers make it too easy to mess up substractions

**Comment by goleo108** [comment]
Then I recommend to change x, y, width and height values because nobody likes crashes, something like (please note I didn't test this code):
```
void wlr_render_rect(struct wlr_renderer *r, const struct wlr_box *box,
		const float color[static 4], const float projection[static 9]) {
	float matrix[9];
	wlr_box tbox = *box;
	if (tbox.width < 0) {
		tbox.width *= -1;
		tbox.x -= width;
	}
	if (tbox.height < 0) {
		tbox.height *= -1;
		tbox.y -= height;
	}
	wlr_matrix_project_box(matrix, &tbox, WL_OUTPUT_TRANSFORM_NORMAL, 0,
		projection);

	wlr_render_quad_with_matrix(r, color, matrix);
}
```

**Comment by goleo108** [comment]
I'll send a PR after testing.

**Comment by ascent12** [comment]
Negative width/height fundamentally doesn't make sense. I don't think adding workarounds for broken user code is a good idea.

**Comment by goleo108** [comment]
Ok, I already patched Wio to avoid negative width and height, I just don't like duplicating code.
