### ISSUE TITLE
Out of context glFinish

### ISSUE THREAD

**Issue by any1** [swaywm/wlroots#2286]
I was running `apitrace` to track down a different issue when I noticed that `glFinish()` is called with no gl context set.

It's most likely this one: https://github.com/swaywm/wlroots/blob/e77c046cf98f53a9307deeb8940d67938c078986/backend/drm/drm.c#L962

**Comment by progandy** [comment]
That one probably lost the gl context because of af2f69e6c1578f848d3e3222804444ff9cff83df

**Comment by emersion** [comment]
We should properly make the mgpu surface current before `glFinish`, and unset it after.

**Comment by emersion** [comment]
Removed in https://github.com/swaywm/wlroots/commit/60001a75a276f931b02d78a95cedfd0098b88617
