### ISSUE TITLE
eb22ae97b01e26f2a64f81c0e34ef7ad1f870ac4 broke sway rendering

### ISSUE THREAD

**Issue by kchibisov** [swaywm/wlroots#2287]
it seems like eb22ae97b01e26f2a64f81c0e34ef7ad1f870ac4 broke the rendering of clients in sway entirely.

sway version used:

sway version 1.4-21b77f37
wlroots - latest master ( or that particular commit with older sway, doesn't really matter).

[debug.log](https://github.com/swaywm/wlroots/files/4796037/debug.log)

![broken-sway](https://user-images.githubusercontent.com/27620401/84973281-6553fd00-b129-11ea-8b9d-56a9594b6aaf.gif)

**Comment by Emantor** [comment]
Could you test https://github.com/swaywm/wlroots/pull/2288?

**Comment by emersion** [comment]
I can't reproduce this issue at all. Can you provide reproductions steps?

**Comment by GreyXor** [comment]
I had the same problem and #2288 fixed it.

**Comment by kchibisov** [comment]
I mean for me the instructions are just open firefox or alacritty. that's all I've done honestly. Maybe OpenGL apps are failing?

**Comment by kchibisov** [comment]
>Could you test #2288?

Yeah, it fixed the issue. thx.
