### ISSUE TITLE
Event system is weird and feels inefficient, overcomplicated

### ISSUE THREAD

**Issue by goleo108** [swaywm/wlroots#2297]
While contributing to Wio I went through a trouble of removing duplicate code, because input.c and output.c both need to calculate same coordinates when creating new windows, resizing windows and moving windows, to solve this problem I created 2 functions: first calculates coordinates, second enforces minimal size: https://github.com/goleo108/wio/commit/ee68d6dfd647cb17ac5be1368fa496fde994113d#diff-8cf3314256bfa2bfee79fd7e409caebeR187

However, that approach didn't handle scaling for HighDPI displays because input.c has no idea of output's scale, so now I need 3 functions: first calculates coordinates, second saves coordinates and third loads last saved coordinates: https://github.com/goleo108/wio/commit/c48c8a7995776a8f9d989be4ba89bbe8cf033140

But that's not over, I forgot about scaling for function that figures out is my mouse cursor pointing at window's surface or at window's border and I have no idea how to fix it because input.c is responsible for figuring it out: https://github.com/goleo108/wio/blob/34233e53b76710cfdb97d1639d72275db1fcb11b/view.c#L156

And this complexity goes further, I can't simply write in one function
```
while (event->button == BTN_RIGHT) {
    calculate_coordinates();
    output_to_display();
    event->button = read_mouse();
}
move_window();
```
like here: https://github.com/0intro/plan9/blob/master/sys/src/cmd/rio/rio.c#L759

And this is not over, I'm trying to improve Wio's menu to remember last item used, sure I can change structure a bit to remember scale, but I can't fix a bug at initialization stage when menu's width and height are 0 and cause a menu to be placed at wrong position when opened first time, but it gets worse if I'll dynamically add and remove items from menu, because input.c will always receive previous height value.

**Comment by emersion** [comment]
Not sure what you're trying to say. I see your compositor code is getting complicated, but that seems like an issue with your compositor, not wlroots.

Do you have practical suggestions to improve the wlroots API?

Side note, the input code shouldn't have to handle HiDPI at all. The scale should only be used when rendering.

**Comment by emersion** [comment]
I also don't understand the relationship between the title of the issue and its content. The issue description doesn't explain any of the points made in the title.

**Comment by goleo108** [comment]
@emersion how do I calculate exact borders' x, y, width and height without knowing their scale?

**Comment by emersion** [comment]
>how do I calculate exact borders' x, y, width and height without knowing their scale?

You're supposed to compute positions in layout coordinates, which is the global coordinate space used for most things. The input code can use these. When rendering multiply these by the scale factor to obtain output buffer coordinates.

**Comment by ddevault** [comment]
Closing as this isn't really an actionable issue

**Comment by goleo108** [comment]
@emersion but I can't, it's impossible for input code to use it: https://github.com/swaywm/wlroots/blob/master/types/wlr_output_layout.c#L308

*all night long I thought I'm too stupid to use it*

**Comment by emersion** [comment]
Not sure what the linked code has to do with scaling, or explains why input code can't use layout coords. Anyway, the issue tracker isn't for support, if you have questions please ask on IRC.

**Comment by goleo108** [comment]
@emersion ... I can't use layout coordinates because input code doesn't have wlr_output instance required by `wlr_output_layout_output_coords()`, so I don't know what you are talking about.

But anyway I don't care anymore, I don't like this library nor Wayland itself, I made a mistake.

**Comment by ddevault** [comment]
Locking as this conversation is unproductive, and as you said, you don't care and Wayland is a mistake.
