### ISSUE TITLE
idle.c example calls free instead of wl_registry_destroy

### ISSUE THREAD

**Issue by j-n-f** [swaywm/wlroots#2303]
I used this example code as a model for some code I was developing, and ran into segfaults as a result:

https://github.com/swaywm/wlroots/blob/master/examples/idle.c#L130

Is there any particular reason that `free` is used in place of `wl_registry_destroy` here?

From some basic debugging I did, issues occur when `wl_registry.global_remove` shows up (which seemed to be happening when DPMS turned the display off for 10+ seconds). From what I understand, the client and server probably both think the `wl_registry` is bound, otherwise I don't think the server would be sending events to it.

**Comment by ascent12** [comment]
Yeah, that's invalid.
Feel free to send a PR fixing that.
