### ISSUE TITLE
Popups render off screen and across outputs

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#231]
To reproduce, move a window adjacent to an output boundary and open some menu. You will notice that the menu can be drawn off the screen. Also, the menu should not be drawn across outputs.

The xdg-positioner has rules for how the popup should be adjusted when the popup is constrained like this, but those rules are currently not used. The popup might ask to "slide over" or maybe to have the popup change its size.

The implementation might be complicated because now the shell will need to find some way to interact with the wlr-output-layout to find the screen boundaries given its layout coordinates.

This feature seems implemented in X11-based window managers, but not in Weston. So maybe we need to try to patch Weston for this first to get their feedback on the implementation.

**Comment by SirCmpwn** [comment]
I think we should bubble up signals and let rootston tell the shell how each popup should be positioned.

**Comment by SirCmpwn** [comment]
bump
