### ISSUE TITLE
Xwayland triggers screensaver if using xss-lock

### ISSUE THREAD

**Issue by mikn** [swaywm/wlroots#2311]
I don't know the exact terms of what's happening, but I've noticed that if I run `xss-lock` together with `Xwayland` (I use sway) the screensaver gets triggered when I use wayland native applications. I assumed this was because of the default screensaver time of 10 minutes (600 seconds) within Xorg and I tried setting `xset s 0`. This removed the screensaver being triggered. I went digging for if I could add this setting to a configuration file, but it seems that Xwayland reads no configuration files on startup. Running `Xwayland --help` however revealed that there's a configuration flag `-s` which controls the default screensaver time. So I went searching for how to add `-s 0` to the parameters and found the code path here: https://github.com/swaywm/wlroots/blob/master/xwayland/server.c#L47-L116 which confirmed that this is currently not provided as a function in wlroots.

As I see it there are two options to solve this:
1. Add a feature to pass in arbitrary flags to the Xwayland command
2. Add `-s 0` as a default flag

With my cursory knowledge I see no problem in doing 2 first, as when you're in a wayland compositor, I don't think you want X to send inactivity notifications "per default" at least. If you're building something similar to `swayidle` I think it is reasonable to be expected to manually set the idle time for X as well as noticing idle activity within the wayland compositor, but again, this is just with my very limited knowledge of this problem area. :)

I can provide a PR for 2 easily, but not sure I have the time for doing 1 soon.

**Comment by emersion** [comment]
X11 screen savers are not supported.

>I don't think you want X to send inactivity notifications "per default" at least

Sounds like this should be an Xwayland patch.

**Comment by mikn** [comment]
> X11 screen savers are not supported.
> 
> > I don't think you want X to send inactivity notifications "per default" at least
> 
> Sounds like this should be an Xwayland patch.

`xss-lock` is not strictly a screensaver, it is merely a trigger which listen to a set of signals, one of which is sent by X, and as it seems, Xwayland. I'll file an upstream ticket with Xwayland however as I think you are correct.

What do you think about suggestion number 1? To add the ability for consumers of this library to send in additional parameters to Xwayland?
Do you have any suggestion for point of implementation?

**Comment by emersion** [comment]
>What do you think about suggestion number 1?

I'm not thrilled about it. This gives access to flags that can potentially break everything in weird ways.

Users that really want to customize their Xwayland flags can always create a wrapper at `~/bin/Xwayland` and add `~/bin` to their PATH. I'd be more open to add a way to customize the default Xwayland executable name (e.g. `export XWAYLAND=/path/to/xwayland`).

**Comment by mikn** [comment]
I will close this ticket in favour of the upstream ticket here: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1051
I am currently using your proposed workaround, so thank you for that! It didn't cross my mind I could do it that way. :)
