### ISSUE TITLE
Resume from DPMS is broken under Sway

### ISSUE THREAD

**Issue by forgottenswitch** [swaywm/wlroots#2312]
When using 0.10.0-216-g6c8f66ff59b2 ("xcursor: add xorg-x11 and cursors path to XCURSORPATH") against Sway 1.5-rc1-2-gbb85b9070d05 ("tree/view: fix smart borders with tabbed/stacked ancestor") on a non-atomic-modesetting-enabled machine, an `swaymsg output 0 dpms on` is unable to restore the monitor back from DPMS sleep previously entered into by means of `swaymsg output 0 dpms off`. Only switching to another VT and back achieves the desired effect.

Testing 15d8f1806e9debd11a1c306e76c97b535e708766 (cc @emersion) against Sway 1.2-rc1-372-g6f7b548589fe ("ipc: invert output transformation when necessary") revealed that the cause is the following([1]) undocumented semantical bit:
```
--- a/backend/drm/legacy.c
+++ b/backend/drm/legacy.c
<..>
@@ -28,18 +28,20 @@ static bool legacy_crtc_commit(struct wlr_drm_backend *drm,
<..>
                uint32_t *conns = NULL;
                size_t conns_len = 0;
                drmModeModeInfo *mode = NULL;
-               if (crtc->active) {
+               if (crtc->pending.mode != NULL) {
                        conns = &conn->id;
                        conns_len = 1;
<..>
```
instead of the purely syntactical
```
-               if (crtc->active) {
+               if (crtc->pending.active) {
```

[1]: https://github.com/swaywm/wlroots/commit/15d8f1806e9debd11a1c306e76c97b535e708766#diff-8e1b4b13cdd2556646cb0e21c7a784fcL35

A quickly testable version is [here] (without pretending that its description is too insightful).

[here]: https://github.com/forgottenswitch/wlroots/tree/dpms-fix-curpending-sample1

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2313?

**Comment by forgottenswitch** [comment]
Confirming that f82a27f works.
