### ISSUE TITLE
Xwayland gets stuck in endless loop with multiple-windows-per-process clients

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#2324]
Initially I found this in Wayfire: https://github.com/WayfireWM/wayfire/issues/561

However, I could reproduce in Sway too:

1. Add bindings to move window to another workspace and to focus that workspace and the new window in it (it is important to focus immediately when switching, otherwise it works):
```
bindsym $mod+Shift+1 move container to workspace 1; workspace 1
```
2. Start Sway with at least 2 monitors
3. Open chrome on one workspace.
4. Open a new chrome window (ctrl-N)
5. Use the binding to move the chrome window to the workspace on the other monitor.

The window freezes, Xwayland and wlroots both have a very high CPU usage (~100%). @damianatorrpm managed to bisect it and the problem is https://github.com/swaywm/wlroots/pull/2219

My theory as to why it happens (say the two windows are X and Y)

1. Client tries to focus X
2. Compositor focuses Y
3. Message from 1. arrives in wlroots, we focus X
4. Message from 2. arrives in client, it resets the focus to Y
5. Message from 3. arrives in client, it resets focus to X
6. Message from 4. arrives in wlroots, it focuses Y

Notice 5./6. is same as 1./2. so we get an infinite loop. Not sure if this is really the problem but something like that is happening. Ideas?

**Comment by ammen99** [comment]
Also forgot to mention that @damianatorrpm could reproduce with Qt clients running under Xwayland, so it is not chrome-specific issue.

**Comment by ynakao** [comment]
I have the same issue after updating sway v1.5 + wlroots v0.11 on Arch Linux. 

In my case, when I open a new Firefox window along with the existing one and move it to another workspace and then focus back to the original window, CPU usage goes around 100% and Firefox doesn't accept any commands.

**Comment by Xyene** [comment]
I just have a question about the mechanism you describe... is there some "focus request acked"-type thing in X11? How does the client distinguish the focusing from step 2 from a regular user-initiated focus request, i.e. why does the client decide to change the focus again? Does it not receive that supposed ack from step 1 before it receives step 2's request?

**Comment by ammen99** [comment]
> why does the client decide to change the focus again?

I assume that indeed we are getting some FocusIn events which are like ACKs (the client or Xwayland sends that ACK to the window-manager). However it first ACKs the first request, and because of the asynchronuous communication we get the described race condition.

**Comment by ammen99** [comment]
A solution to this problem will be difficult because of the following facts:

1. We get response focus-in requests with the apps that are getting stuck, i.e the events look like this:
- Compositor focuses X
- Compositor focuses Y
- FocusIn for X
- FocusIn for Y

This means we need to somehow ignore FocusIn for X

2. For steam, we have the following sequence:
- Compositor focuses X (steam main window)
- (a lot of time & events happen)
- FocusIn for Y (steam popup menu)

The only difference that we have from the xwm point of view is that in the first case, the client wants to switch focus between two toplevel windows, and in the second, steam wants to switch from the toplevel to the popup window.

What would be the desired fix?

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/2355
