### ISSUE TITLE
xdg-popup: don't swallow the button event on ungrab

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#233]
To reproduce, open two windows. Open a popup on one of the windows (like a right click menu) and now click on the other window. You will see that the popup is dismissed, but the other window does not get focused. This is because the grab "swallows" the button event to dismiss the popup so the other window never gets the button press. Better might be if the button event went through to the other window so the compositor can focus the window and the window can process the click.

Weston and i3 has the former behavior. It might be a design decision, or maybe it's just an artifact of our legacy. Windows(tm) has the behavior that I am suggesting here.

I guess it's a matter of opinion on what is correct here. Maybe we should implement this in such a way that compositor implementations can set their own policy.

**Comment by SirCmpwn** [comment]
I agree with your proposed behavior. We should dismiss the popup and send the click to the other window.

**Comment by SirCmpwn** [comment]
via GenkiSky on IRC

  <p>
    This is for wlroot's <a href="https://github.com/swaywm/wlroots/issues/233">Issue #233</a>.
    <em>Summary</em>: If you have two windows open, then open a XDG popup on one, and
    left-click on the other, the newly-clicked window will not receive keyboard
    input. This is especially noticeable as the newly-clicked window
    receives XDG activation, despite keyboard input still going to the old window.
  </p>

  <p>
    The high level cause is that the popup's keyboard grab ignores enter() events,
    which are given when rootston is trying to change focus. Here are some
    options for solutions.
  </p>

  <h3>Option A: Both close the popup menu, and change focus to the other window.</h3>
  <ul>
    <em>Benefits:</em>
      <ul>
        <li>This behavior is what is expected by some, in discussion on <a
            href="https://github.com/swaywm/wlroots/issues/233">Issue #233</a>.
        <li>It's a simpler mental model that you, as the compositor, can
          just cancel the keyboard grab at any point, without worry.
        <li>At least for one of the below patch options, no API change is needed.
      </ul>

    <em>Patch options:</em>
      <ul>
        <li><a href="impl_cancel.patch">impl_cancel.patch</a>: When changing
          focus, each keyboard-grab impl must explicitly cancel themselves.
        <li><a href="rootston_cancel.patch">rootston_cancel.patch</a>: When
          changing focus, wlroots library-user can force-cancel the keyboard-grab.
        <li><a href="default_cancel.patch">default_cancel.patch</a>: When changing
          focus, have all keyboard-grab impls cancel themselves, unless they
          explicitly choose not to.
      </ul>
  </ul>

  <h3>Option B: Don't change focus / activate the new window. Just close the popup.</h3>
  <ul>
    <em>Benefits:</em>
      <ul>
        <li>Both X11 and Weston do this. Generally, seems smartphone UIs also have this behavior.
        <li>
          <a href="https://www.youtube.com/watch?v=GWQh_DmDLKQ">https://www.youtube.com/watch?v=GWQh_DmDLKQ</a>
          (from 35:05 - 36:26) talks about how a significant point of Wayland is
          that clients are in control of lifetimes.
          <ul>
            <li>Yes, he focuses on input devices, but it was discussed in a general manner.
          </ul>
        <li>Like @acrisci said, we might run into keyboard grab-impls that
          actually want to deny the focus change.
        <li>More-complex logic is needed to naturally extend Option A.
          <ul>
            <li>For example, if you right-click on another window, when a popup
              is open, it just focuses it (instead of, for example, opening its
              popup).
          </ul>
        <li>With the proposed patch below, compositors could have the choice of
          doing Option A or Option B.
          <ul>
            <li>Basically, they can choose to ignore if the enter() is swallowed
              or not.
            <li>And if they don't want to ignore the swallowing, they can still
              store the desired enter() until the liftetime of the keyboard grab
              ends naturally, and run it then.
          </ul>
      </ul>

    <em>Other notes:</em>
      <ul>
        <li>Yeah, you have to handle the fact that
          wlr_seat_keyboard_notify_enter() can now fail. But in rootston code, at
          least, that just means handling in two places.
      </ul>

    <em>Patch options:</em>
      <ul>
        <li><a href="enter_can_be_swallowed.patch">enter_can_be_swallowed.patch</a>:
          Check possibility that keyboard enter() is swallowed. If so, don't
          change focus.
      </ul>
  </ul>

**Comment by acrisci** [comment]
> Like @acrisci said, we might run into keyboard grab-impls that actually want to deny the focus change.

Yeah, I'm kind of leaning towards making people manually end grabs now for that reason. I'm afraid we might want to come up with a protocol that does fancier things with keyboard grabs than we have now that might require a completely different keyboard enter mechanism.

For the actual behavior, none of this actually addresses the issue of the button being swallowed. What I really want is for the button to 1) end the grab and then 2) be replayed on the surface it is over.

This way, I can right click on one weston-terminal, and then right click on another weston-terminal and the second right click will 1) dismiss the first popup and then 2) summon a new popup on the other window.

But I want the implementation in wlroots to be simple as possible while allowing for both behaviors, because it intuitively seems to me like the behavior I want is desktop-specific and might not be applicable on other devices.
