### ISSUE TITLE
Draw over screen application/protocol

### ISSUE THREAD

**Issue by Algram** [swaywm/wlroots#2331]
Hi there,

I've been trying to contribute more to the wlroots/sway ecosystem since I've been using it for quite some time now and absolutely love it!

One think I would like to implement is an application that lets me draw over the screen for annotations while screensharing. Basically this: https://framagit.org/abakkk/DrawOnYourScreen

The way waylands architecture works this seems quite tricky. I've researched a bit and think the only option would be if either wlroots supports this directly or there exists a protocol.

Could you give me some pointers on how I would approach this feature?

Thanks!

**Comment by emersion** [comment]
Should be possible to do with the wlr-layer-shell protocol.

(Closing because this isn't a wlroots issue -- next time please ask questions on IRC.)
