### ISSUE TITLE
Firefox crashes on sway reload

### ISSUE THREAD

**Issue by layus** [swaywm/wlroots#2334]
Hi,

I experience some trouble with firefox, as it regularly (but not always) crashes on sway reload. I had homes for #1765 to fix it, but it is not yet okay.

I have placed `WAYLAND_DEBUG=1` logs on gist (see below).

- `debug.log` is when firefox does not crash
- `debug2.log` is when it crashes
- `filtered.diff` is the diff between the two, with all numbers removed.

See in particular the last lines of the crashing process https://gist.github.com/layus/7dc414116d728fbf9c681da3b80ee0de#file-filtered-diff-L5201-L5207

Anything else to debug this ?

**Comment by emersion** [comment]
Can you run Firefox with `G_MESSAGES_DEBUG=all`?

**Comment by emersion** [comment]
Feel free to re-open with a new debug log, see my previous comment.

**Comment by layus** [comment]
Re-opening (virtually, I do not have the rights to) with added debug as the issue persists, and is now fully reproducible.

Debugging with G_MESSAGES_DEBUG=all gives nothing. When sway reloads, I get either of the following messages. There is a full log at https://gist.github.com/layus/8047ba049dcedc6db25a163d3eb9e95d#file-ff_gmessages_all-log.

```
 Gdk-Message: 14:51:46.421: Error flushing display: Broken pipe
 Exiting due to channel error.
 Exiting due to channel error.
```
 
```
 Gdk-Message: 14:52:35.700: Error flushing display: Broken pipe
 Exiting due to channel error.
 Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=13.8534) Exiting due to channel error.
```

I went debugging with WAYLAND_DEBUG=client on top of that, and the log contains way too much information for me. The interesting part start at https://gist.github.com/layus/8047ba049dcedc6db25a163d3eb9e95d#file-ff_debug_all-log-L1900-L2873.

**Comment by layus** [comment]
For comparison, here is what happens when `pkill`ing firefox: https://gist.github.com/41fea3af190e516e0626564dc6c5c374

And here is a normal shutdown with sway keybinding (Ctrl+Shift+c): https://gist.github.com/51b21c871e8caf60b849daf5392f4673

The shutdown happens a few lines after `xdg_toplevel@53.set_title("ff_debug_all.log — Mozilla Firefox")` which is about the end of firefox init. In the pkill case, nothing is written at all from WAYLAND_DEBUG.

**Comment by layus** [comment]
Oh, and this is sway version 1.6.1. I guess I should try with master.

**Comment by layus** [comment]
Aparently the large number of 

```
[2868958,338] wl_keyboard@28.keymap(1, fd 157, 65983)
[2868966,350] wl_keyboard@28.repeat_info(25, 600)
[2868966,382] wl_keyboard@69.keymap(1, fd 158, 65983)
[2868972,257] wl_keyboard@28.repeat_info(25, 600)
...
```

is normal, it must come from wlroot notifying every change happening to the keyboard configuration during reload. While it could be buffered, other apps handle it fine. So should firefox.

The strange part is thus `[2868956,526]  -> wl_display@1.get_registry(new id wl_registry@150)` where firefox keeps asking for a new global registry, and receiving one, in a loop. This operation should be used sparingly, so that is a weird behavior.

**Comment by layus** [comment]
I guess it is still a race condition, possibly related to https://github.com/swaywm/wlroots/pull/1765 as it does not happen under gdb, and not always when tracing. Under gdb, there is no `wl_display@1.get_registry(new id wl_registry@150)` appearing at all in the long sequence of `wl_keyboard@28.{keymap,repeat_info}`.

**Comment by layus** [comment]
Oh, and of course it is even more annoying now that Thunderbird is also a native Wayland app.

**Comment by layus** [comment]
Under gdb, the trace looks like this: https://gist.github.com/f0d04bf72057f21a8061bc8292f48186 (search for "swaymsg reload")
