### ISSUE TITLE
Type casts in rendering process

### ISSUE THREAD

**Issue by Bl4ckb0ne** [swaywm/wlroots#2347]
Here's the following code, taken from the renderer of one of my project

```c
double ox = 0.0, oy = 0.0;
wlr_output_layout_output_coords(routput_layout, output, &ox, &oy);

struct wlr_box box = {
	.x = ox * output->scale,
	.y = oy * output->scale,
	.width = surface->current.width * output->scale,
	.height = surface->current.height * output->scale,
};

enum wl_output_transform transform = wlr_output_transform_invert(
		surface->current.transform);

float matrix[9];
wlr_matrix_project_box(matrix, &box, transform, 0,
		output->transform_matrix);
```

With the flags `-Wfloat-conversion` and `Wconversion` enabled, there's a lot of warnings coming from that part of the code. `ox` and `oy` are doubles, `output->scale` is a float, and `wlr_box` is all int. 
Why is there so many types involved in the process? Shouldn't it all be ints, or floats, or even ints and floats? 

I see that the coordinates from `wlr_output_layout_output_coords` are casted from `float` to `double`, why?

Also I see that `wlr_matrix_project_box` is then casting the integers from `wlr_box` into floats for matrix operations. Wouldn't `wlr_matrix_project_fbox` make more sense?

**Comment by emersion** [comment]
>Wouldn't wlr_matrix_project_fbox make more sense?

No. Rendering a texture "between" two physical pixels will make the whole thing blurry.

**Comment by Bl4ckb0ne** [comment]
So should everything be integers?

**Comment by emersion** [comment]
`wlr_output_layout_output_coords` takes doubles because it's designed to work with input coordinates as well, which are doubles.
