### ISSUE TITLE
gnome-terminal: profile preferences spawn outside rootston

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#237]
1. Open `gnome-terminal` under the Wayland backend
2. Right click > Profiles > Profile Preferences
3. The Preferences window spawns outside rootston, in the parent compositor

**Comment by emersion** [comment]
Under the DRM backend, the Preferences window won't open.

**Comment by martinetd** [comment]
I think that one is actually a gnome-terminal problem. I hardly ever use gnome-terminal, but earlier I poped one in rootston (DRM) then changed VT, and under X11 started another gnome-terminal command... which made another terminal pop up in rootston.

So basically it looks like it's ignoring the DISPLAY/WAYLAND_DISPLAY environment variables and just creates new windows wherever the old ones are. Did you have gnome-terminal started outside of rootston before poping preferences?

**Comment by emersion** [comment]
Yeah, I have, you're right!
