### ISSUE TITLE
vmwgfx resizing doesn't work

### ISSUE THREAD

**Issue by matthewbauer** [swaywm/wlroots#2377]
Running Virtualbox 6.1 with VMSVGA driver, I am unable to resize the guest window and have wlroots resize. This happens in Cage, but I have confirmed that Cage never gets a notification on the resize, so I think this is wlroots responsibility.

Note that wlroots already gets the DRM size correctly if you resize the window and restart the wlroots client. This means that I think we just aren't getting the notification of when resize happens.

wlroots should be able to listen to the VMW_UPDATE_LAYOUT and set the preferred mode based off of that. It should work similarly to how X11 resizing works and I think this is how GNOME/KDE wayland implementations handle it.

**Comment by emersion** [comment]
Sorry, we don't add support for driver-specific features.
