### ISSUE TITLE
Support libei for input emulation

### ISSUE THREAD

**Issue by MayeulC** [swaywm/wlroots#2378]
[libei](https://who-t.blogspot.com/2020/08/libei-library-to-support-emulated-input.html) is a new library for input emulation under wayland. ([git repository](https://gitlab.freedesktop.org/whot/libei/))

The `libeis`, libei input server is to be user by the compositor. It will provide it with inputs the same way libinput does.

Possibly related to #1203.

Possible use-cases include:
* Remote desktop
* KDE Connect remote control
* Synergy
* Task automation and cross-compositor unit testing.
* Sanboxed input emulation
* Password managers?

It has some support from other compositor, and should provide some backwards compatibility with XWayland relatively soon, according to the blog post linked above.

**Comment by emersion** [comment]
We already have Wayland protocols for input emulation. I think libei should add support for those.

Closing because it doesn't make sense for a Wayland library like wlroots to add support for libei anyways. Compositors can do it on their own.

**Comment by MayeulC** [comment]
Thanks. At least this issue will document the answer :)

I thought that would belong to wlroots, as it already supports libinput.

**Comment by whot** [comment]
>  it doesn't make sense for a Wayland library like wlroots to add support for libeis anyways. Compositors can do it on their own.

Yes, I basically agree here. The point of libei is that it is independent of the display manager, there is nothing Wayland-y about it. 

Having said that, it's a separate communication channel for emulated input events, similar to how libinput is a separate communication channel for hardware input events. libeis' API is intentionally quite similar to libinputs API so you may want wlroots to map libeis events into the same events used internally (`wrl_event`) with e.g. a flag to indicate emulated input. But exactly where that merging of hw input events and emulated input events happens is up to the libeis consumers.
