### ISSUE TITLE
Is there a wlroots based WM that uses Rust to configure the Window Manager?

### ISSUE THREAD

**Issue by Joe23232** [swaywm/wlroots#2401]
I am looking for a Window Manager that is like XMonad where I have the source code with me and I make a new file and write my very own WM in a high level manner, all though I want to do this in Rust.

Is there a WM that is based on wlroots where I can configure the entire WM with Rust?

**Comment by emersion** [comment]
Not aware of anything like that.

Please ask questions on IRC next time.

**Comment by Joe23232** [comment]
Is there a discord server or something alternative as well?

**Comment by emersion** [comment]
We will never have a Discord/Slack/other chat walled garden server.

**Comment by Joe23232** [comment]
Oh, what about Matrix, that can't be walled gardened server?

**Comment by emersion** [comment]
Matrix is unsuitable for our needs, but you can use its IRC bridge if you want.

**Comment by Joe23232** [comment]
I see.

Is there a link to the IRC channel, I am trying to find the link.

**Comment by emersion** [comment]
#sway-devel on Freenode

**Comment by Joe23232** [comment]
Thank you.

**Comment by Joe23232** [comment]
IRC is kinda not working on my end, is there a community like discourse (not _discord_) or something similar?

**Comment by progandy** [comment]
For IRC there is also a web-interface: https://webchat.freenode.net/?channels=sway&uio=d4

The rust bindings for wlroots have been abandoned due to the bad match between the API and rust: http://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html

**Comment by Joe23232** [comment]
> For IRC there is also a web-interface: https://webchat.freenode.net/?channels=sway&uio=d4

Apparently I am _banned_ for some weird reason. I did try it the first time, and it was failing to connect so I retryed to log in and it _bans_ me. IRC feels more walled garden than discord itself. Even DIscord is not that bad. I have always had issues with IRC.

> The rust bindings for wlroots have been abandoned due to the bad match between the API and rust: http://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html

I see, thanks for letting me know :)

**Comment by emersion** [comment]
>IRC feels more walled garden than discord itself. 

This is bad faith. It would be the same to say wlroots is closed-source because GitHub is down.
