### ISSUE TITLE
xwayland won't connect, crashes sway entirely

### ISSUE THREAD

**Issue by dumanovskis** [swaywm/wlroots#2412]
I'm using wlroots 0.10 and sway 1.4 on an embedded platform where I have to use Wayland. Weston 7 works just fine, with xwayland, but I'm experiencing a problem with sway and xwayland. If I try to run an X application, e.g. `DISPLAY=:0 xterm` while sway is running, xterm crashes with the usual unable to open display, and sway crashes entirely. The following gets logged:

```
could not connect to wayland server
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)
```
I understand that sway doesn't actually run xwayland at once, rather it waits for some application to request it. I tried starting xwayland before sway, using a systemd service, but that doesn't seem to help. I start it as `/usr/bin/Xwayland :0`, making sure it has access to the `XDG_RUNTIME_DIR` envvar, but if I then start sway and xterm, the result is the same.

After sway starts (with or without xwayland started in advance), I can confirm it's listening to X sockets - `lsof` shows it listening to `/tmp/.X11-unix/X0'.

I assume there's something wrong with how I'm starting sway. I'm using a systemd unit to start sway on tty7 as root like this (I patched it so it won't refuse to run as root):

```
[Unit]
Description=Sway on tty7
RequiresMountsFor=/run
Conflicts=getty@tty7.service plymouth-quit.service
After=systemd-user-sessions.service getty@tty7.service plymouth-quit-wait.service

[Service]
User=root
PAMName=login

UtmpIdentifier=tty7
TTYPath=/dev/tty7
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes

Environment="XDG_RUNTIME_DIR=/run/user/0"
ExecStartPre=/usr/bin/chvt 7
ExecStart=/usr/bin/sway

IgnoreSIGPIPE=no

[Install]
Alias=multi-user.target.wants/sway.service
```
I know systemd integration isn't in the scope of the project, but I'm hoping for some help on how to get xwayland working on my platform.

EDIT: Found in the source that you can set `xwayland force` in the sway config to immediately load xwayland. If I do that, I get a crash with the same log message immediately after starting sway.

EDIT2: Should have been filed against sway - some more debugging reveals that SIGUSR1 from xwayland is the culprit. sway starts xwayland, then gets SIGUSR1, and promptly dies to it not being masked on some threads apparently. It seems that the GPU drivers are causing additional threads to be created, messing up the signal mask.

**Comment by dumanovskis** [comment]
Okay, so as it happens in some other cases, submitting an issue is a good way to help myself find the cause!

Now that I know SIGUSR1 is to blame, I see there have been issues with that in the past both on sway and on wlroots. Patching sway to mask SIGUSR1 fixes xwayland for me. Looks like #2154 is still valid so this problem could reoccur with other GPU drivers?

**Comment by emersion** [comment]
Closing as a dup of #2154.
