### ISSUE TITLE
Don't send keys to clients when they match a keybinding in rootston

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#242]
This will be annoying but we'll have to figure it out anyway for sway.

**Comment by acrisci** [comment]
Use a keyboard grab?

**Comment by SirCmpwn** [comment]
I don't think that makes sense.

**Comment by emersion** [comment]
Can't all keyboard events go through rootston just like the mouse events?

**Comment by SirCmpwn** [comment]
That's likely to be the correct solution, yes.
