### ISSUE TITLE
wlr_texture_from_pixels: missing piece of documentation

### ISSUE THREAD

**Issue by werererer** [swaywm/wlroots#2437]
### Problem
When I use wlr_texture_from_pixels inside wlr_render_begin and wlr_render_end my program crashes after calling the next function that has something to do with rendering with the following message:
```
test: render/gles2/renderer.c:37: gles2_get_renderer_in_context: Assertion `wlr_egl_is_current(renderer->egl)' failed.
```
### Solution
- Maybe wlr_texture_from_pixels should assert when being called when it is inside wlr_render_begin/end block.
- adding Documentation about it (I will do that)

**Comment by emersion** [comment]
>Maybe wlr_texture_from_pixels should assert when being called when it is inside wlr_render_begin/end block.

Yeah. Adding `assert(!r->rendering)` in `render/wlr_renderer.c` should do the trick.

**Comment by werererer** [comment]
I think it is more compilcated than I initialy thought. It also crashes when I call `wlr_output_attach_render` this assert won't help in that case I think.

**Comment by emersion** [comment]
`wlr_output_attach_render` needs to be called right before `begin`, so can add the assert there too I guess.
