### ISSUE TITLE
foreign-toplevel-management: only report parent toplevel to clients that requested version 3

### ISSUE THREAD

**Issue by myfreeweb** [swaywm/wlroots#2442]
In #2419, no version check was added before calling `zwlr_foreign_toplevel_handle_v1_send_parent`, so clients unaware of version 3 blow up when they receive an event they don't know anything about:

```
interface 'zwlr_foreign_toplevel_handle_v1' has no event 7
```

**Comment by emersion** [comment]
cc @dkondor

**Comment by dkondor** [comment]
Not something I thought of, thanks for spotting this!

I made a quick fix here: https://github.com/dkondor/wlroots/commit/d2722d2207194dfcca8e2fad60cd6cfb6829bfed -- should I open a separate PR? (I've tested this with the code in examples)

**Comment by Xyene** [comment]
Yes, that sounds good, thanks. (Preemptive nit, spacing after the `if` and before the `(`. :)
