### ISSUE TITLE
Feature request: have a way to identify the process ID of the focused window, for use in keybindings/commands

### ISSUE THREAD

**Issue by jamadazi** [swaywm/wlroots#2447]
I frequently have issues with hung/unresponsive apps. Since they don't respond to events, I can't close their windows. I need to find out their process ID so that I can kill them.

It is cumbersome to have to open a process manager every time and search for the hung process (especially if I have many instances of the same app).

It would be really nice if I could make a keybinding that gets the process ID of the process behind the currently-focused window and runs a command to kill it. I haven't found an easy way to do this.

Since sway internally already knows what processes it is talking to, I think this should just be a matter of exposing that info. It could be done via some special variable in the config file or something like that.

Perhaps this already exists and I just couldn't find it? If that is the case, please point me in the right direction and feel free to close this issue.

**Comment by emersion** [comment]
You can find this info in the `get_tree` IPC reply.

**Comment by jamadazi** [comment]
Thank you -- I looked at that and found a way to filter it with `jq` to get the PID.

Here is the command, for the benefit of people finding this issue in the future:

`swaymsg -t get_tree | jq '.. | objects | select(.focused==true) | .pid'`
