### ISSUE TITLE
Gamma protocol resets user-set gamma upon process exit/wl_display_disconnect()

### ISSUE THREAD

**Issue by FedeDP** [swaywm/wlroots#2455]
Hi!
Poking around wlr_gamma_control_v1 protocol, i noted that it is currently not possible to do a "oneshot" gamma change, because as soon as a process live, or as soon as wl_display_disconnect() is called, gamma gets resetted.
Is this expected behaviour?
I find it weird as it leads to workarounds such as: https://github.com/swaywm/wlroots/blob/master/examples/gamma-control.c#L189, or  https://gitlab.com/chinstrap/gammastep/-/blob/master/src/redshift.c#L1145.

Moreover, is there a reason why the protocol does not expose a table getter method? Just a curiosity of mine!

Thank you very much for your efforts, i really appreciate them!

**Comment by emersion** [comment]
That's by design, to avoid badly behaving clients from making your system unusable.

**Comment by FedeDP** [comment]
So, does a malicious client just need to keep a display connection alive? 
I just wish to better understand the reasoning behind this choice.
The only reason i could think is that this behavior enforces malicious clients to be long-running process thus making them more discoverable. Am i correct?

Anyway, i think that breaking a common pattern used by lots of utilities for such a small concern could be counterproductive.

> Moreover, is there a reason why the protocol does not expose a table getter method? Just a curiosity of mine!

Thank you!

**Comment by emersion** [comment]
It's not really about malicious clients, it's more about broken clients. You can just SIGKILL them to return to a usable desktop.

The protocol doesn't expose a getter method because clients don't need it.
