### ISSUE TITLE
Forceprobing DRM connections causes sway to lose monitor information/modeset when turning off dpms

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/wlroots#2474]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.5-a56098a2 (Nov 11 2020, branch 'master')`

- **Debug Log:**
Log capture of sway when this behavior was exhibited. Should be around the 58 minute mark.
https://0x0.st/invm.log

- **Configuration File:**
have not figured out a minimally reproducible config (yet).
https://0x0.st/invB.txt

Swayidle config:
```
timeout 300 'swaylock -f -c 000000'
timeout 315 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"'
timeout 15 'if pgrep swaylock; then swaymsg "output * dpms off"; fi' resume 'if pgrep swaylock; then swaymsg "output * dpms on"; fi'
before-sleep 'swaylock -f -c 000000'
```
Run with `swayidle -w`

- **Stack Trace:**
N/A

- **Description:**
This bug appears to be caused by turning off dpms and then forceprobing connections on turning dpms back on. I can fix this bug by reverting 8bc5a92.

**Comment by emersion** [comment]
https://gitlab.freedesktop.org/drm/amd/-/issues/1368

**Comment by LaserEyess** [comment]
After around 60 hours on 5.4.77 I have not seen this bug once. I am concluding this is a kernel bug, but I'll update with more information once I am able to get some better kernel logs on what is happening.

However, debugging this is still difficult so I have a couple questions:
 1. Is there some IPC event I can hook into for sway that can give me information exactly on when sway/wlroots loses the monitor?
 2. Is there any way to get sway logs to use absolute timestamps?

I need to be able to exactly pinpoint when this bug occurs so I don't have to sift through GB of dmesg logs.

**Comment by LaserEyess** [comment]
Fairly certain I was wrong about LTS fixing this, I think it simply made it harder to find. But from some very rough, inconclusive bisecting I believe this is still present in wlroots and specifically caused by https://github.com/swaywm/wlroots/commit/8bc5a92a98ca5b788cd4f426ad2605da265ef422. Or rather it was "fixed" by https://github.com/swaywm/wlroots/commit/713c1661b742f93a7d2167321837c0d99541ca87 and is now back. I'm going to use wlroots with https://github.com/swaywm/wlroots/commit/713c1661b742f93a7d2167321837c0d99541ca87 put back in to see if I can try to trigger the bug.

**Comment by LaserEyess** [comment]
This may still be a kernel bug but testing with 8bc5a92 reverted pretty conclusively causes this bug to go away.

**Comment by emersion** [comment]
>This may still be a kernel bug but testing with 8bc5a92 reverted pretty conclusively causes this bug to go away.

danvet said it's very likely a kernel bug.

**Comment by LaserEyess** [comment]
AMD has not responded to this so maybe I'll ping them again. I guess I'll keep that commit reverted for now, but is there anything sway/wlroots can do to work around this?

**Comment by emersion** [comment]
No

**Comment by LaserEyess** [comment]
Then I guess I'll close this, anyone else with these symptoms can find this bug report
