### ISSUE TITLE
Input configuration protocol

### ISSUE THREAD

**Issue by kirbykevinson** [swaywm/wlroots#2477]
wlroots has the wlr-output-management protocol, which makes tools like wlr-randr possible, but there seems to be no corresponding protocol for input configuration, which would make a tool like xinput possible.

**Comment by emersion** [comment]
I don't think it's worth doing. wlr-output-management is primarily useful for output management daemons. There are no input management daemons.

If you still think it's worth it, the repo to send a patch to is wayland-protocols.
