### ISSUE TITLE
Weird artifacts when closing windows

### ISSUE THREAD

**Issue by MisterDA** [swaywm/wlroots#2478]
Hello,

I’ve noticed weird glitches and color artifacts when closing windows.
I’ve taken two pictures of my screen with my phone ;-)
It’s not possible to screenshot (using grim+slurp), since the glitches disappear when something is drawn over them.

![IMG20201116102221](https://user-images.githubusercontent.com/1773581/99235255-ea853000-27f5-11eb-954b-f89d12d1a606.jpg)
![IMG20201116090933](https://user-images.githubusercontent.com/1773581/99235261-eb1dc680-27f5-11eb-804d-9c50afdcd665.jpg)

I’m using sway [9d6787d1](https://github.com/swaywm/sway/commit/9d6787d10d3800ff4873ad6ac3abe4b096090427) and wlroots [526ae59](https://github.com/swaywm/wlroots/commit/526ae5944c5cc97e02f0282c57ce7320ceb2daa5).
I’ve bisected the issue with that version of sway and found out that the commit introducing this bug is [ef846a8](https://github.com/swaywm/wlroots/commit/ef846a883950e59f95507daa6d3f96f0e84da3af) in wlroots.

On the bright side I sort of enjoy them, but they’re a bit distracting.

A tip if you want to bisect: there's also a bug in https://github.com/swaywm/wlroots/commit/ef846a883950e59f95507daa6d3f96f0e84da3af#diff-b91e9e2ef3f34f2129df43dc0e78f8543153f9ea6699a83ea79269932b9575efR140. The new `age` parameter was added to `wlr_swapchain_acquire` in the parent commit, but the change isn't reflected and triggers a compilation error. It is fixed in the next commit though. https://github.com/swaywm/wlroots/commit/68a8d9905513c0277037cc74325bb2ea507ac012#diff-b91e9e2ef3f34f2129df43dc0e78f8543153f9ea6699a83ea79269932b9575efR140

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by MisterDA** [comment]
Of course, sorry about that.
https://gist.github.com/MisterDA/1844ddd618d93c764d8299ffbbeb67d5
I’m using the dreaded `--my-not-gpu-wont-be-nvidia` but set `WLR_DRM_DEVICE` to the integrated GPU, if that changes anything. If that’s the root of the problem, well… so be it.
I’ve tested with the default configuration and ASAN+UBSAN (no reports except leaks at exit). You have to disable the background picture to reproduce.

**Comment by emersion** [comment]
Does `INTEL_DEBUG=nofc` help?

**Comment by MisterDA** [comment]
Yes, the artifacts don't appear anymore. This fixes my problem, thanks for the workaround.

**Comment by emersion** [comment]
This is an iris driver bug, already fixed upstream: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3425
