### ISSUE TITLE
Assertion failed when creating cursor FBO on multi-GPU setup

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/wlroots#2479]
With latest sources, sway fails to start. Log attached.
[sway.log](https://github.com/swaywm/sway/files/5548472/sway.log)

**Comment by neon64** [comment]
I don't know nearly enough about wlroots to understand this bug, but in the meantime adding this hack inside of [gles2_get_renderer_in_context](https://github.com/swaywm/wlroots/blob/master/render/gles2/renderer.c#L36) at least prevents the crash. I'm sure the actual fix is elsewhere though as `gles2_get_renderer_in_context` is supposed to assume the context is already current, right?

```c
if(!wlr_egl_is_current(renderer->egl)) {
    wlr_egl_make_current(renderer->egl, EGL_NO_SURFACE, NULL);
}
```

function calls leading up to the crash:
`wlr_output_cursor_set_surface` -> `drm_connector_set_cursor` -> `drm_fb_lock_surface` -> `drm_surface_unset_current` -> `wlr_renderer_bind_buffer` -> `gles2_bind_buffer` -> `gles2_get_renderer_in_context`

**Comment by J0nnyMak0** [comment]
FWIW I see the assert only when external monitors are connected.

**Comment by J0nnyMak0** [comment]
I can create a pull request if this is a satisfactory solution. Even with this change, I still get freezes from time to time when hotplugging external monitors. Not sure if that is related to this or some other change. (I haven't kept up with more recent changes to wlroots/sawy as I've not been using sway on a daily basis because of this issue.)

**Comment by emersion** [comment]
`drm_surface_unset_current` must only be called after making the surface current. Apparently that's not the case here.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2520?
