### ISSUE TITLE
is it possible to make a wayland compositor on top of vulkan/someothergerularGAPI?

### ISSUE THREAD

**Issue by seniorivn** [swaywm/wlroots#2481]
this way it would be possible to run all linux apps on any gpu with modern gpu api, from vm etc
May be emulate drm/kms api in vulkan as another abstraction layer?

**Comment by emersion** [comment]
For Vulkan support there is https://github.com/swaywm/wlroots/issues/642

>May be emulate drm/kms api in vulkan as another abstraction layer?

This doesn't make much sense to me.
