### ISSUE TITLE
Remotely creating headless backend fails after commit 61f8cdfb

### ISSUE THREAD

**Issue by ppascher** [swaywm/wlroots#2488]
After commit 61f8cdfb starting sway with `WLR_BACKENDS=headless` remotely (i.e over a ssh connection to start wayvnc in my case) results in the following error:
```[ERROR] [render/egl.c:872] Failed to open primary DRM device: Permission denied
[ERROR] [backend/headless/backend.c:117] Failed to get DRM device FD from renderer
[ERROR] [backend/backend.c:235] failed to start backend 'headless'
[sway/server.c:50] Unable to create backend
```

According to IRC this is due to udev access permissions not being set on `/dev/dri/card*` when not connected locally to the machine.

**Comment by emersion** [comment]
Unfortunately the EGL DRM device ext only gives us a path to the card device. I suspect we don't be able to do anything with it if we don't see the card device.

Maybe we should use `drmGetDevices` to enumerate render nodes in the headless backend. And maybe add `WLR_HEADLESS_DEVICE` to override the default choice.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2497?

**Comment by ppascher** [comment]
That fixed it. Thank you.
