### ISSUE TITLE
wlr_output_update_custom_mode is not called anywhere in the drm backend

### ISSUE THREAD

**Issue by maringuu** [swaywm/wlroots#2490]
Hello!
I am currently working on [implementing wlr_output_management_unstable_v1](https://github.com/ifreund/river/pull/143)  for river.
Currently it crashes when setting a custom mode. To my current understanding this is a wlroots bug and while exploring wlroots code to find this bug I noticed that `wlr_output_update_custom_mode` is not called anywhere in the drm backend code.

According to the docs it should be called.
https://github.com/swaywm/wlroots/blob/754179dacd4c8cbd06d6c646cda9c5e23edcb707/include/wlr/interfaces/wlr_output.h#L104-L109

So this might be a bug. I'll fix it if it is indeed a bug but it might take me a while.

**Comment by emersion** [comment]
When setting a custom mode, the DRM backend adds it to the list of available modes via `wlr_drm_connector_add_mode`. It then updates the `wlr_output` current mode via `wlr_output_update_mode`.

**Comment by maringuu** [comment]
> When setting a custom mode, the DRM backend adds it to the list of available modes via `wlr_drm_connector_add_mode`. It then updates the `wlr_output` current mode via `wlr_output_update_mode`.

Thank you for your answer!
