### ISSUE TITLE
GL_EXTENSIONS parameter is deprecated in OpenGL 3 for glGetString()

### ISSUE THREAD

**Issue by mikeyj001** [swaywm/wlroots#2508]
Taking information from the bug I raised here: https://github.com/WayfireWM/wayfire/issues/915

While trying to run /opt/wayfire/bin/./startwayfire, a crash is logged. See attached.

To Reproduce

Run "git clone https://github.com/WayfireWM/wf-install.git"
Run "/opt/wayfire/bin/./startwayfire"
Wayfire crashes and logs the issue in ~/.local/share/wayfire/wayfire.log
Expected behavior
A wayfire session should start

[wayfire.log](https://github.com/swaywm/wlroots/files/5636064/wayfire.log)

I updated using update_build.sh, which after running meson build --prefix=/opt shows:

system wfconfig: false
system wlroots: false
xwayland: true
x11-backend: true
imageio: true
gles32: true

Build targets in project: 135

wlroots 0.11.0

systemd: 1
elogind: 0
xwayland: 1
x11_backend: 1
xcb-icccm: 1
xcb-errors: 0

wayfire 0.5.0

Subprojects
wf-config: YES
wf-utils: YES
wlroots: YES

The issue is in the file wlroots/render/gles2/renderer.c where this statement:

     const char *exts_str = (const char *)glGetString(GL_EXTENSIONS);

is using a deprecated parameter "GL_EXTENSIONS".

This needs fixing for OpenGL >= 3.0 desktop implementations

**Comment by emersion** [comment]
wlroots' renderer assumes GLES. GLES doesn't have GL_NUM_EXTENSIONS. I don't see an easy way out of this from the wlroots side, using GLES code with a desktop GL context is pretty fragile.

**Comment by mikeyj001** [comment]
I thought this window manager was widely used on desktops to be honest.  Not sure how I can use OpenGLES instead.

**Comment by ammen99** [comment]
@mikeyj001 I asked this question also on the Wayfire issue, what drivers are you using?

**Comment by emersion** [comment]
Sorry, I'm mistaken, Wayfire uses GLES as well. So it should just work. In fact, we succeed when querying client extensions:

```
II 30-11-20 13:47:20.007 - [render/egl.c:298] Supported EGL client extensions: EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_wayland EGL_EXT_platform_x11 EGL_MESA_platform_gbm EGL_MESA_platform_surfaceless EGL_EXT_platform_device
II 30-11-20 13:47:20.007 - [render/egl.c:299] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_EXT_buffer_age EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_image_dma_buf_export EGL_MESA_query_driver 
II 30-11-20 13:47:20.007 - [render/egl.c:300] EGL vendor: Mesa Project
EE 30-11-20 13:47:20.014 - [render/gles2/renderer.c:660] Failed to get GL_EXTENSIONS
```

**Comment by progandy** [comment]
> The issue is in the file wlroots/render/gles2/renderer.c where [wlroots] is using a deprecated parameter "GL_EXTENSIONS".

Using deprecated function that still exists is discouraged and may break in the future, but should not fail.

By the way, it looks like GL_NUM_EXTENSIONS is available in GLES since 3.0 as well. (It is documented in the [ OpenGL® ES 3.0 Reference Pages ](https://www.khronos.org/registry/OpenGL-Refpages/es3.0). Code that should run on both 2.0 and 3.x has to use GL_EXTENSIONS or implement both code paths.

**Comment by mikeyj001** [comment]
> @mikeyj001 I asked this question also on the Wayfire issue, what drivers are you using?

As merntioned in the other thread, I'm using amdgpu.  What I didn't mention is that I'm also using Sabayon OS and an AMD RX460 graphics card.

**Comment by mikeyj001** [comment]
I have been able to use glGetStringi(GL_EXTENSIONS, i) by using GLES3/gl32.h and GLES3/gl3ext.h, instead of the original headers for GLES1 and GLES2, as a test.  I then get issues with the following because it needs an openGL context, which I don't know how to create:

[render/gles2/renderer.c:707] Using (null)
[render/gles2/renderer.c:708] GL vendor: (null)
[render/gles2/renderer.c:709] GL renderer: (null)

**Comment by mikeyj001** [comment]
I should also mention that I get the following errors: 

     wayfire: symbol lookup error: /opt/wayfire/lib64/libwlroots.so.6: undefined symbol: wl_global_set_user_data
     wayfire: symbol lookup error: /opt/wayfire/lib64/libwlroots.so.6: undefined symbol: wl_global_remove

Commenting out lines 25 & 26 in wf-install/wayfire/subprojects/wlroots/util/global.c resolves this issue for me.

**Comment by ammen99** [comment]
@mikeyj001 I have the feeling that something is broken in your setup, maybe you compiled with libraries from one location but then at runtime, Wayfire picks up libraries from another location?

**Comment by mikeyj001** [comment]
As I'm using Sabayon, there are 2 methods of installation of dependencies.  Using portage, there is an option to install gui-wm/wayfire.  Unfortunately it still fails while compiling.  I'm going to continue to try this method, and close this issue.  Thanks for your input.
