### ISSUE TITLE
Link env vars doc from Wiki Getting started page and README.md

### ISSUE THREAD

**Issue by eero-t** [swaywm/wlroots#2512]
I think this: https://github.com/swaywm/wlroots/blob/master/docs/env_vars.md

Is some of the most relevant documentation for end users of wlroots based SW, but I don't see it linked from Getting started Wiki page, Sway documentation etc.  I think it should.

**Comment by emersion** [comment]
I don't think so. These env variables are for advanced usage.

Would be fine to reference them in specific FAQ entries though. For instance it would be fine to mention `WLR_DRM_DEVICES` in a "How to select the primary GPU" entry in the Sway FAQ.

**Comment by emersion** [comment]
Ah, just realized this isn't about Sway. My point stands.

**Comment by eero-t** [comment]
Getting starting Wiki page contains links to other documentation.  I think a link to supported environment variables is relevant. For example, most programs manual pages list what environment variables and files program uses, regardless of how obscure their usage is.

Or if Getting started page is "too visible", maybe there could be a separate Wiki page containing all spec links (which is linked from Getting started page)?

**Comment by emersion** [comment]
Fair enough, added there.
