### ISSUE TITLE
backend/drm: remove DP MST encoder workaround

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2533]
Remove the logic introduced in https://github.com/swaywm/wlroots/pull/1426/commits/efdd4d6ea275ff4a0a22f8a348abca5847a9e65e.

Instead, report the bug upstream. This is almost certainly a driver bug.

**Comment by ascent12** [comment]
>Instead, report the bug upstream. This is almost certainly a driver bug.

Probably fixed already. That was added for a pretty early version of amdgpu's DP MST code.
