### ISSUE TITLE
Can't complete shutdown when connected to external display with Nouveau

### ISSUE THREAD

**Issue by fwSmit** [swaywm/wlroots#2536]
## Can't complete shutdown when connected to external display

- **Configuration File:**
The default /etc/sway/config

- **Description:**
When connected to an external display sway will not shut down correctly.
I couldn't reproduce this bug exactly on another display, so it may be display
dependent.
For reference, #2525 is also by me with the same hardware.

- **Steps to reproduce:**
Connect to an external display via HDMI.
Try to shutdown with systemctl poweroff or the power button.
The external display may show glitchy graphics (see picture).
The shutdown will never finish and you will have to force shutdown.

## **Info**
  - sway version 1.5.1
  - xf86-video-nouveau 1.0.16-2
  - mesa 20.2.3-1
  - Laptop: HP Zbook Studio G5
  - dGPU: GP107GLM [Quadro P1000 Mobile]
  - iGPU: Intel Corporation UHD Graphics 630 (Mobile)

- **Debug Log:**
  - https://gist.github.com/fwSmit/aea17406e76946114a1aaff2f594e470
  - Not much is visible on the log. It seems like logging stops after the shutdown is initiated.

- **Configuration File:**
  - The default /etc/sway/config

![shutdown2](https://user-images.githubusercontent.com/23078054/101903328-659ef380-3bb4-11eb-8452-017ec5f2d491.jpg)
![shutdown](https://user-images.githubusercontent.com/23078054/101903339-69327a80-3bb4-11eb-8b69-cc869822e033.jpg)

**Comment by emersion** [comment]
What happens if you shutdown without Sway running?

This issue doesn't seem like a Sway bug.

**Comment by fwSmit** [comment]
Oh you're right. I forgot that last time I used X11 I used nvidia drivers. You can close this, I'll report it to nouveau
