### ISSUE TITLE
HDMI unplugging not detected

### ISSUE THREAD

**Issue by fwSmit** [swaywm/wlroots#2547]
## HDMI unplugging not detected

- **Configuration File:**
The default /etc/sway/config

- **Description:**
Sway doesn't recognize the unplugging of the HDMI output. 
After unplugging the HDMI cable, the output will stay visible
in the output of `sway -t get_outputs`.
For reference, #2525 and #2536 are also by me with the same hardware.
This time I checked, and it does work on X11, so it's a sway/wlroots thing.

## **Info**
  - sway version 1.5.1
  - xf86-video-nouveau 1.0.16-2
  - mesa 20.2.3-1
  - Laptop: HP Zbook Studio G5
  - dGPU: GP107GLM [Quadro P1000 Mobile]
  - iGPU: Intel Corporation UHD Graphics 630 (Mobile)

- **Debug Logs:**
  - https://gist.github.com/fwSmit/04d5f6747aad92a9fcbe5c3109cf31cd

- **Configuration File:**
  - The default /etc/sway/config

**Comment by emersion** [comment]
Can you grab a [`drm_info`](https://github.com/ascent12/drm_info) log after unplugging the HDMI connector?

**Comment by fwSmit** [comment]
This is very weird. The act of doing the drm dump makes it detect the disconnect. So I can only give you the drm_info with the information that it is disconnected.
https://gist.github.com/fwSmit/d3ec45efb25034e8344718f144c64902

**Comment by emersion** [comment]
`drm_info` force-probes the connectors via `drmModeGetConnector`.

This is a driver bug, nouveau should send a hotplug uevent. Please open an issue at https://gitlab.freedesktop.org/drm/nouveau

**Comment by J0nnyMak0** [comment]
https://gitlab.freedesktop.org/drm/nouveau/-/issues/29
