### ISSUE TITLE
Rendering broken on X11 since recent changes

### ISSUE THREAD

**Issue by dkondor** [swaywm/wlroots#2552]
Hi,
I'm trying to run the latest git master + Wayfire git master and getting the following errors:
```
EE 17-12-20 12:57:25.913 - [backend/x11/backend.c:602] X11 error: op 149:7, code 11, sequence 32, value 109051908
EE 17-12-20 12:57:25.964 - [render/swapchain.c:97] No free output buffer slot
```
Everything works when reverting to 16a51bbab27ba5fa9348f21cfabff3085e25fc99

Notes: I'm on Ubuntu 18.04 and have to revert commits dd69c5871cbfd00b88309fcff8a159f9bb515510 and 1100c509c253bab72a0b51879d23558305e8723a to build; I understand if this might be an issue, but opening this since the problem does not seem directly related.

I'm attaching the full log (note: the error about no matching mode in line 56 appears in a working build as well)
[swapchain_error.log](https://github.com/swaywm/wlroots/files/5707228/swapchain_error.log)

**Comment by emersion** [comment]
Can you try building with xcb-errors? This would make it easier to debug these X11 errors.

What X11 driver are you using? I've tested with the modesetting driver on amdgpu.

**Comment by dkondor** [comment]
Hi,
with xcb-errors, I get the following errors:
```
EE 17-12-20 21:17:57.746 - [backend/x11/backend.c:592] X11 error: op DRI3 (PixmapFromBuffers), code Alloc (no extension), sequence 62, value 52428804
EE 17-12-20 21:17:57.746 - [backend/x11/backend.c:592] X11 error: op Present (Pixmap), code Pixmap (no extension), sequence 64, value 52428805
EE 17-12-20 21:17:57.746 - [backend/x11/backend.c:592] X11 error: op DRI3 (PixmapFromBuffers), code Alloc (no extension), sequence 65, value 52428804
EE 17-12-20 21:17:57.746 - [backend/x11/backend.c:592] X11 error: op Present (Pixmap), code Pixmap (no extension), sequence 67, value 52428807
EE 17-12-20 21:17:57.764 - [backend/x11/backend.c:592] X11 error: op DRI3 (PixmapFromBuffers), code Alloc (no extension), sequence 72, value 52428804
EE 17-12-20 21:17:57.764 - [backend/x11/backend.c:592] X11 error: op Present (Pixmap), code Pixmap (no extension), sequence 74, value 52428809
EE 17-12-20 21:17:57.783 - [backend/x11/backend.c:592] X11 error: op DRI3 (PixmapFromBuffers), code Alloc (no extension), sequence 75, value 52428804
EE 17-12-20 21:17:57.783 - [backend/x11/backend.c:592] X11 error: op Present (Pixmap), code Pixmap (no extension), sequence 77, value 52428811
```

After this, the `No free output buffer slot` keeps repeating until I kill the process, and there is no output.

As far as I can, the X11 driver is `modesetting`, with the `i965` DRI2 driver. DRI3 is loaded, but I see no messages related to it in my Xorg.log -- I'm attaching it here, in case there's something useful in it.

[Xorg.0.log](https://github.com/swaywm/wlroots/files/5709783/Xorg.0.log)

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2553?

**Comment by dkondor** [comment]
Just tried and it's working with #2553 . Thanks!
