### ISSUE TITLE
Can I use wlroots with my own e/evas renderer?

### ISSUE THREAD

**Issue by cederom** [swaywm/wlroots#2557]
Hello world :-)

We are porting Enlightenment WM to FreeBSD. At the moment E has hard dependency on logind/systemd and will not work without it. The solution here may be using wlroots. But E already has its own renderer. Can we use wlroots to make E portable and systemd/logind independent but still use its own renderer "evas"?

Any hints welcome :-)
Tomek

**Comment by emersion** [comment]
Hi! The logind support in wlroots is just a very small part of the library, and wlroots contains a lot more things like Wayland interface implementations and backends. If you just want to add logind support to Enlightenment, I suggest you look into [libseat](https://git.sr.ht/~kennylevinsen/seatd/) from the seatd project. libseat provides a single interface that supports (e)logind, seatd and an embedded direct session. This is also a patch which is more likely to be upstream-able I believe.

(Closing this issue but feel free to continue the discussion.)

**Comment by cederom** [comment]
TANK U SIR :-)
