### ISSUE TITLE
Drop EGL things from wlr_renderer_autocreate

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2563]
Currently `wlr_renderer_autocreate` takes parameters tied to EGL:

1. `EGLint *config_attribs, EGLint visual_id`: with https://github.com/swaywm/wlroots/pull/2562, no one uses those anymore.
2. `EGLenum platform, void *remote_display`: almost everyone uses the GBM platform. The only exception is the Wayland backend, which still has no other way to get the DRM FD used by the parent compositor.

The long-term solution for (2) is to get the DRM FD from dmabuf-hints, however the protocol is still pending. A more realistic solution would be to vendor a copy of the `wl_drm` protocol, which Mesa uses exactly for this.

Once that is done, we can think of picking a new signature for `wlr_renderer_autocreate`. The renderer needs to have access to the DRM FD to initialize itself. There may not be a DRM FD, e.g. on GPU-less setups, in which case we should allow `wlr_renderer_autocreate` to create a software renderer.

Possible new signatures:

```c
/**
 * Automatically create a renderer with the provided DRM FD.
 * Maybe this is too DRM-specific?
 */
struct wlr_renderer *wlr_renderer_autocreate(int drm_fd);

/**
 * Automatically create a renderer suitable for the backend.
 * The rendering device will be queried from the backend.
 */
struct wlr_renderer *wlr_renderer_autocreate(struct wlr_backend *backend);
```

**Comment by emersion** [comment]
(1) is done in https://github.com/swaywm/wlroots/pull/2593.

The issue with the Wayland backend in (2) is fixed in https://github.com/swaywm/wlroots/pull/2592.

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/2602 removes the `struct wlr_egl *` argument from `wlr_renderer_autocreate`

**Comment by bl4ckb0ne** [comment]
What about the `remote_display` parameter? Should the `wlr_gbm_allocator` be a part of the `wlr_backend` now that all of the backends use the GBM platform?

**Comment by emersion** [comment]
> Should the wlr_gbm_allocator be a part of the wlr_backend now that all of the backends use the GBM platform?

I'd prefer not to add an interface to get the `gbm_device` from the backend. Only the DRM backend needs the GBM device to import buffers, other backends only need it for allocations. Eventually we'll want to completely remove the renderer and allocator from backends, so I'd prefer not to rely on the backend having a GBM allocator.

Instead, the renderer can create its own GBM device. It's a little bit unfortunate that EGL needs a GBM device in the first place. Other renderers (Vulkan, pixman) don't require this.

Actually, it may be possible not to use the EGL GBM platform, and instead do something that looks like Vulkan physical device enumeration:

- Get the DRM FD from the backend via https://github.com/swaywm/wlroots/pull/2613.
- Query available physical devices via [`EGL_EXT_device_enumeration`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_device_enumeration.txt).
- Select the EGL device that matches the backend DRM FD via [`EGL_EXT_device_drm`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_device_drm.txt) and `drmGetDevice` (compare DRM node paths).
- Create an EGL display from the EGL device via [`EGL_EXT_platform_device`](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_platform_device.txt).

The only thing I'm concerned about is driver support. Mesa seems to support everything we need.

Regardless of the EGL platform used, we could have a `wlr_egl_create_from_drm_fd` function that does the right thing under the hood.

**Comment by bl4ckb0ne** [comment]
I like having `wlr_egl_create_from_drm_fd`. We could modify `wlr_gles2_renderer_create` signature to be the following

```c
struct wlr_renderer *wlr_gles2_renderer_create(struct wlr_backend *backend);
```

To remove any logic from the renderer creation process, this will help greatly for the pixman renderer creation process.

**Comment by emersion** [comment]
>We could modify wlr_gles2_renderer_create signature to be the following

I'm not sure this will help. When you choose to create a GLES2 renderer, there is a dependency on EGL already. The pixman renderer won't use the GLES2 renderer.

**Comment by bl4ckb0ne** [comment]
Yes that's what I mean, keep the EGL stuff to GLES2 to not bother the pixman renderer with it.

**Comment by emersion** [comment]
`wlr_gles2_renderer_create` is specific to GLES2, so should not bother pixman or other renderers.

**Comment by bl4ckb0ne** [comment]
Could it be possible to have #2613 rebased on master to get the sweet bits from #2623 please?

Which prototype do you prefer between those two? I like the first one to be consistent with `wlr_renderer_autocreate`.

```
struct wlr_egl *wlr_egl_create(struct wlr_backend *backend, const EGLint *config_attribs);

struct wlr_egl *wlr_egl_create(int drm_fd, const EGLint *config_attribs);
```
