### ISSUE TITLE
Segfault during copy&paste operations into Xwayland

### ISSUE THREAD

**Issue by luispabon** [swaywm/wlroots#2565]
- **Sway Version:**
sway version 1.5-32b93ef6 (Nov 28 2020, branch 'master')
wlroots 154fe869 (Nov 19)

- **Debug Log:**
The original log is 27M as it was a debug session that had been going on for a couple of days. The following has the first 3k and last 3k lines of that log:
https://paste.ubuntu.com/p/NwkzHgjVn9/

- **Configuration File:**
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

- **Stack Trace:**
 https://paste.ubuntu.com/p/jWfQpXDHcV/

- **Description:**
This segfault feels similar to another issue that was patched before and could potentially be a regression:
https://github.com/swaywm/wlroots/issues/2425

Apologies if I put the issue in the sway bug tracker and not wlroots as I have no idea if it belongs there.

Same steps: session going for a day or two, pasting into xwayland stops functioning - xwayland apps hang for a few seconds when you paste into them, kill xwayland, start another xwayland app and try to paste again, then hang again for a couple of seconds and segfault.

**Comment by Xyene** [comment]
@luispabon, did you have a chance to try the patch above?

**Comment by luispabon** [comment]
I did, I have it applied and have seen no further segfaults. They did happen very rarely after a prior fix to a similar issue but looks like this might have done it.

Apologies I forgot to report back here.
