### ISSUE TITLE
backend/wayland: mpv stuttering when presentation-time feedback is enabled

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2566]
1. Run Sway nested in Sway
2. Start mpv
3. The video stutters

Running with `--wayland-disable-vsync=yes` fixes it.

**Comment by cyanreg** [comment]
Does it still happen with [my fork](https://github.com/cyanreg/mpv)/old versions from before September last year?

**Comment by emersion** [comment]
Yes, your fork works fine.

**Comment by Dudemanguy** [comment]
Just seeing this issue right now, I know why this happens. It's just the heusteric that mpv is using for detecting if the window is hidden (wayland-disable-vsync ignores said heuristic). It's a very dumb and simple "if x missed frames > than the display's refresh rate, then we consider the surface hidden and skip rendering". In the nested sway case, the display's refresh rate reported is a apparently 0 hence the problem. I could very easily just set it to some random number (60 or whatever) if the display refresh rate being 0 is desirable.

**Comment by emersion** [comment]
The Wayland protocol allows a zero refresh rate for outputs where it doesn't makes sense: https://gitlab.freedesktop.org/wayland/wayland/-/blob/4c2105312379b62dc84f6eaaf26e2ab293d51b92/protocol/wayland.xml#L2566

So yeah some kind of fallback would be welcome! If you don't have time, I can look into it too.

**Comment by Dudemanguy** [comment]
https://github.com/mpv-player/mpv/pull/8741 should fix it.

**Comment by emersion** [comment]
Thanks!
