### ISSUE TITLE
backend/x11: wl_drm.authenticate fails inside wlroots since 94fda89

### ISSUE THREAD

**Issue by djpohly** [swaywm/wlroots#2576]
Since commit 94fda89, EGL fails to initialize inside wlroots (wl_drm.authenticate fails) when using the x11 backend.

[Log from dwl (WLR_DEBUG, EGL_LOG_LEVEL=debug, LIBGL_DEBUG=verbose) running alacritty (WAYLAND_DEBUG=1)](https://gist.github.com/djpohly/36e36cfeecca0a6574666c0492d74565)

Similar errors occur with kitty and Firefox, under both sway and dwl.  Is there any other info I can provide to help troubleshoot?

**Comment by emersion** [comment]
Hm, interesting. I guess we can't authenticate on behalf of the parent X11 server. We'll probably want to open the render node if we received a primary node then.

https://github.com/swaywm/wlroots/blob/c012d770f739fcbb119aba7983d192b48f34e9a7/backend/x11/backend.c#L241

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2585?

**Comment by djpohly** [comment]
Confirmed - #2585 fixes the issue.  Thanks!
