### ISSUE TITLE
backend/x11: WLR_X11_OUTPUTS=2 doesn't work since d79a00b

### ISSUE THREAD

**Issue by djpohly** [swaywm/wlroots#2577]
When I don't have a second monitor on hand, the `WLR_X11_OUTPUTS` environment variable is very useful in testing multi-monitor support while developing a compositor.  Currently, trying to use this feature to create two outputs results in one or both not rendering and the terminal filling with the message:
```
[render/swapchain.c:97] No free output buffer slot
```
I've bisected the regression to commit d79a00b and tested in both dwl and sway.

**Comment by emersion** [comment]
When running the X11 backend under Xwayland, I can reproduce the fact that one of the screens won't render more than once. I don't get the error you describe, however I get this one:

```
00:00:00.279 [wlr] [backend/x11/backend.c:608] X11 error: op Present (SelectInput), code Match (no extension), sequence 63, value 4194307
```

Do you get it as well?

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2579?

**Comment by djpohly** [comment]
Yes, #2579 fixes the issue!
