### ISSUE TITLE
Examples don't run, could not initialize EGL

### ISSUE THREAD

**Issue by fwSmit** [swaywm/wlroots#2580]
Most examples don't run (in sway).
```
00:00:02.118 [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_DISPLAY (0x3008), message: "(null)"
00:00:02.118 [render/egl.c:315] eglQueryDeviceStringEXT(EGL_EXTENSIONS) failed
00:00:02.118 [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:02.120 [render/wlr_renderer.c:281] Could not initialize EGL
00:00:02.120 [backend/wayland/backend.c:325] Could not create renderer
```
I have all required packages installed, except libseat.

**Comment by emersion** [comment]
Please provide full debug logs.

**Comment by neon64** [comment]
This looks like it could be https://github.com/swaywm/wlroots/issues/2480 - the log output looks similar. Do you have any Nvidia  packages installed? If so, what worked for me was installing the latest libglvnd (libglvnd-git on Arch) which has [this patch](https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/235 ) merged

**Comment by fwSmit** [comment]
> This looks like it could be #2480 - the log output looks similar. Do you have any Nvidia packages installed? If so, what worked for me was installing the latest libglvnd (libglvnd-git on Arch) which has [this patch](https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/235) merged

Thanks that works for me. I do have some nvidia packages installed apparently, so that would probably fix this issue as well.

> Please provide full debug logs.

I'll link the debug logs anyways, since I made them already: https://gist.github.com/fwSmit/1d0d9c67d8572b4f15414f934d8d2e94
