### ISSUE TITLE
backend/x11: X11 does not support required DRI3 version

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/wlroots#2586]
```
sway -d
00:00:00.000 [sway/main.c:346] Sway version 1.5-53f5197c (Dec 31 2020, branch 'HEAD')
00:00:00.021 [sway/main.c:154] Linux amd64 5.10.4-gentoo-classic #2 SMP Thu Dec 31 13:26:15 EAT 2020 x86_64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz GenuineIntel GNU/Linux
00:00:00.021 [sway/main.c:170] Contents of /etc/lsb-release:
00:00:00.021 [sway/main.c:154] DISTRIB_ID="Gentoo"
00:00:00.021 [sway/main.c:170] Contents of /etc/os-release:
00:00:00.021 [sway/main.c:154] NAME=Gentoo
00:00:00.021 [sway/main.c:154] ID=gentoo
00:00:00.021 [sway/main.c:154] PRETTY_NAME="Gentoo/Linux"
00:00:00.021 [sway/main.c:154] ANSI_COLOR="1;32"
00:00:00.021 [sway/main.c:154] HOME_URL="https://www.gentoo.org/"
00:00:00.021 [sway/main.c:154] SUPPORT_URL="https://www.gentoo.org/support/"
00:00:00.021 [sway/main.c:154] BUG_REPORT_URL="https://bugs.gentoo.org/"
00:00:00.021 [sway/main.c:170] Contents of /etc/gentoo-release:
00:00:00.021 [sway/main.c:154] Gentoo Base System release 2.7
00:00:00.022 [sway/main.c:142] LD_LIBRARY_PATH=
00:00:00.022 [sway/main.c:142] LD_PRELOAD=
00:00:00.022 [sway/main.c:142] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib64/opencascade-7.3.0/ros/bin:/usr/lib/llvm/11/bin:/usr/lib/llvm/10/bin
00:00:00.022 [sway/main.c:142] SWAYSOCK=
00:00:00.022 [sway/server.c:43] Preparing Wayland server initialization
00:00:00.022 [wlr] [backend/x11/backend.c:412] X11 does not support required DRI3 version
00:00:00.022 [sway/server.c:49] Unable to create backend
```

Used to work a couple of weeks ago.

No problem from console with concurrent Xorg session running, though:

[sway-console-dbg.out.zip](https://github.com/swaywm/wlroots/files/5757161/sway-console-dbg.out.zip)

**Comment by emersion** [comment]
What is the version of xorg-xserver you're using? What xf86 driver?

**Comment by emersion** [comment]
DRI3 1.2 adds GetSupportedModifiers, PixmapFromBuffers, and BuffersFromPixmap. We'd need to add fallbacks for these if we want to support 1.0.

**Comment by CaptainBloodz** [comment]
> What is the version of xorg-xserver you're using? What xf86 driver?

x11-base/xorg-server-1.20.10:0/1.20.10::gentoo  USE="-debug -dmx -doc elogind -ipv6 -kdrive -libressl -minimal (-selinux) -static-libs -suid -systemd udev -unwind wayland -xcsecurity -xephyr -xnest xorg xvfb"

> What xf86 driver?

x11-drivers/xf86-video-intel-2.99.917_p20200515::gentoo  USE="-debug dri sna -tools udev -uxa xvmc"

**Comment by CaptainBloodz** [comment]
glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by emersion** [comment]
I used xf86-video-modesetting in my testing. Maybe xf86-video-intel doesn't support DRI3 1.2.

**Comment by CaptainBloodz** [comment]
xf86-video-intel removed, xorg-drivers rebuild, xorg-server rebuild, xorg-server restart.

wayfire now display fine from terminal.

wlroots-X11-1 main window forever remains grey, i.e. without any display:

https://github.com/swaywm/sway/issues/5928

**Comment by emersion** [comment]
Re-opening because this is still an issue with the xf86-video-intel driver.

**Comment by jbeich** [comment]
Bisected to d79a00bf0208. xf86-video-intel defaults to [DRI3 disabled](https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/issues/188) but when enabled the error appends `(has 1.0, want 1.2)`.

**Comment by emersion** [comment]
>xf86-video-intel defaults to DRI3 disabled

It sounds like this bug report is due to a downstream distribution not enabling DRI3?

>when enabled the error appends (has 1.0, want 1.2)

Right. See https://github.com/swaywm/wlroots/issues/2586#issuecomment-753031332 for the action needed to fix this.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2655?

**Comment by jbeich** [comment]
0.12.0-254-gb0b9638e showed transparent/black screen but 0.12.0-256-g77e7c0c0 works fine if DRI3 is enabled.

**Comment by emersion** [comment]
Thanks for testing. What are these hashes? They don't look like wlroots commits.

**Comment by jbeich** [comment]
> What are these hashes? They don't look like wlroots commits.

`git describe origin/pull/2655/head` output. With only hash: b0b9638e and 77e7c0c0.

**Comment by emersion** [comment]
Oh, I see
