### ISSUE TITLE
wayland backend error in `zwp_linux_buffer_params_v1@N.add`

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#2594]
I have a semi-reliable way of triggering a crash in the wayland backend and Wayfire, I have not noticed this before so it might be a recent regression. What I am doing: resize a client from SSD (so, the compositor sets custom cursor from via wlr_xcursor) inside the Wayland backend. I am seeing the following errors:

```
EE 04-01-21 12:12:07.382 - [render/swapchain.c:97] No free output buffer slot
EE 04-01-21 12:12:07.982 - [render/swapchain.c:97] No free output buffer slot
EE 04-01-21 12:12:14.520 - [render/swapchain.c:97] No free output buffer slot
wl_display@1: error 1: invalid arguments for zwp_linux_buffer_params_v1@954.add
EE 04-01-21 12:12:16.977 - [backend/wayland/backend.c:64] Failed to dispatch remote Wayland display
EE 04-01-21 12:12:16.977 - [backend/wayland/backend.c:64] Failed to dispatch remote Wayland display
```

After that, the compositor either goes into an endless loop, or crashes on shutdown.

**Comment by ammen99** [comment]
Attaching the full log with debug output from wlroots. After the error happens, Wayfire starts doing some stupid things like opening a NOOP output, please disregard that part.
[log.txt](https://github.com/swaywm/wlroots/files/5764377/log.txt)

**Comment by emersion** [comment]
Can you collect `WAYLAND_DEBUG=client` logs?

**Comment by emersion** [comment]
Maybe this helps?

```
diff --git a/backend/wayland/output.c b/backend/wayland/output.c
index 6bc84dcba1a8..633e9a594213 100644
--- a/backend/wayland/output.c
+++ b/backend/wayland/output.c
@@ -450,7 +450,7 @@ static bool output_set_cursor(struct wlr_output *wlr_output,
                wlr_egl_unset_current(&output->backend->egl);
 
                struct wlr_wl_buffer *buffer =
-                       create_wl_buffer(output->backend, wlr_buffer);
+                       get_or_create_wl_buffer(output->backend, wlr_buffer);
                if (buffer == NULL) {
                        return false;
                }
```

**Comment by ammen99** [comment]
Much longer, but here it is:
[client.txt](https://github.com/swaywm/wlroots/files/5764528/client.txt)

**Comment by ammen99** [comment]
> Maybe this helps?

Doesn't seem like it.

**Comment by emersion** [comment]
OK, cool. We were probably running out of FDs in the parent compositor because we were creating many `wl_buffer` objects.

I submitted the change as a PR: https://github.com/swaywm/wlroots/pull/2595

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/2595
