### ISSUE TITLE
Correctly handle ICCCM globally active input model

### ISSUE THREAD

**Issue by BrassyPanache** [swaywm/wlroots#2604]
This issue stems from swaywm/sway#3007.

I've found that from 2020.3 onwards IntelliJ sets the input field of WM_HINTS to **false** for certain dialogs.  This is allowable under the ICCCM specifications (see https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.7).  If the input model is globally active the window receives passive input and then issues a SetInputFocus request to receive focus.  However under Wayland there is no mechanism to access input passively.  This leads to the situation under Sway where these dialogs cannot receive user input.

I've created a rather broad fix (perhaps overly so) which I've tested with:

- Chrome
- IntelliJ
- Alacritty
- VSCode

I have not seen any major issues.  The fix is to always enable the input flag.  My rationale is as follows:

1. If wlroots is not compiled with ICCCM support this is the default so it must be somewhat reasonable otherwise I'd expect to see some open issues.
2. If a window really does not require input and receives it this is somewhat easier for the end-user to navigate around rather than the current situation whereby the window can never receive input.

If this fix is too broad then perhaps we can at least open the discussion on how this can be better handled.  The current situation leaves JetBrains products rather unusable.

**Comment by luispabon** [comment]
Do you have the fix you mention on a branch somewhere? I'd love to help testing this out.

**Comment by emersion** [comment]
We had a very hard time getting focus to work somewhat correctly with X11 windows. We'll need extensive testing before merging anything.

Some windows _really_ don't want input focus, like tooltips. How does your patch handle them?

In the spec, with "Globally Active Input" the input field is set to False but WM_TAKE_FOCUS is enabled. Can't we special-case it?

**Comment by BrassyPanache** [comment]
I think supporting special-cases would make sense.  I agree that you don't want tooltips to take focus. I'll have more of a look at this.

**Comment by Haardt** [comment]
Hi,
your patch breaks another behavior. 'Normal' child windows from intelli no longer get the focus. If the mouse not over the new window i can't use shortcuts (for example the quit dialog and 'enter').

**Comment by BrassyPanache** [comment]
Thanks for testing, @Haardt.

Just following up after some further investigation.  It appears as though the dialog boxes in question do not set WM_TAKE_FOCUS.  The relevant logging can be seen below (there are no protocols configured).

```
00:00:58.707 [DEBUG] [wlr] [types/wlr_surface.c:673] New wlr_surface 0x55bd86009d30 (res 0x55bd860021f0)
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:1525] New xwayland surface: 0x55bd86009d30
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:415] XCB_ATOM_WM_CLASS: jetbrains-idea jetbrains-idea
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:468] XCB_ATOM_WM_NAME: win2
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:514] XCB_ATOM_WM_TRANSIENT_FOR: 0x55bd85e87870
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:573] WM_PROTOCOLS (0)
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:606] Input disabled for 4194685 as non-modal
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:609] WM_HINTS (9)
00:00:58.707 [DEBUG] [wlr] [xwayland/xwm.c:661] WM_NORMAL_HINTS (18)
```

At this point I am not sure of the best course of action.  I will update the issue in IntelliJ with the information provided above in the hope that they correctly set WM_TAKE_FOCUS.

Any suggestions?

**Comment by Haardt** [comment]
Sorry - can only test the patches. I don't know anything about wlroots :|. A patch would be fantastic - idea is my daily tool

**Comment by BrassyPanache** [comment]
An update from the JetBrains team seems to indicate that it is a Sway issue: https://youtrack.jetbrains.com/issue/JBR-3015

**Comment by emersion** [comment]
Is this fixed with https://github.com/swaywm/wlroots/pull/2605?

**Comment by BrassyPanache** [comment]
It’s fixed along with: https://github.com/swaywm/sway/pull/5958

**Comment by emersion** [comment]
Closing because wlroots now exposes a helper to allow compositors to properly fix this issue.
