### ISSUE TITLE
Cleanup wlr_egl

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2624]
There are some EGL features that are no longer used by backends:

- [x] `wlr_egl_swap_buffers` (https://github.com/swaywm/wlroots/pull/2623)
- [x] `wlr_egl_create_surface` and `wlr_egl_destroy_surface` (still used by client examples)
- [x] Buffer age support in `wlr_egl_make_current` (https://github.com/swaywm/wlroots/pull/2623)

**Comment by emersion** [comment]
I think we should remove any `wlr_egl` usage from the examples. I'm not yet clear what's the best way to do this, since EGL initialization is quite verbose. Maybe a we need simple `bool setup_wl_egl(struct wl_display *display, EGLDisplay *display, EGLContext *context)` helper for examples, but I'm not a fan of having examples that aren't self-contained. OTOH these aren't self-contained right now since they depend on `wlr_egl`.

**Comment by ammen99** [comment]
> OTOH these aren't self-contained right now since they depend on `wlr_egl`.

What is the definition of self-contained? They surely depend on wlroots?

**Comment by emersion** [comment]
The clients using `wlr_egl` directly are Wayland clients, for instance [toplevel-decoration](https://github.com/swaywm/wlroots/blob/master/examples/toplevel-decoration.c). The compositor examples don't use `wlr_egl` directly, instead they rely on `wlr_renderer` and `wlr_backend`.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/2666.
