### ISSUE TITLE
render/egl: use EGLDevice instead of the GBM platform

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2649]
We use the GBM platform to initialize EGL on a particular GPU. Instead, we could use the EGL device platform.

See https://github.com/swaywm/wlroots/issues/2563#issuecomment-757869784 for details.

cc @bl4ckb0ne

**Comment by bl4ckb0ne** [comment]
So, the plan from #2563 

- Get the DRM FD from the backend
- Query available physical devices via EGL_EXT_device_enumeration.
- Select the EGL device that matches the backend DRM FD via EGL_EXT_device_drm and drmGetDevice (compare DRM node paths).
- Create an EGL display from the EGL device via EGL_EXT_platform_device.

We should still be able to create a `wlr_egl` from a `gbm_device`, so we'll add a `wlr_egl_create_from_drm_fd` function. The creation logic should be split internally for the common bits.

**Comment by emersion** [comment]
Unfortunately I had to revert the PR.
