### ISSUE TITLE
wlr_surface is never free'd

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#265]
I don't see a `wlr_surface_destroy`, and the destroy handler only calls `wl_resource_destroy(surface->resource)`.

**Comment by versusvoid** [comment]
What about https://github.com/swaywm/wlroots/blob/2272f3d47cdcb5ffa42dcd20ad87253f78a2e9d0/types/wlr_surface.c#L615 ?

**Comment by emersion** [comment]
My bad, didn't saw that one.
