### ISSUE TITLE
gbm build dependency 

### ISSUE THREAD

**Issue by shoober420** [swaywm/wlroots#2651]
I’ve been building wlroots for quite some time now, and yesterday wlroots now requires “gbm” to build. I have a Radeon card, so I for sure have gbm. Would I say the mesa package provides gbm for this to build again?

**Comment by emersion** [comment]
wlroots has always required GBM. GBM is part of Mesa. I'm not sure I understand why your build fails.

**Comment by shoober420** [comment]
Maybe I need to add gbm to  the provides of my mesa package. Could I be compiling mesa without gbm? I do compile a minimal version of mesa. I havent had any issues with it until yesterday and sway works fine. Heres the log in case it helps.

[wlroots-nosystemd-git-0.12.0.r247.g32c30481-1-x86_64-build.log](https://github.com/swaywm/wlroots/files/5825127/wlroots-nosystemd-git-0.12.0.r247.g32c30481-1-x86_64-build.log)

**Comment by emersion** [comment]
Maybe. Mesa has a `-Dgbm=enabled` flag you can set.

Closing because this isn't a wlroots issue.
