### ISSUE TITLE
How can I try input-method-keyboard-grab?

### ISSUE THREAD

**Issue by Riey** [swaywm/wlroots#2678]
I've tried example source `input-method-keyboard-grab` with `text-input` in sway master branch but it seems any of grab keyboard callback isn't called

Is there something I miss?

**Comment by mozartilize** [comment]
Just encountered that yesterday, [this PR](https://github.com/swaywm/sway/pull/4932) need to merged into sway though

**Comment by Riey** [comment]
@mozartilize Thanks you! I'm gonna have to wait.
