### ISSUE TITLE
Visual glitches with external display on Pinebook Pro

### ISSUE THREAD

**Issue by appelgriebsch** [swaywm/wlroots#2683]
After updating to the latest version of ManjaroARM on my Pinebook Pro with kernel 5.10.7 and Mesa 2.3.3 I suddenly receive visual glitches on the external display connected via USB-C hub...

![gtk-greeter with Sway](https://forum.manjaro.org/uploads/short-url/tVhjS4b3GikG7sGcozxN3OKmHQL.jpeg)

Initially I thought this might be a Sway issue, which is used to show the gtkgreeter, so I tried other options like Cage for the greeter and added a Weston session, but the results are always the same...

![gtk-greeter with Cage](https://forum.manjaro.org/uploads/default/optimized/2X/f/f4c1170fd4dd7b43e59e7e79e43ca9885484ab53_2_666x500.jpeg)

![gtk-greeter with Cage](https://forum.manjaro.org/uploads/default/optimized/2X/6/60e6910f3ef0d881b536def1453668d8f7c2e657_2_666x500.jpeg)

It was working flawlessly on an older kernel / Mesa combination and AFAIK the newer kernel/Mesa will bring additional support for OpenGL on the panfrost graphic chip used by the Pinebook Pro... (which I guess might cause those effects eventually)

**Comment by emersion** [comment]
You'll probably want to report a Mesa bug.

**Comment by appelgriebsch** [comment]
I've checked running the same kernel/Mesa combination with an X11 desktop (MATE) and with a GNOME Wayland session without any issues....

![x11-MATE](https://forum.manjaro.org/uploads/default/original/2X/e/e2507fbdfe6a39623cf793f20a423a2645fa4fb0.jpeg)

![GNOME-Wayland](https://forum.manjaro.org/uploads/default/original/2X/2/242d70f45a11e09110e2841f52cbca0de1bfa32c.jpeg)

As such I assume it's not a kernel/Mesa issue, isn't it?

**Comment by emersion** [comment]
X11 and GNOME don't use all the kernel features wlroots and Weston use. For instance, X11 and GNOME don't support format modifiers. I don't think we can do much from the Sway side.

**Comment by appelgriebsch** [comment]
hmm ok, any idea how I can pinpoint the issue further?

**Comment by emersion** [comment]
Maybe try `WLR_DRM_NO_MODIFIERS=1`

**Comment by appelgriebsch** [comment]
Japp, That makes a huge difference...

![1C880069-C71A-411D-A86D-7D2BB7E44AB5](https://user-images.githubusercontent.com/6803419/105612283-62a24000-5dbb-11eb-932b-fec6df33f4b6.jpeg)

**Comment by emersion** [comment]
All right, then you can open a bug report for your graphics driver saying modifiers don't work properly.

**Comment by appelgriebsch** [comment]
Thanks for your support!
