### ISSUE TITLE
Can't get 3D acceleration on panfrost

### ISSUE THREAD

**Issue by divVerent** [swaywm/wlroots#2696]
This appears to be similar to https://github.com/swaywm/wlroots/issues/2122 but different. In fact, it may very well be user error on my end.

I am running on Arch Linux on an Asus C101PA with panfrost GPU:

```
[    9.198673] panfrost ff9a0000.gpu: mali-t860 id 0x860 major 0x2 minor 0x0 status 0x0
[    9.209100] panfrost ff9a0000.gpu: features: 00000000,100e77bf, issues: 00000000,24040400
```

Things I've tried:

- Building new libdrm from Git.
- Building new mesa from Git (and 100% making sure that kmsro is enabled).
- Building new vanilla kernel with the `linux-aarch64-chromebook` package.
- Forcing `WLR_DRM_DEVICES=/dev/dri/card0` (which is platform-ff9a0000.gpu-card); fails to start with `DRM universal planes unsupported`.
- Forcing `WLR_DRM_DEVICES=/dev/dri/card1` (which is platform-display-subsystem-card): starts but uses llvmpipe according to glxinfo.
- Enabling verbose logging with `sway -V`: only additional information is that sway calls card0 `panfrost` and card1 `rockchip`.

I also tried building `gl4es` and running some OpenGL stuff in that; it doesn't seem any faster, so most likely I'm still on llvmpipe for GLES too when using `card1` (too bad eglinfo doesn't tell such info, so I have to guess).

On X11 I do get GL, but curiously is really slow at 2D acceleration (e.g. urxvt renders really slowly). Maybe that's a hint to what is wrong?

Anything else to try? Especially, any way to get useful debugging info about why kmsro doesn't appear to be working? Also, this error is from a call to drmSetClientCap, which is a direct ioctl - so how can kmsro which is a thing in Mesa even influence this? I probably am misunderstanding something there - can anyone help?

**Comment by divVerent** [comment]
Sure; attached.

[drm_info.txt](https://github.com/swaywm/wlroots/files/5895750/drm_info.txt)
[sway.txt](https://github.com/swaywm/wlroots/files/5895751/sway.txt)
[glxinfo.txt](https://github.com/swaywm/wlroots/files/5895752/glxinfo.txt)

Roughly reading, it seems like Sway itself is using acceleration, but applications aren't. Any idea why?

**Comment by divVerent** [comment]
In comparison, here a dump of glxinfo running under X.org:

[glxinfo-x11.txt](https://github.com/swaywm/wlroots/files/5895783/glxinfo-x11.txt)

On all my other computers I can use desktop OpenGL under Sway, so I assume it should be possible here too. Or is there a reason why not? Any way how I can validate that at least GLES is HW accelerated?

**Comment by divVerent** [comment]
One more tidbit: the problem certainly seems to be in Xwayland or in WLRoots/XWayland communication, as mpv with Wayland backend uses desktop OpenGL, as evidenced by:

```
[vo/gpu/wayland] Detected desktop OpenGL 2.1.
[vo/gpu/wayland] GL_VENDOR='Panfrost'
[vo/gpu/wayland] GL_RENDERER='Mali T860 (Panfrost)'
```

**Comment by divVerent** [comment]
I think I found a workaround on my end:

I created a shell script with the following content and put it in my PATH:

```
#!/bin/sh
exec /usr/bin/Xwayland "$@" +extension GLX
```

I now have OpenGL in X11 applications.

Now I can't tell why this is now necessary - but would it maybe make sense to make wlroots spawn Xwayland this way?

**Comment by divVerent** [comment]
In any case - let's look at it from another angle. Is there anything wlroots does that might turn the GLX extension off?

If not, let's close this here and I'll look further - might be something to file against Xwayland then.

**Comment by emersion** [comment]
Hm, no, I'm not sure what could cause this. We don't do anything in particular to enable GLX. Maybe xserver's internals check for a RENDER node somewhere and don't initialize GLX if it's missing.

**Comment by emersion** [comment]
Closing for now.
