### ISSUE TITLE
Support winit

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#270]
Support [winit](https://github.com/tomaka/winit) gui toolkit and do QA so that it is reasonably well supported on wlroots. This should make [alacritty](https://github.com/jwilm/alacritty) terminal emulator work.

Currently doesn't work on weston because of xdg-shell protocol violations [(issue)](https://github.com/tomaka/winit/issues/306). Currently doesn't work on wlroots because of rendering issues.

cc @Timidger

**Comment by Timidger** [comment]
I haven't worked closely with winit directly, but I think that @vberger has. He might have more insight on how to get it working.

**Comment by vberger** [comment]
(yes, I've written the wayland backend of winit, so I kinda know it)

What I can say if that helps:

- the potential xdg-shell protocol violations is that, in some circumstances, a winit client might try to commit an xdg-surface before it has been configured by the server, though https://github.com/tomaka/winit/pull/309 should have mostly mitigated it.
- winit uses [wayland-window](https://github.com/Smithay/wayland-window) to draw its decorations using subsurfaces, so if the rendering issues are linked to decorations, the example from wayland-window repository may be a simpler test case than a full winit application (be it to find bugs in wlroots or wayland-window, I'll not claim the latter is bug-free).

**Comment by emersion** [comment]
What happens is that winit requests two pointers for the same seat and we don't support that: https://github.com/swaywm/wlroots/blob/master/types/wlr_seat.c#L76

```
[3595634.124]  -> wl_seat@3.get_pointer(new id wl_pointer@15)  <-- request first pointer
...
[3595646.826]  -> wl_seat@3.get_pointer(new id wl_pointer@19) <-- request second pointer on same seat
...
[3595673.093] wl_display@1.delete_id(15) <-- wlroots deletes the first one
```

A similar issue happens with the keyboard.

**Comment by vberger** [comment]
Ah yes, this is he way the winit backend is built that causes it, [wayland-window](https://github.com/smithay/wayland-window) binds its own wl_pointer to handle decoration interactions while keeping a simple & non-intrusive API.

Note that I asked on #wayland@freenode if binding the same seat/pointer/keyboard/...is supported, and was told that yes, and if the same pointer/... is created multiple time, each instance must receive a copy of all associated events.

**Comment by emersion** [comment]
Yeah, I'm working on a PR to fix this right now. We violate the protocol, so we need to fix this.

**Comment by acrisci** [comment]
@emersion probably just put a list of pointers in the seat client?

**Comment by emersion** [comment]
I'm doing it with `wl_list` and `wl_resource_get_link`, which is more appropriate than a list of pointers here.

**Comment by emersion** [comment]
Alacritty master now works with rootston. There's still one issue: on startup the surface buffer is bigger than the surface. This seems like a winit bug, but we should probably clip surface buffers when they're too large.
