### ISSUE TITLE
Rename wlr-seat-handle to wlr-seat-client

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#273]
It's a pretty big refactoring, so I'm making a proposal here to see what you guys think.

Rationale:

The name "handle" is kind of confusing (handle for who?). "handle" just means a nickname for something else. Every interface we work with could by this definition be a "handle".

We can be more specific because this is really for a connected wl_client to interact with the seat.

Also, it collides with our actual handlers somewhat. So if a function starts with `handle_` is it a handler or for the seat handle?

Anyway, this is one of the hard things in computer science, so if you guys are used to it, we can keep it in, but it sounds a bit nicer to me. Btw, weston has no such abstraction so we can't do what they do.

**Comment by SirCmpwn** [comment]
You could call it jim for all I care. This is your interface, you can maintain it as you see fit.
