### ISSUE TITLE
Cancel grabs when escape key is pressed

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#274]
To demonstrate (and test) forceful grab cancellation, rootston should cancel all grabs when the escape key is pressed. This will:

* close all popups
* end all drag and drop operations

And also should:

* end all window moves, returning the window to its original position
* end all pointer resize operations returning the window to its original size

But probably should not:

* stop listening to window manager binding keys

**Comment by emersion** [comment]
Is this already done?

https://github.com/swaywm/wlroots/blob/master/rootston/keyboard.c#L148

**Comment by acrisci** [comment]
It won't cancel rootston moves or resizes yet.
