### ISSUE TITLE
Rename wlr-output-layout to just wlr-layout

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#275]
The name `wlr_output_layout` is very long and it makes the code hard to read, but even worse is `wlr_output_layout_output` which makes me dizzy to look at sometimes. I think it's the duplication of the word "output" that makes it hard to scan the code. It's kind of difficult to tell what it is at first glance.

I don't think there will be any other different kinds of layouts to consider, so the chance of name collision is pretty low. Just "layout" is less descriptive, but I think the boost in readability is worth the tradeoff and the "output" bit of that is easy to keep in your head once you know it.

Once again, this is a hard thing in computer science and a matter of subjective taste, but I think it would be an improvement when working with this interface.

**Comment by SirCmpwn** [comment]
My 2c is -1. Sway has other kinds of layouts.
