### ISSUE TITLE
No output through HDMI port - DisplayPort works 

### ISSUE THREAD

**Issue by wunderf1tz** [swaywm/wlroots#2753]
Dear all,

The HDMI port is not detected when connected to different external monitors. miniDP and Thunderbolt works.
drm/dmesg log after starting a new sway instance while plugging ext. monitor in:

```
[ 3032.207387] i915 0000:00:02.0: [drm:intel_hdmi_set_edid] HDMI GMBUS EDID read failed, retry using GPIO bit-banging
[ 3032.207391] i915 0000:00:02.0: [drm:intel_gmbus_force_bit] enabling bit-banging on i915 gmbus dpc. force bit now 1
[ 3032.215098] [drm:drm_do_probe_ddc_edid] drm: skipping non-existent adapter i915 gmbus dpc
```

https://dpaste.com/BV42TY9NU
https://paste.c-net.org/ScarierRoxie

It this a kernel thing?

In the sway output. just the laptop monitor is listed:
```
swaymsg -t get_outputs
Output eDP-1 'Unknown 0x0747 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.027000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2a
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.027000 Hz
```

I posted dmesg files in different setups (HDMI connected, mDP connected, USB-C Display Port connected) in gitlab: 

https://gitlab.freedesktop.org/drm/intel/-/issues/3108

**Comment by emersion** [comment]
Can you reproduce the bug with Weston?

**Comment by wunderf1tz** [comment]
Yes, same error message when launched Weston from terminal on running sway. 
Tested it like this (good?): 
```
echo 0xFE | sudo tee /sys/module/drm/parameters/debug 
sudo dmesg -C
dmesg -f >dmesg.log &
weston >weston.log 2>&1
echo 0x00 | sudo tee /sys/module/drm/parameters/debug  
```

**Comment by emersion** [comment]
Yeah, definitely sounds like a kernel bug. Closing for now, good thing you've reported it to Intel already.

**Comment by wunderf1tz** [comment]
> Yeah, definitely sounds like a kernel bug. Closing for now, good thing you've reported it to Intel already.

Just to be sure, is the way Weston was launched as shown above representative to call it reproducible that way?
When I plug / unplug / plug drm events from sway are also logged into drm/dmesg logs, arent they?
