### ISSUE TITLE
Delegate logind support to seatd

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2755]
Drop our logind code, rely on seatd instead.

cc @kennylevinsen

**Comment by Conan-Kudo** [comment]
I'm not sure this is a good idea, given that [seatd calls itself "alpha" right now](https://git.sr.ht/~kennylevinsen/seatd/tree/34f55a3e2479daf0dae294dd22af25fcb6b25a01/item/README.md).

Can we hold off on this until it matures more?

**Comment by kennylevinsen** [comment]
> seatd calls itself "alpha" right now.

https://git.sr.ht/~kennylevinsen/seatd/commit/0d855a28f20ab3d7b2058fbe58a172a97affbde5

**Comment by Conan-Kudo** [comment]
@kennylevinsen Do you consider it stable to rely on?

**Comment by emersion** [comment]
I'm not too worried about the libseat code.

**Comment by Conan-Kudo** [comment]
Why not?

**Comment by emersion** [comment]
It's pretty similar to wlroots' code, and has been around for a while.

**Comment by emersion** [comment]
I guess the next step would be to make libseat a required dependency for wlroots, and nuke our direct session (and perhaps our session interface).

**Comment by prez** [comment]
>and nuke our direct session

why?

**Comment by emersion** [comment]
Because it's code which I'd rather share with other compositors than maintain, just like e.g. libinput. It's pretty trivial to drop seatd into `subprojects/` and make Meson build it as a subproject anyways.

**Comment by emersion** [comment]
libseat is now required and replaces all of our session code.

**Comment by emersion** [comment]
If you were using the direct backend and libseat is not yet packaged for your distribution, the replacement is now:

- Drop seatd into `subprojects/seatd`
- Run Meson with `-Dseatd:builtin=enabled`

And things should work just like before.
