### ISSUE TITLE
Cursor corruption

### ISSUE THREAD

**Issue by jpalus** [swaywm/wlroots#2766]
I realize it might not be an issue with wlroots but I had to start somewhere and hopefully wlroots developers will know more who should I bother instead.

Under unknown circumstances mouse cursor in my sway session sometimes gets corrupted:
Normal cursor:
![IMG_20210302_124558](https://user-images.githubusercontent.com/484155/109645457-24850280-7b57-11eb-8950-bd5714436b86.jpg)
Corrupted a moment later:
![IMG_20210302_124858](https://user-images.githubusercontent.com/484155/109645474-2cdd3d80-7b57-11eb-8d34-08e48a084b02.jpg)

Tested under:
* sway 1.5.1
* wlroots 0.12.0
* Mesa 21.0.0-rc4 (panfrost, T860, rk3399)
* kernel 5.11.0

Few observations:
* cursor corruption changes with moving mouse it's about 50% correct 50% corrupted
* corrupted "cursor" is much larger than correct one
* corrupted cursor somewhat has like parts of other window? Like terminal in a photo
* it might be related to plugging external display on and off but not sure still trying to figure out steps to reproduce
* also not sure but corrupted cursor seems to be only visible on external display
* around the time cursor gets corrupted following is logged:
```
02:44:51.102 [ERROR] [backend/drm/util.c:210] Unable to add DRM framebuffer: No such file or directory
02:44:51.103 [ERROR] [backend/drm/atomic.c:164] Failed to set plane 41 properties
02:45:04.804 [ERROR] [backend/drm/util.c:210] Unable to add DRM framebuffer: No such file or directory
02:45:04.804 [ERROR] [backend/drm/atomic.c:164] Failed to set plane 41 properties
02:45:13.635 [ERROR] [backend/drm/util.c:210] Unable to add DRM framebuffer: No such file or directory
02:45:13.635 [ERROR] [backend/drm/atomic.c:164] Failed to set plane 41 properties
```
Any idea what might be the issue?

**Comment by jpalus** [comment]
Ah sorry about the size of pictures, didn't realize it would get that big here.

**Comment by kennylevinsen** [comment]
Could you try with sway/wlroots master? Quite a lot has happened since wlroots 0.12.0. Please share the full debug log when it happens, and [drm_info](https://github.com/ascent12/drm_info) output as well.

We're failing to add framebuffers to the what is presumably the cursor plane, which exists per output (well, per CRTC) - hence the cursor only being garbled on one monitor. It's quite likely that it occurs occasionally when setting up an external monitor, so maybe turn a monitor on/off or re-plug it to provoke the error.

**Comment by jpalus** [comment]
Not sure if I'm doing something wrong but master wlroots/sway fails to start without WLR_RENDERER_ALLOW_SOFTWARE:
```
00:00:00.090 [INFO] [wlr] [backend/backend.c:167] Found 1 GPUs
00:00:00.091 [INFO] [wlr] [backend/drm/backend.c:155] Initializing DRM backend for /dev/dri/card0 (rockchip)
00:00:00.091 [DEBUG] [wlr] [backend/drm/drm.c:68] Using atomic DRM interface
00:00:00.091 [DEBUG] [wlr] [backend/drm/drm.c:81] ADDFB2 modifiers supported
00:00:00.091 [INFO] [wlr] [backend/drm/drm.c:243] Found 2 DRM CRTCs
00:00:00.092 [INFO] [wlr] [backend/drm/drm.c:170] Found 6 DRM planes
00:00:00.330 [ERROR] [wlr] [render/egl.c:282] Software rendering detected, please use the WLR_RENDERER_ALLOW_SOFTWARE environment variable to proceed
00:00:00.330 [ERROR] [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "eglMakeCurrent"
00:00:00.330 [ERROR] [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.330 [ERROR] [wlr] [backend/drm/renderer.c:33] Failed to create EGL/WLR renderer
00:00:00.331 [ERROR] [wlr] [backend/drm/backend.c:201] Failed to initialize renderer
00:00:00.335 [ERROR] [wlr] [backend/backend.c:174] Failed to create DRM backend
00:00:00.336 [ERROR] [wlr] [backend/backend.c:312] Failed to open any DRM device
00:00:00.418 [ERROR] [sway/server.c:55] Unable to create backend
```
Not sure how/when panfrost at /dev/dri/card1 should be involved.

**Comment by jpalus** [comment]
wlroots 0.12.0 is able to find 2 GPUs:
```
00:00:00.087 [INFO] [backend/backend.c:157] Found 2 GPUs
00:00:00.088 [INFO] [backend/drm/backend.c:138] Initializing DRM backend for /dev/dri/card0 (rockchip)
00:00:00.088 [DEBUG] [backend/drm/drm.c:70] Using atomic DRM interface
00:00:00.088 [INFO] [backend/drm/drm.c:255] Found 2 DRM CRTCs
00:00:00.088 [INFO] [backend/drm/drm.c:176] Found 6 DRM planes
00:00:00.298 [INFO] [render/egl.c:297] Using EGL 1.4
00:00:00.299 [INFO] [render/egl.c:298] Supported EGL client extensions: EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
```

**Comment by emersion** [comment]
> master wlroots/sway fails to start without WLR_RENDERER_ALLOW_SOFTWARE

This is a Mesa bug: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4178

**Comment by jpalus** [comment]
Since wlroots 0.12.0 is able to find 2 GPUs is there any chance to introduce env variable for forcing legacy behavior? Unless current design relies on new logic and cannot be exchanged.

**Comment by emersion** [comment]
No.

**Comment by kennylevinsen** [comment]
Just set the WLR_RENDERER_ALLOW_SOFTWARE flag until the bug in Mesa is fixed. It's just Mesa being confused, nothing harmful.

The (full) debug output and test result from master would be helpful.

**Comment by jpalus** [comment]
So far so good, let me keep it open for a while and if issue won't come up I will close it.

One other thing though -- after updating wlroots/sway pinentry-gnome3 stopped working even though it worked fine before without any actions from my side. Any idea if that's expected? gpg-agent runs pinentry-gnome3, which in turn activates SystemPrompter and gcr-prompter fails with "cannot open display:". I've switched to pinentry-qt5 which works after importing WAYLAND_DISPLAY into session environment. It does not help for pinentry-gnome3 though.

**Comment by jpalus** [comment]
Works fine closing.
