### ISSUE TITLE
Do not render regions under opaque surfaces

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#277]
ATM, we just iterate over all surfaces and render each of them. However, there are many situations when we don't need to render a surface: when a window is totally hidden behind other windows, or when the lockscreen is enabled.

We can use `wlr_surface.current.opaque_region` for that.

**Comment by ascent12** [comment]
This is somewhat part of #190.
I've been looking into making the renderer more efficient, but I haven't had the time to implement it yet.

**Comment by ammen99** [comment]
Just saw this issue, sounds like it is obsolete now that we don't have rootston anymore?

**Comment by emersion** [comment]
Indeed, this is the compositor's job.
