### ISSUE TITLE
9601a2 breaks rotations

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/wlroots#2774]
After commit 9601a2abf024fb8ac400c0df178bb41ec9e5d215 my rotated monitor no longer works, reverting the commit fixes this issue.

Relevant config section:
```
output DP-1 {
    pos 0 0
    res 2560x1440@144Hz
    adaptive_sync on
}
output DP-2 {
    pos 2560 -500
    transform 270
    res 2560x1440@144Hz
    adaptive_sync on
}
output DP-3 {
    pos 4000 -200
    res 3840x2160@60Hz
    adaptive_sync on
    scale 2
}
```

DP-2 is affected, DP-1 and DP-3 are not. Will try to reproduce with a clean config.

**Comment by emersion** [comment]
Can repro as well. Some notes:

- Only repros with 90 and 270. 180 is fine.
- Everything looks fine when the resolution is a square (width == height), so probably width and height need to be swapped somewhere.

**Comment by LaserEyess** [comment]
On a clean config with nothing except those transforms, I can still reproduce it and as emersion says only 90/270 are affected.

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/2775

**Comment by LaserEyess** [comment]
#2775 fixes this for me
