### ISSUE TITLE
Multi-GPU outputs blank starting with 9601a2a

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/wlroots#2780]
https://github.com/swaywm/wlroots/commit/9601a2abf024fb8ac400c0df178bb41ec9e5d215 has brought back the issue with blank external monitors using intel+nouveau configuration:

https://github.com/swaywm/wlroots/issues/2526

`WLR_DRM_NO_MODIFIERS=1` workaround is broken as well.

**Comment by J0nnyMak0** [comment]
I'm also getting a few meson warnings. (I can open a separate issue for this if required.)
```
|WARNING: Project targeting '>=0.56.0' but tried to use feature deprecated since '0.56.0': meson.build_root. use meson.current_build_dir instead.
```
I'm using meson 0.57.1

**Comment by emersion** [comment]
The warnings are a Meson bug: https://github.com/mesonbuild/meson/pull/7772#issuecomment-775201986

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2788?

**Comment by Dirbaio** [comment]
not OP but I also had the same symptoms: intel+nouveau, black screen since 9601a2a. 

Can confirm with #2788 everything works again!
