### ISSUE TITLE
Sway crashes when opening XWayland windows after regular Wayland windows

### ISSUE THREAD

**Issue by quietvoid** [swaywm/wlroots#2781]
- **Sway Version:**
  - sway version 1.5.1

- **Debug Log:**
  - https://gist.github.com/quietvoid/238d2a1c130aaad8d83a1c761380bd73

- **Configuration File:**
  - https://gist.github.com/quietvoid/0de6f6d293827d28523cbed8869f0a60
  - Here the only modification is changing the application launcher to `wofi`

- **Stack Trace:**
  - Sway does not crash, it exits cleanly
  - With the default config, the `amdgpu` driver is erroring because of switching from/to adaptive sync, but the issue is not affected by the output configuration.

- **Description:**
- This seems to be a bug caused by using `wofi` to launch a Wayland window, followed by an XWayland window. In this specific order.
- The issue does not happen when using the default launcher, or when launching an XWayland window followed by a native Wayland window.
- Steps:
  - In tty, run `sway -c ~/sway-test.conf -d 2> ~/sway.log`
  - With `wofi`, launch `kitty`
  - Using `kitty`, launch an XWayland app (this could be reproduced by Spotify, Discord, VSCode or any other GTK app forced through X11)
  - Sway exits back to tty

**Comment by emersion** [comment]
Would be nice to try with Sway/wlroots master, there were a few changes regarding Xwayland startup and restart. See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by quietvoid** [comment]
Doesn't seem to be reproducible using `master`

**Comment by emersion** [comment]
OK, not sure we can do anything here then.
