### ISSUE TITLE
Stuttering horizontal bar when running tinywl on master nvidia gpu

### ISSUE THREAD

**Issue by neurosnap** [swaywm/wlroots#2782]
Greetings!

Specs:

```
GPU: nvidia GTX 970
kernel: Linux arc 5.11.5-arch1-1
mesa: 20.3.4-3
wlroots: https://github.com/swaywm/wlroots/tree/44fa2c4b49ced30a69e86a2ed78dd9bf62e0fbb3 (master)
```

I've been playing around with `wlroots` on `master` trying to get it to run with the `tinywl`.  When I get my build setup properly and execute `./tinywl -s alacritty` I get a shuttering horizontal bar instead of the terminal emulator.

It's possible that something is not configured correctly with my system, but I decided to test `tinywl` on tag `0.12.0` and it runs the terminal emulator successfully.  I decided to dig in and see if I can figure out the problem.

I performed a `git bisect` and traced the first bad commit here: https://github.com/swaywm/wlroots/commit/0e927533

I went further and determined that the source of the failure is happening in  `wlr_drm_format_intersect`: https://github.com/swaywm/wlroots/blob/master/backend/drm/renderer.c#L246

I printed the results between the `plane_format (a)`, the `render_format (b)`, and the intersection `format`.  Below are the results:

```
a->format 34325241
a->cap 8
a->modifiers 3000000004fe010
a->modifiers 3000000004fe011
a->modifiers 3000000004fe012
a->modifiers 3000000004fe013
a->modifiers 3000000004fe014
a->modifiers 3000000004fe015
a->modifiers 0

b->format 34325241
b->cap 8
b->modifiers 0
b->modifiers 300000000000010
b->modifiers 300000000000011
b->modifiers 300000000000012
b->modifiers 300000000000013
b->modifiers 300000000000014
b->modifiers 300000000000015

format->format 34325241
format->cap 7
format->modifiers 0
```

If instead of an intersection of modifiers I copy all of the `plane_format (a)` modifiers onto the new `format` I can successfully load the terminal emulator using `tinywl`.  For some reason it seems like the modifiers should be lining up but the only intersection between the two is `0`.

I hope this debugging has been helpful.  Please let me know if you want me to provide any more logs.  I'm also more than happy to be a guinea pig to test any potential fixes.

**Comment by neurosnap** [comment]
WLR_DRM_NO_MODIFIERS=1 appears to fix the issue. I'd love to learn more about modifiers and why they need to be disabled for nvidia gpus.

**Comment by emersion** [comment]
I think this will be fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3724.

Without this MR, the nouveau user-space driver supports modifiers but not the same ones as the recent kernel driver. When intersecting the two sets you'd end up with a single one, LINEAR. The nouveau kernel driver has buffer synchronization issues with LINEAR buffers: https://gitlab.freedesktop.org/drm/nouveau/-/issues/41

**Comment by neurosnap** [comment]
Great, thanks for the response!

**Comment by emersion** [comment]
Closing since this is a Mesa issue.
