### ISSUE TITLE
Move master version ahead of the last tag

### ISSUE THREAD

**Issue by jbeich** [swaywm/wlroots#2792]
Consumers may want to support both latest release and master snapshot. To do so they can check `WLR_VERSION_*` but because wlroots only bumps minor version just before a tag is created it's not usable. So, some consumers choose to not support wlroots master until after the changes end up in a release that may end up being less stable due to not being tested in advance.

**Comment by emersion** [comment]
Do people really want to support building with different wlroots versions? Looks like it would be some pretty annoying `#ifdef` soup…

**Comment by jbeich** [comment]
For example, **A** project `master` branch uses `dependency('wlroots', version: ['>=0.12.0', '<0.13.0'])` and builds fine with wlroots 0.12.0 tag while **B** project `master` branch using the same statement fails because it wlroots `master` which hasn't bumped version yet.

**Comment by emersion** [comment]
Right. Some projects use version numbers like `1.90.0` for the development version after `1.0.0` is released. I'm not a fan of abusing version numbers like this though…

**Comment by kennylevinsen** [comment]
Yeah, let's not break version number continuity with hacks like that.

The cleanest method is probably just bumping the minor immediately after a tag, so master basically always represents an alpha/beta of a future release. It's the same amount of work as bumping before a release, although harder to remember to do. If we want to do a major release then two bumps will end up occurring between releases, but it shouldn't have any consequence. Patch releases when made on a maintenance branch from a release tag should be unaffected.

The "snapshot" version approach, just like the hack version number, is more of a chore as it requires first setting a real version number, tagging the release, then undoing the real version number again.

**Comment by emersion** [comment]
> The cleanest method is probably just bumping the minor immediately after a tag, so master basically always represents an alpha/beta of a future release.

That sounds like a good idea.

**Comment by emersion** [comment]
Done in 1c10079a67ca. I've also updated the instructions on the wiki: https://github.com/swaywm/wlroots/wiki/Core-contributor-guide#releasing-a-new-version
