### ISSUE TITLE
Idea : implement a lua wrapper

### ISSUE THREAD

**Issue by deb75** [swaywm/wlroots#2812]
Hi,

If I understand well, anyone could build its own wayland window manager, like `sway`, based on `wlroots`,
with any of the wrappers. Right ?

I was using `awesomewm` which was highly extensible through lua scripts as it was itself mostly written in `lua`.
Should it be possible to write a lua wrapper library ?

Regards

**Comment by emersion** [comment]
It's possible to add Lua scripting to the compositor, yes. That's what Way Cooler was doing.

It would also be possible to write some Lua bindings for wlroots, but not sure this is a good idea.

**Comment by progandy** [comment]
Here is an active lua scriptable compositor project:
https://github.com/taiwins/taiwins
