### ISSUE TITLE
Pointer events on Xwayland are buggy as hell

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#284]
I'm still seeing pointer events sent to the wrong clients and in the wrong places all the time. It's especially buggy when you have multiple outputs.

**Comment by acrisci** [comment]
Can you provide steps to reproduce?

**Comment by SirCmpwn** [comment]
1. Configure two outputs next to each other
2. Open urxvt on the first
3. Open qutebrowser on the second
4. Focus qutebrowser
5. Click urxvt
6. Observe the click was sent to qutebrowser and urxvt does not have focus

**Comment by acrisci** [comment]
I can reproduce this on master.

This is fixed by #297 for me. Can you retest on that branch and let me know if the bug is still there?

**Comment by SirCmpwn** [comment]
Yep, that works fine. Thanks!
