### ISSUE TITLE
Improve backend, renderer and allocator initialization

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2861]
This proposal is about solving the following problem: given an existing backend, how do we create a renderer and an allocator suitable for it?

Right now the renderer and allocator are created inside the backend. Each backend can have its own logic to choose a renderer and an allocator. In the future we'd like to move the renderer and allocator initialization out of the backend, to allow compositors to have more control and to allow for third-party renderers and allocators.

The backend is created first. Then the renderer is created from the backend in `wlr_renderer_autocreate` (this allows to switch between hardware and software rendering in this function depending on the backend DRM FD, and allows to have a `WLR_RENDERER` env override). Then we need to create an allocator from the backend and the renderer.

An obvious solution is to have somewhere a list of (backend, renderer, allocator) that work fine together. However this list highly depends on a fixed list of backends and renderers -- it doesn't allow third-party implementations to blend in. The list also needs to record compat for each permutation, so can be quite long and tricky to maintain.

@bl4ckb0ne suggested having a `is_software_renderer` flag that renderers can set. This would allow us to choose between GBM and shm or DRM dumb, but doesn't completely solve the issue since we have no good way to figure out whether the backend wants DRM dumb buffers or shm buffers. There's also the edge-case of llvmpipe, a software renderer behind an OpenGL API that only groks DMA-BUFs.

Another solution would be to have in each backend and renderer a list of supported allocators. However the backends and renderers don't really care about which specific allocator is used, they only care about the capabilities of the `wlr_buffer`s submitted to them. By "capability" I mean the supported functions in `wlr_buffer_impl`.

Here's a recap table:

| Module | Supported buffer(s) |
|-|-|
| GLES2 renderer | dmabuf |
| Vulkan renderer | dmabuf |
| Pixman renderer | data_ptr |
| Wayland backend | dmabuf, shm |
| X11 backend | dmabuf (shm in the future) |
| Headless backend | _any_ (doesn't care) |
| GBM allocator | dmabuf |
| shm allocator | shm, data_ptr |
| DRM dumb buffer allocator | dmabuf, data_ptr |

This proposal is about adding a list of supported buffer capabilities in each backend and renderer. With the following new API:

```c
/**
 * Given a backend and a renderer, automatically create an allocator suitable
 * for both.
 */
struct wlr_allocator *wlr_allocator_autocreate(struct wlr_backend *backend,
	struct wlr_renderer *renderer);

/**
 * Buffer capabilities.
 *
 * These bits indicate the features supported by a wlr_buffer. There is one bit
 * per function in wlr_buffer_impl.
 */
enum wlr_buffer_cap {
	WLR_BUFFER_CAP_DMABUF = 1 << 0,
	WLR_BUFFER_CAP_SHM = 1 << 1,
	WLR_BUFFER_CAP_DATA_PTR = 1 << 2,
};

#define WLR_BUFFER_CAP_ALL (WLR_BUFFER_CAP_DMABUF | WLR_BUFFER_CAP_SHM | \
	WLR_BUFFER_CAP_DATA_PTR)

/**
 * Get the buffer capabilities supported as render targets.
 *
 * This returns a bitfield of wlr_buffer_cap entries. The renderer supports
 * buffers which implement one of the returned capabilities.
 */
uint32_t wlr_renderer_supported_render_buffer_caps(struct wlr_renderer *renderer);

/**
 * Get the supported buffer capabilities.
 *
 * This returns a bitfield of wlr_buffer_cap entries. The backend supports
 * buffers which implement one of the returned capabilities.
 */
uint32_t wlr_backend_supported_buffer_caps(struct wlr_renderer *renderer);
```

Then we can collect the backend and renderer requirements in `wlr_allocator_autocreate`, and create a suitable allocator without having logic which depends on specific backend/renderer implementations. A compositor using a third-party allocator could use this information as well.

**Comment by bl4ckb0ne** [comment]
I thin `wlr_renderer_is_software_renderer` is a fast solution to our issue, but will not last in a foreseeable future. 

I like your proposal. It would still allow third parties backend and renderer, and make some links between them without making too many dependencies.

If I understand correctly, `wlr_allocator_autocreate` would create an allocator by intersecting the caps from the buffer and the renderer?

**Comment by emersion** [comment]
If we want the absolutely fastest and simplest solution, we could just go for something like this:

```c
if (wlr_renderer_is_pixman(renderer)) {
    if (wlr_backend_is_drm(backend)) {
        return wlr_drm_dumb_allocator_create();
    } else {
        return wlr_shm_allocator_create();
    }
} else {
    return wlr_gbm_allocator_create();
}
```

> If I understand correctly, wlr_allocator_autocreate would create an allocator by intersecting the caps from the buffer and the renderer?

Something like this yeah. Specifically we want an allocator that has one of the renderer buffer caps and one of the backend buffer caps. The logic in `wlr_allocator_autocreate` could look like this:

```c
uint32_t backend_caps = wlr_backend_supported_buffer_caps(backend);
uint32_t renderer_caps = wlr_renderer_supported_render_buffer_caps(renderer);

uint32_t gbm_caps = WLR_BUFFER_CAP_DMABUF;
if ((backend_caps & gbm_caps) && (renderer_caps & gbm_caps)) {
    return wlr_gbm_allocator_create();
}

uint32_t shm_caps = WLR_BUFFER_CAP_SHM | WLR_BUFFER_CAP_DATA_PTR;
if ((backend_caps & shm_caps) && (renderer_caps & shm_caps)) {
    return wlr_shm_allocator_create();
}

uint32_t drm_dumb_caps = WLR_BUFFER_CAP_DMABUF | WLR_BUFFER_CAP_DATA_PTR;
if ((backend_caps & drm_dumb_caps) && (renderer_caps & drm_dumb_caps)) {
    return wlr_drm_dumb_allocator_create();
}
```

**Comment by hizukiayaka** [comment]
I think GLES2 could support shm memory or internal buffer reading back
I have made an patch for DMAbuf importing #2835

**Comment by emersion** [comment]
With the existing EGL API, the GLES2 renderer can't render to shm memory.

**Comment by hizukiayaka** [comment]
Yes, you can't assign a shm memory for rendering, you could only read then back then copy to a shm memory. I should just want to say a cpu memory.

**Comment by hizukiayaka** [comment]
It just came to my mind, I wonder why we want Vulkan here, for rendering nothing that opengl (es) can't do that Vulkan could nor Vulkan would make thing simple in rendering. Or any platform that only support vulkan but not opengl (es) ?

**Comment by emersion** [comment]
OpenGL has a lot of shortcomings: global state, bad error handling, implicit synchronization everywhere, too high level of an API to allow us to properly optimize things like image uploads and downloads, etc.

**Comment by emersion** [comment]
Implemented in https://github.com/swaywm/wlroots/pull/2884
