### ISSUE TITLE
Corrupted rendering on sway 1.6 and wlroots 0.13

### ISSUE THREAD

**Issue by ikalnytskyi** [swaywm/wlroots#2862]
Hey there,

I just get upgraded to Sway 1.6 on my Arch and things got broken: I've got a corrupted rendering upon login. I have `NVIDIA GTX 970` and `nouveau` driver installed. I know, that NVIDIA is not great choice to work with open source community. Nevertheless, things used to work fine under `nouveau`, and maybe you will be able to help. I'm attaching `sway.log` to the issue.

I opened this issue in wlroots repo because I see a lot of errors coming from there.

```
Apr 16 20:35:52 endor sway[941]: 00:00:10.365 [DEBUG] [wlr] [backend/drm/legacy.c:80] connector DP-1: Failed to acquire cursor FB
Apr 16 20:35:52 endor sway[941]: 00:00:10.416 [ERROR] [wlr] [backend/drm/legacy.c:108] connector DP-1: drmModePageFlip failed: Device or resource busy
Apr 16 20:35:52 endor sway[941]: 00:00:10.920 [DEBUG] [wlr] [backend/drm/legacy.c:80] connector DP-1: Failed to acquire cursor FB
Apr 16 20:35:53 endor sway[941]: 00:00:11.522 [DEBUG] [wlr] [backend/drm/legacy.c:80] connector DP-1: Failed to acquire cursor FB
```

---

```
❯ pacman -Q | grep -E "sway|wlroots"
sway 1:1.6-1
swaybg 1.0-4
swayidle 1.6-1
swaylock 1.5-1
wlroots 0.13.0-1

❯ sway -v
sway version 1.6
```

[sway.log](https://github.com/swaywm/wlroots/files/6327007/sway.log)

**Comment by emersion** [comment]
Hm, there are a number of Nouveau bugs. From your logs:

```
Apr 16 20:35:42 endor sway[941]: 00:00:00.651 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 1920x1200 GBM buffer (format 0x34325241, modifier 0x0)
```

This modifier is linear, and there are a number of issues with linear buffers, e.g. https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8500.

This should be all fixed with a newer Mesa and kernel. In the meantime maybe try `WLR_DRM_NO_MODIFIERS=1`?

Closing since these are nouveau bugs.

**Comment by ikalnytskyi** [comment]
It seems `WLR_DRM_NO_MODIFIERS=1` helped! Thank you very much!
