### ISSUE TITLE
Redesign keyboard interface

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#287]
This is a proposal to redesign the keyboard interface to be able to fix #242.

Right now, keyboard events follow this flow:

```
                                    +----> [ rootston ]
                                    |
[ backend ] +------> [ wlroots ] +--+
                                    |
                                    +----> [ client ]
```

So `rootston` has no control over keyboard events. It just selects the client to which events are sent to with `wlr_seat_keyboard_notify_enter` and `wlr_seat_keyboard_clear_focus`.

The idea is to change the flow to something similar to pointer events:

```
[ backend ] +---> [ wlroots ] +---> [ rootston ] +---> [ wlroots ] +---> [ client ]
```

With these functions:

* `wlr_seat_keyboard_send_key`, `wlr_seat_keyboard_send_modifiers` used by backends [same as right now]
* `wlr_seat_keyboard_notify_enter` and `wlr_seat_keyboard_clear_focus` used by rootston [same as right now]
* `wlr_seat_keyboard_notify_key`, `wlr_seat_keyboard_notify_modifiers` used by rootston [new]

Keyboard events won't be forwarded automatically by wlroots anymore, it'll be the compositor's role to listen to them and to call the two new functions.

**Comment by SirCmpwn** [comment]
One issue to take into consideration here is that I *like* that wlr_seat handles sending keymaps to clients and sorts out different keymaps for different keyboards.

**Comment by Timidger** [comment]
What was the decision on this issue?

**Comment by SirCmpwn** [comment]
I have no idea. Shouldn't have been closed.

**Comment by emersion** [comment]
Sorry, I thought a new issue would be opened for a better proposal. I closed this issue because this proposal won't happen.

**Comment by SirCmpwn** [comment]
We can continue to develop a better proposal here.

**Comment by Timidger** [comment]
One option is to have wlroots expose the functionality we currently have (eg sending keymaps to clients on the appropriate event) as functions that can be called by the compositor.

It'll still be opt in, but rootson (as well as Sway and Way Cooler) won't need to implement the "obvious" functionality and can instead call those functions if they so wish.

**Comment by acrisci** [comment]
One thing for sure is that we are going to try to get devices out of the seat as much as possible.

The default solution is to simply let rootston manage the keyboard device itself. What this proposal should be is for the layer of abstraction between the device and rootston. That abstraction might end up looking a lot like wlr-cursor.

What I think we're looking for is a container for zero to many keyboard devices that manages their state, helps to configure the devices in a semantic way (abstracting some of xkb), provides a centralized source of events with helpers for interpreting their values (such as keycodes to keysyms), and guides interactions with wlr-seat.

We may find that when coming up with the specifics of this that the abstraction is not necessary and rootston is better off just handling the raw devices.

But let's take our time on this. Rootston is really buggy right now and it has an "island of misfit toys" feel to it so that's currently my priority.

**Comment by acrisci** [comment]
I don't think the container will be necessary, but I think we do need some kind of wrapper for the raw device to store keyboard state and help process events. We have this presently in `wlr_keyboard` but it's owned by the seat, which is what is causing the problems.

We should transfer ownership of the wlr-keyboard to rootston. When a device is added, rootston creates a wlr-keyboard from the device and configures it based on compositor policy.

Events are routed from the input device to wlr-keyboard to rootston. This gives the wlr-keyboard a chance to see the event and possibly update its state in response, keeping track of what keys are pressed (required for the seat), and maybe other kinds of state processing like what LEDs are lit up, and possibly a binding interface.

The seat has one of these wlr-keyboards at a time (representing the "active keyboard" that are the source of key press events given to clients). Rootston is responsible for telling the seat what keyboard is active by calling `wlr_seat_set_keyboard()` on the seat after a keypress event on the wlr-keyboard. This gives the seat a chance to send the device state it sees in this wlr-keyboard to clients for the currently active keyboard (keys currently pressed and the keyboard layout).

The active keyboard from the seat is used by grabs to interpret keyboard events. Some keyboard grabs need to translate codes, such as the dnd keyboard grab which changes the dnd action based on what modifiers are pressed.

**Comment by SirCmpwn** [comment]
I like that design, +1

**Comment by emersion** [comment]
How to fix #242 with this design? Have another keyboard state in rootston to get keysyms from raw events, then check if there's a matching keybinding, and then re-send the raw events to `wlr_keyboard` (which will update its own keyboard state)?

**Comment by acrisci** [comment]
> How to fix #242 with this design?

Windows only see the keyboard event when it is sent to the seat. Right now, this is handled by the seat internally on key press.

The seat will gain a new function `wlr_seat_keyboard_notify_key`. This function is called at the end of rootston's handling of the wlr-keyboard key event to send the event to the current grab which then sends the event to focused seat resources or can choose to consume the event itself.

In the case of a binding, rootston should first check if any grabs want to handle the event (the keyboard grab is not the default grab). If there are no grabs, rootston determines whether or not a binding should be run. If so, rootston runs the binding and simply does not notify the seat that any event occurred, thus not sending the keyboard event to focused resources.

**Comment by emersion** [comment]
Okay, I misread your explanation. So that would look like: `backend -> wlr_keyboard (steup by rootston) -> rootston -> seat -> clients`. Seems good.

What about multiple keyboards per seat?

**Comment by acrisci** [comment]
> What about multiple keyboards per seat?

This is handled by the concept of the "active keyboard" on the seat described above.

**Comment by emersion** [comment]
No, I mean, with this design it's not possible to have multiple keyboards per seat. The question was: if you have two keyboards plugged in, you have to create two seats? Is that a problem?

**Comment by acrisci** [comment]
> No, I mean, with this design it's not possible to have multiple keyboards per seat.

Rootston tells the seat which keyboard is active for the seat in the wlr-keyboard key press event. There can only be one keyboard active at a time, but which keyboard is active can potentially change on any key press event.
