### ISSUE TITLE
sway output transform 90 is percieved as transform 270 by other programs

### ISSUE THREAD

**Issue by williamkray** [swaywm/wlroots#2873]
Wasn't sure where to file this, so `danieldg` in the irc chan suggested putting it here and it can be moved if necessary.

I have two external monitors connected to my laptop, one horizontal and one vertical next to it. my sway config looks like this:

```
output eDP-1 resolution 1920x1080 position 0,1080
output DP-3 resolution 1920x1080 position 0,0
focus output DP-3
output DP-4 resolution 1920x1080 position 1920,0 transform 90
```
Everything works fine with SwayWM, but wdisplays, wlay, and screenshots taken with grimshot (grim/slurp) all see this output as transformed 270 degrees instead of 90. so everything is upside down (screenshots of smaller areas using slurp appear to be the correct coordinates, but of the inverted screen image).

Please let me know if this should be moved to a different project or tool for resolution.

**Comment by emersion** [comment]
Most likely these are client bugs. wlroots used to send the `Y_INVERT` screencopy flag but stopped recently. This wasn't a well-tested codepath in clients, so some of them weren't prepared for this.

A new grim release has been shipped yesterday, FWIW.
