### ISSUE TITLE
libseat not found

### ISSUE THREAD

**Issue by Puspam9876** [swaywm/wlroots#2888]
I am trying to build wlroots from source, but it stuck at this point:

```
Run-time dependency libseat found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libseat

backend/session/meson.build:1:0: ERROR: Neither a subproject directory nor a seatd.wrap file was found.

A full log can be found at /home/puspam/Downloads/wlroots/build/meson-logs/meson-log.txt
```

I use Ubuntu and I cannot find `libseat` or `libseat-dev` in the Ubuntu repositories. Searched the internet, but getting inconsistent results. What should I do about this?

**Comment by kennylevinsen** [comment]
In your wlroots checkout, `git clone https://git.sr.ht/~kennylevinsen/seatd subprojects/seatd`
