### ISSUE TITLE
render/drm_dumb_allocator: doesn't work on amdgpu

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2916]
The GBM imports are failing. See https://github.com/swaywm/wlroots/pull/2700#issuecomment-832508102.

Fixing this requires side-stepping GBM.

We probably have two choices here:

- Pass GEM handles around directly. In theory this is simpler, but also more dangerous if there's no safe-guard. In particular, on multi-GPU systems, it's pretty easy to mix up GEM handles between devices.
- Open a separate DRM FD in the DRM backend. Manually perform the GEM handle ref'counting.

**Comment by sjnewbury** [comment]
I'm getting severe corruption on fullscreen windows, for example alacritty with "super-f".  I've bisected it to this commit.

Using current git master/main libdrm/mesa/wlroots/sway, amdgpu (POLARIS10).

**Comment by emersion** [comment]
Please open a new bug report with debug logs and dmesg.
