### ISSUE TITLE
0.13 and newer problems

### ISSUE THREAD

**Issue by piotr-sikora-v** [swaywm/wlroots#2923]
I have fresh installation gentoo with wayland
On wlroots-0.13.0 and sway-1.6 when (and also git latest versions) I start sway I see black screen... I must switch to conosle (ctrl+alt+f3) and go back to sway console.
and also when I do this few times I see only artefacts on my screen.

on wlroots-0.12.0 and sway-1.5.1-r1 everything wokrs greate

here is debug from start "sway -d" for both versions
wlroots-0.12  https://chmura.ftdl.pl/s/zSqn3x5xQAjGBkb
wlroots-0.13 https://chmura.ftdl.pl/s/kEN3QnPYqMZcExy

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau
