### ISSUE TITLE
Efficient hashmap for add-on structs

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2927]
Often times in wlroots, we need to extend "base" objects like `wlr_surface` or `wlr_buffer`:

- [`wlr_presentation_surface_sampled`](https://github.com/swaywm/wlroots/blob/6369f7093178f0d66414eb67c312a403bfbb84a4/include/wlr/types/wlr_presentation_time.h#L86)
- [`drm_fb_get`](https://github.com/swaywm/wlroots/blob/6369f7093178f0d66414eb67c312a403bfbb84a4/backend/drm/renderer.c#L447)
- [`gles2_texture_from_buffer`](https://github.com/swaywm/wlroots/pull/2851#discussion_r633555311)

Instead of using a `wl_list`, using a hashmap that uses a pointer for the keys would be more efficient. It would be nice to study from which number of element the list approach becomes an issue performance-wise.

**Comment by bl4ckb0ne** [comment]
Fwiw I like the one mcf did for [samurai][1]. I cleaned the implementation in my [personal snippets][2]. 


[1]: https://git.sr.ht/~mcf/samurai/tree/master/item/htab.c] 
[2]: https://git.sr.ht/~bl4ckb0ne/tyr/tree/master/item/tyr/hash_table.c

**Comment by emersion** [comment]
That implementations hashes string keys, though. We can probably drop `murmurhash64a` completely and replace it with a a function that shuffles the bits of the `uintptr_t` keys sufficiently.

Also, I'm not sure about that hashtable behaviour when two different entries end up with the same hash… It doesn't seem like this case is handled?

**Comment by bl4ckb0ne** [comment]
I think the murmur hash has a pretty low collision rate.

**Comment by emersion** [comment]
Low collision rate doesn't mean that collisions won't happen.

**Comment by kennylevinsen** [comment]
> Also, I'm not sure about that hashtable behaviour when two different entries end up with the same hash… It doesn't seem like this case is handled?

It's handled in key_index. The hash is used to find the *initial* index, and key_index then simply increments the index until it either finds a matching key or an empty slot. It grows whenever usage reaches 50% capacity, at which point it rebalances.

Note that hash_table_put does *not* override the value if it already exists (that is, key_index found an entry). In this case it simply returns a pointer to the existing value.

> I think the murmur hash has a pretty low collision rate.

Murmur hash is a cheap and small hash and thus have a pretty high likelihood of collision, but it doesn't matter as we don't really need arbitrary string hashing.

We just need something like a 64-bit mixer. MurmurHash has one as the final step. A CRC could also be used.

(If we're bored, we could unroll MurmurHash for 64-bit.)

**Comment by emersion** [comment]
Ah, makes sense!

**Comment by emersion** [comment]
Yup, that's a possible alternative solution. Change `wlr_renderer_buffer_handle.renderer` to be something like `void *owner` and this can be used by the DRM backend as well.

One downside is that it requires adding an extra data structure to all of the structs that we want to "extend" (ie. attach add-ons to).

**Comment by emersion** [comment]
Note, add-on structs aren't just for `wlr_buffer`, we use them for other structs as well, e.g. `wlr_surface` or `wlr_output`.

**Comment by zccrs** [comment]
Yes. I look forward to your choice between these two solutions.

**Comment by vyivel** [comment]
Assuming I understand what's required correctly, is it possible to store a list "extended" objects in the base object?
Something like this:

```c
/* wlr_extension.{h,c} */

typedef uint8_t wlr_extension_id;

struct wlr_extension {
    const wlr_extension_id *id;
    struct wl_list link;
};

struct wlr_extension *wlr_extension_find(
        struct wl_list *extensions, const wlr_extension_id *id) {
    struct wlr_extension *extension;
    wl_list_for_each(extension, extensions, link) {
        if (extension->id == id) { /* comparing unique pointers */
            return extension;
        }
    }
    return NULL;
}

/* wlr_base_object.h */

struct wlr_base_object {
    /* ... */

    struct wl_list extensions;
};

/* wlr_extended_object.{h,c} */

struct wlr_extended_object {
    struct wlr_base_object *base;
    struct wlr_extension extension;
    /* ... */
};

/* An object with a unique pointer */
static const wlr_extension_id extended_id;

struct wlr_extended_object *wlr_extended_object_create(
        struct wlr_base_object *base) {
    struct wlr_extended_object *extended = calloc(1, sizeof(*extended));
    extended->base = base;
    extended->extension.id = &extended_id;
    wl_list_insert(&base->extensions, &extended->extension.link);
    return extended;
}

struct wlr_extended_object *wlr_extended_object_from_base(
        struct wlr_base_object *base) {
    struct wlr_extension *extension
            = wlr_extension_find(&base->extensions, &extended_id);
    struct wlr_extended_object *extended = NULL;
    if (extension) {
        extended = wl_container_of(extension, extended, extension);
    } else {
        /* No extended object */
    }
    return extended;
}

```

`wlr_extension_id` thing can be replaced with an enum, though I find this approach somewhat cleaner.

This implementation assumes there can be at most one `wlr_extended_object` for each `wlr_base_object`, but `wlr_extension_find()` could be modified to support all cases.

**Comment by emersion** [comment]
@Vyivel, it seems like you've posted a comment, but then deleted it? Was that intentional?

**Comment by vyivel** [comment]
Yes. I didn't realize my approach was actually very similar to zccrs's solution before I posted it. I still have the example code though, if you need it.

**Comment by emersion** [comment]
I see, indeed, these are quite similar.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/3097.
