### ISSUE TITLE
fix wiki

### ISSUE THREAD

**Issue by gramcracker** [swaywm/wlroots#2928]
The wiki shows blog links with a tutorial for mcwayface, but that project is outdated.

**Comment by fluix-dev** [comment]
For others, I believe [this](https://drewdevault.com/2018/02/17/Writing-a-Wayland-compositor-1.htm) is the blog post being referred to, but I don't think the project being outdated is necessarily an issue unless it does things in an incorrect (by current standards) way. If that *is* the case, I don't think it's huge deal[1] (It's under "Additional resources") but perhaps it would be good to add a year to the links and/or mention the inaccuracies.

[1]: Unless it's something really wrong: in which case yeah, deletion seems warranted.

**Comment by emersion** [comment]
Yeah, I think an old blog post is still a good introduction to wlroots.
