### ISSUE TITLE
cannot start Wayfire due to EGL_KHR_platform_gbm not supported

### ISSUE THREAD

**Issue by dkondor** [swaywm/wlroots#2939]
On recent wlroots, I get the following error message when trying to start Wayfire:

```
EE 23-05-21 22:33:53.519 - [render/egl.c:177] EGL_KHR_platform_gbm not supported
```

Surprisingly, after reverting commit 69e1997ebe3e38dee2f7318c3989f16e2bcac8f3, everything works fine.

I'm on Ubuntu 18.04 with mesa 20.0.8, so I'm aware the solution might be to update mesa.

Attaching a full log below; some relevant details:
```
Using EGL 1.4
GL renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
```
(the log is from running nested under Wayfire, but I get the same error when running natively with the drm backend)
[wayfire-log-gbm-error.txt](https://github.com/swaywm/wlroots/files/6528903/wayfire-log-gbm-error.txt)

**Comment by emersion** [comment]
Yup, your Mesa is too old. I'm fine with merging a check for `EGL_MESA_platform_gbm`.

**Comment by dkondor** [comment]
Thanks, that makes sense. But it seems `EGL_MESA_platform_gbm` is supported, only `EGL_KHR_platform_gbm` is missing:
```
II 24-05-21 10:29:34.578 - [render/egl.c:305] Using EGL 1.4
II 24-05-21 10:29:34.578 - [render/egl.c:306] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_wayland EGL_EXT_platform_x11 EGL_MESA_platform_gbm EGL_MESA_platform_surfaceless EGL_EXT_platform_device
```
This is after reverting commit 69e1997, the full log is attached.
[wayfire-log-gbm2.txt](https://github.com/swaywm/wlroots/files/6530962/wayfire-log-gbm2.txt)

**Comment by dkondor** [comment]
Edit: I just saw the comments here: https://github.com/swaywm/wlroots/pull/2832/files#r608651161

I'm OK closing this since I'm confident my workaround should work.

**Comment by emersion** [comment]
Yeah. `EGL_MESA_platform_gbm` is the old name for `EGL_KHR_platform_gbm`, before it was ratified by Khronos.

Closing this, as said above feel free to send a PR to allow `EGL_MESA_platform_gbm`.
