### ISSUE TITLE
xwayland: make sure server side decorations are possible

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#294]
I don't know how server side decorations work, but we should make sure they are possible in xwayland.

Can the current xwayland api support this?

I'm making this issue because Weston seems to do ssd within xwayland itself, and I know from dealing with this in other window managers that there are potentially things that need to be done with the X11 protocol to support this.

**Comment by SirCmpwn** [comment]
Couldn't you just render them around the view like you'd do SSD for any other view?

**Comment by acrisci** [comment]
> Couldn't you just render them around the view like you'd do SSD for any other view?

That's what I'm trying to figure out. I think that's the case, but I don't know how SSD works in sway.

**Comment by SirCmpwn** [comment]
It works as I described.

**Comment by Timidger** [comment]
It works the same way in Way Cooler. I'm unaware of any WMs that do it differently in fact

**Comment by SirCmpwn** [comment]
Yeah, I think this is a non-issue. We already have everything we need for this.

**Comment by acrisci** [comment]
Ok that makes sense. That's actually quite a change from the current rootston way of doing things, which assumes that the toplevel of the view is what is positioned with x/y. But these probably aren't going to be differences that are specific to xwayland (although I am not familiar with the kde ssd protocol). So if you're confident it's possible, I am too.
