### ISSUE TITLE
Add wlr_touch frame signal

### ISSUE THREAD

**Issue by subdiff** [swaywm/wlroots#2943]
I was wondering why wlr_touch does not have a  frame event like wlr_pointer has.

In the libinput backend the corresponding event `LIBINPUT_EVENT_TOUCH_FRAME` is declared as noop, and that according to git blame [already for longer](https://github.com/swaywm/wlroots/blame/d0560e2597e79f0f25c0ad9fd6969eaf10fd5558/backend/libinput/events.c#L264)

In the wlr_seat implementation a frame event is currently directly sent [after each touch event](https://github.com/swaywm/wlroots/blob/d0560e2597e79f0f25c0ad9fd6969eaf10fd5558/types/seat/wlr_seat_touch.c#L289,L347).

Would it make sense to implement a touch signal that relays the libinput event?

**Comment by emersion** [comment]
Yup, seems like on oversight. We should definitely add it.

**Comment by emersion** [comment]
Done in https://github.com/swaywm/wlroots/pull/3001.
