### ISSUE TITLE
Allow pass of cmdline parms to Xwayland 

### ISSUE THREAD

**Issue by droc12345** [swaywm/wlroots#2960]
I'm pretty sure this falls under enhancement. But is it possible to allow passing of command line parameters to Xwayland.

Specifically I've modified the call to Xwayland to add the -dpi and -auth flags. 

This is what I have done 
Change this
>         char *argv[] = {
>                 "Xwayland", NULL /* display, e.g. :1 */,
>                "-rootless", "-terminate", "-core",

To
>         char *argv[] = {
>                 "Xwayland", NULL /* display, e.g. :1 */,
>                 "-dpi", "163", "-auth", "/home/kdef/.Xauthority",
>                 "-rootless", "-terminate", "-core",

It works, dpi is seen properly, and auth allows what it's supposed to, so it works.

Any thoughts on this?
I was thinking of modifying the code to accept an environment variable for the flags like
WLR_XWAYLAND_ARGS='"-dpi", "163", "-auth", "/home/kdef/.Xauthority"'
and then just using that line as part of the args.

**Comment by emersion** [comment]
You can set `WLR_XWAYLAND=~/bin/Xwayland`, then but a script in there that adds custom parameters:

```sh
#!/bin/sh
exec /usr/bin/Xwayland <params> "$@"
```

**Comment by droc12345** [comment]
That seems to work. Thanks
