### ISSUE TITLE
Hotplugging a second screen fails

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/wlroots#2963]
I'm seeing a few scenarios which fail:

1. When I my external monitor, it generally does not turn on (not sure if always or _almost_ always).
2. When I'm in clamshell mode and open the laptop monitor it does not turn on.
3. For the above case, if I unplug the external monitor first, opening the laptop lid also does not turn it on.

I debugged the first scenario here ([previously mentioned in an issue I though might be the same](https://github.com/swaywm/wlroots/issues/2373#issuecomment-859632749)).

[dmesg.log](https://github.com/swaywm/wlroots/files/6639461/dmesg.log)
[sway.log](https://github.com/swaywm/wlroots/files/6639463/sway.log)

I tried using `WLR_DRM_NO_MODIFIERS=1`, and that does work.

**Comment by emersion** [comment]
> I tried using WLR_DRM_NO_MODIFIERS=1, and that does work.

Ah, so this is already tracked by https://github.com/swaywm/wlroots/issues/1873. Closing as a duplicate.

**Comment by WhyNotHugo** [comment]
Thanks for confirming that, I really wasn't sure if it was the same bug or not.
