### ISSUE TITLE
xwayland: add support for the startup notification protocol

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2968]
Ref https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt

**Comment by emersion** [comment]
Ref https://github.com/swaywm/wlroots/pull/3124

**Comment by agx** [comment]
I think we don't need much more than #3146 here since handling the lanuchee part on the X side looks out of scope for wlroots.

**Comment by agx** [comment]
Do we want anything more here besides https://github.com/swaywm/wlroots/pull/3146 and https://github.com/swaywm/wlroots/pull/3124 or can it be closed?

**Comment by emersion** [comment]
I think this can be closed. It would be nice to expose a function to manually request xdg-activation tokens to pass down to X11 clients, and another function to validate a token. But that's separate I suppose, opened https://github.com/swaywm/wlroots/issues/3211.
