### ISSUE TITLE
External monitor broken on multi-GPU setup

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/wlroots#2987]
https://github.com/swaywm/wlroots/commit/6c3d080e25e56404228ad7704eed43e40fa0c623 breaks external monitors. Nothing is rendered on external monitors as they remain gray.

I'm on a multi-gpu setup with i915+nvidia. Sorry for catching this late, I haven't been testing new commits regularly because of #2636

Log attached.
[sway.log](https://github.com/swaywm/wlroots/files/6711169/sway.log)

**Comment by J0nnyMak0** [comment]
If it is of any help, this seems to be a problem with hardware cursors. external displays work with `WLR_NO_HARDWARE_CURSORS=1` set.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/3021?
