### ISSUE TITLE
Output mirroring

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#299]
Output mirroring is currently not supported in rootston.

A "mirrored output" should display the contents of its (unique and existent) "parent output" (master output?). A mirrored output has no position in the output layout and therefore no associated wlr-output-layout-output object used in considering where windows are positioned, and no associated `wl_output` object for clients to consider when querying for layout info.

When a mirroed output is being rendered, it should use its parent's wlr-output-layout-output object and its parent's width and height to decide what the contents of the output will be.

If the parent output is not connected or is disconnected, the mirrored output should either be disabled or auto-added into the output layout (rootston's choice).

If the outputs do not match in resolution, the mirrored output should be clipped or scaled (rootston's choice).

TODO:

* do not send a wl_output global for mirrored outputs
* mirrored output rendering
* decide how to store mirrored output info (in wlr-output-layout or wlr-output)
* rootston configuration for output mirroring

**Comment by martinetd** [comment]
I think design-wise it shouldn't be explicitly "mirrored output", but being able to have multiple overlapping outputs and just rendering whatever is overlapping twice e.g. you should obviously be able to render mirror but also these kind of layouts:

```
+---------------------+---------+
|                     |         |
|                     |         |
|                     |         |
|                     |         |
|                     |         |
|                     |         |
+---------------------+         |
|                               |
|                               |
|                               |
|                               |
|                               |
+-------------------------------+
```

or
```
+-------------------------------+
|                               |
|                               |
|                               |
|                               |
|         +---------------------------------------+
|         |                     |                 |
|         |                     |                 |
|         |                     |                 |
|         |                     |                 |
|         |                     |                 |
|         |                     |                 |
|         |                     |                 |
+-------------------------------+                 |
          |                                       |
          |                                       |
          |                                       |
          |                                       |
          |                                       |
          +---------------------------------------+
```

That should come automatically as soon as outputs can have overlapping positions :)

**Comment by emersion** [comment]
I agree with @martinetd but if both outputs have a different resolution mirroring might be useful.

**Comment by acrisci** [comment]
Oh I didn't think about that. That actually seems to work correctly right now.

**Comment by SirCmpwn** [comment]
Yeah, we don't need to do this.
