### ISSUE TITLE
xwayland: Unrecognized option: -listenfd

### ISSUE THREAD

**Issue by alandiwix** [swaywm/wlroots#2990]
- **Sway Version:**
1.6.1-7571507451 (Jun 26 2021, branch 'master')

- **Debug Log:**
https://pastebin.com/FnQ6JgqD

- **Configuration File:**
Seems to be reproducable on default.

- **Description:**
1. Launch sway
2. Launch any application that uses Xwayland
3. Application fails to start, Xwayland X11 socket disappears

**Comment by alandiwix** [comment]
@Xyene So, seems like xwayland in Alpine repository got renamed some time ago and I ended up with the old package. I will upgrade this ASAP.
Here is the aports commit for the latest sway/wlroots upgrade I've got:
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/22649

**Comment by emersion** [comment]
Closing because wlroots assumes the user will have at least an xwayland version as recent as the one it's been compiled with (just like dynamic libraries).
