### ISSUE TITLE
Firefox URL dropdown is positioned incorrectly

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#300]
Tested on the wayland backend.

**Comment by SirCmpwn** [comment]
This is just conjecture but I bet this works fine on the DRM backend.

**Comment by SirCmpwn** [comment]
Nope, does not work on DRM either.

**Comment by acrisci** [comment]
There's nothing in the xwayland code that handles the position of transient windows.

**Comment by emersion** [comment]
Also happens with `gnome-calculator`'s combobox.

**Comment by acrisci** [comment]
I'll have a fix for this today.

**Comment by emersion** [comment]
Can we close this one?
