### ISSUE TITLE
box: questions before stabilization

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#3006]
1. Why does `wlr_box` live in `types/`? Should it live in `util/` instead? Note, we already have a stabilized `types/wlr_matrix.h`, which is similar.
2. Should `wlr_box` members be `int`, `int32_t`, `int64_t`? IMHO, `int` is probably enough.
3. Why do some functions operating on `wlr_box` take `double` arguments? Should we replace these with `int` args?
4. Why does `wlr_box_from_pixman_box32` take a `pixman_box32_t` value, instead of a pointer to it? The Pixman functions take a pointer.
5. Do we really need `wlr_box_rotated_bounds`? If arbitrary rotation isn't going to be a first-class citizen of the wlroots APIs, maybe we should remove it.

References: https://github.com/swaywm/wlroots/issues/1008

**Comment by bl4ckb0ne** [comment]
Should we keep all wayland-related stuff in `/types` and move the internal structs to `/util`? We could maybe move `wlr_surface` to `render` and the `wlr_buffer` related stuff to its own folder?

Regarding `wlr_box` members, I think `int` is enough too. Maybe pass the width/height member to `uin32_t`? Also `wlr_fbox` seems to be only used by the `render_subtexture_with_matrix` function, should we keep it and do the convertion to float internally? 

`wlr_box_from_pixman_box32` and `wlr_box_rotated_bounds` are unused, we could just get rid of it and let the compositor implement it if needed.

**Comment by emersion** [comment]
In general we try to use `types/` for Wayland implementations. Since `wlr_surface` is the implementation for the `wl_surface` interface I'd prefer to keep it in there. Also surfaces aren't just tied to rendering - they affect a lot of others things too, like input and other state.

The `wlr_buffer` things can maybe be split into multiple files, but 500 LoC isn't too bad. It does feel like `wlr_buffer.c` is not very well organized -- because many unrelated things are in there. But let's discuss all of this in a separate issue if need be.

> Maybe pass the width/height member to uin32_t?

I'm always a little concerned about unsigned integers, they're extremely easy to mis-use. The footgun is a `box->x + box->width` away -- if `x` is negative, that expression goes boom.

> wlr_box_from_pixman_box32 and wlr_box_rotated_bounds are unused, we could just get rid of it and let the compositor implement it if needed.

Agreed. `wlr_box_from_pixman_box32` seems to have been introduced in https://github.com/swaywm/wlroots/commit/fa2e6e7d9d5ffbd782063c89e460a915b29d4a58 but it was already unused at this point.

**Comment by bl4ckb0ne** [comment]
I think `wlr_box` should live in `/util` then. 

That's indeed a very dangerous footgun. Pixman does the following for it's box, I don't mind sticking with what we already have.

```c
struct pixman_box32
{
    int32_t x1, y1, x2, y2;
};
```
