### ISSUE TITLE
xdg-desktop-portal-wlr[1465]: 2021/07/01 09:20:43 [ERROR] - config: no config file found

### ISSUE THREAD

**Issue by Crandel** [swaywm/wlroots#3007]
OS: **Arch Linux** 
**wlroots** 0.14.0-1
**xdg-desktop-portal-wlr** 0.4.0-2

After updating to new wlroots version today I got strange error in xdg-desktop-portal-wlr

```
Jul 01 09:20:43 crandel systemd[1134]: Starting Portal service (wlroots implementation)...
Jul 01 09:20:43 crandel xdg-desktop-portal-wlr[1465]: 2021/07/01 09:20:43 [ERROR] - config: no config file found
Jul 01 09:20:43 crandel systemd[1134]: Started Portal service (wlroots implementation).
```

**Comment by emersion** [comment]
We should downgrade this to INFO at least. This isn't an error.

**Comment by emersion** [comment]
Ah, just realized this is the wlroots bug tracker. Please re-open this on the xdg-desktop-portal-wlr bug tracker. Or even better, send a patch to downgrade the log message to INFO.
