### ISSUE TITLE
Wezterm pauses task/command execution when hidden into scratchpad

### ISSUE THREAD

**Issue by Crandel** [swaywm/wlroots#3008]
# Describe the bug

When I hide scratchpad with [wezterm](https://github.com/wez/wezterm) it pause task execution.
For example.

```bash
$ while true; do
date; sleep 1
done
2021-06-18T13:46:37 CEST
2021-06-18T13:46:38 CEST
2021-06-18T13:46:39 CEST
2021-06-18T13:46:40 CEST
2021-06-18T13:46:41 CEST
2021-06-18T13:46:42 CEST
2021-06-18T13:46:43 CEST
2021-06-18T13:46:44 CEST
2021-06-18T14:17:27 CEST
2021-06-18T14:17:28 CEST
2021-06-18T14:17:29 CEST
2021-06-18T14:17:30 CEST
2021-06-18T14:17:31 CEST
```

So `wezterm` paused command execution on `2021-06-18T13:46:44 CEST` and continue on `2021-06-18T14:17:27 CEST`

# Environment

 - **OS**: Arch Linux - Swaywm
 - **shell**: zsh
 - **wlroots** 0.14.0-1
 
# To Reproduce

I emulate quake like behavior with sway build-in scratchpad. [One keybinding](https://github.com/Crandel/home/blob/master/.config/sway/config#L98) toggle show/hide scratchpad, so terminal shows only if it's necessary. I test alacritty and tilix on the same scratchpad and they both works as expected, so issue is not on sway side.
 
 Sway config could be found [here](https://github.com/Crandel/home/blob/master/.config/sway/config)
 
 Wezterm author @wez did some research in related [issue](https://github.com/wez/wezterm/issues/884)

**Comment by emersion** [comment]
Yes, this is expected. The client needs to listen to `wl_surface.frame` callbacks. See https://emersion.fr/blog/2018/wayland-rendering-loop/.
