### ISSUE TITLE
buffer: get rid of wlr_resource_get_buffer_size

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#3015]
The only reason why we have `wlr_resource_get_buffer_size` is that we historically didn't always have a `wlr_buffer` for all types of `wl_buffer` objects coming from clients. With https://github.com/swaywm/wlroots/pull/2708, this time has passed.

I'd like to remove `wlr_resource_get_buffer_size` because it creates duplication with `wlr_client_buffer_import`: both functions need to handle all existing types of `wl_buffer` objects. This will help with enabling third-party `wl_buffer` implementations as well.

A possible plan is:

- Split `wlr_client_buffer_import` into two functions: one that turns a `wl_resource` into a `wlr_buffer` (e.g. named `wlr_buffer_from_resource`), and another that creates a `wlr_client_buffer` from a `wlr_buffer` (e.g. named `wlr_client_buffer_create`).
- In `wlr_surface_state`, add a new `struct wlr_buffer *buffer` field.
- In `surface_state_finalize`:
  - Before anything else, turn the `buffer_resource` into a `wlr_buffer` (via `wlr_buffer_from_resource`).
  - Get the buffer size from the `wlr_buffer`.
- In `surface_apply_damage`, turn the `wlr_buffer` into a `wlr_client_buffer` (via `wlr_client_buffer_create`), then unlock the `wlr_buffer` (so that the `n_locks` check in `wlr_client_buffer_apply_damage` continues to work).

cc @bl4ckb0ne

**Comment by bl4ckb0ne** [comment]
Should we keep the `wlr_client_buffer` API? We could implement third-party `wl_buffer` in `wlr_buffer` and remove a layer of complexity.

**Comment by emersion** [comment]
This issue is just about `wlr_resource_get_buffer_size`, not about the whole `wlr_client_buffer`. One step at a time :)

**Comment by bl4ckb0ne** [comment]
Sorry, got carried away :D

The plan looks good to me, I'll give a go at the implementation.
