### ISSUE TITLE
freezes when using protocol input-method-unstable-v2

### ISSUE THREAD

**Issue by GaZaTu** [swaywm/wlroots#3018]
hi,

i'm using `input-method-unstable-v2` to input text from my application into another.

This works for example with gedit, alacritty and firefox (xwayland mode), but when i do the same with vscode (xwayland), qt apps or firefox (MOZ_ENABLE_WAYLAND=1) then my application just freezes on `wl_display_dispatch`  right after `zwp_input_method_manager_v2_get_input_method`.

Is there any known reason why this is happening?

also: using `text-input-unstable-v3` also makes `wl_display_dispatch` freeze my application (with all apps)

edit: the same thing happens with `text-input-unstable-v3` under KDE Plasma (wayland)

**Comment by emersion** [comment]
This doesn't seem to be a wlroots bug, this seems to be a client bug. If you want help regarding writing Wayland clients, please ask in #wayland on Libera Chat.
