### ISSUE TITLE
Basic wl_shell_client hidden in rootston

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#302]
My basic `wl_shell` client isn't working anymore with rootston: https://gist.github.com/emersion/7e453eb466beb3c2958c042ccf239ba7

It doesn't show up, but the surface is created properly. I think it's a regression related to the change that waits the surface to be fully configured before emitting `wlr_wl_shell.new_surface`.

**Comment by acrisci** [comment]
It shows up for me.

**Comment by emersion** [comment]
Oh, my bad, I tested with a modified version. Sorry.
