### ISSUE TITLE
Rapid window updates result in incorrect frame order in nested Sway sessions

### ISSUE THREAD

**Issue by vyivel** [swaywm/wlroots#3020]
- Sway version: 1.6.1
- Configuration: none/irrelevant (tested with `sway -c /dev/null`)

### Description
Sometimes Sway renders frames out of order when run with a Wayland/X11 backend, resulting in older frames being seen after newer ones. At least, that's what it looks like.

### Reproduction
1) Start Sway
2) Start `weston-terminal` (or any other program capable of updating its window contents rapidly)
3) Hold a key
4) Observe the incorrect rendering order, something like this:
Frame 1: `$ aaaaaaaaaa`
Frame 2: `$ aaaaaa` 
Frame 3: `$ aaaaaaaaaaaaaaaa`

This isn't reproducible with Sway 1.6 or when the DRM backend is used.

### Notes
- This might be a wlroots issue; https://github.com/swaywm/wlroots/commit/543f5b35d02c825347e4a2d6f032ddfa938c3fd7 is the commit that causes this behavior (under Wayland), compiling Sway with a commit before that fixes the problem.
- `-D damage=highlight` has no effect for nested Sway sessions, which may or may not be related to this. Also introduced with the wlroots commit mentioned above.
- It's easier to reproduce this under a high CPU load (can be simulated with `cpulimit -l 1 sway -c /dev/null`).

**Comment by emersion** [comment]
Just to understand the bug buffer, does this wlroots patch help? https://l.sr.ht/qsvv.txt

**Comment by vyivel** [comment]
Nope, the issue persists.

**Comment by emersion** [comment]
Okay, new attempt: https://l.sr.ht/BSq5.txt

If this doesn't work, can you try `-Ddamage=rerender` and see if it helps? The flag disables damage tracking and forces the whole output to be re-rendered each frame.

**Comment by vyivel** [comment]
This patch fixes `-Ddamage=highlight` (seems like nested sessions using `WLR_OUTPUT_STATE_BUFFER_SCANOUT` damage the whole output each frame anyway), but doesn't fix the flickering issue. `-Ddamage=rerender` has no effect.

**Comment by vyivel** [comment]
`wlr_output_damage` doesn't seem to be relevant at all, as the issue is reproducible with tinywl.

**Comment by emersion** [comment]
Thanks for confirming this isn't a damage tracking issue.

Here' yet another attempt: https://l.sr.ht/xcCP.txt. Can you try it? (Sorry, I'm having trouble reproducing reliably.)
