### ISSUE TITLE
Disappearing cursor on multi-GPU setup

### ISSUE THREAD

**Issue by IntinteDAO** [swaywm/wlroots#3030]
- **Sway Version:**
  - sway version 1.6-5cdce42d (Jun 26 2021, branch 'master')

- **Debug Log:**
https://0bin.net/paste/up-swxj-#PJPVTysHFaMxP3QLzyxcJ-EN4sFoSob1FtZtbqIm2FW

- **Configuration File:**
https://0bin.net/paste/eUn83bT7#nkNcFBESXx5ruLKva2F+zyzxJuhy5rw6Bu22csinUPT

- **Description:**
The error is probably due to disabling one monitor (using wdisplays). This causes problems with the cursor not displaying in Sway. Various actions turn it off and on. For example hover the mouse over wofi makes the cursor disappear and running wdisplays makes it come back.

The mouse is on button (it changed a color, but invisible)
![20210627_22h03m11s_grim](https://user-images.githubusercontent.com/56807194/123559385-0e512100-d79c-11eb-8b00-96db2d5efee9.png)

Here the mouse is near the menu, but also invisible)
![20210627_22h03m20s_grim](https://user-images.githubusercontent.com/56807194/123559387-0f824e00-d79c-11eb-9913-e637f3358059.png)

**Comment by emersion** [comment]
Does this wlroots patch help by any chance? https://l.sr.ht/-ZAc.txt

**Comment by IntinteDAO** [comment]
For me - works great! But it's nice to check @nwg-piotr also

**Comment by nwg-piotr** [comment]
> check @nwg-piotr also

I'll check as soon as I'm back  home.

**Comment by nwg-piotr** [comment]
Works for me, too. Great news!

**Comment by emersion** [comment]
Thanks for testing!

**Comment by nwg-piotr** [comment]
Just for curiosity: average CPU load measured on idle in the same conditions. Ryzen 7 + hybrid AMD graphics.

| version  | CPU load | MEM usage |
| ------------- | ------------- | ------------- |
| 0.12.0  | 1.88%  | 490 MiB |
| 0.13.0  | 3.50%  | 435 MiB |
| 0.14.0  | 3.15%  | 433 MiB |
| 0.14.1  | 2.82%  | 435 MiB |
