### ISSUE TITLE
Disappearing windows in Chrome wayland

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/wlroots#3031]
I'm running into a weird issue. I'm using chrome with `--ozone-platform=wayland`. In Chrome Settings I have "On startup" set to "Continue where you left off".

Now, say I have 4 or 5 windows open when I quit Chrome. When I relaunch Chrome not all of the windows appear on screen. Only a couple of the windows are visible. The weird part is that if I have Xwayland running, and then start Chrome, all windows become visible. Note that in both instances Chrome is launched using `--ozone-platform=wayland`.

I'm attaching the log. This log corresponds to when I had 5 windows open prior to quitting Chrome. Upon launch only 2 windows were visible.

[sway.log](https://github.com/swaywm/wlroots/files/6779988/sway.log)

Edit: chrome flags used for launch: `--ignore-gpu-blacklist --enable-gpu-rasterization --enable-native-gpu-memory-buffers --enable-zero-copy --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-accelerated-video-decode=enabled`

**Comment by emersion** [comment]
Anything in dmesg?

**Comment by J0nnyMak0** [comment]
> Anything in dmesg?

Nope. Nothing in dmesg.

**Comment by emersion** [comment]
Can you reproduce with Weston too?

**Comment by J0nnyMak0** [comment]
> Can you reproduce with Weston too?

Haven't tried that. I'll give it a shot.

**Comment by J0nnyMak0** [comment]
Happens on Weston as well.

**Comment by emersion** [comment]
Ah, then sorry, this doesn't look like a wlroots bug. Please report it to nouveau and/or Chromium.

Note, Chromium support for native Wayland is still WIP, so there might be some bugs.
