### ISSUE TITLE
Google Chrome Dev Channel fails to show window

### ISSUE THREAD

**Issue by JordanP-Dev** [swaywm/wlroots#3049]
The latest Google Chrome Dev build (93.0.4573.0) fails to bring up a window in Sway.  I am using Sway 1.6.1 and wlroots 0.14.1.

I get the following error when trying to start it.

`[4113929:4113996:0715/122239.922722:ERROR:wayland_event_watcher.cc(249)] Fatal Wayland communication error: Broken pipe`

It starts properly when running in Weston.  I've attached a log for each with WAYLAND_DEBUG=client set.

[chrome_sway.log](https://github.com/swaywm/wlroots/files/6825447/chrome_sway.log)
[chrome_weston.log](https://github.com/swaywm/wlroots/files/6825448/chrome_weston.log)

I also ran bisect-builds.py to find the build that stopped working, and I think it was probably the following commit: [Fixed server-side decorations on KDE Plasma](https://chromium.googlesource.com/chromium/src/+/93d36f46a1267dda5ecedcf869eb29cd7ba46da5%5E%21/).  The full range of commits in the build are [here](https://chromium.googlesource.com/chromium/src/+log/1b438d4cfe9d601d094fe82e3ad37737ee1a388d..bbc0944b66035a2716e919cb5c896ab12692ba92).

**Comment by kennylevinsen** [comment]
Try a away debug log, and maybe WAYLAND_DEBUG=server on sway.

It's probably chromium making a protocol error. Wouldn't be the first.

**Comment by JordanP-Dev** [comment]
Here is the Sway debug log, with WAYLAND_DEBUG=server set.  It looks like there is an error after an xdg_surface ack_configure with an id of 0.  Is that supposed to have the id from the initial configure (87)?

[sway.log](https://github.com/swaywm/wlroots/files/6852500/sway.log)

**Comment by kennylevinsen** [comment]
> Is that supposed to have the id from the initial configure (87)?

It must have the ID of the specific configure it is ACKing, which must only be ACKed once. Note that ACKing a later configure event implies ACK of previous ones.

**Comment by JordanP-Dev** [comment]
This has been fixed in the current dev build and should be in the next beta build of Chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=1231526#c24
