### ISSUE TITLE
Steam GUI/Chromium freeze/super slow on launch

### ISSUE THREAD

**Issue by shoober420** [swaywm/wlroots#3060]
When compiling the current master as of this post (https://github.com/swaywm/wlroots/commit/66c42f4fcb77724d9b19829eeb0c66fe4771f2db), the main Steam GUI and Chromium completely freeze or are super slow when trying use. I have the log attached.

[sway.log](https://github.com/swaywm/wlroots/files/6858849/sway.log)

**Comment by shoober420** [comment]
I've bisected from https://github.com/swaywm/wlroots/commit/a47f89cf7c198153c153c53f52d42810e1c73ed5 and still have the issue. Is this an issue with sway not wlroots? I've downgraded both wlroots and sway on twoachines and the bug disappeared.

**Comment by fluix-dev** [comment]
> Is this an issue with sway not wlroots?

The conclusive way to check is to try other compositors that still use wlroots like Wayfire.

**Comment by shoober420** [comment]
It appears that when reinstalling sway and launching steam, it works the first time, then closing steam and relaunching thereafter will trigger the behavior. this bug must lie elsewhere in another lib.
