### ISSUE TITLE
Direct scanout not working because clients choose incompatible modifier

### ISSUE THREAD

**Issue by nowrep** [swaywm/wlroots#3066]
Direct scan-out isn't working because clients will always choose modifier incompatible with scanout on my system. Tested with XWayland and native Vulkan clients.
Hardcoding supported modifiers in `types/wlr_linux_dmabuf_v1.c linux_dmabuf_send_modifiers` will make it work.

Should wlr_linux_dmabuf only advertise formats/modifiers supported by scanout?

RX 6700XT, 5.13.4-zen1-1-zen, mesa 21.1.5-1, vulkan-radeon 21.1.5-1, xorg-xwayland 21.1.2-1

**Comment by emersion** [comment]
> Should wlr_linux_dmabuf only advertise formats/modifiers supported by scanout?

This won't cut it, because this will prevent non-fullscreen clients from using more optimized modifiers.

The plan is the following: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/8
