### ISSUE TITLE
wlroots and seatd as subprojects causes multiple definitions error 

### ISSUE THREAD

**Issue by dylanaraps** [swaywm/wlroots#3072]
### Expected behavior:

Everything builds without error.

### Actual behavior:

```
log.c:11: multiple definition of `NSEC_PER_SEC'; subprojects/wlroots/libwlroots.a(util_time.c.o):/home/dylan/.cache/kiss/proc/20779/build/sway-tiny/build/../subprojects/wlroots/util/time.c:7: first defined here
collect2: error: ld returned 1 exit status
```

### Workaround:

```
# Remove conflict between static libseat and wlroots.
# Workaround can also be applied to wlroots rather than seatd.
sed 's/\(const long NSEC\)/static \1/' \
    subprojects/seatd/common/log.c > _ 
mv -f _ subprojects/seatd/common/log.c
```

The conflict is between wlroots and libseat.  Was not sure where to open this issue. 
Let me know if I should open this elsewhere. This is with latest master for wlroots,
sway and seatd.

**Comment by emersion** [comment]
Can you send a PR to make the definition `static`? It doesn't seem like the values are used elsewhere.
