### ISSUE TITLE
Add a helper to dump surface tree state

### ISSUE THREAD

**Issue by vyivel** [swaywm/wlroots#3094]
Ref: https://github.com/swaywm/wlroots/issues/2957

>For the purposes of wl_subsurface, the upcoming transactions protocol and explicit sync, we've recently introduced wlr_surface_lock_pending and wlr_surface_unlock_cached. With a few additions, I believe compositors could use these functions to implement atomic transactions.
>
>The benefit is reduced complexity in compositors: they won't need to manually save the whole surface tree state and buffers anymore.

After some attempts to use surface locking for atomic layout updates in Sway and my own compositor, I came to the conclusion that it's not the best available option. There are functions which use current surface state (e.g. `wlr_xdg_surface_get_geometry()`), and the pending state is labeled as "internal", i.e. not meant to be used by compositors directly. In general, I think this approach is too complex for the problems it attempts to solve.

With that said, I believe a better solution would be preserving the way Sway works now, saving the buffers and rendering them, but moving the logic for that to wlroots. For example, a hypothetical `wlr_surface_dump_state()` function could provide a phony `wlr_surface` with a `NULL` resource, which then could be used for rendering.

**Comment by emersion** [comment]
This has been discussed with @ammen99 previously.

Can you expand on your proposal? How would the surface be aware of all of the add-on state it needs to duplicate? How do compositors swap the surface pointers? Why is `wlr_xdg_surface_get_geometry` operating on current state an issue? How is this proposal less complicated?

**Comment by emersion** [comment]
Note, for the purposes of sub-surfaces + explicit sync +upcoming transactions protocol, we'll still need to wire up the cache logic in e.g. xdg-shell, xdg-decoration, layer-shell, etc.

**Comment by vyivel** [comment]
>How would the surface be aware of all of the add-on state it needs to duplicate?

The helper would create surfaces only usable for rendering. Everything that is required for that is stored in `wlr_surface` itself.

>How do compositors swap the surface pointers?

Sorry, not sure what you mean. I don't think there is a need to swap anything.

>Why is wlr_xdg_surface_get_geometry operating on current state an issue?

https://github.com/swaywm/wlroots/pull/3068#issuecomment-893558337

It's not *that* much of an issue and it's not even *that* related, but it's still a bit unintuitive.

>How is this proposal less complicated?

Implementation-wise, I think? This proposal would require minimal changes to how Sway handles transactions.

Note that I don't suggest this *instead* of surface addon state caching. Both of these can be implemented.

**Comment by emersion** [comment]
> Sorry, not sure what you mean. I don't think there is a need to swap anything.

Sway uses `wlr_surface` for many things. So we'd need to teach Sway to use a temporary, different `wlr_surface` when a transaction is in progress.

> Implementation-wise, I think? This proposal would require minimal changes to how Sway handles transactions.

Ah, so you mean it would require less changes to Sway? Or do you mean that the resulting code will be less complicated overall?

I'd prefer to avoid ending up with two ways of doing the same thing if possible. And ending up with the best design, even if it means more changes to existing compositors like Sway. But it may very well be that surface caching isn't the right tool for this job.

---

Sorry, I don't think I understand your proposal fully.

**Comment by vyivel** [comment]
>So we'd need to teach Sway to use a temporary, different wlr_surface when a transaction is in progress.

Not really. We could have something like this:

```c
struct sway_view {
	struct wlr_surface *surface;
	struct wlr_surface *displayed_surface;
	...
};

static void render_view_toplevels(struct sway_view *view,
		struct sway_output *output, pixman_region32_t *damage, float alpha) {
	...
	if (view->displayed_surface) {
		output_surface_for_each_surface(output, view->displayed_surface, ox, oy,
			render_surface_iterator, &data);
	} else {
		output_surface_for_each_surface(output, view->surface, ox, oy,
			render_surface_iterator, &data);
	}
}
```

Basically, replace `struct wl_list saved_buffers` with `struct wlr_surface *displayed_surface`.

**Comment by vyivel** [comment]
With https://github.com/swaywm/wlroots/pull/3143 merged, `wlr_surface_state` will be complete enough to be saved instead of `wlr_surface`. However, this whole proposal is probably useless by now as compositors would rather create scene nodes with saved buffers instead and render them.
