### ISSUE TITLE
[render/allocator/gbm.c:63] gbm_bo_get_fd failed

### ISSUE THREAD

**Issue by jbeich** [swaywm/wlroots#3156]
Regressed by #3153. Starting Sway on DRM console hangs without leaving console (Ctrl+Alt+Fn works fine). Tested on FreeBSD with i915 ported from Linux 5.4.92.

From [debug log](https://github.com/swaywm/wlroots/files/7096553/sway.log):
```diff
 [DEBUG] [wlr] [types/wlr_output.c:689] Attaching empty buffer to output for modeset
 [DEBUG] [wlr] [types/wlr_output.c:524] Choosing primary buffer format 0x34325241 for output 'DP-1'
 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
-[DEBUG] [wlr] [render/allocator/gbm.c:129] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0x100000000000004)
-[DEBUG] [wlr] [render/gles2/renderer.c:143] Created GL FBO for buffer 3840x2160
-[DEBUG] [sway/config/output.c:346] Output DPI: 162.560000x161.364706
+[ERROR] [wlr] [render/allocator/gbm.c:63] gbm_bo_get_fd failed
+[ERROR] [wlr] [render/swapchain.c:109] Failed to allocate buffer
+[DEBUG] [sway/config/output.c:388] Preferred mode rejected, falling back to another mode
+[DEBUG] [wlr] [backend/drm/drm.c:464] connector DP-1: Can't enable an output without a buffer
```

**Comment by emersion** [comment]
Hm, weird. Seems like the buffer was successfully created but *something* prevents it from being exported as a DMA-BUF… Is there anything in `dmesg`?

**Comment by emersion** [comment]
Please also try enabling the bit 0x08 in the DRM logs (https://github.com/swaywm/wlroots/wiki/DRM-Debugging).

**Comment by jbeich** [comment]
dmesg shows nothing from kernel, even after `sysctl hw.dri.debug=0x08`.

[DRM debug log](https://github.com/swaywm/wlroots/files/7099872/sway.drm-debug.log) with every bit enabled.

**Comment by emersion** [comment]
Hm, `DRM_IOCTL_PRIME_HANDLE_TO_FD` fails with `EACCES` it seems. May be due to the use of a primary node without authentication.

**Comment by jbeich** [comment]
On FreeBSD devices of the same type may have different major numbers which may confuse DRM authentication.
```
$ ls -lL /dev/dri
total 0
crw-rw----  1 root  video   0x95  2 Sep 05:47 card0
crw-rw----  1 root  video  0x174  2 Sep 05:47 renderD128

$ major() { echo $(( (($1 >> 32) & 0xffffff00) | (($1 >> 8) & 0xff) )) }
$ major 0x95
0
$ major 0x174
1
```

**Comment by emersion** [comment]
Can you try this?

https://github.com/swaywm/wlroots/pull/3163

**Comment by jbeich** [comment]
I confirm, works fine after applying #3163. `sway -dc /dev/null` doesn't show errors anymore.
