### ISSUE TITLE
Remove unused user data properties on wlr interface structs

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#316]
Lots of the wlr interface structs have user data properties. Maybe at one time we thought they were necessary, but now that we are farther along with the reference compositor, we are finding that they are never used.

We should probably just get rid of them.

**Comment by SirCmpwn** [comment]
I'm pretty sure @Timidger needs them

**Comment by SirCmpwn** [comment]
Also, we are using them in several places in rootston.

**Comment by Timidger** [comment]
Yes they would be very helpful to have for my bindings (as as @SirCmpwn mentioned it's used in rootson)
