### ISSUE TITLE
Assertion failed: (resource && wlr_resource_is_buffer(resource)), function wlr_buffer_from_resource, file types/wlr_buffer.c, line 198.

### ISSUE THREAD

**Issue by jbeich** [swaywm/wlroots#3173]
Regressed by ba0525c5c08b. Steps to reproduce:
```
$ echo "exec sleep 0.3 && foot -d none -c /dev/null sh -c 'sleep 0.3 && exit'" >/tmp/sway.conf
$ sway -c /tmp/sway.conf
Assertion failed: (resource && wlr_resource_is_buffer(resource)), function wlr_buffer_from_resource, file types/wlr_buffer.c, line 198.
```

See also [debug log](https://github.com/swaywm/wlroots/files/7118124/sway.log)

**Comment by emersion** [comment]
For some reason I'm not able to reproduce. Can you try https://github.com/swaywm/wlroots/pull/3174?

**Comment by tsdh** [comment]
@emersion Your commit 913dcdc1e649fa99eb1a42ad9694b9e3e9ffab4f fixes the issue for me.  Sway starts again.

**Comment by jbeich** [comment]
I confirm, sway doesn't crash after applying #3174.

**Comment by emersion** [comment]
Thanks for testing!
