### ISSUE TITLE
Examples not working in DRM

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots#321]
The examples (all non-rootson ones) are no longer working on my machine (tested on master). I did a bisect, and found the culprit is one of these commits:

```
1d716241afbc721c3ae65d4a2bb0e25866fe081c
c03e7746367194b859125624b059c1725eb7ae30
e1f196a3e9477385ca30180686cda82e3ab735ce
```

It's hard to say because they don't actually build.

The one that _doesn't_ work is `e1f196a` and the last one that _does_ is `bde25fe`

Here's a diff from `e1f196a` to `bde25fe`: https://pastebin.com/jfTyrvyd

EDIT: Sorry hit "enter" before it completed. Stupid vim plugin

EDIT X2: From the logs looks like this was when `wl_list` was used instead in the DRM stuff. Probably an issue somewhere where it's mis-used. Probably shouldn't be hard to find.

**Comment by SirCmpwn** [comment]
I think there's a typo here? Anyway, which backends are affected? I can still use the rotation example under wayland and I tried it on drm a few days ago.

**Comment by Timidger** [comment]
All of them (save rootson) are affected. I tried this for all of them including rotation. They work under Wayland and X

**Comment by SirCmpwn** [comment]
Thanks. Are you taking a look?

**Comment by Timidger** [comment]
I'm looking into it, but I probably won't get very far since I don't know the codebase very well (and the DRM less so). I posted it here in case others can beat me to it.

I first noticed it while working on my Rust bindings, took me a while before I realized it's not my code that's causing the issue necessarily.

**Comment by SirCmpwn** [comment]
It sounds like a great chance for you to become familiar with the codebase :) I don't think this is so urgent that we can't wait for you to sort it.
