### ISSUE TITLE
[regression, bisected] Rendering problems using multi-gpu

### ISSUE THREAD

**Issue by manio** [swaywm/wlroots#3217]
Hi!
With recent wlroots the rendering on multi-gpu started to not working flawless. I can see that the cursor is moving "choppy", same with other rendered elements besides cursor - all windows and eg video playback.
It is very clearly visible when moving the cursor. I don't know if I describe it well - but it seems like the FPS is very low.

I was using old sway and wlroot versions for longer period but it's time to bisect the problem, so I prepared the testing environment and started to bisecting wlroots. After some time I found the first bad commit:
```
91cb0fc4432592a8c0806d3e63dc77ce16c73cb6 is the first bad commit
commit 91cb0fc4432592a8c0806d3e63dc77ce16c73cb6
Author: Simon Ser <...>
Date:   Tue Dec 22 18:23:28 2020 +0100

    backend/drm: only keep track of local buffer

    Stop keeping track of buffers on the parent GPU when multi-GPU is used.

    This removes support for export_dmabuf on secondary GPUs, but renderer
    v6 will bring this back by managing the swapchains in wlr_output instead
    of the backends.

 backend/drm/drm.c              |  6 +++++-
 backend/drm/renderer.c         | 10 +++-------
 include/backend/drm/renderer.h |  4 +---
 3 files changed, 9 insertions(+), 11 deletions(-)
```
This commit starts the regression, after this commit the rendering is not flawless.
I was trying to revert this commit on top of 0.14.1 but I gave up because of conflicts which I cannot resolve :(
Can you please provide me some revert patch which I can test?

Details:
Multi-gpu system, Arch Linux.
When upgrading from sway sway-1:1.5.1-2 to sway-1:1.6-1 and wlroots-0.12.0-1 to wlroots-0.13.0-1 problems started to happen. 
Most recent wlroots and sway packages has the same problem.

**Comment by kennylevinsen** [comment]
Please provide the full debug output from sway as well as information about your system.

> Can you please provide me some revert patch which I can test?

We don't intend to just revert the patch.

**Comment by manio** [comment]
> Please provide the full debug output from sway as well as information about your system.

Sure
Log from 5bd86b94 (working OK): https://skyboo.net/temp/sway/log_5bd86b94.log
Log from 91cb0fc4 (bad rendering): https://skyboo.net/temp/sway/log_91cb0fc4.log

System: Arch Linux x86_64, 3 GPU (radeon, NVIDIA GT216, NVIDIA G96), 5 displays (monitor configuration is in the log)

**Comment by J0nnyMak0** [comment]
@manio that regression was fixed with https://github.com/swaywm/wlroots/commit/ebb661532c57bf5c44301b03602abd2cd30f794f
Are you using latest sources?

**Comment by manio** [comment]
Ooops... I indeed didn't test it with greater version then 0.14.1 as that is the latest package for Arch currently. I wrongly assumed that if the bug is in v0.13 and v0.14 than it is also in recent master. My bad!

So I just build the recent master of sway and wlroots and indeed this bug is now gone!

@J0nnyMak0 thank you very much!
Big sorry for all this confusion and time spent on this :(

It's great that it is now working properly!
Closing.

**Comment by Zeioth** [comment]
I experience exactly the same issue as OP. Screens connected to the 2º GPU are choppy and feel like refresh rate is half of the expected. It is very clearly visible when moving the cursor. On the screens attached to the main GPU everything seem fine thouhg. I tried with 'wlroots-git' and 'sway-git', but no luck.

Both AMD GPU (RX 6700 XT and XT 550).

**Comment by manio** [comment]
I just give it another try after @Zeioth response. In my case I cannot see this problem. Using all 3 GPU involved I have a fluent rendering, widow movement across all displays and cursor movement... Maybe it is related to something else...
