### ISSUE TITLE
How does wlroots compare with smithay?

### ISSUE THREAD

**Issue by Joe23232** [swaywm/wlroots#3248]
Hey guys I am a bit confused what is the difference between `wlroots` and [`smithay`](https://github.com/Smithay/smithay)?

**Comment by DemiMarie** [comment]
Main difference is the programming language.  wlroots is written in C while Smithay is written in Rust.  wlroots is currently significantly more mature than Smithay at this time, though this will hopefully change someday.  Right now, wlroots is used in at least two production compositors (Sway and KWinFT), while Smithay is not used in any that I am aware of.

**Comment by Joe23232** [comment]
Right I see thanks mate.

Another question would be that if I were to make my own tiling wm using wlroots, how difficult would it be?
