### ISSUE TITLE
Rootston: configure keymap per keyboard

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#326]
The rootston config should be able to configure a keymap for each keyboard in the keyboard config separately.

**Comment by emersion** [comment]
```
input "some keyboard" {
    options "caps:escape"
    layout "us,de"
}
```

**Comment by SirCmpwn** [comment]
That's the sway syntax. The rootston stuff should just be some ini shit.

**Comment by emersion** [comment]
Yeah, I was just posting this for reference. Rootston's will look like:

```
[input:some keyboard]
options = caps:escape
layout = us,de
```
