### ISSUE TITLE
Reachable assertion in buffer handling

### ISSUE THREAD

**Issue by DemiMarie** [swaywm/wlroots#3260]
wlroots commit 2edf468aeb7d4703aa211cea3b58f04cbc73298c runs the following code every time a new buffer is submitted:

https://github.com/swaywm/wlroots/blob/2edf468aeb7d4703aa211cea3b58f04cbc73298c/types/wlr_surface.c#L58-L59

But if this is called enough times with the same buffer, it will cause a crash:

https://github.com/swaywm/wlroots/blob/2edf468aeb7d4703aa211cea3b58f04cbc73298c/types/wlr_buffer.c#L55-L61

**Comment by vyivel** [comment]
In that function, `buffer` is a `wlr_buffer_from_resource()` call result:

https://github.com/swaywm/wlroots/blob/2edf468aeb7d4703aa211cea3b58f04cbc73298c/types/wlr_surface.c#L45-L52

`wlr_buffer_from_resource()` locks the buffer before returning:

https://github.com/swaywm/wlroots/blob/2edf468aeb7d4703aa211cea3b58f04cbc73298c/types/wlr_buffer.c#L197-L235

As a result, attaching the same buffer should lock it and then unlock it, causing no `n_locks` change.

Do you have a stack trace?

**Comment by DemiMarie** [comment]
Nope, closing.
