### ISSUE TITLE
Firefox Nightly with with Wayland compositing force enable will crash on launch (Vulkan)

### ISSUE THREAD

**Issue by pravinxor** [swaywm/wlroots#3280]
Flags: gfx.webrender.compositor true and gfx.webrender.compositor.force-enabled true causes firefox nightly to crash with 

Nightly version 95.0a1 (2021-10-20) (64-bit)

ExceptionHandler::GenerateDump cloned child 12841
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
Exiting due to channel error.

This issue only occurs with WLR_RENDERER=vulkan and worked fine with the previous backend

**Comment by pravindoesstuff** [comment]
https://crash-stats.mozilla.org/report/index/7c79e603-2541-4038-87a9-4f9850211020
