### ISSUE TITLE
XWayland pointer bound to first received mode

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#330]
1. Launch the Wayland backend
2. Resize the rootston window to make it bigger
3. Launch a X11 app
4. Pointer events work well in the initial window size box, but don't outside

**Comment by emersion** [comment]
Note that `xrandr` prints the original window size too.

**Comment by emersion** [comment]
Had a look at Weston's XWayland code. It cannot change output configuration dynamically, so we can't really learn things from it.

**Comment by SirCmpwn** [comment]
I think we need to create new modes from the ether and send them along.

**Comment by emersion** [comment]
We already do that.

**Comment by SirCmpwn** [comment]
Whelp
