### ISSUE TITLE
wlroots 0.15.0 issue

### ISSUE THREAD

**Issue by stpnwf** [swaywm/wlroots#3317]
I am following [this tutorial](https://llandy3d.github.io/sway-on-ubuntu/simple_install/) to install Sway on my Ubuntu machine.

But I am running into a problem where I am unable to meson build sway because I get this error:

`meson.build:74:1: ERROR: Invalid version of dependency, need 'wlroots' ['>=0.15.0'] found '0.12.0'.`

I used 0.12.0 because that is what the tutorial used, but when I tried to `git checkout` to the latest version I saw that 0.15.0 is [still unreleased](https://github.com/swaywm/wlroots/issues/2983). 
So how can I carry on with the installation? Am I doing something wrong?

**Comment by ifreund** [comment]
The master branch of sway requires the master branch of wlroots. If you want to build the master branch of sway you'll need to build the master branch of wlroots from source as well.

**Comment by stpnwf** [comment]
Sorry, I am under the implession I did just that though. Should I have git cloned another repo other than https://github.com/swaywm/wlroots? 
I did build version 0.12.0. But to build sway, it says, I need 0.15.0. which doesn't exist.

**Comment by ifreund** [comment]
The master branch of this repository is the not yet released wlroots 0.15.0. It appears that "tutorial" you linked instructed you to check out the `0.12.0` tag for some unknown reason. Run `git checkout master` in the wlroots repo and try again.

Also, I'd recommend not blindly trusting tutorials for this reason, instead refer to the official docs :)

**Comment by stpnwf** [comment]
I think that worked. Now I must figure out the error about meson not being in /usr/bin/

Thank you, it is the first time I compile from source. Checking out the official docs now. Again thanks for your help though!
