### ISSUE TITLE
rootston's force drag/resize does not work if Logo is a compose key

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#339]
Here come the particularities :D

I'm using `XKB_DEFAULT_OPTIONS=compose:lwin` so I'm configuring rootston to use Alt (or Alt_L? something's confusing about these two, not always seem interchangeable I need to dig that up as well ; I also managed to get alt stuck in rootston state machine so just pressing Return would spawn a new shell.. can't reproduce now, need to figure what it is I was doing)

Once you do that you are no longer able to move/resize window with Logo + drag
I fired up 'xev' and it does get Multi_key up/down events, just doesn't seem interpreted by rootston anymore.

**Comment by panaman67** [comment]
@martinetd Can close as rootston is archived?
