### ISSUE TITLE
Multiseat support in rootston

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#350]
The [wl-seat](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_seat) is a global that represents a group of input devices.

> A seat is a group of keyboards, pointer and touch devices. This object is published as a global during start up, or when such a device is hot plugged. A seat typically has a pointer and maintains a keyboard focus and a pointer focus.

There can be more than one seat global published on the server that window clients can bind to to receive events for the seat.

If this sounds appealing to you and you would like to do something with it, I would like to hear you explain your use case in this issue.

Example:

The design metaphor goes like this. Imagine there are two seats in front of your computer with people sitting in them. Each person has their own keyboard and mouse. Multiseat allows both the people to use their devices independently of each other. For example, we can both type into different windows at the same time (multiple keyboard focus) and control two cursors that appear in different locations on the screen and have a different window focused.

Some compositors may choose not to support multiseat because it is a niche use case and simplifying things will make their code more understandable.

Required:

* Associate input devices with seats (by name) in the rootston config
* Refactor all input-related functions (such as interactive resize/move) with seats
* Remove the assumption of a single focused window
* Test all existing wlroots interfaces that use the seat interface to make sure they work with multiseat

**Comment by emersion** [comment]
>Refactor all input-related functions (such as interactive resize/move) with seats

I've assumed so far that one `roots_input` is one seat, am I wrong? If so, resize/move shouldn't require a refactor.

**Comment by emersion** [comment]
We'll also have issues with hardware cursors: there can be only one hardware cursor per output at a time.

**Comment by acrisci** [comment]
> I've assumed so far that one roots_input is one seat, am I wrong?

This seems like the intent. The cursor parameter in both these functions needs to be assumed to be the cursor for that input.

**Comment by SirCmpwn** [comment]
It's just the main container for all input-related state in rootston. There should only be one of them.

**Comment by emersion** [comment]
>It's just the main container for all input-related state in rootston. There should only be one of them.

I'm looking at all the fields and all of them seem more seat-related than related to a global input state (apart from `xcursor_theme` maybe).

**Comment by acrisci** [comment]
There is a concept of a seat in udev, but I'm beginning to think it's a different concept because it doesn't appear to be possible to have more than one seat per session.

If you look up the common [multiseat](https://en.wikipedia.org/wiki/Multiseat_configuration) definition, it is nothing like the interface that is given by `wl_seat`. This seems to be more for multiple sessions on the same computer for running separate instances of the compositor. In the udev "seat" concept, seats do not share outputs while multiple `wl_seats` would because seats are not associated with outputs.

I don't think these concepts (if they are actually meant to be different) are incompatible with each other. You could have multiple session seats with multiple `wl_seats` and it should work just fine. The session seat you are running the current instance of wlroots on would not have visibility of inputs assigned to a different udev seat.

More research probably needs to be done on this, but I think the feature as I've outlined it above is possible, and it would be a pretty cool feature to have. Gtk will bind to multiple seats and listen to input on all of them. Now I need to test if it will listen to input on seats simultaneously which I will do now.

So we'll do seat configuration in rootston and ignore the udev seat concept for now and see how it goes. Device config will now have a "seat" member that sets the name of the `wl_seat` the device belongs to. Whenever an input device is added, we'll create a global for the seat name if it doesn't already exist and associate that device with the seat. The default seat is called "seat0".

When a device is removed, if there are no input devices plugged in associated with the seat, we'll destroy the global.

Let's see how this goes. I think there's a chance this won't work at all but we might as well try.

**Comment by acrisci** [comment]
One more thing to note is that multiseat will not work at all with xwayland windows because the xwayland input model does not support it and is not seat aware. You can only have one window focused at a time in xwayland, while in this input model you will have one focused window per seat.

**Comment by emersion** [comment]
>One more thing to note is that multiseat will not work at all with xwayland windows

What happens in GNOME is that XWayland windows are responsive only to the first seat, all other seats inputs are ignored. This is a little annoying: because of this, tablet tools are ignored by XWayland drawing apps. Is there a way to use the last seat that focused a XWayland surface as the XWayland seat?

**Comment by acrisci** [comment]
That's actually quite a workaround because then a seat has to route its input to another seat depending on the view type which somewhat breaks the intended encapsulation of the seat and it still doesn't fix the main issue which is that xwayland windows are not seat aware.

Raise the issue with xwayland. If it's a simple matter of having the windows listen for events on all the seats it shouldn't be hard to fix.

**Comment by emersion** [comment]
>If it's a simple matter of having the windows listen for events on all the seats it shouldn't be hard to fix.

That's a better idea actually, I somewhat thought this wouldn't be possible.
