### ISSUE TITLE
Draw multiple cursors per output

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#351]
Multiseat (#350) requires to draw potentially multiple cursors on the same output. The current API isn't designed for this, as an output can only draw zero or one cursor. That's because of hardware cursors: no more than one hardware cursor can be set per output (if hardware cursors are supported).

The functions affected are:
* `wlr_output_set_cursor` and `wlr_output_set_cursor_surface`
* `wlr_output_move_cursor`

A first question is: do we want to support drawing multiple cursors in `wlr_output` or in `wlr_cursor`? Currently it's possible to draw and move a cursor without `wlr_cursor` (see `examples/pointer.c`). Also, currently the `wlr_cursor` is responsible for moving the cursor on the output.

We could either:
1. Add support for multiple cursors per output in `wlr_output`. We'll need a `wlr_output_cursor_create(struct wlr_output *)` function that returns a new cursor for that output, and `wlr_output_cursor_{move,set_image}` functions to move and set its image.
2. Add support for multiple cursors per output in `wlr_cursor`. We'll just need to add a `wlr_cursor_set_image` function and `wlr_output` will be responsible for moving _and_ drawing the cursor.

Note that we can add `wlr_cursor_set_image` even with solution 1 to make things more easy for compositors. Also, solution 2 dangerously ties `wlr_output` to `wlr_cursor`: it won't be possible to use `wlr_output` without `wlr_cursor` anymore.

**Comment by Timidger** [comment]
The first solution seems better to me. It's conceptually simpler, keeps outputs separate from cursors, and would be easier to wrap in wlroots-rs (since the ownership is more straightforward, with a cursor being owned by an output)
