### ISSUE TITLE
Cross cursors in GTK on XWayland

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#369]
![screenshot from 2017-11-01 17-12-21](https://user-images.githubusercontent.com/506932/32284566-ef3bf352-bf27-11e7-8909-90ea5ad6be55.png)

Over the textarea, the carret cursor is used correctly.

**Comment by SirCmpwn** [comment]
I see this on urxvt a lot too.

**Comment by acrisci** [comment]
Yeah I think we have to load the cursor theme.

**Comment by emersion** [comment]
We need to load the root cursor with `XCB_CW_CURSOR`.
