### ISSUE TITLE
Right click copy/paste in weston-terminal not working

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#370]
Keybindings to copy/paste work correctly, but not the right click menu. Not sure if this is a weston-terminal bug or a wlroots bug.

**Comment by SirCmpwn** [comment]
Trying to reproduce this in sway crashed sway for me!

**Comment by emersion** [comment]
In GNOME it crashes `weston-terminal` with `listener function for opcode 5 of wl_data_source is NULL`.

**Comment by SirCmpwn** [comment]
If it doesn't work in wlroots, weston, *or* GNOME then it's definitely not our problem.
