### ISSUE TITLE
Transcient windows hidden under their parent

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#373]
1. Open Gedit
2. Write something
3. Close Gedit, this shows a dialog that asks to save before closing
4. Click on the parent
5. You end up in a state where the parent is focused, but you can't move it because it has a child, and the child is hidden under the parent. Pointer events are not sent to the parent, so you can't do anything.

**Comment by acrisci** [comment]
What shell?

**Comment by emersion** [comment]
Gedit, so xdg-shell.

**Comment by acrisci** [comment]
What does Weston do?

**Comment by emersion** [comment]
Weston also has this bug. GNOME prevents dialogs from being hidden behind their parent.

**Comment by acrisci** [comment]
File the bug with gtk. There is no parent child relationship with xdg-toplevel.

**Comment by emersion** [comment]
What about https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-shell/xdg-shell-unstable-v6.xml#L533 ?

**Comment by acrisci** [comment]
Oh I forgot about that. That will probably do it.

**Comment by abdelq** [comment]
What's exactly the wanted behaviour? Preventing dialogs from being hidden like GNOME?
