### ISSUE TITLE
Allow compositors to do not call wlr_output_swap_buffers

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#375]
Compositors right now have to call `wlr_output_swap_buffers` even if the output is not damaged because software cursors are rendered during this step. We should add a way for compositors to detect when they don't need to call `wlr_output_swap_buffers`.

Software cursors need to be rendered again when they move or when their image is updated. Hardware cursors never need to be rendered.

A few possible solutions:
1. Add a `damaged` signal to `wlr_output`, compositors can listen to it and schedule a `swap_buffers` call
2. Add a `bool damaged` field to `wlr_output`, compositors can check it before calling `swap_buffers`
3. Add a `bool wlr_output_render_cursors` function that needs to be called by the compositor to render software cursors, and returns `true` if the output becomes damaged. This has the upside of removing software cursor rendering from `swap_buffers` (and let the compositor do it whenever it wants to), but also requires compositors to do one more thing.

Related to #190.

**Comment by SirCmpwn** [comment]
```c
bool wlr_output_needs_swap(struct wlr_output *output);
```

**Comment by emersion** [comment]
The downside of your solution is that we need to keep a state anyway: if there are software cursors, we don't always need to render them (ie. if they don't move and their image isn't updated). So we'll need a field in `wlr_output` anyway.

**Comment by SirCmpwn** [comment]
I think that's more of an implementation detail than a downside.

**Comment by emersion** [comment]
Sure, what I'm saying is that it would be simpler to just add a `bool needs_swap` field to the struct. Adding a new function doesn't add value.

**Comment by SirCmpwn** [comment]
Alright, w/e.
