### ISSUE TITLE
Resizing from the top-left corner is laggy

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#386]
Try to resize from the top-left corner, the view is moved before being resized by the client.

To fix this in xdg-shell, we should wait for an `ack_configure` event from the client. To do this, we need to save the position we want to move the surface to when sending the `configure` event, and read it when receiving `ack_configure`.

So far, I've tried two ways of doing it:

1. Adding a list of configure request states in rootston. However, configure requests are scheduled, so after calling `wlr_xdg_toplevel_v6_set_size` there's no way of guessing the serial that will be used when sending the configure request. This could be fixed by assigning the serial when calling `wlr_xdg_toplevel_v6_set_size` (if not already assigned).
2. Adding a `void *data` field to `wlr_xdg_toplevel_v6_state`. This is appealing because it simplifies a lot rootston (no need to maintain a list of configure requests since wlroots already does it). However, I'm not sure about memory management. Since the client is required to acknowledge only the last configure request, some can be discarded.

@acrisci Thoughts?

**Comment by acrisci** [comment]
I'll give some thoughts without actually looking at the code in depth so this may or may not actually be good advice.

Try not to involve the xdg-toplevel protocol events at all if it's possible. The configure structs are intended for internal use.

When the resize begins, listen to `surface.commit`. Don't actually move the view until it commits with a different sized window geometry. Determine the new location based on the change in window geometry. For instance, if the geometry width shrunk by 10 and it's a left resize, add 10 to the x view coordinate.

**Comment by martinetd** [comment]
Haven't looked either, but I don't see why the `pending.width`, `pending.height` etc aren't enough. Couldn't we just use/have `pending.x` and `pending.y` as well, and apply them on ack_configure?

**Comment by acrisci** [comment]
The x/y coordinates are intentionally not a concern for wlroots. They are under the control of the view implementation of the compositor. This is one of our fundamental differences in design from Weston.

The Wayland surface protocol is mostly unaware of the layout. We have x/y coordinates set on attach relative to the buffer which are used for some protocols, but that's it for positioning.

The surface `width`/`height` are the width and height of the buffer which can differ from window geometry. If you use those in the calculation, you may not get the resize right because the buffer extents may include shadows if the surface changes its shadows in response to the resize event (unlikely, but possible).

All of that chatter for the configure events are not important. The real state of the surface is determined when the surface is committed.

**Comment by emersion** [comment]
So I wanted to use the ack_configure signal to only change the view position for configure requests sent when resizing a window.

I don't know if changing the view position when the surface is committed will work. Imagine:

1. A configure request is sent because the user resizes the window
2. Another configure request is sent because the user continues to resize the window
3. The first configure event is taken into account by the client, a new surface is committed
4. The view is incorrectly moved by the compositor

Also some apps a not resizable, so they could send an ack_configure without commiting a new surface.

**Comment by acrisci** [comment]
At the `surface.commit` event, this is the only time when any of the properties of the surface are valid for the current state. At any other time, they are in the process of being negotiated by the protocol. Rootston should not nose its way into the protocol to try to predict what might happen when a commit actually occurs.

> Also some apps a not resizable, so they could send an ack_configure without commiting a new surface.

Great. If the surface is not resized, then it shouldn't be moved.

**Comment by emersion** [comment]
Oh, I think I misunderstood ack_configure. So compositors should never listen for ack_configure signals?

>Great. If the surface is not resized, then it shouldn't be moved.

Not really: there will be a pending move operation in rootston, and the next received commit will move the surface.
