### ISSUE TITLE
rootson cursor jump on resize start

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#395]
More cursor woes, tied to resize, that I first noticed trying to resize rootston (wayland) within rootston (drm).

I think there's two issues as other xdg-shell don't behave exactly the same, and the x11 backend (unset WAYLAND_DISPLAY then starting rootston) works as well but basically:
* when you start a force-resize (logo+right click) before moving, the cursor isn't where you expect it would be. This happens to varying degrees with everything I tried (xwayland, native gtk stuff...)
* with other apps, once you start moving it warps back to original position and the resize looks ok
* with rootston-in-rootston, the behavior isn't clear cut but it looks like it usuallys warps back but considers the wrong position to be the resize start, making it a huge resize as soon as you move 1px; then it behaves mostly as expected.

**Comment by acrisci** [comment]
@emersion is working on redoing the resize handler in #387 which should affect this.
