### ISSUE TITLE
wlr_data_device_manager_destroy

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots#399]
Should there be a wlr_data_device_manager_destroy? There currently isn't one defined like in the other globals.

**Comment by emersion** [comment]
Yeah, there should definitely be one.

**Comment by acrisci** [comment]
Note the global is wl_data_device_manager and the wl_data_device is a feature of the seat client.

**Comment by Timidger** [comment]
@acrisci Good catch, I'll update the issue
