### ISSUE TITLE
rootston cursor is not redshifted, but client cursors are

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#406]

**Comment by emersion** [comment]
I think that's a _won't fix_. `drmModeCrtcSetGamma` takes a `crtc_id` - thus the gamma ramp is applied to the whole connector, not to a specific DRM plane.

Note that this issue also happens in GNOME.

**Comment by Ongy** [comment]
That explanation sounds weird to me.
If it's applied to the entire connector, why would the hardware cursor not be redshifted? That has to pass the connector as well, doesn't it?

Are the client cursor all software cursors so far?
If so, does wlroots/rootston use any overlay planes currently?
And what variety of hardware was this tested on?

**Comment by emersion** [comment]
>If it's applied to the entire connector, why would the hardware cursor not be redshifted?

The gamma ramps are set per-connector, but are only applied to the primary plane.

>Are the client cursor all software cursors so far?

For now: 
* Rootston cursor = compositor cursor = hardware cursor
* Client cursor = software cursor

>If so, does wlroots/rootston use any overlay planes currently?

Primary and cursor planes are used for now.

>And what variety of hardware was this tested on?

I tested on Intel and AMD.
