### ISSUE TITLE
remap modifiers/keycodes in rootston

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#425]
What is the prescribed way for a wlroots compositor to remap modifiers and keycodes?

I see that we can intercept the XKB variables making it possible to configure some of these in the config (like `ctrl:nocaps` for one such remapping) but is the general case possible?

On X, I do `xmodmap ~/.Xmodmap` to remap keys how I like them. I don't know if that's possible with the environment variables. I've run into situations where I've had to do this to make a keyboard work correctly.

**Comment by SirCmpwn** [comment]
Just change them before passing them to the seat?

**Comment by emersion** [comment]
From https://wiki.archlinux.org/index.php/Xmodmap

>xmodmap is not directly related to X KeyBoard extension (XKB), as it uses different (pre-XKB) ideas on how keycodes are processed within X.

So it seems the compositor would have to support parsing `xmodmap` files.
