### ISSUE TITLE
clipboard manager protocol

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#441]
Is there interest in supporting a clipboard manager protocol?

The clipboard manager would be an out of process application that gets an api for clipboard contents. Primarily hooks for clipboard selection change it can use to change the contents of a copy/paste.

The clipboard manager can use this to:

* store history of clipboard contents
* offer an interface to get/set the contents of the clipboard (like `xclip` or `xsel`).
* show a tray icon where the user can select clipboard contents from history
* multiple clipboard selections handled by the manager

For more on what a clipboard manager can do, see [this list of clipboard managers](https://wiki.archlinux.org/index.php/clipboard#List_of_clipboard_managers).

**Comment by SirCmpwn** [comment]
Yes, I think we should do this at some point.

**Comment by lindhe** [comment]
Is the current behaviour the same as in i3, that when an application is closed anything copied from that program is lost?

**Comment by emersion** [comment]
Yes.

**Comment by ReK2Fernandez** [comment]
yes please

**Comment by ormung** [comment]
Some clipboard managers (like clipster) allow users to pass a list of applications which should be ignored when storing clipboard history, most notably password managers. Under wayland this can only be done by the window manager, so please consider this when designing the protocol.

**Comment by Ongy** [comment]
Just a wild idea, password managers could probably use the input method protocol in the long run. And just input the password directly (gui or cli manager shouldn't matter much I think).

**Comment by emersion** [comment]
Closing because this has moved to wlr-protocols: https://github.com/swaywm/wlr-protocols/issues/20
