### ISSUE TITLE
Change backend/wayland/os-compatibility.c

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#448]
Some functions are being used outside of the wayland backend, so this file should be moved to util and an appropriate header should be written for it.
I'm not sure if we want this to be public or not, though.

~~Also, the file doesn't match our coding style (it's largely unmodified after it was copied from weston), so that should be fixed.~~

**Comment by SirCmpwn** [comment]
It doesn't need to be updated to use our coding style. It's intentional that files originating from external sources use the external coding style.

**Comment by moritz31** [comment]
Did some minor changes, hopefully i understood things right, otherwise please correct me

**Comment by moritz31** [comment]
Issue should be solved, or is there something missing?

**Comment by SirCmpwn** [comment]
In the future you can add `Fixes #448` to your extended commit message and it'll automatically close the issue.

**Comment by Timidger** [comment]
You can also add it to the root comment on the PR, in case you don't have a distinct commit that "fixes" it and you forget to add it before opening the PR
