### ISSUE TITLE
DRM: change wlr_drm_connector_set_gamma to use DRM properties

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#450]
Currently this uses the "legacy" DRM API. This should be updated to use DRM properties where available.
The properties can be found here:
https://01.org/linuxgraphics/gfx-docs/drm/gpu/drm-kms.html#color-management-properties
I believe GAMMA_LUT and GAMMA_LUT_SIZE are the ones you want.

This will include adding the new properties to `wlr_drm_crtc_props` and adding a new function to `wlr_drm_interface`.

**Comment by VincentVanlaer** [comment]
I have implemented this, but I am going to wait until the damage patch is merged before creating a pull request for this, since I will probably use needs_swap in a similar way to the atomic hardware cursor.
