### ISSUE TITLE
wlroots and sway tries to use a virtual terminal when XDG_SEAT != seat0

### ISSUE THREAD

**Issue by n3rdopolis** [swaywm/wlroots#454]
Hi

It seems that when starting on seat1 (instead of seat0) 
wlroots tries to use a virtual terminal

Virtual Terminals (TTYs) only work on seat0 , (and not on any other seat)

Thanks

**Comment by acrisci** [comment]
Can you give us a bit more context on the issue? What are you trying to accomplish, how is it failing, and what is the expected result?

**Comment by n3rdopolis** [comment]
Sorry I wasn't clear. 
If I configure a second seat, by adding devices to it with udev (like a second card, and a few input devices), and then I start a session with logind, trying to start wlroots-sway fails because there is no TTY, and only logind seat0 has TTYs...

Basically I think it should only try to use a TTY if XDG_SEAT=seat0

This will allow a second instance of Sway running on the same computer like Zaphod mode.

I am going to try something...

**Comment by n3rdopolis** [comment]
I _think_ this might be what would get it to work
[wlroots.txt](https://github.com/swaywm/wlroots/files/1523884/wlroots.txt)
I'm having an issue starting wlroots *fully* on QEMU as I think I might be having a Mesa issue (or it could be a wlroots issue)

But with that, I do get the exact same errors now starting on both seats
