### ISSUE TITLE
Allow compositor to set size of outputs without modes

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#464]
Some backends (wayland, X11, RDP) don't have output modes. The compositor should still be able to change the output resolution.

**Comment by emersion** [comment]
Two proposals:
* Add a `void wlr_output_set_resolution(struct wlr_output *output, int width, int height)` function for this special case (it fails if the output has modes)
* Add a `bool wlr_output_set_custom_mode(struct wlr_output *output, int width, int height, int refresh)` that updates the resolution for this special case, and tries to match an existing mode if the output has modes

**Comment by ascent12** [comment]
I think custom modes would be the better solution.

DRM can handle custom modes as well, but it's something that we've never got around to implementing.
Custom DRM modes usually look horrible, but they can be a solution to buggy displays or GPU drivers that aren't advertising all of the modes a monitor is supposed to have.
