### ISSUE TITLE
Use destroy listeners on the wl_display

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#467]
We never use `wl_display_add_destroy_listener` anywhere in our codebase.
If we changed our code to use it, it could simplify proper cleanup of wlroots and have it just become `wl_display_terminate(disp)` for the library users.

We'll probably need to investigate how appropriate these destroy listeners are for our uses. I don't know if there are any cases where one type NEEDS be destroyed before another, and whether this may have an effect on that.

This is just a point for discussion, but you could even take it a step further and remove the `wlr_type_destroy' functions from our API.
Maybe there is a use case for destroying some types before the wl_display is terminated, though.

**Comment by SirCmpwn** [comment]
>Maybe there is a use case for destroying some types before the wl_display is terminated, though.

There are, e.g. tearing down a wayland output.

**Comment by emersion** [comment]
A compositor might want to setup/teardown the screenshooter at runtime (when the config file is reloaded and enables/disables that feature for instance).
