### ISSUE TITLE
wl_surface.{enter,leave} not sent to all surfaces in rootston

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#472]
These signals are only sent to the view surfaces.

We need to send them to fullscreen surfaces, popups and such.

**Comment by martinetd** [comment]
I guess this is related, if you open two windows e.g. urxvt and gnome-terminal, go into the menues like `File` in gnome-terminal and keep the popup open, then click on urxvt you will focus urxvt (it comes to front, blinking cursor fills up to indicate focus) but keyboard input still goes to the former gnome-terminal.

**Comment by emersion** [comment]
I don't think this is related, `wl_surface.{enter,leave}` is only used for HiDPI, not for grabs. Can you file another issue? Maybe this issue is already mentioned in one of these "fix xdg-shell" issues.

**Comment by martinetd** [comment]
This is actually #233, so ignore me :)
