### ISSUE TITLE
modifiers not updated properly when changing focus

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#476]
Example: in rootston, run mpv --opengl-backend=wayland <some video>, press alt, click on another surface, release alt, click back on mpv window, press space: mpv complains there is no key bound to Alt+SPACE instead of pausing.

This doesn't seem to happen on xwayland window, but as far as I can tell happens on wl_shell as well.
Looking a bit further it seems that we try to work around this in `types/wlr_seat.c:849`: in the code path entering a new surface, we explicitely call `wlr_seat_keyboard_send_modifiers(seat);` to update it... But looking a bit harder it looks like the leaving surface gets that final `wl_keyboard_send_modifiers()` and not the newly focused surface. That is because `seat->keyboard_state.focused_client` is only updated AFTER we call that `wlr_seat_keyboard_send_modifiers()`, which uses `seat->keyboard_state.focused_client` to tell where to send the event.

Proposal: send modifier later, or make a new function that takes client as argument.
This works:
```diff
$ git diff
diff --git a/types/wlr_seat.c b/types/wlr_seat.c
index c64cbef..a126d12 100644
--- a/types/wlr_seat.c
+++ b/types/wlr_seat.c
@@ -846,7 +846,6 @@ void wlr_seat_keyboard_enter(struct wlr_seat *seat,
                        surface->resource, &keys);
                wl_array_release(&keys);
 
-               wlr_seat_keyboard_send_modifiers(seat);
                wlr_seat_client_send_selection(client);
        }
 
@@ -868,6 +867,10 @@ void wlr_seat_keyboard_enter(struct wlr_seat *seat,
 
        seat->keyboard_state.focused_client = client;
        seat->keyboard_state.focused_surface = surface;
+
+       if (client && client->keyboard && seat->keyboard_state.keyboard) {
+               wlr_seat_keyboard_send_modifiers(seat);
+       }
 }
 
 void wlr_seat_keyboard_notify_enter(struct wlr_seat *seat, struct
```

Will submit a PR once one of the solution has been picked.

**Comment by emersion** [comment]
I'm fine with this fix (since it's a public function anyway). Maybe a comment that explains why the call is at the end of the function would help a future patch to revert this and introduce a regression.
