### ISSUE TITLE
Option to disable "rich" clipboard contents

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#484]
I would like to configure the wlr-data-device to disable rich clipboard contents.

This would probably involve only sending a text encoding mime type and deny setting the selection for large binary types like images.

Configuration currently would need to go in the wlr-data-device code in order to use that library feature.

Does this belong in wlroots or an external clipboard manager program?

**Comment by SirCmpwn** [comment]
I think it makes sense to expose to the compositor a means to approve/deny an offer based on its mimetype.

**Comment by emersion** [comment]
The compositor would need to mutate the data source or offer a proxy data source instead of the original one. Right now when clients set the selection `wlr_seat_set_selection` is called immediately and the focused client receives all available MIME types.

Do we want to trigger a `request_selection` event when a client requests to set a selection, and make the compositor call `wlr_seat_set_selection` manually, just like keyboard and pointer events?

**Comment by SirCmpwn** [comment]
>Do we want to trigger a request_selection event when a client requests to set a selection, and make the compositor call wlr_seat_set_selection manually, just like keyboard and pointer events?

Seems reasonable to me

**Comment by acrisci** [comment]
We need to keep the solution compatible with #441 which should (optionally) allow this to happen from an external program through a wayland interface.

When the selection is set, it should first be sent to the clipboard manager for processing if a clipboard manager is present. The clipboard manager should have a chance to approve the selection or modify it in some way. Only after that should the compositor be made aware of the selection (in our usual way of hiding protocol chatter from the compositor). But we should give the compositor the ability to completely override this and be its own clipboard manager without using the protocol if that is what is desired.

So it's possible that requiring the compositor have the final word with selection setting is a bit heavy handed for this goal. If the compositor makes use of this hook, it's easy for the clipboard manager and the compositor to fight over the clipboard and get out of sync with each other or cause infinite loops. I think conceptually there should only be one clipboard management hook to avoid this problem.

We should probably have the other interfaces call `wlr_seat_notify_selection` which will then cause the seat to start the clipboard manager protocol with the clipboard manager. If there is no clipboard manager, the default action will be to simply set the contents and notify the compositor. If there is a manager, then clipboard contents will be set by the seat at the end of the protocol negotiation.

Maybe the right solution is that if a compositor wants to manage the clipboard, it must use the clipboard manager interface.

**Comment by emersion** [comment]
We now have `request_set_selection`, compositors can mutate the selection before setting it.
