### ISSUE TITLE
wlr-test protocol

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#494]
The end goal would be to issue commands to a compositor to do things for testing. Create, control, and destroy input and output devices for tests (automated scripts and manual control). This will probably only be applicable to the wl and x11 backends.

This interface will not be meant to be enabled in production use.

Create the `wlr-test` Wayland interface definition. This interface will create objects like `wlr-test-output`, `wlr-test-pointer`, `wlr-test-keyboard`, etc. When these objects are created, they will create the simulated version on the Wayland display. For instance, creating a `wlr-test-output` will create a new `wlr-output` with the wlroots Wayland backend as specified by the user. The user has control over things like the modes, name, vendor, scale, etc of the output. When the `wlr-test-output` is destroyed, this is like the physical output being disconnected.

The `wlr-test-pointer` and `wlr-test-keyboard` will act similarly. This interface will also give the user the ability to control the pointer by sending the desired events via the interface.

Create a command line interface to `wlr-test` included in the wlroots project. This CLI can be used with any compositor with the interface enabled (including sway and rootston).

The interface should require no management from the compositor:

```c
// in the `main` method that creates the server things...
#ifdef ENABLE_WLR_TEST
wlr_test_create();
#endif
// and it will just work correctly because the library handles all the
// management of the interface (like wlr-data-device).
```

Then with the cli:

```bash
# wlr-test binary built at ./build/wlr-test/wlr-test
wlr-test output FAKE1 --create
wlr-test output FAKE1 --destroy
wlr-test input MOUSE1 --create
wlr-test input MOUSE1 --motion=0.5,0.5 # given as deltas
wlr-test input MOUSE1 --destroy
wlr-test input KEYBOARD1 --create
wlr-test input KEYBOARD1 --key=50 # a keycode to press
# etc
```

**Comment by SirCmpwn** [comment]
:-1: 

I don't see what's compelling about this over making a simple headless compositor that implements fake devices in C.

**Comment by acrisci** [comment]
> I don't see what's compelling about this over making a simple headless compositor that implements fake devices in C.

Maybe I didn't really explain the use case well enough. This is not for testing the wlroots library directly. This is a tool for compositor developers (sway contributors) to easily test hotplugging on the Wayland backend.

I am not aware of any way to dynamically set the number of Wayland displays used by the Wayland backend while the compositor is running. There is the `WLR_WL_OUTPUTS` environment variable set, but this value cannot be changed at runtime.

It would be nice for working on sway features if the developer could easily test what happens when an output goes away. To do this, he would start sway with the wayland backend with two outputs, then use the `wlr-test` cli to destroy one of the outputs, then visually inpsect what happens and read through his logs.

There is no way to do this without some IPC mechanism where another process can tell the backend to create/destroy outputs because the wlroots Wayland backend is self-contained. This interface would have direct control over the backend to do these things easily.

This way I don't have to crawl on my dusty floor and physically disconnect things from out of my computer while I am working on input hotplugging right now.

**Comment by SirCmpwn** [comment]
Can't the compositor just add or remove devices (including wayland outputs) themselves?

https://github.com/swaywm/wlroots/blob/master/include/wlr/backend/wayland.h#L20

**Comment by acrisci** [comment]
> Can't the compositor just add or remove devices (including wayland outputs) themselves?

Yes. The alternative would be to build all of this into the sway ipc.

**Comment by SirCmpwn** [comment]
I'm probably in favor of devs in your situation just writing temporary patches that i.e. add it to the IPC for as long as they need them while developing rather than try to build out this protocol.

**Comment by acrisci** [comment]
Ok, in that case I will start a wlroots-extras project and put the interface in there.

**Comment by SirCmpwn** [comment]
Sure, I don't see any reason why this couldn't be implemented out of tree. There are plans to implement a headless backend here on wlroots, by the way, which would presumably have some sort of IPC mechanism for testing it with.

**Comment by acrisci** [comment]
Ok, now that I understand how the headless backend approach would work, I like it better than this proposal for accomplishing these goals.
