### ISSUE TITLE
Headless backend design proposal

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#495]
Very straightforward backend:

```c
struct wlr_backend *wlr_headless_backend_create();

struct wlr_output *wlr_headless_add_output(unsigned int width, unsigned int height);

struct wlr_input_device *wlr_headless_add_input(enum wlr_input_device_type type);
```

If you want to simulate events on it, just dereference the pointers and raise signals yourself. Override the functions on the type impl too if you want to e.g. handle calls to `wlr_keyboard_impl.led_update`. If you want to take screenshots of the output, use wlr_render_read_pixels or just wire up screenshooter to it.

**Comment by SirCmpwn** [comment]
Note: this backend would have to spin up a headless EGL context and handle swapping etc on its outputs. Not difficult, but it's not all roses either.

**Comment by ascent12** [comment]
I imagine [EGL_MESA_platform_surfaceless](https://www.khronos.org/registry/EGL/extensions/MESA/EGL_MESA_platform_surfaceless.txt) would be relevant.

**Comment by SirCmpwn** [comment]
Yeah this is pretty easy.

Specify `EGL_SURFACE_TYPE, EGL_PBUFFER_BITEGL_SURFACE_TYPE, EGL_PBUFFER_BIT in your EGL config, use `eglGetDisplay(EGL_DEFAULT_DISPLAY)` instead of `eglGetPlatformDisplayEXTeglGetPlatformDisplayEXT`, and get an EGL surface handle with `eglCreatePbufferSurface`.
