### ISSUE TITLE
libinput configuration

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#497]
One of the things I'm missing right now when using rootson (/ need to test recent wlroots branch of sway), is libinput configuration.

I can use a script that runs some xinput commands at startup, but that wouldn't work without xwayland and I think it's rather kludgy compared to how far our XKB support has gotten.

My problem is that the libinput API is quite complex... https://wayland.freedesktop.org/libinput/doc/latest/group__config.html
There are plenty of function calls I do not really care about/need (calibration matrixes), some that I don't care about but should probably be done anyway (left handed etc), and in general the API is so large that I feel it's going to be pretty close to config parsing ultimately: I can't see how to abstract this easily.

I see rootston hooks on input_add.notify/input_remove.notify so should we just try to check if input is of proper type (e.g. pointer + libinput backend?) and leave it to rootston to try to set things then?
I'm not even sure how to check if the input is a libinput input or not at this point, but if that's fine I suggest we do a couple of arbitrary input settings in rootston just to illustrate and then do as many as we're comfortable having in sway?
Is there a better way I didn't think of?

(I'll have time to work on this starting next week, but might as well get some design plan first)

**Comment by emersion** [comment]
>I see rootston hooks on input_add.notify/input_remove.notify so should we just try to check if input is of proper type (e.g. pointer + libinput backend?) and leave it to rootston to try to set things then?

That's the plan. This will be done in sway after https://github.com/swaywm/sway/pull/1505 is merged. See https://github.com/swaywm/wlroots/issues/482

**Comment by martinetd** [comment]
Ok, had indeed missed #482.
I'm not sure why we need to wait for swaywm/sway#1505 though (except to not disperse too many efforts all around) so unless you've started I'll take a look at both soonish™

**Comment by acrisci** [comment]
Let's keep the discussion about this at the original issue. I'll write up our current thinking of how this should work over there.

@martinetd read the requirements at the [sway-input man page](https://github.com/swaywm/sway/blob/master/sway/sway-input.5.txt) for the input pr and write an example config file for rootston. Any further suggestions for how this works is appreciated.
