### ISSUE TITLE
Wrong cursor position on rotated outputs with DRM backend

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#517]
1. `rotate = 90`
2. Launch rooston with DRM backend

**Comment by SirCmpwn** [comment]
Is this via swaywm/sway#1534? Are you able to reproduce it?

**Comment by emersion** [comment]
This issue is different from the sway issue: this own is about the cursor position, the other about the cursor rotation. I encountered this bug while trying to reproduce the sway issue.
