### ISSUE TITLE
Restart xwayland when it dies

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#539]

**Comment by emersion** [comment]
We're already doing that.

**Comment by SirCmpwn** [comment]
Via #538:

>Can no longer spawn X11 apps

**Comment by martinetd** [comment]
Yes, but if you look at his logs Xwayland tried to restart while the tty wasn't focused, and got permission denied. I'm actually surprised/impressed we don't busy-loop retrying perpetually, I guess I had thought that if the startup doesn't succeed carrying on retrying again won't help much... Might want to just have a back-off timer or something instead though.
