### ISSUE TITLE
Use GL_KHR_debug

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#55]
Currently we use a macro (GL_CALL) to wrap around each of the OpenGL functions to check glError and log if anything went wrong. It works, but it's used inconsistently (e.g. outside of wlr-render) and is ugly, in my opinion.

With [this OpenGL extension](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt), we can set log handlers that the OpenGL implementation will call when something goes wrong and actually get better quality debug messages than what we have currently.

A disadvantage of this is that we will lose the ability to print line numbers of where the error specifically happens. The extension does have some ways to get some arbitrary data into the messages, so we could probably do as good as file + function.

**Comment by SirCmpwn** [comment]
:-1: 

Line numbers are very important imo. It'd be better to make our use of GL_CALL more consistent.

**Comment by ascent12** [comment]
GL errors (excluding GL_OUT_OF_MEMORY) are basically always application bugs, so these messages are only really needed during 'debug mode' (which is settable at runtime).

I would prefer that we eventually used GL_KHR_no_error for 'release mode' when Mesa finishes it, which will hopefully allow for better performance.
Using these callbacks instead macros allows us to have an easy runtime-switch for error checking that doesn't require a branch and an extra function call for every GL function.

Also, instead of just getting "GL_INVALID_OPERATION" or something, we can actually get a description from the driver for why it's invalid.

I personally think the tradeoff is worth it, but I'm not really pushing this too hard. I've just been looking through the GL and EGL extensions and I thought these sorts of things would be useful.

**Comment by SirCmpwn** [comment]
>Also, instead of just getting "GL_INVALID_OPERATION" or something, we can actually get a description from the driver for why it's invalid.

That's a much more compelling reason. Could we combine the two approaches in debug mode?

**Comment by ascent12** [comment]
I suppose something like
```c
struct line_loc {
    const char *file;
    int line;
};

#define GL_CALL(func) do { \
    glDebugMessageCallback(_gles_error_callback, \
        &(const struct line_loc){ _strip_path(__FILE__), __LINE__ }); \
    func; \
} while (0)
```
could work, so we're constantly setting the user-data pointer to be the current line.
I imagine simply setting a callback is a cheap operation, and it just won't be used if no error happens or KHR_no_error is used.
It doesn't remove the wrapper over the GL calls, though.

I would personally be more of a fan of
```c
void function() {
    // This would probably behind some macro
    glPushDebugGroup(GL_DEBUG_SOURCE_THIRD_PARTY, 0, -1, gl_str(__FILE__, __func__));

    // Call some GL functions normally

    glPopDebugGroup();
}
```

**Comment by SirCmpwn** [comment]
Either approach is cool with me, send along a PR if you like.
