### ISSUE TITLE
xwayland window does not handle resizing properly while fullscreen

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#552]
rootston should resize a window again if it is fullscreen and that window just requested to be resized.

Example: spawn an urxvt, use hotkey to maximize or set it fullscreen, then change font size. urxvt by default will want to keep the same number of columns/rows, so will resize: we let it do that while fullscreened so if font size got bigger the window will now be bigger than screen, if it got smaller it will only cover part of screen.
We need to resize it again after the client requested the new size so that it can allocate proper number of columns/row and look correct again.

I'm not sure it's an Xwayland problem or if it is more global, I know of no xdg-shell program that I can resize that way, gnome-terminal for example will resize font within the same boundary so we will not see that behavior. I think we'd let them do if they ask, we don't really care about width/height except when toggling fullscreen itself?

**Comment by emersion** [comment]
The width/height is up to the client. When setting a view to fullscreen, we send a hint to the client with the new requested size, but it's up to the client to resize itself. It's perfectly legal to keep another size (for instance, `gnome-terminal` is not resizable). In this case we need to center the surface on screen with a black background.

What's urxvt's behaviour on other compositors?

**Comment by martinetd** [comment]
On wmii it works as I'd expect: the window is resized back to fullscreen after its own resize, so the column number changes as I change font size. I'll try i3 later today.

I think the window is currently recentered as you say it should be, I'm not sure what's best in general as I do not know any other program behaving like this, but for wmii it's comfortable to be able to resize font while fullscreen :)

**Comment by emersion** [comment]
Maybe we're missing a X11 event that unsets fullscreen, if that exists in X11.

**Comment by martinetd** [comment]
I'll see if I can snoop on these and report a log of x11 events

**Comment by emersion** [comment]
Closing because this is a rootston issue.

**Comment by FreeFull** [comment]
Also seems to affect sway, at least when testing with xterm. You have to unfullscreen and refullscreen the window for it to take the full size. I haven't tested with urxvt since I'm not entirely sure how to change the font size in it.
