### ISSUE TITLE
Add stable xdg-shell support

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#557]
Source: https://github.com/wayland-project/wayland-protocols/blob/master/stable/xdg-shell/xdg-shell.xml

Changelog: https://cgit.freedesktop.org/wayland/wayland-protocols/log/stable/xdg-shell/xdg-shell.xml

We'll probably have to copy the whole code. If the changes are minor maybe we can share some code?

It's still a bit early, we may want to wait a little.

Test clients:

* https://github.com/glfw/glfw/pull/1152
* https://github.com/Enlightenment/efl/commit/ffa276fce3b812372a063431903fa0569d71fcb2

No idea if GTK+ implements this already. Mutter does.

**Comment by linkmauve** [comment]
Fyi, this just got merged into GLFW, you can use master to check your implementation, if xdg-shell isn’t present it will use wl_shell instead.

**Comment by emersion** [comment]
GTK tracking bug: https://bugzilla.gnome.org/show_bug.cgi?id=791939

**Comment by SirCmpwn** [comment]
```
~/sources/gtk+ > git grep "zxdg_.*_v6" | wc -l
72
```

**Comment by SirCmpwn** [comment]
```
~/s/gtk+ > git grep -l "zxdg_.*_v6"
gdk/wayland/gdkdisplay-wayland.c
gdk/wayland/gdkdisplay-wayland.h
gdk/wayland/gdksurface-wayland.c
```
