### ISSUE TITLE
Renderer redesign v4

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#558]
Goals:

- [x] 2D matrices
- [x] Opacity uniform
- [ ] Multiple renderers at the same time
- [x] Simple interface for common tasks

**Comment by acrisci** [comment]
My goals:

- Simple interface for common tasks
- Multiple renderers at the same time
- Partial screen updates (damage tracking)

**Comment by ascent12** [comment]
Regarding multiple renderers at the same time, you'll certainly want to be using dma-bufs. It's a zero-copy way of sharing buffers between processes or devices.
EGL has a couple of relevant extensions: [EGL_EXT_image_dma_buf_import_modifiers](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_image_dma_buf_import_modifiers.txt) and [EGL_MESA_image_dma_buf_export](https://www.khronos.org/registry/EGL/extensions/MESA/EGL_MESA_image_dma_buf_export.txt).
We're already using dma-bufs for multi-GPU, but it should work more generally.

My original renderer redesign already could do some of these things, but it wasn't written to use multi-planar formats (i.e. YUV) properly.

**Comment by emersion** [comment]
#571 is a first step towards multiple renderers at the same time: it always uses the output's renderer (instead of the global `server->renderer`). When using multiple renderers, far less GL errors are triggered. The only place `server->renderer` is still used is to upload textures in `wlr_surface`. Uploading a texture using one renderer and drawing it using another one probably doesn't work.

**Comment by emersion** [comment]
Bits that still need to be ported from the old renderer redesign PR (#319):
- [x] Screenshooter
- [x] Matrix
- [ ] Renderer (GL_KHR_debug, remove global state)
- [ ] Texture (immutable, always use EGL images)
- [ ] `wlr_render_subtexture` and use that for damage tracking
- [ ] Check nobody's using raw GL calls anymore
- [ ] [EGL_KHR_debug](https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_debug.txt)

Things that could be done after that:
- Remove wlr_render from wlr_surface. They are causing wlr_render to be a non-optional type.
- A `wlr_tex_export_dmabuf` function, which may be useful for future multi-GPU work.

**Comment by ascent12** [comment]
>always use EGL images

Unfortunately, some drivers are really picky (intel) and don't allow using EGLimages created from a "local" texture, so I had to remove that in my renderer PR.

**Comment by emersion** [comment]
>Simple interface for common tasks

Could you elaborate on this? Is the new

```c
bool wlr_render_texture(struct wlr_renderer *r, struct wlr_texture *texture,
	const float projection[static 9], int x, int y, float alpha);
```

enough?

**Comment by emersion** [comment]
Most of the stuff has been done. Opening a separate issue for the remaining feature: #778.
