### ISSUE TITLE
Split screen (FakeXRandr)

### ISSUE THREAD

**Issue by jakubn551** [swaywm/wlroots#560]
Hi i want to ask you, if wlroots will be able to split one bigscreen to multiple virtual screen, devices like TripleHead2go output one big screen it will be great to split that one in to multiple virtual.
in normal windows manager is that not a big deal but in I3wm and sway it is must have feature for me 
Thanks
PS: sorry for my bad english

**Comment by 4e554c4c** [comment]
It seems like it could be useful

**Comment by acrisci** [comment]
I would like to see this as a possibility eventually, but the path to get there technically is not clear to me.

**Comment by gwtwod** [comment]
This would be extremely useful with ultrawide (21:9) and super-ultrawide (32:9) monitors. As a long time i3-user I actually prefer to use Windows with "displayfusion" these days on ultrawide monitors, sadly.

**Comment by emersion** [comment]
This would be implemented by compositors, not by wlroots.
