### ISSUE TITLE
rootson: Drag and drop in epiphany does not work

### ISSUE THREAD

**Issue by tsloughter** [swaywm/wlroots#563]
Running master of wlroot's rootson I launched Epiphany since it works on wayland to try moving issue cards around on a Github projects board. This was a project for work that I regularly modify, and could modify fine with Epiphany in anyway except for dragging cards, they do not move at all when clicked on and attempted to be dragged.

**Comment by emersion** [comment]
Cannot reproduce.

**Comment by tsloughter** [comment]
Ok, I'll try again later today, maybe something changed since I tried a few days ago.

If it doesn't, is there anything specific information I should include?

**Comment by emersion** [comment]
Which backend are you using?

**Comment by tsloughter** [comment]
Not sure. How do I set a backend or find out which one is used after running rootson?

**Comment by emersion** [comment]
How are you starting rootston? In a tty, in another Wayland compositor, in X11?

**Comment by tsloughter** [comment]
From a terminal running in sway.

**Comment by emersion** [comment]
Sway doesn't support drag'n'drop.

**Comment by SirCmpwn** [comment]
Drag and drop from two clients within rootston should work fine even if rootston is running nested into Sway.

**Comment by SirCmpwn** [comment]
Though that does make me think about how cool it would be to drag and drop from a wayland client in sway to a wayland client in rootston in sway.

**Comment by tsloughter** [comment]
Yes, the demo drag'n drop works fine, just not in epiphany.

**Comment by emersion** [comment]
My bad.

>Though that does make me think about how cool it would be to drag and drop from a wayland client in sway to a wayland client in rootston in sway.

Same with the clipboard.

**Comment by acrisci** [comment]
I can't even run epiphany 1:3.26.5.1-1.fc27 on fedora on the drm backend.

```
WaylandCompositor requires eglCreateImage and eglDestroyImage.
Nested Wayland compositor could not initialize EGL
Gdk-Message: Error 71 (Protocol error) dispatching to Wayland display.
```

If the window gets any input events at all, it's probably not our issue (unless they are doubled or something).

Does the drag and drop work on Weston?

**Comment by acrisci** [comment]
Just got it working and cannot reproduce on the drm or wayland backend. Drag and drop works perfectly within the epiphany window.

**Comment by acrisci** [comment]
> Though that does make me think about how cool it would be to drag and drop from a wayland client in sway to a wayland client in rootston in sway.

You get a data device for your backend wayland window. Just proxy the selection.

**Comment by tsloughter** [comment]
D'oh. Yup, sorry I should have tried the current master before opening! It does work for me now too. So something fixed it in the last couple days, I've got to be sure to keep up to the latest commit on such a fast moving project.

**Comment by tsloughter** [comment]
Or not... it worked when I first started rootson and loaded epiphany but shortly after it has stopped working.

**Comment by emersion** [comment]
Please investigate a deterministic way to reproduce.
