### ISSUE TITLE
gtk-primary-selection does not work in rootston

### ISSUE THREAD

**Issue by Laaas** [swaywm/wlroots#600]
Tested using commit 429f06d3f

The client tested was gnome-terminal. I confirmed that the exact same behavior works properly under GNOME.

**Comment by emersion** [comment]
gnome-terminal is known to have issue if you have multiple graphical sessions. It starts a server on the first one so all clipboard operations go to the first graphical sessions.

**Comment by Laaas** [comment]
so it's a client bug then?

**Comment by emersion** [comment]
Not really. It's just gnome-terminal being dumb.
