### ISSUE TITLE
Remove input_remove and output_remove from wlr_backend

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#605]
We can just use `wlr_output.destroy` and `wlr_input_device.destroy` instead.

One issue is that `wl_signal_emit` is not safe if you remove the next signal handler. I've submitted a patch to wayland (https://lists.freedesktop.org/archives/wayland-devel/2018-January/036711.html) but it got ignored. Maybe we could implement a safe `wlr_signal_emit` in util?

**Comment by acrisci** [comment]
I agree 👍 .
