### ISSUE TITLE
Pointer button release outside of view does not send it to surface via seat

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#613]
To reproduce:

1. Click and drag text in `gnome-terminal`.
2. Hold the pointer button down after you exit the view.
3. Release the button outside of the view.
4. Move the pointer back into the view

The seat client of the view should have received a button up.

Instead, it did not. The text will still be highlighted as you move the pointer around in the surface.

**Comment by emersion** [comment]
> The seat client of the view should have received a button down.

You mean a button up?

**Comment by SirCmpwn** [comment]
We should probably make pointer focus "sticky" until all buttons are released.

**Comment by acrisci** [comment]
> We should probably make pointer focus "sticky" until all buttons are released.

This seems to be what Weston is doing. It will not send pointer enter/leave to a surface while a button is down full stop.
