### ISSUE TITLE
Add wlr_output_damage

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#614]
The damage logic lives in rootston. This is a proposal to isolate it into a wlr submodule.

```c
struct wlr_output_damage {
    struct wlr_output *output;
    pixman_region32_t damage;

    struct {
        struct wl_signal render;
    } events;
};

struct wlr_output_damage *wlr_output_damage_create(struct wlr_output *output);
void wlr_output_damage_destroy(struct wlr_output_damage *output_damage);
void wlr_output_damage_add_at(struct wlr_output_damage *output_damage, int x, int y, pixman_region32_t damage);
void wlr_output_damage_add_whole(struct wlr_output_damage *output_damage);
void wlr_output_damage_get_from_box(struct wlr_output *output, struct wlr_box *box, pixman_region32_t damage_out);
```

This would take care of output damage history, calling `wlr_output_make_current` and `wlr_output_swap_buffers` when necessary. When the desktop should render the `render` signal will be emitted.

This maybe abstracts too much. We could replace that `render` event with just a `frame` event and let the compositor call `wlr_output_make_current` and `wlr_output_swap_buffers`. That frame event won't be emitted when there's no damage.

**Comment by SirCmpwn** [comment]
>This maybe abstracts too much. We could replace that render event with just a frame event and let the compositor call wlr_output_make_current and wlr_output_swap_buffers. That frame event won't be emitted when there's no damage.

yes

**Comment by emersion** [comment]
Proposal v2:

```c
struct wlr_output_damage {
    struct wlr_output *output;
    pixman_region32_t damage;

    struct {
        struct wl_signal frame;
    } events;
};

struct wlr_output_damage *wlr_output_damage_create(struct wlr_output *output);
void wlr_output_damage_destroy(struct wlr_output_damage *output_damage);
void wlr_output_damage_add_at(struct wlr_output_damage *output_damage, int x, int y, pixman_region32_t damage);
void wlr_output_damage_add_whole(struct wlr_output_damage *output_damage);
void wlr_output_damage_get_from_box(struct wlr_output *output, struct wlr_box *box, pixman_region32_t damage_out);
bool wlr_output_damage_make_current(struct wlr_output *output);
bool wlr_output_damage_swap_buffers(struct wlr_output *output, struct timespec *when);
```

This exposes `wlr_output_damage_make_current` and `wlr_output_damage_swap_buffers` without th buffer age and damage since `wlr_output_damage` will take care of it.
