### ISSUE TITLE
libinput: Touch event handling is not reliable

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#639]
The current way to handle a touch event, gets the x/y position of the event, and the size of the device and reports them as x/y+width/height in the wlr_event.

There's also `libinput_event_touch_get_x_transformed` which gets a pre-transformed x value.
This uses evdev variables internally, that I don't think get exported to us.
It applies the transformation with a minimum and maximum axis value.

On my machineTM things work if I simply replace width/height with 1, and let libinput transform the event coordinates into a a width/height of 1.

**Comment by emersion** [comment]
Fixed in #765
