### ISSUE TITLE
Investigate race conditions in DRM hotplug support

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#646]
Sometimes the discovery of disconnected (haven't seen with connected) outputs can be rather slow, which breaks atomicity asumptions.

It is possible, that physically distinct events happen at the same time in software (either because udev is being slow, or probably DRM fd paused/device suspend)

Case one:
* Con1 is disconnected
* Con2 is connected
If the currently uses all planes (e.g. my laptop can only handle one external display) the modeset on the new output will fail, because the now unplugged output still takes up planes.

Case two:
* Con1 is disconnected
* Con1 is connected (other output)
We should investigate if this can cause an inconsistency in discoverd and actually provided modes and other output identifiers.

**Comment by emersion** [comment]
Closing because this isn't actionable. Please re-open with more details if necessary.
