### ISSUE TITLE
Replace the libwayland event loop with something "proper"

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#648]
The libwayland eventloop treats every fd equal (timers are fds).

This worksTM. But this means a spammy client can delay our redraw cycle or cause input delay.

A proper eventloop should be able to have prioritised events (every backend fd) and timers (If we do [the delayed render](https://www.collabora.com/about-us/blog/2015/02/12/weston-repaint-scheduling/) to let clients catch vsync cycle.

Another feature (in the category of defense against clients) would be to process wayland events chunked, so a client only gets a maximum timeslice, and does not (how it currently is according to #wayland) get to block us in its events until eternety.

**Comment by emersion** [comment]
Isn't this decision up to compositors?

**Comment by Ongy** [comment]
Yea, I talked about this in #wayland.
I'm not on the ML, but I think Sardem sent something to address this in libweston after I pointed it out.

**Comment by SirCmpwn** [comment]
Is there a client that demonstrates the problem?

**Comment by Ongy** [comment]
Trying to hack one together real quick I noticed that events are effectivly chunked already (contrary to what I was told on #wayland...).
libwayland will fill it's buffer, then process these events, continue to the next fd, continue to the next loop, so that's nothing we need to worry about.

The other one is purely about missing timings. I'd have to look into what's the easiest to get rootston to take a while in a single processed buffer, spam that and then measure input lag.
I don't have any good way to measure input lag. And currently we have a lot of leeway with rendering (~17ms on my outputs). 
I don't think it has a high priority as is.
