### ISSUE TITLE
Support being opened by display managers

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#663]
It's going to be a pretty common use-case for people to want to open wlroots-based compositors with gdm/lightdm/whatever, and we can't really just tell them all that they need to open everything from a fresh VT. It's an issue that gets brought up with sway quite often.

I have no idea what we actually need to do for this, though.

**Comment by SirCmpwn** [comment]
The reason Sway doesn't support DMs is because the *DMs* need to support Sway, not the other way around. There's nothing Sway can do to be better for DMs (aside from throwing everything away and becoming an X11 window manager instead). Lobby the DMs, not us.

**Comment by ascent12** [comment]
I honestly have no idea what the "protocol" for handing control to the wayland compositor is. Maybe there is something we're supposed to to, maybe not?
I made this ticket so someone else would look into it (I can't really be bothered with this).

I was just skimming over some DM-related stuff, and it reminded me that it's probably something that doesn't work.

**Comment by SirCmpwn** [comment]
I mean, odds are that GDM works with rootston (and Sway) and we might want to stop discouraging users from using it. We still aren't going to field questions about them, though. The "protocol" doesn't really exist, there's no handover besides releasing their own resources before exec'ing into us. But this is totally different from X11 and many DMs only support X11 so I don't really want to hear about it from users.
