### ISSUE TITLE
mpv’s initial fullscreen is ignored

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#674]
Here is the full `WAYLAND_DEBUG` log: [mpv.txt](https://github.com/swaywm/wlroots/files/1756658/mpv.txt)

As we can see, mpv is asking to set fullscreen on line 110, yet on line 125 the configure array is empty.

On line 333 I then pressed f, so on line 334 it asks for fullscreen again, and then on line 342 we can see the value 2 being passed to the configure event.

The only difference between these is that the initial fullscreen request requests a specific output, while the latter doesn’t, but it may be unrelated and a simple race somewhere.

**Comment by Ongy** [comment]
This happens before the first commit.
So we don't have the window yet on the rootston side, but only in the `wlr_xdg_shell_v6` stuff.

The compositor should probably check the toplevel state for the fullscreen state.
To make this work properly we will likely have to move the output into that as well.

**Comment by linkmauve** [comment]
Of course this happens before the first commit, xdg-shell is designed to allow clients to do all of their configuration before the first configure, in order to avoid any race that could happen there.

(Sadly not all of them, scale factor isn’t specified before the surface is mapped, at which point the client has already drawn its first frame.)
