### ISSUE TITLE
Alt-tabbing out of a fullscreen client asks for any size in the configure event

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#677]
The compositor keeps the client in fullscreen, but stops asking for the exact output size, which can lead to the client giving a non-optimal buffer.

Here is the problematic event:
```zxdg_toplevel_v6@15.configure(0, 0, array(0x02, 0x00, 0x00, 0x00))```

**Comment by Ongy** [comment]
Looks like https://github.com/swaywm/wlroots/pull/680 also fixes this one.

**Comment by acrisci** [comment]
Is it fixed? Can we close this?
