### ISSUE TITLE
Alt-tabbing between two clients should draw the cursor of the next one

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#678]
It currently requires the user to move the pointer to let it get drawn by the next client.  Before doing so, the last cursor from the previous client continues to be displayed at its last location, even if it should otherwise be hidden.

**Comment by Ongy** [comment]
The underlying problem should be, that the pointer focus and thus pointer.enter event is not emitted if z-order changes, but only on cursor movement.

I asume you have the pointer on an area covered by both clients? Otherwise I think the behaviour would be correct.

**Comment by linkmauve** [comment]
Correct, I mostly only use maximised clients.
