### ISSUE TITLE
Segfault or damage tracking issue when displaying a tooltip in Firefox and alt-tabbing to another client

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#679]
How to reproduce:
- Go to a page where a tooltip can be displayed by Firefox.
- Put your pointer on the element that will generate the tooltip.
- Alt-Tab to another client before the tooltip is displayed.

In some cases the tooltip will keep being drawn on the other client, until the cursor moves on top of it; in other cases it will vanish properly; in yet other cases rootston will segfault (but I don’t have a gdb trace yet).

This may be related to #678.

**Comment by Ongy** [comment]
I'm more inclined to connect it to https://github.com/swaywm/wlroots/issues/671 and https://github.com/swaywm/wlroots/issues/650 in terms of segfault.

The tooltip issue is something I have seen on waymonad when pointer focus went from firefox to a native wayland client. I had blamed it on Xwayland keeping the pointer where it is, once it lost focus.

How does weston behave in that case?

**Comment by linkmauve** [comment]
AFAIK Weston still displays the tooltip on top of the next client, but removes it on the first interaction with it.

Feel free to report that issue to xorg-xserver instead.
