### ISSUE TITLE
Unplugging an output and plugging another on the same port reuses the exact same object

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#695]
If I unplug an output and plug in another one, I get a new geometry/mode/done suite of events, but there has been no notification to the client that a disconnect has happened.  This may cause issues when an application is expecting to be noticed, for example to destroy a surface associated to this now-removed output.

**Comment by SirCmpwn** [comment]
To clarify, you're saying the Wayland global is not removed?

**Comment by linkmauve** [comment]
Yes.
