### ISSUE TITLE
Expose xwm_atoms_contains

### ISSUE THREAD

**Issue by martinetd** [swaywm/wlroots#702]
As a follow-up on #699, `xwm.h` was moved to our private headers so the function got removed from our API.

We need to:
 * Move the `atom_name` enum to `wlr/xwayland.h` (probably rename it along the way, `wlr_xwayland_atom`?)
 * Move and rename `xwm_atoms_contains` to `wlr/xwayland.h` (`wlr_xwayland_atoms_contain`?)

**Comment by emersion** [comment]
I'm not a fan of exposing `xwm_atoms_contains`. Exposing atoms is probably a good idea though.

**Comment by martinetd** [comment]
@ongy says it would be needed for compositors to handle X11 bars, as it would need to check atoms of the surface to tell what it's supposed to be (these would be atoms we do not support yet); I agree it could make sense for the compositor to want to check if a xwayland view has atom x or y to handle it differently?

**Comment by emersion** [comment]
In this case, I'd prefer something like `wlr_xwayland_surface_has_atom`. It's a simple function compositors can implement themselves anyway.

**Comment by martinetd** [comment]
Compositor does not currently have access xwm->atoms that maps the `enum atom_name` to actual xcb atom value, so they can't check it themselves.
I approve the name change though, easier to pass the surface as argument than surface->window_type + surface->window_type_len.

**Comment by acrisci** [comment]
I think the normal approach here is to read the atoms and expose them as properties on the wlr-xwayland surface.

**Comment by emersion** [comment]
The compositor can connect to the X11 server (just like the WM) in order to retrieve atoms. Sway does that.
