### ISSUE TITLE
x11 backend: Broken window close handling

### ISSUE THREAD

**Issue by psychon** [swaywm/wlroots#706]
I am not quite sure what the intention behind the following code is, but I am sure that it does not work:

https://github.com/swaywm/wlroots/blob/9716aa9b9247e7af08f4887fec494dcb9a918d9d/backend/x11/backend.c#L147-L150

`XCB_GLX_DELETE_QUERIES_ARB` is the opcode for the request that `xcb_glx_delete_queries_arb()` sends/generates. It is not an opcode for an event.

Since this define has value 161, which is in the space for extension events, this is just a time bomb: If the x11 backend ever starts using some x11 extension that generates events, eventually someone will run an x11 server where this extension's events ends up being assigned number 161, which means that wlroots now handles whatever this event is by quitting.

Since this code comes from commit 6bf508df816750f41b9b0c362f5bc6f64f737a70, let me CC @ascent12 and quote ICCCM §4.2.8.1.

> Clients, usually those with multiple top-level windows, whose server connection must survive the deletion of some of their top-level windows, should include the atom WM_DELETE_WINDOW in the WM_PROTOCOLS property on each such window. They will receive a ClientMessage event as described above whose data[0] field is WM_DELETE_WINDOW.

So, the code for quitting should be under `case XCB_CLIENT_MESSAGE`, it should cast the event to `xcb_client_message_event_t *` and check if the event has `->data.data32[0] == x11->atoms.wm_delete_window.reply->atom`.

(To whoever writes a patch for this: I suggest a `puts("This works");` in the newly-added `case` for testing)

(Also, please get rid of `#include <xcb/glx.h>` while you are at it)

(Oh and: Why does `struct wlr_x11_backend` contain an `xcb_intern_atom_cookie_t` and an `xcb_intern_atom_reply_t` when all that you want is the `xcb_atom_t` that is saved as `->reply->atom`? Plus, the content of the reply field is just plain leaked instead of being `free()`d on shutdown)

(The symptom of what the code currently does should be that closing the window just does not work at all... either I am wrong here or how come no one noticed?)

Edit: Okay, the current code actually does work correctly... kind of. What I forgot is that the highest bit of an event indicates that it was generated by `xcb_send_event`. Now, `XCB_CLIENT_MESSAGE` is 33 and 33+128 is 161, so we end up with the value of `XCB_GLX_DELETE_QUERIES_ARB`. However, all of this is just accidential and not really the right way to handle client messages.

So: Instead of `switch (event->response_type)` you need `switch (event->response_type & 0x7f)`, or for readability `switch (XCB_EVENT_RESPONSE_TYPE(event))` (this macro is from `xcb_event.h`).

**Comment by ascent12** [comment]
>What I forgot is that the highest bit of an event indicates that it was generated by xcb_send_event. Now, XCB_CLIENT_MESSAGE is 33 and 33+128 is 161, so we end up with the value of XCB_GLX_DELETE_QUERIES_ARB. However, all of this is just accidential and not really the right way to handle client messages.

Damn, I've been wondering about that for ages. I knew something was wrong with that code, even as I was writing it.
