### ISSUE TITLE
Screenshooting and screencasting

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#709]
This is just an issue to keep track of prior art and progress of these features in other compositors.

Possible solutions:

* Custom IPC (Sway 0.x)
* D-Bus API (GNOME, KDE) w/ Pipewire
* Wayland protocol (Weston, Orbital - only screenshots)

GNOME and KDE seem to take the [Pipewire](https://pipewire.org/) path with a custom private D-Bus protocol ([here](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/screencast.c) and [here](https://github.com/KDE/xdg-desktop-portal-kde/blob/screencast/src/screencast.cpp)). They expose a public D-Bus interface via [Flatpak](https://www.flatpak.org/)'s [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal).

If we want to support screenshooters and screencasters using xdg-desktop-portal, we could implement an xdg-desktop-portal backend out-of-tree which talks to the compositor via IPC or a Wayland protocol.

The most efficient way would be to export dmabufs with GBM and give them to the client. That gives a zero-copy, direct access to GPU resources.

References:
* KDE status: http://www.jgrulich.cz/2018/03/06/screen-sharing-in-plasma-wayland-session/
* Private GNOME D-Bus API: https://gitlab.gnome.org/GNOME/mutter/blob/master/src/org.gnome.Mutter.ScreenCast.xml

**Comment by emersion** [comment]
Status update: we're building a Wayland protocol for this: https://github.com/swaywm/wlr-protocols/pull/11

**Comment by Ongy** [comment]
Side note, afaik KDE is doing something close to what I consider the good path for now.
They have a (currently private) wayland protocol to get the buffers into an external daemon that then "speaks" pipewire.

This should cover the 2nd and 3rd bullet point option nicely (we may be able to share work on pipewire/portal integration with KDE).

But from what I've seen the protocol KDE currently uses is more of a quick hack, so working out the 3rd bullet point, then collaborating on covering the second with an external service is the way to go.

Reference: https://www.reddit.com/r/linux/comments/8le7rm/first_steps_for_kde_screencast_on_wayland/dzfit7z

**Comment by emersion** [comment]
Yeah, I've noticed that and this is good news! Started to discuss with Scott Harvey (https://www.reddit.com/r/linux/comments/8le7rm/first_steps_for_kde_screencast_on_wayland/dzfqftz)

**Comment by emersion** [comment]
The last remaining piece to get this issue completely fixed is: https://github.com/swaywm/wlr-protocols/pull/17

**Comment by edrex** [comment]
Linking #992
