### ISSUE TITLE
Tag generation makes build fail when a file is deleted

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#725]
When deleting a file while developing, the build always fails because the meson script generating tags uses git to list files.

Also happens when moving a file.

**Comment by acrisci** [comment]
My vote is to remove tag generation.

**Comment by acrisci** [comment]
Actually @agx did the implementation so maybe he's using it and will fix it.

**Comment by agx** [comment]
On Fri, Mar 23, 2018 at 01:14:37AM +0000, Tony Crisci wrote:
> Actually @agx did the implementation so maybe he's using it and will fix it.
I'll have a look.

**Comment by agx** [comment]
Does freebsd have '-f' - is so we can use that instead

**Comment by agx** [comment]
Oh, I see it has. PR forthcoming.
