### ISSUE TITLE
Segfault in xwayland/selection.c On copy+paste wayland->X11

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#728]
I don't have a good way to reproduce this :/ Sometimes it happens, sometimes it doesn't.
When it happens it's mostly copy in qutebrowser, then paste in X11.

This happens to me in waymonad, but from what I can tell, this should be a wlroots issue, I don't think I can fail to handle anything related.
```
(gdb) backtrace
#0  0x00007f28b32237e9 in wl_event_source_remove () at /usr/lib/libwayland-server.so.0
#1  0x00007f28b2ad7fd0 in xwm_read_data_source (fd=61, mask=4, data=0x153a510) at ../xwayland/selection.c:114
#2  0x00007f28b32239b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#3  0x00007f28b322214c in wl_display_run () at /usr/lib/libwayland-server.so.0
#4  0x00000000008f8026 in haylandzm0zi1zi1zi0zminplace_GraphicsziWaylandziInternalziServer_displayRun1_info ()
#5  0x0000000000000000 in  ()
```

**Edit:** Probably Helpful aswell
```
(gdb) frame 1
#1  0x00007f28b2ad7fd0 in xwm_read_data_source (fd=61, mask=4, data=0x153a510) at ../xwayland/selection.c:114
114                     wl_event_source_remove(selection->property_source);
(gdb) p selection->property_source
$1 = (struct wl_event_source *) 0x0
```

**Comment by emersion** [comment]
Can you reproduce in Weston?

**Comment by Ongy** [comment]
I don:t even have a reliable way to reproduce on waymoand or rootston.
This happens  *sometimes*, not even every day on my usual use pattern

**Comment by acrisci** [comment]
@Ongy we think this will fix it, but let us know if you get any more crashes with this.
