### ISSUE TITLE
Qutebrowser crashs on overlay dismiss

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#732]
E.g. hover over something with an explanation text.

This happens since the #711 but may quite well be a qt bug we just didn't trigger before (qt seems to be bad at xdg-shell, it also messes up creation (e.g. snd level popup in konsole/obs-studio).
```
zxdg_shell_v6@24: error 2: xdg_popup was destroyed while it was not the topmost popup
```

**Comment by Ongy** [comment]
Hm, can't reproduce on current packages, so this probably got fixed on the qt side?

Anyways, looking at `wlr_xdg_shell.c`, I think it's likely caused by unmapping (commit NULL buffer) a popup before it's destroyed over the protocol. Which I'm not quite sure whether we should allow it or not.

The protocol says `If this xdg_popup is not the "topmost" popup, a protocol error will be sent.`, but it's not very explicit about whether unmapped popups count.

I think a "create -> destroy" workflow (same problem as https://github.com/swaywm/wlroots/pull/741) should be supported.

**Comment by emersion** [comment]
>The protocol says If this xdg_popup is not the "topmost" popup, a protocol error will be sent., but it's not very explicit about whether unmapped popups count.

This is about the destroy request, so I don't think it applies to unmapping. Also the whole `grab` description is talking about "destroying" popups rather than "unmapping" them. Though the `not_the_topmost_popup` error description says:

>the client tried to map or destroy a non-topmost popup

I wonder what the "map" case is about.

**Comment by Ongy** [comment]
Not during unmap. But the popup is unmappend, and then later destroyed.
If I understand the current code correctly, it's not considered toplevel at that moment in wlroots, and I'm really not sure whether it should, from the protocol text.

**Comment by Ongy** [comment]
Ok, can still reproduce, just not on duckduckgo, github works.

WAYLAND_DEBUG=client:
https://gist.github.com/Ongy/70c46d62bac458fedd7884ff7a01e0ae

I only see one `get_popup` over the entire log, so I don't think it can fail with the error it produces.
It also doesn't do the order I suspected. It's first `popup@31.destroy` then `surface@27.destroy` which are the related objects as far as I can tell.

**Comment by Ongy** [comment]
Hm, I think the problem is, that it never calls `grab` on the `xdg-popup`, which is currently required by wlroots to become the topmost popup

**Comment by Ongy** [comment]
I think https://github.com/swaywm/wlroots/issues/846 was a duplicate of this issue.
The change seems reasonable to me, should the topmost semantics be refined further?
*Maybe* filter the list for mapped popups?

**Comment by SirCmpwn** [comment]
>*Maybe* filter the list for mapped popups

*Maybe*
