### ISSUE TITLE
(Possible?) double free in wlr_x11_backend_destroy()

### ISSUE THREAD

**Issue by psychon** [swaywm/wlroots#745]
In `wlr_x11_backend_create()`, the connection to the X11 server is initialised a bit like this:
```C
x11->xlib_conn = XOpenDisplay();
x11->xcb_conn = XGetXCBConnection(x11->xlib_conn);
```
where `XGetXCBConnection` comes from `libX11` and is implemented as `return dpy->xcb->connection;`, so there is (for example) no reference counting or copying involved.
Both the error path in `wlr_x11_backend_create` as well as (since https://github.com/swaywm/wlroots/commit/b0c2bbebd1c4c50173a01175d049842b79ee7e1b) `wlr_x11_backend_destroy` tear down the state via something like the following:
```C
xcb_disconnect(x11->xcb_conn);
XCloseDisplay(x11->xlib_conn);
```
This really should cause a double free since `XCloseDisplay` owns the XCB connection and also calls `xcb_disconnect`, and the first thing that `xcb_disconnect` does is `free(c->setup);`. I wonder why glibc did not yet complain about this double free for anyone yet.

I can send a patch soonish, but right now I'm not at the right computer for that.

**Comment by martinetd** [comment]
:+1: to that, it somehow detects the disconnect in that order but I had noticed doing `XCloseDisplay` first then `xcb_disconnect` would fail, and I can confirm the `xcb_disconnect` isn't needed leak-wise.
It's a simple patch & doesn't seem to hurt too much so letting you take the time to post a PR though, thanks!
