### ISSUE TITLE
damage tracking on xdg-popup only partial

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#752]
As the title says, the damage tracking for xdg-popups seems to only partially cover the popup.

It looks like the damage is clipped to the xdg-toplevel's surface (not geometry)

**Comment by Ongy** [comment]
Ahh, I think it's only on the surface unmap. It does work for the highlights when hovered over elements of the popup.

**Comment by emersion** [comment]
Hum, I don't think we handle well xdg popup unmap in rootston.

**Comment by emersion** [comment]
With which client can you reproduce the issue?

**Comment by Ongy** [comment]
worked with both gnome-shell and weston-terminal

It's the full surfaces, not just geometry, so you'll have to click somewhat far to the side, since there's fully transparent area around the visible window
