### ISSUE TITLE
test GTK xdg-shell stable

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#771]
Here is a patch for xdg-shell stable:

https://bugzilla.gnome.org/show_bug.cgi?id=791939

Build and test this with out implementation to make sure it still works.

Also port xdg-positioner to xdg-shell stable implemented in #720.

**Comment by emersion** [comment]
GTK with xdg-shell stable is available on Arch.

**Comment by SirCmpwn** [comment]
woo
