### ISSUE TITLE
mpv output doesn't update

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#773]
MPV seems to be stuck at one of the first frames, this is with mpv 0.27.2, which used to worked.

Debug log doesn't look like done events are missing. Rather like the surface buffer is never updated on the wlroots end.

**Comment by Ongy** [comment]
Forcing https://github.com/swaywm/wlroots/blob/master/types/wlr_surface.c#L412 to be true fixes the issues

**Comment by martinetd** [comment]
That bool just makes wlroots reupload the buffer all the time...
We seem to be in the 2nd branch of `wlr_surface_apply_damage` with `wlr_renderer_resource_is_wl_drm_buffer`... Where we don't consider damage at all.

It looks like we're supposed to reimport the damaged area from drm in that case?

**Comment by emersion** [comment]
This is a #744 regression.

**Comment by martinetd** [comment]
Indeed, now I'm looking at the old `wlr_surface_apply_damage`, it used to unconditionally call `wlr_texture_upload_drm` without any check on previous image in the `wl_drm` case. Same with dmabuf.

That's pretty trivial to revert this behaviour (just remove the `if (!surface->texture || reupload_buffer)` check after wl_shm handling in `wlr_surface_apply_damage`; and it obviously "works"), but I wonder if there's a way to only fetch the damaged portion of these buffers somehow, which doesn't look possible atm but am not sure how realisable it would be in the first place.


@emersion I suppose I'd rather let you look into it

**Comment by emersion** [comment]
>I wonder if there's a way to only fetch the damaged portion of these buffers somehow

When using wl_drm or linux_dmabuf, we're not copying pixels around - the client is directly updating the texture. We don't need to "only upload the damaged region" since we don't upload anything.

What we do need to do is to re-create the texture when the client attaches a new buffer.
