### ISSUE TITLE
Renderer redesign v5

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#774]
Boy, I really love breaking this, don't I?

This is all pretty breaking stuff, so I'm not suggesting we do this immediately, but I'll put this idea out there to get feedback on it. This may be a wlroots 2.0 kind of change, unless it's wanted sooner.

Obviously, changes are needed to facilitate a Vulkan renderer, and possibly other renderer types that we may think up in the future.
@SirCmpwn suggested merging `wlr_egl` and `wlr_renderer` together (before retracting it), and while I originally didn't like the idea, I've come around to thinking that it's the way we should probably go.

## Current issues

The main problem is that EGL types are deeply embedded into our code. A `wlr_backend` has an `EGLDisplay`, a `wlr_output` has an `EGLSurface`, and our renderer expects nothing else. This is fine if we can create those from various 'native' types using `EGL_KHR_platform_*`, but it doesn't work in cases where no such extension exists. We've only managed to scrape by in the other cases because `EGL_MESA_platform_surfaceless` exists.

Vulkan is where this really becomes a problem. There are similar types, but they're not available in all of the same places. `EGLDisplay` == `VkDevice`and `EGLSurface` == `VkSurfaceKHR` + `VkSwapchainKHR`.
However, we have no way to create the `VkSurfaceKHR` from GBM or in the headless backend. Vulkan can definitely do surfaceless rendering, just not with a `VkSurfaceKHR`.

Basically, this model can only work with the Wayland and X11 backends, unless more Vulkan extensions are added, but that's not something I would bank on. This abstraction is just too limiting.

## Renderer-specific backends to backend-specific renderers

So instead of having the backends need to add support for every renderer and cram it into some `EGLSurface`-like, we just have the renderer take the 'native' backend resources, and create rendering resources from them however it sees fit.

So we tear all of the EGL code out of the backends and put them into `wlr_renderer`. With this, `wlr_egl` doesn't really have a purpose any more, and would just be merged into `wlr_renderer` too.

This will allow the renderer to work differently based on what backend its using. Backend-specific code isn't great, and will make things more complicated, but I think it's going to be a necessary evil.

It does make adding new backends a bit harder, but I hope the headless rendering case would be able to work with most other backends that people would want to add.

## The Design

I even bothered to draw a fancy little diagram.

![wlroots_renderer](https://user-images.githubusercontent.com/5235114/38083927-7f9fb520-33a7-11e8-99a7-d3e475609a3a.png)

`wlr_rendersurface` is just a container for `wlr_output` render state, like `EGLSurface`, but should be more flexible. I really would want to call it `wlr_surface`, but that name was taken, unless you can think of something better.

## The user API

It would probably be along the lines of
```c
// Just like it is now, but may fail if renderer doesn't support the backend type
struct wlr_renderer *wlr_gles2_renderer_create(struct wlr_backend *backend);
struct wlr_renderer *wlr_vk_renderer_create(struct wlr_backend *backend);

// Automatically pick the "best" renderer for the backend.
// You would use this if you're using the rest of the renderer API and don't really care
// what type of renderer was picked.
// Ideally, this would never fail, since every backend would have at least 1 valid renderer.
struct wlr_renderer *wlr_renderer_create(struct wlr_backend *backend);

struct wlr_rendersurface *wlr_rendersurface_create(struct wlr_output *output);

void wlr_renderer_begin(struct wlr_renderer *renderer, struct wlr_rendersurface *surface,
    int *buffer_age);
void wlr_renderer_end(struct wlr_renderer *renderer, struct wlr_rendersurface *surface,
    pixman_region32_t *damage);
```
And the other renderer functions would work as they do now.

We'd also need to add a few backend specific functions to get their underlying resources.
```c
struct gbm_device *wlr_drm_get_gbm(struct wlr_backend *backend);
struct wl_display *wlr_wl_get_display(struct wlr_backend *backend);
xcb_connection_t *wlr_x11_get_xcb(struct wlr_backend *backend);

struct gbm_surface *wlr_drm_output_get_gbm(struct wlr_output *output);
struct wl_surface *wlr_wl_output_get_surface(struct wlr_output *output);
xcb_window_t wlr_x11_output_get_window(struct wlr_output *output);
// Would fail on the above 3 backends
void *wlr_output_get_pixels(struct wlr_output *output, int32_t *width, int32_t *height, int32_t *stride
    uint32_t *format);
// Or return a struct. You get the idea.
```

## Disadvantages

It would be harder for users to write custom renderers, as they may now need to do backend-specific things and handle a lot of EGL themselves.
It may be possible to write some utility functions to help, but I'm not sure what they would look like. Maybe just sharing some of the internal state of the various renderers would be enough, or keeping `wlr_egl` around purely as a utility type?

**Comment by emersion** [comment]
How would multiple backends used at the same time work? I guess only if the renderer supports all of the backends in use? Or maybe by exporting and importing DMA-BUFs to share textures between each backend's renderer?

**Comment by emersion** [comment]
I see opportunities to share code between renderers (e.g. #775).

This design prevents custom backends from being written without a custom renderer. As I understand it the only point of contact between backend- and renderer-specific code is wlr_rendersurface. How would you design the interface of this type? I think it would be possible to do something similar to the current wlr_texture design (texture_from_pixels, texture_from_wl_drm, texture_from_dmabuf). Something like rendersurface_from_wl_display, rendersurface_from_gbm, rendersurface_from_xcb_conn without requiring the renderer to detect the backend type.

**Comment by SirCmpwn** [comment]
My initial impression is to dislike this approach. It makes it too hard to write new renderers and backends. It might be good to see a patch like this for research purposes and then come up with a better final approach afterwards.

**Comment by ascent12** [comment]
Can we think of any backends that possibly could be added that wouldn't work as just having some raw memory that we can write to?
All of the things which currently have "native windows", we already do, excluding stupid shit like Mir.

So any new backend could just implement `wlr_output_get_pixels`, and the renderer would hopefully just work with it.

Yes, I agree that this new design make it way harder to write new renderers for users. I can't think of a sane design that allows the flexibility we need, without hacking heaps of complexity into the backends, and making it even harder to write other non-GL renderers.

**Comment by emersion** [comment]
I think I'm okay with this design as long as there's not a hardcoded list of supported backends in each renderer.

**Comment by emersion** [comment]
Just to be clear, what I'm trying to say is that it should be possible to do it the other way around.

```
+-----------------------+      +-----------------------+      +-----------------------+
|                       |      |                       |      |                       |
|      wlr_texture      +----->|     wlr_renderer      |<-----+      wlr_backend      |
|                       |      |                       |      |                       |
+-----------------------+      +-----------------------+      +-----------------------+
                                           ^                               ^
                                           |                               |
                                           |                               |
                               +-----------+-----------+      +------------+----------+
                               |                       |      |                       |
                               |   wlr_rendersurface   |<-----+       wlr_output      |
                               |                       |      |                       |
                               +-----------------------+      +-----------------------+
```

**Comment by emersion** [comment]
Tentative API design:

```c
// Creates custom renderers
struct wlr_renderer *wlr_gles2_renderer_create(struct wlr_egl *egl);
struct wlr_renderer *wlr_gles3_renderer_create(struct wlr_egl *egl);
struct wlr_renderer *wlr_vk_renderer_create();
struct wlr_renderer *wlr_pixman_renderer_create();

/**
 * Creates a backend depending on the environment and the provided renderer. If
 * the renderer is NULL, automatically creates the best renderer for the
 * backend.
 */
struct wlr_backend *wlr_backend_autocreate(struct wlr_renderer *renderer);

/**
 * Returns the backend's renderer. A backend always has a compatible renderer.
 */
struct wlr_renderer *wlr_backend_get_renderer(struct wlr_backend *backend);

// Functions used by the backend to check if a renderer is appropriate
bool wlr_renderer_support_wl_display(struct wlr_renderer *renderer);
bool wlr_renderer_support_gbm(struct wlr_renderer *renderer);
bool wlr_renderer_support_xcb_conn(struct wlr_renderer *renderer);

// Creates wlr_rendersurface, used by the backend
struct wlr_rendersurface *wlr_rendersurface_from_wl_display(
	struct wlr_renderer *renderer, struct wl_display *display);
struct wlr_rendersurface *wlr_rendersurface_from_gbm_device(
	struct wlr_renderer *renderer, struct gbm_device *gbm);
struct wlr_rendersurface *wlr_rendersurface_from_xcb_conn(
	struct wlr_renderer *renderer, xcb_connection_t *xcb_conn);

// Gets resources backing a wlr_rendersurface, used by the backend
struct gbm_surface *wlr_rendersurface_get_gbm_surface(
	struct wlr_rendersurface *surface);
struct wl_surface *wlr_rendersurface_get_wl_surface(
	struct wlr_rendersurface *surface);
xcb_window_t wlr_rendersurface_get_xcb_window(
	struct wlr_rendersurface *surface);

// Starts rendering on a particular wlr_rendersurface
void wlr_renderer_begin(struct wlr_renderer *renderer,
	struct wlr_rendersurface *surface, int *buffer_age);
void wlr_renderer_end(struct wlr_renderer *renderer,
	struct wlr_rendersurface *surface, pixman_region32_t *damage);
// … other wlr_renderer functions remain the same
```

**Comment by SirCmpwn** [comment]
What is this wlr_rendersurface?

**Comment by emersion** [comment]
It's an abstraction for EGLSurface. A wlr_rendersurface can be backed by an EGLSurface, a Vulkan equivalent (I don't know enough Vulkan to elaborate), or an in-memory buffer.

**Comment by SirCmpwn** [comment]
I would prefer `wlr_render_surface` fwiw

**Comment by emersion** [comment]
Yeah, me too, but at this step of the redesign I'm not too picky about names.

**Comment by dumblob** [comment]
The design of @emersion doesn't look that bad to me.

My goal would be to integrate a purely software-based renderer (e.g. https://github.com/blend2d ) for constraint environments and/or environments with the main focus on saving energy (I can even imagine dynamic switching of renderers in runtime to be able to switch off a dedicated graphic card in case a laptop/smartphone turns low on battery).

**Comment by emersion** [comment]
If you're going to build a software renderer, using pixman is probably a better idea since:
* We already depend on it
* We're just compositing, not actually drawing anything

Dynamically switching renderers seems like a very complicated feature. It's probably not even possible.

**Comment by ascent12** [comment]
Superseded by #1352
