### ISSUE TITLE
Cursor rotated in wrong direction when using rotated output

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/wlroots#795]
Rootston config:

    [output:VGA-1]
    x = 0
    y = 500

    [output:HDMI-A-1]
    x = 1920
    y = 0
    rotate = 90

When the mouse cursor is on the rotated output, the cursor icon is upside down. This also happens in Sway's wlroots branch.

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/sway/issues/1534

Do not report bugs about wlroots

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/wlroots/issues/592

**Comment by emersion** [comment]
This is not #592. I can reproduce.
