### ISSUE TITLE
Remove wlr_backend_get_egl

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#801]
It's a platform-specific API (as opposed to `wlr_renderer`) and the only place it's actually used is in Linux DMA-BUF.

We can move the functions used by Linux DMA-BUF (`check_import_dmabuf`, `get_dmabuf_formats`, `get_dmabuf_modifiers`) in the renderer, as optional functions.

**Comment by agx** [comment]
Wouldn't it be better to keep it in the backend given that it's' platform specific?

**Comment by emersion** [comment]
>Wouldn't it be better to keep it in the backend given that it's' platform specific?

We eventually want to support a Vulkan renderer, and maybe a software renderer, how would that work if we keep it in the backend? See #774

**Comment by agx** [comment]
Looking at https://user-images.githubusercontent.com/5235114/38083927-7f9fb520-33a7-11e8-99a7-d3e475609a3a.png it should be in the renderer, agreed.

**Comment by ascent12** [comment]
#850
