### ISSUE TITLE
Downgrade dmabuf L_ERRORs to L_DEBUG

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#814]

**Comment by agx** [comment]
Are you refering to `wlr_egl_get_dmabuf_formats` and `wlr_egl_get_dmabuf_modifiers`? These are IMHO real errors since the extension is present but we fail to query it.

**Comment by martinetd** [comment]
I think he meant this line, was brought up on irc:

```
render/egl.c:		wlr_log(L_ERROR, "dmabuf extension not present");
```

**Comment by agx** [comment]
On Tue, Apr 03, 2018 at 11:55:46PM -0700, Dominique Martinet wrote:
> I think he meant this line, was brought up on irc:
> 
> ```
> render/egl.c:		wlr_log(L_ERROR, "dmabuf extension not present");
> ```

One is L_DEBUG alread on master since
4bf936360d42fb5b96a44fd17028ae66fc462362 but there's another one left:

https://github.com/swaywm/wlroots/pull/818

Thanks!
