### ISSUE TITLE
Support for rebinding keys

### ISSUE THREAD

**Issue by hkupty** [swaywm/wlroots#819]
I guess this is the correct place for me to fill this in (and the correct time, since you're hacking into it).

One of the things that hold me from moving completely to Wayland-based apps is my key setup with Caps Lock acting both as Ctrl (when on hold) and Esc (when pressed alone).

I know this is an exotic feature (accomplished with hacks, which sometimes cause flawed or undesired behavior), but in order for it to work as intended, this should be implemented on the compositor.

I *believe* that this is something that can be done on wlroots and that would benefit anyone that uses it.

Sorry if spamming in the wrong place, but his seemed the most reasonable place to ask this.

**Comment by exrok** [comment]
I believe this is the xcape feature that is a currently a bounty, https://github.com/swaywm/sway/issues/986

**Comment by emersion** [comment]
The recommended way is to use custom keymaps.

**Comment by hkupty** [comment]
Is there any documentation on keymaps showing/guiding how to have this behavior (different keycodes for hold and press)? I couldn't find any...
