### ISSUE TITLE
Implement xdg-output

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#826]

**Comment by emersion** [comment]
I'd like to replace `wlr_output_{create,destroy}_global` by a new `wlr_output_expose(struct wlr_output *output, bool expose)` for consistency with `wlr_output_enable`. Also this change will require to add an `expose` signal.

Some background:
* https://bugs.freedesktop.org/show_bug.cgi?id=101436
* https://bugs.freedesktop.org/show_bug.cgi?id=101193
* https://bugs.freedesktop.org/show_bug.cgi?id=93315

**Comment by SirCmpwn** [comment]
>I'd like to replace wlr_output_{create,destroy}_global by a new wlr_output_expose(struct wlr_output *output, bool expose) for consistency with wlr_output_enable. Also this change will require to add an expose signal.

-1
