### ISSUE TITLE
How to run apps in rootston?

### ISSUE THREAD

**Issue by Sunderland93** [swaywm/wlroots#827]
Hi. I'm build wlroots on Debian Sid (GNOME), according to instructions. After start rootston, it give's a gray window with cursor. How to run applications? There is no terminal icon, like in Weston.

**Comment by Toggleton** [comment]
you can run a program on startup in rootston with  `-E <COMMAND> `
and AFAIK you can something like this `Alt+Return = exec weston-terminal` to your rootston.ini https://github.com/swaywm/wlroots/blob/master/rootston/rootston.ini.example

**Comment by Sunderland93** [comment]
Thanks!
