### ISSUE TITLE
Resizing the X11 backend window breaks xwayland pointer behavior

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#836]
To reproduce, open X11 backend and resize it (larger). Then run gimp and File -> New, then try to interact with this dialogue outside of the previously-sized region of the output.

**Comment by emersion** [comment]
Cannot reproduce on GNOME.

Does `weston-info` print the correct new output size after resizing the X11 backend window?

If so, is this an issue with xdg-output?

**Comment by SirCmpwn** [comment]
>Does weston-info print the correct new output size after resizing the X11 backend window?

Yes, but interestingly so does xrandr

**Comment by SirCmpwn** [comment]
>Yes, but interestingly so does xrandr

I take this back
