### ISSUE TITLE
wlroots cannot seem to find Xwayland when it's installed to /opt/bin

### ISSUE THREAD

**Issue by n3rdopolis** [swaywm/wlroots#874]
Hi

I am not sure why, as since I use checkinstall to build and install wlroots, it loses the feature flags, so the system is not stripping PATH as far as I know... It seems that PATH is still getting stripped? since the path to Xwayland does not appear to be hard coded. 

Thanks

**Comment by turlando** [comment]
Could you please show the steps you're taking and the commands you're running? The meson version would help too.

**Comment by n3rdopolis** [comment]
It's meson 0.44.0
I build it with
```
meson --buildtype=plain --prefix=$INSTALLDIR --libdir=$INSTALLDIR/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH) -Dwerror=false build
```
(where $INSTALLDIR=/opt)

and I get the error by running `sway` or `rootston`
symlinking /opt/bin/Xwayland to /usr/bin/Xwayland works around it, but I don't want to do that permanently

**Comment by emersion** [comment]
Can you run `echo $PATH`? Can you try to run `Xwayland` manually?

**Comment by n3rdopolis** [comment]
Hi
```
PATH=/opt/bin:/opt/games:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Xwayland is /opt/bin/Xwayland
and it runs for Weston

Thanks

**Comment by ascent12** [comment]
Weston:
```
section = weston_config_get_section(config,
						    "xwayland", NULL, NULL);
		weston_config_section_get_string(section, "path",
						 &xserver, XSERVER_PATH);

		// ...

		if (execl(xserver,
			  xserver,
			  display,
			  "-rootless",
			  "-listen", abstract_fd_str,
			  "-listen", unix_fd_str,
			  "-wm", wm_fd_str,
			  "-terminate",
			  NULL) < 0)
```
wlroots:
```
execvp("Xwayland", argv);
```
They're using a config option (which is also set at build time) instead of PATH.

**Comment by emersion** [comment]
Can you try to run `Xwayland` directly, from your CLI, to make sure that wlroots _can_ find it?

Can you print `$PATH` right before `execvp("Xwayland", argv);` in wlroots?

**Comment by n3rdopolis** [comment]
is that 
```
wlrlog(L_INFO, "XWAYLANDPATH %s", getenv("PATH"));
```
it turns out to be (null)
but I could be doing something wrong...

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/886
