### ISSUE TITLE
Layer shell popups todo

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlroots#889]
- [ ] handle popup with popups using surface_iterators
- [ ] handle subsurfaces
- [x] handle grabs (including dismissing popups with grabs when losing focus, see xdg_popup.grab)

**Comment by agx** [comment]
Grabs work already since it uses the xdg_* code (see https://github.com/swaywm/wlroots/pull/891)

**Comment by agx** [comment]
Damage tracking is broken for scaled  outputs since we're  not using output_damage_from_local_surface. I'm looking into it.

**Comment by agx** [comment]
The damage issues are fixed in https://github.com/swaywm/wlroots/pull/895
