### ISSUE TITLE
layer-shell popups are not closed when clicking on other layer-surface (e.g. background layer) but should

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#897]
If you have e.g. a top panel that uses popups (with grab) for menus and you click outside the popus and panel the menu closes (as it should). This does not work if one clicks on another layer surface (e.g. ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND) that is being clicked on (which makes using layer-shell for backgrounds and panels at the same time impossible). 

I have yet to figure out if we want to make ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND special or only always close popups when clicked outside the parent layer-shell and the popup.

This can e.g. be checked with phosh's layer-surfaces branch (https://code.puri.sm/guido.gunther/phosh/src/layer-surfaces). Comment out create_background() in phosh_shell_constructed() and closing of popups works as expected otherwise popups won't close since the background spans the whole output.

Opening a new issue instead of cluttering https://github.com/swaywm/wlroots/issues/889

**Comment by SirCmpwn** [comment]
I don't fully understand the problem. If you click on another surface, background or not, we should close the grab.

**Comment by agx** [comment]
...and that's not happening. I'll have  look.

**Comment by agx** [comment]
The reason is that the pointer grab is client based so if the pointer moves out of the popup onto the background layer-surface ```wlr_seat_pointer_send_button()``` will determine that the same client is still focues and therefore not close the popup. If one moves the pointer of the surface of another client the popup is correctly closed.

**Comment by SirCmpwn** [comment]
You're elaborating on the causes of the bug, rather than on why you believe it's the intended behavior, right?

**Comment by agx** [comment]
Right.
