### ISSUE TITLE
wlr_cursor doesn't support absolute coordinates outside 0..1

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#907]
But libinput docs say it's possible, if the tool is outside the working region of the tablet for instance.

`wlr_cursor` will just ignore them, because negative values mean "ignore me". Maybe an infinite/NAN value would be better?

Note that the cursor shouldn't go outside the mapped region, even if it receives absolute coordinates outside 0..1.

**Comment by SirCmpwn** [comment]
>Note that the cursor shouldn't go outside the mapped region, even if it receives absolute coordinates outside 0..1.

If this is the case then why do we need to handle it? Negative values will always be outside of the mapped region.

**Comment by SirCmpwn** [comment]
Gotcha.
