### ISSUE TITLE
Consider dropping per-plane DMA-BUF modifiers

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#908]
The kernel people say it was a mistake.

Thanks @atomnuker for pointing that out.

References:
* http://kiwitree.net/~chadv/vulkan/1.0-VK_EXT_image_drm_format_modifier/html/vkspec.html#_issues_58
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bae781b259269590109e8a4a8227331362b88212

**Comment by agx** [comment]
I would keep the modifiers in the structs since it matches what the wayland API expects but we should check that they're identical in params_create_common. linux-dmabuf-unstable-v1.xml should then drop that from the *add* request and move it to *create* I guess.

**Comment by emersion** [comment]
>I would keep the modifiers in the structs since it matches what the wayland API expects but we should check that they're identical in params_create_common.

DRM will do that for us right? If we check that we should remove the ability to put per-plane modifiers in the struct.

>linux-dmabuf-unstable-v1.xml should then drop that from the add request and move it to create I guess.

Not sure people will find this compelling enough to bump the protocol version with an backwards-incompatible change.

**Comment by agx** [comment]
On Wed, Apr 25, 2018 at 01:59:02PM +0000, emersion wrote:
> >I would keep the modifiers in the structs since it matches what the wayland API expects but we should check that they're identical in params_create_common.
> 
> DRM will do that for us right? If we check that we should remove the ability to put per-plane modifiers in the struct.

Agreed.

> 
> >linux-dmabuf-unstable-v1.xml should then drop that from the add request and move it to create I guess.
> 
> Not sure people will find this compelling enough to bump the protocol
> version with an backwards-incompatible change.

This was more ment like "if there's a v2 we should fix this up as well
with the other changes". I agree that it's not worth an incompatible new
version.
