### ISSUE TITLE
Absolute touch events don't work with multiple screens

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#925]
Absolute touch events are mapped to the whole layout by default. This works if there's only one screen, but fails if there are multiple.

We should provide screen information in the input device.

The same issue forces us to have a rather complicated code to correctly support multiple outputs in the Wayland and X11 backends. This approach fails short when there are multiple backends (#924).

**Comment by emersion** [comment]
There's also [`libinput_device_get_output_name`](https://wayland.freedesktop.org/libinput/doc/1.1.1/group__device.html#gaf48626f6190e9c9bc14abb704e66cc22), not sure where the information is retrieved from.

In any case, sometimes the mapping is known by the backend (via udev, or directly if Wayland/X11), and we need a way to communicate this to the compositor.

>Get the mapping by some compositor configuraion

This should always override heuristics and the backend hint.

>Provide some metric to map them (e.g. LVDS/eDP are more likely to be touch) 

This should be done by the compositor. The aspect ratio of the output and input device can be used too.

**Comment by SirCmpwn** [comment]
>There's also libinput_device_get_output_name, not sure where the information is retrieved from (EDIT: from the WL_OUTPUT udev property).

In my experience this is never set.
