### ISSUE TITLE
Touch events don't take output output rotation into account

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#928]
With e.g. 

```
[output:HDMI-A-1]
rotate = 90
```

in rootston touch events are still reported towards the unrotated screen. If there's e.g. a top panel with a button on the left and the screen is rotated 90⁰ one still has to click into the upper left corner of the sreen to activate it. The menu then "correctly" opens on the rotated location.

**Comment by emersion** [comment]
`wlr_cursor` probably needs to transform input events. This is already done in the Wayland and X11 backends, we might want to move it in `wlr_cursor`.

**Comment by agx** [comment]
On Sun, Apr 29, 2018 at 07:14:37AM -0700, emersion wrote:
> `wlr_cursor` probably needs to transform input events. This is already done in the Wayland and X11 backends, we might want to move it in `wlr_cursor`.

With your https://github.com/swaywm/wlroots/pull/930 we could track the
output of each input_device and apply the output transform there right
aways (that's how weston does it):

    https://github.com/wayland-project/weston/blob/master/libweston/libinput-device.c#L117
    
The input device is matched to the output here

    https://github.com/wayland-project/weston/blob/master/libweston/libinput-seat.c#L123

**Comment by emersion** [comment]
>With your #930 we could track the output of each input_device and apply the output transform there right aways

Hmm, remember that the compositor config can override `wlr_input_device.output_name`. That's why I suggested to transform the event in `wlr_cursor`.
