### ISSUE TITLE
rootston: no initial cursor on startup

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#929]
If the pointer is not on top of  client surface when rootston starts there's no cursor displayed. If one starts a client and the pointer moves over a client's surface the pointer is displayed (and stays visible from there on).

Rootston should display an initial cursor (iff there's a pointing device attached, if there's only touch and/or keyboard then better not)

**Comment by emersion** [comment]
>If the pointer is not on top of  client surface when rootston starts there's no cursor displayed.

Is this specific to one backend? I don't understand the "client surface" part since on startup there's no client yet.

**Comment by agx** [comment]
It should better read "if one starts up a client and the pointer moves over on of it's surfaces the pointer is displayed". I can't tell whether X11 is affected as well since there's already a cursor from the outer X11/Wayland present. It surely happens on DRM.
