### ISSUE TITLE
Don't try to render damage from too many rectangles

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#949]
Drawing damage from too many rectangles is not efficient. We should fallback to rendering the bounds of the damaged region when the region is too complicated.

This is how how GTK+ does it: https://streamable.com/rb6rr

Proposed plan: add a `uint32_t max_rects` field to `wlr_output_damage`. This is set to a reasonable value by default (something between 20 and 30?), and is override-able by the compositor. If the number of rectangles is too high, it'll just return the bounds of the damaged region. Since `wlr_output_damage` is optional anyway, I don't think this will do any harm. Compositors that wish to disable this feature can set it to MAX_INT.

**Comment by ammen99** [comment]
I have also seen the same optimization in Compiz, and it improved performance, so this seems a good idea.
