### ISSUE TITLE
Sections of Xwayland windows within negative output coordinates receive incorrectly positioned cursor events

### ISSUE THREAD

**Issue by vilhalmer** [swaywm/wlroots#958]
If a portion of an Xwayland window is positioned within negative display coordinates, the cursor events received within that portion will be forced to zero on any axis which is negative. This is probably easier to show than tell:

```
                          +-----------------------------+
                          |1920,-380 +---------+        |
                          |          |xxxxxxxxx|        |
                          |          |xxxxxxxxx|        |
+-------------------------+          |xxxxxxxxx|        |
|0,0                     ||1920,0    | window  |        |
|                        ||          |         |        |
|                        ||          +---------+        |
|                        ||                             |
|                        +------------------------------+
|                        |
|                        |
|                        |
+------------------------+
```
The "x" filled portion of the window will only ever receive events with a y coordinate of zero.

I discovered this in sway 1.0 alpha, but it can be reproduced in rootston. I did so by positioning a Chromium window as in the diagram, and observing that interaction with the top of the window triggered click events along y=0 instead.

It can also be seen in the output of xev, as you move the cursor up onto that area. Note that both the local and root y coordinate stops decrementing:
```
MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351420, (189,350), root:(2927,3),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351443, (189,349), root:(2927,2),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351454, (189,348), root:(2927,1),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351476, (189,347), root:(2927,0),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351499, (189,347), root:(2927,0),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 34, synthetic NO, window 0x1c00001,
    root 0x342, subw 0x0, time 88351521, (189,347), root:(2927,0),
    state 0x0, is_hint 0, same_screen YES
```

**Comment by hedgepigdaniel** [comment]
would this be easy to work around by translating output coordinates when going in and out of XWayland apps such that they are consistent within XWayland and always positive?

I find it easier to understand a monitor configuration for e.g. a laptop when the internal screen is at 0,0 and other screens are positioned relative to it, as in the example here. And this is quite a bad bug when it happens.

**Comment by emersion** [comment]
No. The right solution is to fix Xwayland.

**Comment by maxhille** [comment]
I don't see a bug report at the XWayland bug tracker[1]. Maybe someone more into the specifics (so, not me) can open one?

[1] https://bugs.freedesktop.org/buglist.cgi?component=XWayland&product=Wayland&resolution=---

**Comment by emersion** [comment]
The Xwayland bug tracker is on GitLab.

**Comment by emersion** [comment]
https://gitlab.freedesktop.org/xorg/xserver/issues/899

**Comment by emersion** [comment]
Patch available here: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/395

**Comment by oniGino** [comment]
Anyone know if this patch exists for 1.20.7 stable branch instead of master?

**Comment by Emantor** [comment]
> Anyone know if this patch exists for 1.20.7 stable branch instead of master?

As long as the MR hasn't been merged into master, upstream won't backport to a stable release. I also recommend using 1.20.8 since it includes a fix for a race between xwayland and the compositor which could result in flickering.

**Comment by emersion** [comment]
Closing because this isn't a wlroots bug.

**Comment by tcmeggs** [comment]
xwayland says it's a close/wontfix. see https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/395#note_555613 cc: @emersion

**Comment by oniGino** [comment]
its fixed in the next major branch of xorg-server but they are refusing to backport the patch
