### ISSUE TITLE
Gamma correction isn't applied to hardware cursors

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlroots#968]

**Comment by ascent12** [comment]
Gamma is a CRTC property. We cannot set it on the cursor plane.
This is basically a limitation everybody faces.

The only way I'd see this working is colouring the cursor in software.

**Comment by SirCmpwn** [comment]
:(

**Comment by martinetd** [comment]
Actually I don't see why we couldn't color the cursor in software, iiuc we upload an arbitrary texture to the cursor plane if there is one so we could probably apply some software filter just before uploading that texture and it should just work™ ; We do transforms like rotate/flip/scale so why not gamma?

Or am I missing something? Can the texture sometimes not go through wlroots?


One tricky point I see is that a naive implementation would likely only update the cursor gamma when the cursor texture is updated, unless we keep the latest untransformed texture around to update it on set_gamma...

**Comment by ascent12** [comment]
I'm fine with doing it in software.

**Comment by VincentVanlaer** [comment]
This seems to be working fine on DRM backend with i915 (Intel HD Graphics 530).

**Comment by emersion** [comment]
Yeah, I can reproduce on i915 too. I don't see any way of detecting of the cursor needs gamma or not.

**Comment by SirCmpwn** [comment]
>The i915 driver apparently

If the drivers are making the call maybe we can speak to the AMDGPU folks?

**Comment by emersion** [comment]
Not applying the gamma LUT to all planes is a driver bug, see https://lists.freedesktop.org/archives/dri-devel/2020-September/279398.html

**Comment by emersion** [comment]
Reported the issue here: https://gitlab.freedesktop.org/drm/amd/-/issues/1290

If you can reproduce this issue on radeon, please add a comment with your graphics card model and kernel version.
