### ISSUE TITLE
Lingering cursor on output border

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#976]
"Sometimes" (I'm not sure yet when exactly) a cursor lingers in the visible area on an output, after it was moved from it.

I have only seen this on waymonad with the DRM backend so far, it's hard to reproduce reliably, so I can't exactly test on rootston =.=

My observations so far:
* Cursor hotspot is outside visible area
* Usually had mpv on the output the cursor lingers on
* Not every cursor is visible (larger ones are, thinner ones aren't)

Just looking at it, I guess a small cursor isn't moved far enough outside the visible area, and uploading a new cursor makes a lingering cursor visible.
But looking at the code, I'd expec the cursor to move again when it's enlarged to be visible, so I'm a little confused

**Comment by SirCmpwn** [comment]
I can reproduce similar issues in sway which are likely related to the same bug.

**Comment by Ongy** [comment]
Ok, I was just dumb reading earlier. It's kinda obvious why things fail.

The cursor is set to invisble when the current cursor rectangle does not intersect the output.
When it's updated, it is still considered invisible (and thus not moved, to not force a flip) if the cursor rectangle does not intersect the output at the *current* position, not the position the plane is set to.

My quick fix idea: Don't just park the cursor plane where it's at, when it becomes invisible, but move it far enough that the plane can't intersect with the output (afaik there's a max-size for planes).

Any hardware weirdness that interferes with that?

**Comment by emersion** [comment]
Yeah, what you're saying has been the number 1 suspect when I read this issue. Though:

>When it's updated, it is still considered invisible (and thus not moved, to not force a flip)

I think we should just move even if the cursor isn't visible when we update it.

> Don't just park the cursor plane where it's at, when it becomes invisible, but move it far enough that the plane can't intersect with the output (afaik there's a max-size for planes).

Meh, this only works in the DRM backend "by chance". Also the DRM backend isn't even called when the cursor is not visible?
