### ISSUE TITLE
Alpha blend mode is broken

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#984]
1. Start rootston with the Wayland backend
2. Open gnome-calculator
3. The window shadows (which are semi-transparent) clear the gray background, making the Wayland backend window semi-transparent

Can also reproduce on DRM by making a screenshot.

No idea how to fix this, the current blend mode looks good to me.

**Comment by ammen99** [comment]
I have a hypothesis, but I'm no expert on GL, so what I say might be completely wrong. But looking at the documentation here: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glBlendFunc.xhtml, it seems that by using `(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)` the alpha channel will be multiplied by itself and as a result the total alpha will be less than 1(after blending).I mean, the equation for the final alpha is actually `Sa * Sa + 1 - Sa` where `Sa` is the source alpha and the buffer RGBA values(which are taken for screenshot or when nested) becomes less than 1.

 A solution could be: In the fragment shader, pre-multiply RGB values by the alpha value, then use `(GL_ONE, GL_ONE_MINUS_SRC_ALPHA)`. This seems to fix the problem, if it looks good to you, I can make a PR later

**Comment by ammen99** [comment]
I didn't know about `glBlendFuncSeparate` it might be the right fix (with rgb SRC_ALPHA, ONE_MINUS_SRC_ALPHA and for alpha ONE ONE_MINUS_SRC_ALPHA)

However I'm thinking what should be the resulting alpha when we blend two textures with alpha 0.5

**Comment by emersion** [comment]
>However I'm thinking what should be the resulting alpha when we blend two textures with alpha 0.5?

That's a good question. For our uses-case it shouldn't happen too often (in fact only on Wayland/X11 backends with transparent backgrounds, unless a transparent screen is used but these are still pretty rare). Not sure but I'd say 0.5?

Paging @ascent12

**Comment by VincentVanlaer** [comment]
Not sure if this is the right way to think about it, but say one defines alpha as the factor of 'light', coming from lower layers, that gets blocked. Then the factor of light that gets through after two layers with a1 and a2 as their alphas would be `(1-a1)*(1-a2)`. Since we defined alpha as the factor of 'light' that gets blocked, we still need to subtract that from one. We then get that the alpha of the combined layers is `1 -  (1-a1)*(1-a2) = a1+a2-a1*a2` . In the case of two layers with alpha 0.5, the resulting alpha is 0.75.

**Comment by emersion** [comment]
In this case it seems that ONE, ONE_MINUS_SRC_ALPHA would do it for the alpha channel.

**Comment by ammen99** [comment]
Yes, thinking about it in terms of light seems that this approach is the correct one. But Weston uses just `glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA)` and pre-multiplies view alpha(e.g what the compositor here passes with the alpha parameter). So maybe clients are expected to pre-multiply RGB channels? Or weston does it wrongly?

**Comment by emersion** [comment]
We used to do this as well (see #982). Now that I think of it, multiplying RGB by the alpha parameter is probably the right thing to do.

**Comment by ammen99** [comment]
So it should be assumed the client has pre-multiplied alpha?

**Comment by emersion** [comment]
I don't understand what you mean by that?

**Comment by ammen99** [comment]
I meant this: if we multiply alpha in the shader, do we do:
1) `gl_FragColor.rgb = tex.rgb * tex.a * alpha` or
2) `gl_FragColor.rgb = tex.rgb * alpha`?

"client has pre-multiplied alpha" = "we should do 2"

**Comment by emersion** [comment]
I think we should assume pre-multiplied alpha?

**Comment by ammen99** [comment]
Shouldn't this issue be closed?

**Comment by emersion** [comment]
Yeah. In the future, add "Fixes #984" to your PR description so it closes issues automatically when merged.

**Comment by ammen99** [comment]
Didn't know github does this automatically, will do it in the future. Thanks for the info.
