### ISSUE TITLE
After hotplugging, xwayland windows are scaled up

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#988]
1. Have outputs configured without scaling
2. Launch dmenu, everything is normal
3. Hotplug an output, everything is still normal
4. Unplug the output
5. Launch dmenu, the font size is increased by 2

The mode and physical size reported by `weston-info` and by `xrandr` are correct.

**Comment by emersion** [comment]
https://lists.x.org/archives/xorg-devel/2018-July/057305.html

**Comment by martinetd** [comment]
List archive doesn't contain message-id so I can't reply there, but "meh" for the question (yes I noticed how old it is, after writing most of this)


The values printed come from here in xdpyinfo source code:
```c
    xres = ((((double) DisplayWidth(dpy,scr)) * 25.4) /
            ((double) DisplayWidthMM(dpy,scr)));
    yres = ((((double) DisplayHeight(dpy,scr)) * 25.4) /
            ((double) DisplayHeightMM(dpy,scr)));
```
which in xlib's code are the screen's fields width/height and mwidth/mheight, which in turn come from
```c
            sp->width       = u.rp->pixWidth;
            sp->height      = u.rp->pixHeight;
            sp->mwidth      = u.rp->mmWidth;
            sp->mheight     = u.rp->mmHeight;
```

which are set in `update_screen_size` in hw/xwayland/xwayland-output.c

For the x11 backend, it turns out it takes the branch that sets the mmWidth/Height to `xwl_output->randr_output->mmHeight` but they are set to 0, because in `apply_output_change` they set the `width`/`height` with `RROutputSetModes` but they don't set the mm dimensions with `RROutputSetPhysicalSize`...

Anyway, cheating in gdb to take the other branch seems to work, so a patch like this ought to work:
```diff
diff --git a/hw/xwayland/xwayland-output.c b/hw/xwayland/xwayland-output.c
index 0d2ec7890..94784ea1a 100644
--- a/hw/xwayland/xwayland-output.c
+++ b/hw/xwayland/xwayland-output.c
@@ -185,7 +185,9 @@ update_screen_size(struct xwl_output *xwl_output, int width, int height)
     xwl_screen->screen->width = width;
     xwl_screen->screen->height = height;
 
-    if (xwl_output->width == width && xwl_output->height == height) {
+    if (xwl_output->width == width && xwl_output->height == height &&
+           xwl_output->randr_output->mmWidth != 0 &&
+           xwl_output->randr_output->mmHeight != 0) {
         xwl_screen->screen->mmWidth = xwl_output->randr_output->mmWidth;
         xwl_screen->screen->mmHeight = xwl_output->randr_output->mmHeight;
     } else {
```


For DRM and screen hotplugging your DPI isn't 0 so my guess is that something is wrong with `approximate_mmpd` or randr_output's mmWidth/Height must be set somehow?
I don't have any screen to test hotplugging around here but it shouldn't be too hard to take from there..

**Comment by emersion** [comment]
I was told setting `randr_output->mm{Width,Height}` to 0 was common X11 behaviour to mean "it doesn't make sense in this situation".

**Comment by SirCmpwn** [comment]
The message ID was `<dk-acdbRGAnylcm94r9l6STBBZseOOLmGiD5LuIHIhwSM_uXqHhz7RRNbNwB2biPfChcJ9I37r00D5aw9fibDrWNBktRf4wyGh_HPwK2Zck=@emersion.fr>`. You can get this by clicking on Simon's email on the top of the page.

**Comment by martinetd** [comment]
Oh, that's a mailto: link where they hid it... I don't see what logic made them decide that was a good place to put it, but fair enough, thanks for pointing that out.


> I was told setting randr_output->mm{Width,Height} to 0 was common X11 behaviour to mean "it doesn't make sense in this situation".

Well, they use it... :)

FWIW I don't have more external screens now, but the breakpoint I set up yesterday triggered (on what?!) and surely enough the randr mmWidth/height are off (screen contains the previous "correct" values):
```
(gdb) p xwl_output->randr_output->mmWidth
$3 = 344
(gdb) p xwl_screen->screen->mmWidth
$4 = 508
(gdb) p xwl_output->randr_output->mmHeight
$5 = 193
(gdb) p xwl_screen->screen->mmHeight
$6 = 286
```

You can actually see the incorrect values in `xrandr -q`:
```
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
```

And these values come from us alright:
```c
@@ types/wlr_output.c
static void output_send_to_resource(struct wl_resource *resource) {
        struct wlr_output *output = wlr_output_from_resource(resource);
        const uint32_t version = wl_resource_get_version(resource);
        if (version >= WL_OUTPUT_GEOMETRY_SINCE_VERSION) {
                wl_output_send_geometry(resource, output->lx, output->ly,
                        output->phys_width, output->phys_height, output->subpixel,
                        output->make, output->model, output->transform);
        }
```

We send 0 for x11 backend and whatever I just got for DRM; I have no clue why this change when you hotplug/unplug things either but it's probably something on our side that has to do with these.


`update_screen_size()` I was talking about is done when we `send_done()` a few lines below, so my guess is that the first send_done we do at init goes into the else branch and X11 picks the DPI itself, then it has correct values and expects to find things in xrandr_output...

I'm not quite sure where that logic comes from either, the original commit that added this added both branches at once here and explains how we get 96DPI at start...
```
commit 880d4e78b1823bcc0e66e68270af1a475f097bb5
Author: Jonas Ådahl <jadahl@gmail.com>
Date:   Wed Oct 7 12:02:39 2015 +0800

    xwayland: Set physical screen size to something
    
    When we have a single output, just set it to the physical size of that
    output. Otherwise try to approximate it calculating a mean m.m. per
    dot. Last fallback is to default to 96 DPI.
    
    Signed-off-by: Jonas Ådahl <jadahl@gmail.com>
    Reviewed-by: Daniel Stone <daniels@collabora.com>
```

Anyway, the dimensions we feed it look more correct than 96 DPI... But even on plain X11 I get xdpyinfo to tell me 96x96 with the same dimensions in `xrandr -q` that would lead to 142 dpi... so... meh.

I'll let whoever else take over from here as if I made a patch now it'd be to just always take the fallback and I'm sure that's not correct (with regards to e.g. hidpi), GLHF.

**Comment by SirCmpwn** [comment]
This is an Xwayland bug, so let's move the discussion to their court.

**Comment by Timidger** [comment]
Ugh this is that bug I "fixed" in wlroots and wlc. I tried filing a (shitty) patch upstream to xwayland but I let it drop because I focused on other things.

Here it is, for completeness, but this isn't very good. 

```
hw/xwayland/xwayland-output.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hw/xwayland/xwayland-output.c b/hw/xwayland/xwayland-output.c
index 48faeb142..dc988ed2f 100644
--- a/hw/xwayland/xwayland-output.c
+++ b/hw/xwayland/xwayland-output.c
@@ -194,7 +194,7 @@ update_screen_size(struct xwl_output *xwl_output, int width, int height)

     SetRootClip(xwl_screen->screen, xwl_screen->root_clip_mode);

-    if (xwl_screen->screen->root) {
+    if (xwl_screen->screen->root && xwl_output->width != width && xwl_output->height != height) {
         BoxRec box = { 0, 0, width, height };

         xwl_screen->screen->root->drawable.width = width;
```
