### ISSUE TITLE
Check DRM link-status property

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#995]
There is some user-space stuff we're supposed to be doing to make sure black screens don't happen in some situations. I don't know a huge deal about this or even how to test it, though.
I don't think any other wayland compositor handles this, but Xorg does.

Some information is here.
https://fosdem.org/2018/schedule/event/kms_dp/attachments/slides/2703/export/events/attachments/kms_dp/slides/2703/Fosdem2018__final.pdf

**Comment by emersion** [comment]
Some more information: https://patchwork.kernel.org/patch/9428849/

**Comment by emersion** [comment]
Weston issue, with what needs to be done: https://gitlab.freedesktop.org/wayland/weston/issues/124#note_30387

We don't have a signal to update the list of available modes yet.

**Comment by emersion** [comment]
We need to: on hotplug event, check for link-status, if it's bad, force a new modeset with the highest mode available. The kernel will prune bad modes itself.

We need to make sure we update our list of modes in this case.
